### ISSUE TITLE
[WEBSITE] completely unrelated results are loaded if you type fast enough in the search box

### ISSUE THREAD

**Issue by teo1978** [yiisoft/yii#1200]
This is a bug in the yiiframework.com website, specifically the API documentation:
http://www.yiiframework.com/doc/api/1.1/

However, I guess it is probably build using the yii framework, in which case this may also be a bug in yii's autocomplete textfield functionality.

Steps to reproduce:

Start typing in the "LOOK UP A CLASS, METHOD, PROPERTY OR EVENT" search box.
- Start typing slowly, for examle type "CD" and wait until "CDataColumn" and other results appear
- Now go on typing, this time very fast, and type something that is unrelated to CDataColumn but still does have matches. For example, type "CDbAuthManager" and hit ENTER

Expected result: either the correct page for CDbAuthManager should be loaded, or nothing should be loaded and the waiting animation should be shown until the search results are updated.

Actual result: the page for "CDataColumn" is opened if the results haven't been updated before you hit enter.

The real-life use case is that you type quickly and correctly a name that has an exact match and, at apparently random times, a completely unrelated page is opened.

**Comment by teo1978** [comment]
I don't know why this got closed, but I am still observing the issue as of today

**Comment by cebe** [comment]
The new website (WIP) wil have a new search engine: https://github.com/yiisoft-contrib/yiiframework.com
