### ISSUE TITLE
Enh: CDbCriteria method for fulltext search condition

### ISSUE THREAD

**Issue by kmindi** [yiisoft/yii#1209]
There should be a method like the existing addSearchCondition() which handles fulltext index search in InnoDB (since MySQL 5.6.4)

Currently I am using CDbCriteria this way:

~~~
$criteria=new CDbCriteria;
		$criteria->condition = "MATCH (username,firstname,lastname) AGAINST(:term IN BOOLEAN MODE)";
		$criteria->params = array(
			':term' => "+$term*",
		);
        $criteria->order='username ASC';
        $criteria->limit=10;
        
        $models = User::model()->findAll($criteria);
~~~

It is bad if you have to specify the column names (of the fulltext index).
The function could have the following signature:

~~~
public CDbCriteria addFullTextSearchCondition(string $keyword, boolean $escape=true, string $operator='AND', string $mode='BOOLEAN')
~~~

This feature should use the feature #1208

**Comment by khurshedt9l** [comment]
what is $term in this

**Comment by kmindi** [comment]
`$term` refers to the search term we want to search for.

**Comment by khurshedt9l** [comment]
thank you so much for you very very quick responce
