### ISSUE TITLE
batch save and update to increase performance

### ISSUE THREAD

**Issue by Niklas-Peter** [yiisoft/yii#1255]
So far I have found no built-in possibility to do a batch insert or update.
If you add just 1 item per request it is OK as it is, but if you want to update many more you will have performance problems, just imagine a shop, that imports a product list in a loop...

I think that it should be possible to implement something like this using the SQL options like INSERT INTO (a,b) VALUES (c,d),(e,f),(g,h) etc.

Furthermore such an option could be used for the HAS_MANY or MANY_MANY relations, so that you can add many comments to a post and save all in one query.

Maybe the basis of these functionalities can be build in DAO, so that non-AR-users can use them, too. 

See:
http://www.yiiframework.com/forum/index.php/topic/34441-batch-save-and-update-to-increase-performance/page__p__165727__fromsearch__1#entry165727

**Comment by LHRchina** [comment]
This funcition is not security . It 's injection
