### ISSUE TITLE
getPathOfAlias('webroot') return wrong value in console applications at least with default settings

### ISSUE THREAD

**Issue by teo1978** [yiisoft/yii#1267]
yiic seems to be designed to be run from the "protected" directory, at least that's what all the tutorials suggest.

however, when you run a ConsoleApplication using yiic, at least without tweaking any of the default settings of a default installation, getPathOfAlias('webroot') will return the path of the protected directory, which usually not the webroot.

This seems to be because CApplication sets the path of webroot to dirname($_SERVER['SCRIPT_FILENAME'])
(https://github.com/yiisoft/yii/blob/1.1.12/framework/base/CApplication.php#L136) but that's the expected value only for web applications.

**Comment by dtmp** [comment]
if (get_class(Yii::app()) == 'CConsoleApplication') {
  preg_replace('/\/protected$/', '', Yii::getPathOfAlias('webroot'))
}

**Comment by wesslim** [comment]
is there any solution?
