### ISSUE TITLE
CActiveForm disable submit button option to prevent multiple form submits

### ISSUE THREAD

**Issue by qiangxue** [yiisoft/yii#128]
This is an enhancement request.

It would be nice if there was an option on the CActiveForm widget to enable disabling the Submit button on a successful form submission, to help prevent duplicate form submits.

I modified the default jquery.yiiactiveform.js file to do this. Attached is the modified JS file and the modified CActiveForm file to use it.

Basically, there are 3 new options on the ActiveForm widget:
-disableAfterSubmit (false by default)
-disableText (text displayed on the submit button while disabled)
-disableCssClass (css class to apply to the submit button while disabled

Then I added some code to the JS so that while submitting, the submit button is disabled, has the disabled CSS class, and says &quot;Please wait...&quot; by default.

If the AJAX validation is on and fails, the submit button is reactivated.

Regardless of whether you guys find my code usable or not, it would be a nice feature to have. I made this for my order/checkout form, to help prevent duplicate submissions. I am posting it here as an enhancement request after seeing this question on StackOverflow: http://stackoverflow.com/questions/7982637/yii-make-submit-disabled-when-post-is-processing

I would just release this as an extension, but I could not figure out a way to do this with the JS callback hooks provided, so I had to override the entire yiiactiveform.js file. This means the extension would need to be re-release any time a new Yii release modifies the ActiveForm js. But perhaps the answer is just to add more cleverly placed callback hooks in the JS, then make this an extension?

I just learned about jQuery's new Deferred pattern and can see a proper rewrite of the ActiveForm validation using Deferreds and Promises might be in order anyhow. ;P

Thanks for reading!
Cheers
<p>Migrated from http://code.google.com/p/yii/issues/detail?id=2924</p><hr/><h2>earlier comments</h2>
<p><strong>zaporojetsilya said, at 2011-11-08T14:19:43.000Z:</strong></p>
<p>How to use your scripts files?</p><p><strong>qiang.xue said, at 2012-01-01T03:36:55.000Z:</strong></p>
<p>set for 1.1.10 milestone</p><p><strong>thaddeusmt said, at 2012-01-04T03:52:38.000Z:</strong></p>
<p>Two updates / bugfixes to my code:

1) With (apparently) FireFox 8+ this code fails. I think it's triggering the $button.click(); event too soon - before the "disabled" attribute is removed maybe. It does not submit the form. I changed my code so it just submits with $form.submit(), which works for *my* purposes but watch out for that. Be sure to test in FF 8+.

2) There was a problem on Windows when using the asset manager in debug mode in my overridden ActiveForm.php where I call registerScriptFile(). It doesn't work with the DIRECTORY_SEPARATOR. I am using this now '/jquery.activeform.js'. But it won't matter if this is put in core, just a heads up for folks trying to use my code.

Cheers</p><p><strong>janek.jan said, at 2012-01-27T13:19:43.000Z:</strong></p>
<p>When not using validateOnSubmit here's a simple solution to just block submitting.

Add this to htmlOptions when initializing CActiveForm widget:
'onsubmit' => 'js:var settings = $(this).data("settings"); if (settings.submitting) {return false;} settings.submitting = true; $(this).data("settings",settings); return true;',

This code could be added as "else" block to "if (settings.validateOnSubmit)"

I was looking at jquery.yiiactiveform.js how it behaves with validateOnSubmit set to true and it is using "submitting" var, but I haven't checked that.
</p>

**Comment by chanifla** [comment]
hjg kutyt
