### ISSUE TITLE
Yii support pdo_odbc for mysql and mssql.

### ISSUE THREAD

**Issue by qiangxue** [yiisoft/yii#132]
I am using Yii framework 1.1.9.

I search for net and found that Yii cannot support pdo_odbc for mysql and mssql.

So, I have modified Yii Framework\db\CDBConnection.php
Line 415;

<pre><code>if(($pos=strpos($this-&gt;connectionString,':'))!==false)
{
  $driver=strtolower(substr($this-&gt;connectionString,0,$pos));
  if($driver==='mssql' || $driver==='dblib')
  $pdoClass='CMssqlPdoAdapter';
}
return new $pdoClass($this-&gt;connectionString,$this-&gt;username, $this-&gt;password,$this-&gt;_attributes);
</code></pre>

Which didn't reuse the function called getDriverName

So, I rewrite it to 

<pre><code>$driver=$this-&gt;getDriverName();
if($driver==='mssql' || $driver==='dblib')
  $pdoClass='CMssqlPdoAdapter';
return new $pdoClass($this-&gt;connectionString,$this-&gt;username, $this-&gt;password,$this-&gt;_attributes);
</code></pre>

For getDriverName function, I rewrote it when db object detect odbc the retrieve driver property.

<pre><code>public function getDriverName()
{
  if(($pos=strpos($this-&gt;connectionString, ':'))!==false)
  {
    $driverName = strtolower(substr($this-&gt;connectionString, 0, $pos));
    if ($driverName == 'odbc')
    {
      $connectionProperty = array();
      $connectionPropertyString = strtolower(substr($this-&gt;connectionString, $pos + 1));
      $connectionPropertyItems = explode(&quot;;&quot;, $connectionPropertyString);
      foreach($connectionPropertyItems as $connectionPropertyItem)
      {
        $items = explode(&quot;=&quot;, $connectionPropertyItem, 2);
        if (count($items) &gt; 1)
          $connectionProperty[strtolower(trim($items[0]))] = strtolower(trim($items[1]));
        else
          $connectionProperty[strtolower(trim($items[0]))] = '';
      }
      $driverType = $connectionProperty['driver'];
      if ($driverType == '{sql server}' || $driverType == '{sql server native client 10.0}' || $driverType == '{sql native client}')
      {
        $driverName='mssql';
      }
      elseif ($driverType == '{mysql}' || $driverType == '{mysql odbc 3.51 driver}' || $driverType == '{mysql odbc 5.1 driver}')
      {
        $driverName='mysql';
      }
    }
    return $driverName;
  }
  // return $this-&gt;getAttribute(PDO::ATTR_DRIVER_NAME);
}
</code></pre>

for windows php versio 5.2, we need download http://s3.paramorphicdesigns.com/random/php/php_pdo_odbc.dll patch which support to 5.2.17 (Because php has PDO ODBC: Long binary field in query result crashes PHP (&quot;Out of memory&quot; error)) Ref:http://www.mail-archive.com/php-bugs@lists.php.net/msg148533.html<p>Migrated from http://code.google.com/p/yii/issues/detail?id=3074</p><hr/><h2>earlier comments</h2>

<p><strong>yhlaikk said, at 2012-01-07T02:36:44.000Z:</strong></p>

<p>function createPdoInstance didn't reuse the function called getDriverName()</p><p><strong>coderkk said, at 2012-01-09T09:26:47.000Z:</strong></p>

<p>php_pdo_odbc Long binary field issue has fixed at PHP 5.4, I am testing yii at PHP 5.4 RC5 now

forget to tell you my connection string is 
'odbc:Driver={SQL Server Native Client 10.0};Server={host name};Database={database name};</p>

**Comment by williamyiu** [comment]
does yii2 support odbc with mssql?

**Comment by samdark** [comment]
Yes but it's better to use forums to ask questions.

**Comment by rapttor** [comment]
I got this problem with Yii 1.1.x project and almost got crazy: 

First make sure you have 

        sudo apt install php-xml php-mbstring php-pdo php-mysql 

installed, and restart apache

        sudo apachectl restart
        or: 
        sudo service apache2 restart

Detailed error was that **database library cannot be found**.

My solution was related to caching: 

        cache' => array(
            'class' => 'system.caching.CDbCache',
            //'class' => 'system.caching.CFileCache',
            'connectionID'=>'db', // <<< THIS IS THE ISSUE
        ),

if connectionID is not set, db caching defaults to mysqli database in /protected/data directory which cannot be accessed if mysqli driver is not installed on system (common issue with dedicated servers, DO droplets, xampp/wamp...)

or, you can disable db caching and enable fileCache instead.
