### ISSUE TITLE
Setup Oracle and MSSQL test server

### ISSUE THREAD

**Issue by cebe** [yiisoft/yii#1358]
As travis does not cover MSSQL and Oracle unit tests I'll try to setup a machine that can do unit testing with MSSQL and Oracle.

http://www.microsoft.com/sqlserver/en/us/editions/2012-editions/express.aspx
http://www.oracle.com/technetwork/products/express-edition/overview/index.html

**Comment by fommil** [comment]
wow, this sounds amazing. I'd love to be able to run integration tests against the gratis versions of MS-SQL and Oracle. Is there a recipe or an example project somewhere that I can use as template?

**Comment by fommil** [comment]
oh, darn, are you guys just talking to your own oracle/mssql? nothing in your config :cry: https://github.com/SOCI/soci/blob/master/.travis.yml

**Comment by mloskot** [comment]
@fommil If you follow what we do for SOCI, you need to look here as we have split a typical Travis CI one-file config into separate Bash scripts https://github.com/SOCI/soci/tree/master/bin/ci

I haven't tried MS SQL yet.

**Comment by fommil** [comment]
@mloskot I have MS-SQL working on a local Debian machine. Just need to get travis to let me install some applications in their docker env and then we can integration test it in CI :smile:. Feel free to have a look at what we've done and let me know if you build on it, for example SyBase or Oracle provisioning.

**Comment by ribasushi** [comment]
@fommil Could you link to the final setup you ended up with ( the one you mention in https://github.com/yiisoft/yii/issues/1358#issuecomment-73209836 ). Thank you!

**Comment by samdark** [comment]
I'm interested as well. Could be great for Yii 2.0.

**Comment by fommil** [comment]
smootoo/freeslick

**Comment by mloskot** [comment]
@fommil Yes, links would be helpful. I'm still interested. Thanks!

**Comment by samdark** [comment]
https://github.com/smootoo/freeslick

**Comment by samdark** [comment]
@fommil thanks.
