### ISSUE TITLE
Blog tutorial text and blog demo application should be improved to use a new features

### ISSUE THREAD

**Issue by resurtm** [yiisoft/yii#1384]
https://github.com/yiisoft/yii/tree/master/docs/blog
https://github.com/yiisoft/yii/tree/master/demos/blog

Many things have to be altered and improved so that the blog tutorial and application would use new framework features. A striking examples:
- https://github.com/yiisoft/yii/blob/master/demos/blog/protected/controllers/PostController.php — generated CRUD looks a bit different since application was created (e.g. $_GET parameters could be passed as an action arguments);
- https://github.com/yiisoft/yii/blob/master/demos/blog/protected/views/post/index.php — generated views became slightly different;
- etc.

I think that it is quite important for beginners and newcomers when tutorials matches the main code.

**Comment by samdark** [comment]
Won't be done because Yii 1.1 is reaching its EOL.
