### ISSUE TITLE
Exception in CHttpSession

### ISSUE THREAD

**Issue by teo1978** [yiisoft/yii#1416]
I have no idea what triggered this and I don't know what session regeneration is. This happened on an ajax request initiated by the rbam module (i got the trace in an alert popup), but I guess this may have happened on any random request. 

I neither logged in nor logged out. I had been logged in for a very long time (with the "remember me" option activated).

Error 500: <h1>PHP Error [2]</h1>

<p>session_regenerate_id() [<a href='function.session-regenerate-id'>function.session-regenerate-id</a>]: Session object destruction failed (/var/www/vhosts/megafone.net/httpdocs/yii/framework/web/CHttpSession.php:182)</p>

<pre>#0 unknown(0): CWebApplication->handleError()
#1 /var/www/vhosts/megafone.net/httpdocs/yii/framework/web/CHttpSession.php(182): session_regenerate_id()
#2 /var/www/vhosts/megafone.net/httpdocs/yii/framework/web/auth/CWebUser.php(700): CHttpSession->regenerateID()
#3 /var/www/vhosts/megafone.net/httpdocs/yii/framework/web/auth/CWebUser.php(451): WebUser->changeIdentity()
#4 /var/www/vhosts/megafone.net/httpdocs/yii/framework/web/auth/CWebUser.php(196): WebUser->restoreFromCookie()
#5 /var/www/vhosts/megafone.net/httpdocs/yii/framework/base/CModule.php(388): WebUser->init()
#6 /var/www/vhosts/megafone.net/httpdocs/yii/framework/web/CWebApplication.php(210): CWebApplication->getComponent()
#7 /var/www/vhosts/megafone.net/httpdocs/yii/framework/web/auth/CAccessControlFilter.php(120): CWebApplication->getUser()
#8 /var/www/vhosts/megafone.net/httpdocs/yii/framework/web/filters/CFilter.php(39): CAccessControlFilter->preFilter()
#9 /var/www/vhosts/megafone.net/httpdocs/yii/framework/web/CController.php(1146): CAccessControlFilter->filter()
#10 /var/www/vhosts/megafone.net/httpdocs/yii/framework/web/filters/CInlineFilter.php(59): AuthItemsController->filterAccessControl()
#11 /var/www/vhosts/megafone.net/httpdocs/yii/framework/web/filters/CFilterChain.php(131): CInlineFilter->filter()
#12 /var/www/vhosts/megafone.net/httpdocs/yii/framework/web/CController.php(292): CFilterChain->run()
#13 /var/www/vhosts/megafone.net/httpdocs/yii/framework/web/CController.php(266): AuthItemsController->runActionWithFilters()
#14 /var/www/vhosts/megafone.net/httpdocs/yii/framework/web/CWebApplication.php(283): AuthItemsController->run()
#15 /var/www/vhosts/megafone.net/httpdocs/yii/framework/web/CWebApplication.php(142): CWebApplication->runController()
#16 /var/www/vhosts/megafone.net/httpdocs/yii/framework/base/CApplication.php(162): CWebApplication->processRequest()
#17 /var/www/vhosts/megafone.net/httpdocs/yiiindex.php(13): CWebApplication->run()
</pre>

**Comment by samdark** [comment]
Closing since no occurrences since 2012...

**Comment by teo1978** [comment]
Don't the last three comments point to the cause of the issue and a possible solution??

In my case, the reason why I stopped observing the issue is just that I forced the "remember me" option (whatever it is called in the framework which I don't remember now) and don't even show it to the user. But that is obviously not a solution.
