### ISSUE TITLE
getLastInsertID not working properly in MySQL with certain configurations

### ISSUE THREAD

**Issue by c-schmitz** [yiisoft/yii#1557]
Reproducable with MySQL 5.5 and PHP 5.3.8

When running 

```
        $result = Yii::app()->db->createCommand()->insert('{{groups}}', $someinsertdata);
        $newgid=Yii::app()->db->getCommandBuilder()->getLastInsertID('{{groups}}');
```

$newgid is returning 0

Expected result: Returning the last Insert ID

The same statement works on Postgres and MSSQL just fine.

I debugged into this and the reason for that is MySQL seems to loose the sequence ID because getCommandBuilder executes additional statements on the database:

```
    SHOW COLUMNS FROM `groups`
SHOW CREATE TABLE `groups`
```

After these statements MySQL/PDO always gives back 0. 

Since we are maintaining a huge cross-DB FOSS application this has become real trouble for us which will most likely end in writing a helper function which uses the right statement related to the database type. 
However      

```
   getCommandBuilder()->getLastInsertID('<sometablename>');
```

should always return the same output no matter which database type is used.

**Comment by mochalygin** [comment]
@samdark 
It may be reproduced if auto_increment field is not the Primary key -- always returns 0

**Comment by mochalygin** [comment]
> It may be reproduced if auto_increment field is not the Primary key -- always returns 0

FYI, it is PDO problem, Yii just uses wrong PDO answer
