### ISSUE TITLE
关于app不run的notice BUG

### ISSUE THREAD

**Issue by qq71151461** [yiisoft/yii#1558]
入口文件代码如下：

```
$yii = dirname(__FILE__) . '/../yii/framework/YiiBase.php';
$config = dirname(__FILE__) . '/protected/config/main.php';
// remove the following lines when in production mode
defined('YII_DEBUG') or define('YII_DEBUG', true);
// specify how many levels of call stack should be shown in each log message
defined('YII_TRACE_LEVEL') or define('YII_TRACE_LEVEL', 3);
require_once($yii);

class Yii extends YiiBase {

    /**
     * @static
     * @return CWebApplication
     */
    public static function app() {
        return parent::app();
    }
}

Yii::createWebApplication($config);
```

这里有一个notice错误，如：
$tt = $_GET["tttt"];tttt参数不存在

会导致发生
Fatal error: Nesting level too deep - recursive dependency。

XDEBUG信息如下：
Fatal error: Nesting level too deep - recursive dependency? in E:\www\yii\framework\base\CErrorHandler.php on line 417
Call Stack
# Time    Memory  Function    Location

1   0.0012  389000  {main}( )   ..\pay.php:0
2   0.0269  2015368 CApplication->handleError( )    ..\pay.php:28
3   0.0312  2746064 CErrorHandler->handle( )    ..\CApplication.php:803
4   0.0312  2705296 CErrorHandler->handleError( )   ..\CErrorHandler.php:131
5   0.0313  2709816 CErrorHandler->render( )    ..\CErrorHandler.php:287
6   0.0317  2739648 include( 'E:\www\yii\framework\views\exception.php' )   ..\CErrorHandler.php:338
7   0.0337  2740440 CErrorHandler->argumentsToString( ) ..\exception.php:204

**Comment by samdark** [comment]
Closing since it seems no to be valid anymore.
