### ISSUE TITLE
COutputCache should respect Content-Type headers

### ISSUE THREAD

**Issue by navarr** [yiisoft/yii#1565]
Right now COutputCache (when used as a filter) does not listen for any headers sent with the page, so far as I can tell.

This means that it can not cache json, images, or other content that might be dynamic without extending upon it.

COuputCache should honor at least the content-type header sent by the page when it is being used as a filter.

**Comment by martinytodorov** [comment]
I just added a new class that will help me with the caching of the RESTful module and its headers:
```
class ApiOutputCache extends COutputCache
{

    public function init()
    {
        if(Get('format') == 'xml')
            $content_type = 'text/xml';
        else
            $content_type = 'application/json';

        header('Content-type: ' . $content_type . ";charset=utf-8");
        return parent::init();
    }

}
```
