### ISSUE TITLE
enableClientValidation+enableAjaxValidation = random bogus validation errors on valid fields

### ISSUE THREAD

**Issue by teo1978** [yiisoft/yii#1600]
I don't know the exact pattern to reproduce the issue, but

On a form with both ajax validation and client-side validation (maybe just ajax validation is enough to reproduce), if you type fast enough and use the TAB key to go from a field to another, you can randomly get some bogus validation errors. The one that I get most frequently is "xxxx cannot be blank" for required fields that I _have_ filled.

When this happens, it is especially difficult to get rid of the bogus error. You go back to the field, you edit it, and it keeps complaining. Desperately deleting the field, randomly editing other fields, and so on, will eventually allow you to get it validated succesfully, but I never figured out the exact pattern.

**Comment by teo1978** [comment]
Why closed??

**Comment by samdark** [comment]
http://www.yiiframework.com/news/90/update-on-yii-1-1-support-and-end-of-life/
