### ISSUE TITLE
Active Record foreach error in relations when no primary key defined

### ISSUE THREAD

**Issue by qiangxue** [yiisoft/yii#176]
<b>What steps will reproduce the problem?</b>
1.create table with no primary key
2.create a relation to from that table to another (with or without primary key)
3.attempt to use it

<b>What is the expected output? What do you see instead?</b>
join on the specified FK or array('t1.column'=&gt;'t2.column')

<b>What version of the product are you using? On what operating system?</b>
r3484 on linux

<b>Please provide any additional information below.</b>
In CActiveFinder Line 481 defaults to an array of primary keys if the primary key in the schema isn't a string, causing the foreach error. 

Replacing this line with &quot;elseif (is_array($this-&gt;_table-&gt;primaryKey))&quot; allows it to skip over the PK storage and continue. This is not completely tested but fixed my specific problem, I'm not versed enough in active record to suggest it as an immediate fix before someone can look it over. :)<p>Migrated from http://code.google.com/p/yii/issues/detail?id=3023</p><hr/><h2>earlier comments</h2>

<p><strong>paystey2k5 said, at 2011-12-14T15:55:45.000Z:</strong></p>

<p>I should explain that when joining the relation simply providing a one column FK obviously won't work in HAS_ONE as it needs the foreign table column to equal the base tables primary key. But the BELONGS_TO should work with only a primary key as should specifying an array of column=>column values.</p><p><strong>qiang.xue said, at 2012-01-01T03:36:55.000Z:</strong></p>

<p>set for 1.1.10 milestone</p><p><strong>paystey2k5 said, at 2012-01-13T13:24:44.000Z:</strong></p>

<p>Here's my current fix attached</p>

**Comment by johnss** [comment]
It should generate a CException primary key not found error instead of the foreach error, it make me think that the error is in yii code syntax, need several hour to know that the error is because of no primary key defined, also yii should has the ability to manually set primary key, is this already implemented ?

**Comment by cebe** [comment]
you can override this method: http://www.yiiframework.com/doc/api/1.1/CActiveRecord#primaryKey%28%29-detail to define the primary key manually

**Comment by johnss** [comment]
I'm still dont know why yii not throwing an exception, it will make it the programmer know what is wrong, the error is in the sql schema not in CActiveFinder.

it takes me lot of time to know the error, is there any reason for not throwing exception ?

**Comment by cebe** [comment]
the code at this place is run a lot of times, checking for possible problems in your db layout all the time it runs will slow it down significantly.
