### ISSUE TITLE
activeCheckBox client-side validation problem

### ISSUE THREAD

**Issue by Ziggizag** [yiisoft/yii#1869]
Hmm,

This looks like a bug actually but you may be more clever than myself:

presuming we have a form:

``` php
<div class="form">

<?php

$form=$this->beginWidget('CActiveForm', array(
    'id'=>'users-form',
    'enableClientValidation'=>true,
    'clientOptions' => array(
        'validateOnSubmit'=>true,
        'validateOnChange'=>true,
        'validateOnType'=>false,
    ),
));

?>

<div class="row">
        <?php echo $form->labelEx($model, 'active'); ?>
        <?php echo $form->checkBox($model, 'active', array('uncheckValue'=>0)); ?>
        <?php echo $form->error($model,'active'); ?>
</div>
```

Having client-side validation enabled this way it is imposible to uncheck the 'active' checkbox in case:

``` php
array('active', 'required', 'message'=>'{attribute} cannot be null !')
```

is within model validation rules. Simply - client-side validation throws validation error.

This looks like a discrepancy as the class documentation reads clear:

"A special option named 'uncheckValue' is available that can be used to specify the value returned when the checkbox is not checked. By default, this value is '0'. Internally, a hidden field is rendered so that when the checkbox is not checked, we can still obtain the posted uncheck value. If 'uncheckValue' is set as NULL, the hidden field will not be rendered."

And this is working actually in case form is submitted having client validation switched off. But it seems client validation javascript is unaware of this documentation and does not observe a hidden field!

**Comment by mmshlrfsh** [comment]
Today I used this validator in a project with this code:
```php
<?php $form = $this->beginWidget('CActiveForm', array(
    'id' => 'category-form',
    'enableClientValidation' => true,
    'clientOptions' => array(
        'validateOnSubmit' => true,
        'validateOnChange'=>true,
        'validateOnType'=>false,
    ),
    'focus' => array($category, 'name'),
    'htmlOptions' => array(
        'class' => 'form-horizontal',
    ),
)); ?>
<div class="form-group">
    <?php echo $form->labelEx($category, 'confirmed', array('class'=>'control-label col-sm-2')); ?>
    <div class="col-sm-4">
        <?php echo $form->checkBox($category, 'confirmed', array('class'=>'form-control','style'=>'font-size:14pt;')); ?>
    </div>
    <div class="col-sm-6"><span style="color:red;"><?php echo $form->error($category, 'confirmed'); ?></span></div>
</div>
```
With the validation rule:
```php
array('confirmed', 'required'),
```
And the validation error displayed when I unchecked the checkbox element.

**Comment by cebe** [comment]
@mmshlrfsh this issue is already closed for milestone 1.1.14, please open a new issue.
Also I do not get the problem, if you uncheck a checkbox which is required you should get a validation error.

**Comment by mmshlrfsh** [comment]
@cebe You're right. If it's required, it is but when I uncheck the checkbox, the default value (zero) is posted and of course, zero is not null. I think the implementation of this validator is somehow weird because it takes zero equal to null !

**Comment by cebe** [comment]
I do not see uncheckValue in your code example...

**Comment by mmshlrfsh** [comment]
@cebe
Of course it's not mentioned in my code because it's the default value which yii uses and when the form is generated, I can see the hidden form element with 0 value inserted inside the form. It's not necessary to hard code the default uncheck value unless you want to use another value (not zero). Please read the yii docs about the CUniqueValidator.

**Comment by cebe** [comment]
Now I am getting really confused, what has CUniqueValidator to do with all this?
Please open a new issue, this seems not related and the issue is already closed.
