### ISSUE TITLE
Passing additional data to the CGridView

### ISSUE THREAD

**Issue by undsoft** [yiisoft/yii#1883]
This is a minor feature request.

It would be nice to be able to pass additional data to the CGridView for use in column expressions.
I know that you can easily do this by extending CGridView class and adding additional property, but wouldn't it be nice to have this feature out of the box?

Just adding $data or $columnData property to the CGridView should do the trick.

It's a small change. I may do it myself later.

**Comment by wajdijurry** [comment]
It works for me :)
Thanks for the tip
