### ISSUE TITLE
CTestCase PHPUnit 3.7.10 autoload fails

### ISSUE THREAD

**Issue by Ragazzo** [yiisoft/yii#1907]
I know there are some issues about that (phpunit < 3.7.10) and looks like there were solved but, i got this problem, need to notice that problem occures when tests fails:
When i run unit tests, Yii::autoloader throws Exceptions on not found files, this files:

```
PHP_invoker.php, PHPUnit_Extensions_Database_TestCase.php, PHPUnit_Extensions_Story_TestCase.php
```

on 
`YiiBase::autoload() ...\php\pear\PHPUnit\Util\GlobalState.php:0`
So i found that problem again in autoloader order, if i comment  `spl_autoload_register(array('YiiBase','autoload')); // put yii's autoloader at the end` than no exceptions will be thrown by Yii::autoload() even if there is a fail test. But if i run WebTestCase tests Yii autoload throws errors again.
So is it my problem or its a Yii bug or phpunit bug? Btw. spl autoloaders list is correct (Yii autoload is the last one). Could it be because of in YiiBase at the end of the file there is already `spl_autoload_register(array('YiiBase','autoload'));` ?

**Comment by marcovtwout** [comment]
Does PHPUnit 4.6 fix this issue?

https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-4.6.md
"Fixed #1599: The PHAR build of PHPUnit no longer uses an autoloader to load PHPUnit's own classes and instead statically loads all classes on startup"

**Comment by marcovtwout** [comment]
Unfortunately, no:

```
PHPUnit 4.6.2 by Sebastian Bergmann and contributors.

Configuration read from S:\www\xxx\application\tests\phpunit.xml

F
Warning: include(PHP_Invoker.php): failed to open stream: No such file or directory in S:\www\xxx\application\vendor\yiisoft\yii\framework\YiiBase.php on line 432
```

**Comment by marcovtwout** [comment]
(this issue still exists in PHPUnit 6 when running tests from NetBeans)
