### ISSUE TITLE
Search on bigint using the LIKE operator

### ISSUE THREAD

**Issue by bsagal** [yiisoft/yii#1912]
I have a table with a bigint column, when tying to preform a search a get the the following exception:

```
Error 500: <h1>CDbException</h1>
<p>התרחשה שגיאה בעת הרצת שאילתה בעזרת CDbCommand. השגיאה: SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: bigint ~~ unknown
LINE 1: SELECT COUNT(*) FROM "meter" "t" WHERE (id LIKE '%1860240090...
                                                   ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.. The SQL statement executed was: SELECT COUNT(*) FROM "meter" "t" WHERE (id LIKE :ycp0) AND (current_reading=:ycp1). Bound with :ycp0='%18602400902%', :ycp1='1102' 
```

It seems like the like operator is used in the comparison but is not supported by the database for the bigint column.

DB:     postgresql 9.1
PHP:  5.4.8
yii:       1.1.13

**Comment by thehiddennepali** [comment]
Hi also stucked with pg admin 

What I am trying to search the model with date_cated where date is input by select from datepicker

and I got the error as below:

<h1>CDbException</h1>
<p>CDbCommand failed to execute the SQL statement: SQLSTATE[42883]: Undefined function: 7 ERROR:  operator does not exist: timestamp without time zone >= integer
LINE 1: ... COUNT(*) FROM "block_mac" "t" WHERE date_created BETWEEN -3...
                                                             ^
HINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.. The SQL statement executed was: SELECT COUNT(*) FROM "block_mac" "t" WHERE date_created BETWEEN :ycp0 AND :ycp1 (E:\xampp\htdocs\yii\framework\db\CDbCommand.php:528)</p><pre>

"
