### ISSUE TITLE
多字段联合的唯一性验证

### ISSUE THREAD

**Issue by qiangxue** [yiisoft/yii#201]
框架里的唯一性验证都是单一字段的，或者自己加验证条件（criteria或function），可是实际应用中很多都是联合几个字段的不能相同，比如同一城市下有两个名称相同的县等。

看到有人写了一个扩展unique-multiple-columns-validate，
不知道强有没有考虑下集成这种情况到框架里。。。 

就算是新的需求吧。。。<p>Migrated from http://code.google.com/p/yii/issues/detail?id=2372</p><hr/><h2>earlier comments</h2>
<p><strong>chenggang.china said, at 2011-07-04T08:42:24.000Z:</strong></p>
<p>Perfect!</p><p><strong>qiang.xue said, at 2012-01-01T03:36:54.000Z:</strong></p>
<p>set for 1.1.10 milestone</p>

**Comment by likunyan** [comment]
// a1 and a2 need to be unique together, and they both will receive error message
[['a1', 'a2'], 'unique', 'targetAttribute' => ['a1', 'a2']]
