### ISSUE TITLE
CDbCommandBuilder.createInCondition() doesn't use sql parameter binding

### ISSUE THREAD

**Issue by MonkeyMaster** [yiisoft/yii#2031]
<code>CDbCommandBuilder.createInCondition()</code> puts column values directly in SQL statement instead of binding them. Since <code>CActiveRecord.findByPk()</code> calls it and is used very often, database server load is increased due to frequent query parsing for literal values.

Please apply param binding for that method.

**Comment by samdark** [comment]
It's true for repeated queries with the same number of parameters but false otherwise.
