### ISSUE TITLE
Command builder - wrong SQL for delete with joins in MySQL

### ISSUE THREAD

**Issue by serebrov** [yiisoft/yii#2159]
When use criteria with joins in createDeleteCommand the generated SQL is wrong.
Example:

``` php
$builder->createDeleteCommand($table,new CDbCriteria(array(
    'condition'=>'u.`username`=:username and `posts`.`title`=:title',
    'join'=>'JOIN `users` u ON `author_id`=u.`id`',
    'params'=>array(':username'=>'user1', ':title'=>'new post delete'))));
```

Generated SQL:

``` SQL
DELETE FROM `posts` JOIN `users` u ON `author_id`=u.`id` 
WHERE u.`username`=:username and `posts`.`title`=:title
```

Correct SQL:

``` SQL
DELETE `posts` FROM `posts` JOIN `users` u ON `author_id`=u.`id` 
WHERE u.`username`=:username and `posts`.`title`=:title
```

Related links:
- issue #124 and pull request 525 (https://github.com/yiisoft/yii/pull/525)
- issue #1645
- http://www.yiiframework.com/forum/index.php/topic/40245-i-think-there-is-a-flaw-in-the-code-for-createdeletecommand/page__gopid__193809#entry193809
- http://www.yiiframework.com/forum/index.php/topic/14936-cdbcriteria-deleteall-problems/

**Comment by lamarck001** [comment]
Same think happens when using mssql

Example:
```php
$criteria = new CDbCriteria();
$criteria->select = 'param_data';	
$criteria->join ='JOIN ticket_data ON param_data.ticket_data_id = ticket_data.ticket_data_id';		
$criteria->condition ='ticket_data.ticket_data_id is null';		
$command = Yii::app()->db->schema->commandBuilder->createDeleteCommand('param_data', $criteria);
```
Generated SQL:
```sql
DELETE FROM [dbo].[param_data] JOIN ticket_data ON param_data.ticket_data_id = ticket_data.ticket_data_id WHERE ticket_data.ticket_data_id is null
```

Correct SQL:
```sql
DELETE [dbo].[param_data] FROM [dbo].[param_data] JOIN ticket_data ON param_data.ticket_data_id = ticket_data.ticket_data_id WHERE ticket_data.ticket_data_id is null
```

Fix: in db\schema\CDbCommandBuilder.php line: 19
```php
$sql="DELETE {$table->rawName} FROM {$table->rawName}";
```

**Comment by serebrov** [comment]
@lamarck001 - I fixed this for MySQL only, the fix is not complex, see the changes here - https://github.com/yiisoft/yii/pull/2160/files

**Comment by lamarck001** [comment]
Okay i see it now.
I'm no expert but wouldn't be easier to add {$table->rawName} to CDbCommandBuilder than changing applyJoin($sql,$join) for both MySQL and MSSQL?

**Comment by serebrov** [comment]
It was almost two years ago, so I don't remember the details, but it can be related to slightly different SQL syntax in different DBs.
It may be the same for MySQL and MSSQL, but is it the same for all supported databases?

**Comment by lamarck001** [comment]
Guess you are right. I'm just reading about Sqlite (https://www.sqlite.org/lang_delete.html).
