### ISSUE TITLE
Bug in CMemCache.php

### ISSUE THREAD

**Issue by ardicoetzee** [yiisoft/yii#2164]
Little more details can be found here: http://stackoverflow.com/questions/14954778/yii-time-caching-not-working/14956296

But in a nutshell... this:

``` php
protected function setValue($key,$value,$expire)
{
  if($expire>0)
    $expire+=time();
  else
    $expire=0;

  return $this->useMemcached ? $this->_cache->set($key,$value,$expire) : $this->_cache->set($key,$value,0,$expire);
}
```

Must be changed to:

``` php
protected function setValue($key,$value,$expire)
{
  return $this->useMemcached ? $this->_cache->set($key,$value,$expire) : $this->_cache->set($key,$value,0,$expire);
}
```

Because Memcache does not want the time to be added to expire, but rather just the seconds from now that it must expire.

**Comment by boazrymland** [comment]
Just hit the same issue. I use memcached on Linux (stock Ubuntu 14.04-2 packages), Yii v1.1.16.

I needed to use a timestamp of 'this midnight' as the expiration date for the cache record. Output of the convenient command
```php
strtotime('tomorrow midnight');
```
When I used it, the cache record didn't stay in the cache at all. Short dive into CMemCache.setValue() discovered what's described above. Actually, I have my own child class that extends CMemCache and supports memcache**d** only (and adds support for 'cas()' method of memcached, which was the reasoning for this extension). So I changed the setValue() code to simply:
```php
protected function setValue($key, $value, $expire = 0)
    {
        return $this->_cache->set($key, $value, $expire);
    }
```
And now it functions as expected.
