### ISSUE TITLE
CHttpRequest::decodePathInfo crash PHP on windows for a long pathInfo

### ISSUE THREAD

**Issue by Maxsh** [yiisoft/yii#2292]
Regular expressions in the decodePathInfo() method crash PHP on a windows platform.
I've tested on 3 win platforms and got an error when I was trying use pathInfo with length around 310 characters and more
This issue is known. Please see for details
http://stackoverflow.com/questions/1282986/utf-8-validation-in-php-without-using-preg-match

Please see log from win machine:
Имя сбойного приложения: httpd.exe, версия: 2.2.22.0, отметка времени: 0x4f242d7a
Имя сбойного модуля: php5ts.dll, версия: 5.3.11.0, отметка времени 0x4f97356f
Код исключения: 0xc00000fd
Смещение ошибки: 0x0018b5d3
Идентификатор сбойного процесса: 0x1598
Время запуска сбойного приложения: 0x01ce3074ef780b8b
Путь сбойного приложения: C:\Program Files (x86)\Apache Software Foundation\Apache2.2\bin\httpd.exe
Путь сбойного модуля: C:\Program Files (x86)\PHP\php5ts.dll
Код отчета: 7e848139-9c68-11e2-bfeb-bcaec5bd8575

**Comment by Corfiot** [comment]
I opted for the workaround in the config file. This will allow configuration of the recursion limit at will, at least until this is permanently solved.

//https://github.com/yiisoft/yii/issues/2292
ini_set('pcre.recursion_limit',100);
