### ISSUE TITLE
session_regenerate_id(): Session object destruction failed 

### ISSUE THREAD

**Issue by markoffk** [yiisoft/yii#2376]
When I am trying to log-in after logging off, I getting such WARNING:
D:\work\localhost\yii-1.1.13\framework\web\CHttpSession.php(185)

This WARNING appears randomly.

```
183     public function regenerateID($deleteOldSession=false)
184     {
185         session_regenerate_id($deleteOldSession);
186     }
```

If I add check to code:

```
183     public function regenerateID($deleteOldSession=false)
184     {
185         if (session_status() != PHP_SESSION_ACTIVE)
186           session_regenerate_id($deleteOldSession);
187     }
```

Then the problem (warning) disappears.

**Comment by suriyabaskaran** [comment]
@samdark  i am running into same issue, if i use CRedisCache as my session component on Yii 1.1.17.
My system is configured as,

1. Ubuntu 14.04 LTS
2. Apache 2.4.7
3. PHP Version 7.0.3-5+deb.sury.org~trusty+1 (php7.0-fpm)
4. redis-server 2.8.4

Trace log,

> 2016/02/23 12:49:27 [error] [php] session_regenerate_id(): Cannot regenerate session id - session is not active (/var/www/html/library/framework/yiilite.php:4615)
Stack trace:
#0 /var/www/html/library/framework/yiilite.php(4361): WebUser->changeIdentity()
#1 /var/www/html/library/framework/yiilite.php(4220): WebUser->restoreFromCookie()
#2 /var/www/html/library/framework/yiilite.php(1073): WebUser->init()
#3 /var/www/html/library/framework/yiilite.php(925): CWebApplication->getComponent()
#4 /var/www/html/protected/components/Controller.php(156): CWebApplication->__get()
#5 /var/www/html/protected/controllers/SiteController.php(10): SiteController->init()
#6 /var/www/html/library/framework/yiilite.php(1767): SiteController->init()
#7 /var/www/html/library/framework/yiilite.php(1688): CWebApplication->runController()
#8 /var/www/html/library/framework/yiilite.php(1205): CWebApplication->processRequest()
#9 /var/www/html/index.php(16): CWebApplication->run()
REQUEST_URI=/
in /var/www/html/protected/components/Controller.php (156)
in /var/www/html/protected/controllers/SiteController.php (10)
in /var/www/html/index.php (16)

**Comment by coolcflame87** [comment]
same issue, using  CRedisCache as my session component on Yii 1.1.17.

CentOS 6 x64
Nginx 1.8.1
PHP 7.0.3 with OPcache enable
redis-server 3.0.7

Trace log,

```
[error] [php] session_regenerate_id(): Session callback expects true/false return value (/var/www/yii-main/framework/1.1.17/yiilite.php:4614)
Stack trace:
#0 /var/www/yii-main/framework/1.1.17/yiilite.php(4233): YumWebUser->changeIdentity()
#1 /var/www/protected/modules/user/controllers/YumAuthController.php(256): YumWebUser->login()
#2 /var/www/protected/modules/user/controllers/YumAuthController.php(56): YumAuthController->authenticate()
#3 /var/www/protected/modules/user/controllers/YumAuthController.php(348): YumAuthController->loginByUsername()
#4 unknown(0): YumAuthController->actionLogin()
#5 /var/www/yii-main/framework/1.1.17/yiilite.php(4147): ReflectionMethod->invokeArgs()
#6 /var/www/yii-main/framework/1.1.17/yiilite.php(4164): CInlineAction->runWithParamsInternal()
#7 /var/www/yii-main/framework/1.1.17/yiilite.php(3678): CInlineAction->runWithParams()
#8 /var/www/yii-main/framework/1.1.17/yiilite.php(6922): YumAuthController->runAction()
#9 /var/www/yii-main/framework/1.1.17/yiilite.php(6931): CFilterChain->run()
#10 /var/www/yii-main/framework/1.1.17/yiilite.php(4056): CAccessControlFilter->filter()
#11 /var/www/yii-main/framework/1.1.17/yiilite.php(6964): YumAuthController->filterAccessControl()
#12 /var/www/yii-main/framework/1.1.17/yiilite.php(6919): CInlineFilter->filter()
#13 /var/www/yii-main/framework/1.1.17/yiilite.php(3668): CFilterChain->run()
#14 /var/www/yii-main/framework/1.1.17/yiilite.php(3653): YumAuthController->runActionWithFilters()
#15 /var/www/yii-main/framework/1.1.17/yiilite.php(1768): YumAuthController->run()
#16 /var/www/yii-main/framework/1.1.17/yiilite.php(1688): CWebApplication->runController()
#17 /var/www/yii-main/framework/1.1.17/yiilite.php(1205): CWebApplication->processRequest()
#18 /var/www/index.php(45): CWebApplication->run()
REQUEST_URI=/user/auth/login
```
