### ISSUE TITLE
endCache() should accept a CacheDependency, rather than beginCache

### ISSUE THREAD

**Issue by teo1978** [yiisoft/yii#2391]
When you call beginCache() and endCache(), you can only pass a dependency to beginCache().
Instead, you should be able to pass a dependency to endCache(), rather than (or as well as) to beginCache().

When you're done building the contents to be cached, _that_'s when you know on what the cached fragment should depend. Not always can you know it a priori.

I'm under the impression that this can be accomplished with COutputCache (can't it?) by assigning the dependency property after beginwidget() and before endwidget(). However, this limitation obliges you to use COutputCache directly, loosing the advantages of the shorthand methods beginCache() and endCache()

**Comment by teo1978** [comment]
I see you are massively closing bugs, I guess those which you consider feature requests (while some of them are rather design flaws, as in this case).
Are they all implemented/fixed in Yii 2? If not, are you opening the corresponding issues in Yii2?

**Comment by samdark** [comment]
Most of these are fixed or do not exist in 2.0.
