### ISSUE TITLE
Trouble managing table names containing spaces by CDbCommand

### ISSUE THREAD

**Issue by devivan** [yiisoft/yii#2399]
Hi,
using a Microsoft SQL server I found table names with spaces O_o.

I fixed this problem in /framework/db/CDbCommand.php line 707 and 1562 (Yii ver 1.1.13)
from:
	if(preg_match('/^(.*?)(?i:\s+as\s+|\s+)(.*)$/',$table,$matches))  // with alias
to:
	if(preg_match('/^(.*?)(?i:\s+as|)\s+(\w+)$/',$table,$matches))  // with alias

The regex idea is:
- mantain the back compatibility
- the alias must not have any space in the name
- if the tablename has one or more spaces you MUST use the AS particle to seaparate tablename from alias

**Comment by samdark** [comment]
Fixed.
