### ISSUE TITLE
Missing / broken documentation definition for CFileValidator->sizeToBytes (table only)

### ISSUE THREAD

**Issue by trejder** [yiisoft/yii#2421]
Documentation for [CFileValidator->sizeToBytes](http://www.yiiframework.com/doc/api/1.1/CFileValidator#sizeToBytes-detail) is fine in details section, but in summary table, in the beginning of page, it is broken prematurely after _size suffix_ words.

See _Public Methods_ table. After clicking `Hide inherited methods`, problematic table row is the only visible (`Description` column).

**Comment by cebe** [comment]
fixed, thanks for reporting!
