### ISSUE TITLE
CListView documentation is broken

### ISSUE THREAD

**Issue by ifdattic** [yiisoft/yii#2489]
I think the documentation for [CListView](http://www.yiiframework.com/doc/api/1.1/CListView/) is broken.

The description of some class properties is cut off.
For example:
```
baseScriptUrl - 'the base script URL for all list view resources (e.'
enableHistory - 'whether to leverage the {@link https://developer.'
```

**Comment by samdark** [comment]
Looks like it's OK.

**Comment by cebe** [comment]
yeah, I fixed that some time ago.
