### ISSUE TITLE
Docs: text overlay

### ISSUE THREAD

**Issue by ifdattic** [yiisoft/yii#2490]
While checking the documentation I noticed that that long method names escape their allocated space on overlays the text on description column (e.g [docs page](http://www.yiiframework.com/doc/api/1.1/CMysqlCommandBuilder))

A fix like `word-wrap: break-word;` probably wouldn't be very good, but it would still be better than text stacking on each other.

**Comment by cebe** [comment]
will be fixed on the new website. https://github.com/yiisoft-contrib/yiiframework.com
