### ISSUE TITLE
Yii::app()->cache->delete($cacheId) is not working

### ISSUE THREAD

**Issue by a-amiri** [yiisoft/yii#2541]
@samdark 
I should cache a "user_profile" that is combination of (at least) 4 records from 4 tables.

using dependency has no performance, since I should check the 'update_time' fieldes of 4 records in 4 tables!

I thought it will be useful if every time any information of a user's profile updates in DB, I just delete the cached page of that user. so in the next visit, new cached page will be automatically generated.

but the command below is not working with CFileCache. (I get the same with CDbCache too).
Yii::app()->cache->delete($cacheId);

I did the following hack. but still no thing will be deleted from runtime/cache directory!

components part of config/main.php:
'cache'=>array('class'=>'system.caching.CFileCache'),

 public function actionView($profile_id)
 {
   $cacheId= $profile_id;
   if($this->beginCache($cacheId, array('duration'=>360000))) {

```
  $prof=$this->loadModel($profile_id);
  $this->render('view',array(
     'model'=>$prof,
  ));
```

   $this->endCache(); }
Yii::app()->cache->delete($cacheId);  // but it can't delete the generated cache file!
 }

**Comment by Alankar-sri-icreon** [comment]
sdsfsf
