### ISSUE TITLE
[BUG] CSqlDataProvider clears CDbCommand::_paramLog

### ISSUE THREAD

**Issue by AnatolyRugalev** [yiisoft/yii#2557]
I'm using CSqlDataProvider with `$sort` and faced problem: when `CSqlDataProvider` updates `$command->text` `CDbCommand` calls `cancel()` and it's `$_statement` currently is null.

AND when data provider calls `$command->queryAll()` `CDbCommand::_paramLog` variable sets to empty array because CDbCommand was cancelled.

This causes PDO error `Invalid parameter number: no parameters were bound` althrough parameters is displayed as bound to this statement:
```
Bound with :ycp0='0', :ycp1='3', :ycp2='1'
```

Possible solution in CDbCommand:
```php
	public function setText($value)
	{
        $this->setRawText($value);
		$this->cancel();
		return $this;
	}
    public function setRawText($value)
    {
	    if($this->_connection->tablePrefix!==null && $value!='')
		    $this->_text=preg_replace('/{{(.*?)}}/',$this->_connection->tablePrefix.'\1',$value);
	    else
		    $this->_text=$value;
    }
```

`setRawText()` will provide functionality to change raw $_text variable of command
(I request more friendly method name)

**Comment by seregagl** [comment]
I have the same bug with CSqlDataProvider parameters. 

```php
$criteria = new CDbCriteria();
$criteria->addInCondition('t.param_id', array(1, 2));
$command = $this->builder->createFindCommand(BProductParam::model()->tableName(), $criteria);
$dataProvider = new CSqlDataProvider($command);
$data = $dataProvider->getData();
```

This code makes error
> Invalid parameter number: no parameters were bound.

My workaround is
$dataProvider = new CSqlDataProvider($command, **array('params' => $criteria->params)**);

```php
$criteria = new CDbCriteria();
$criteria->addInCondition('t.param_id', array(1, 2));
$command = $this->builder->createFindCommand(BProductParam::model()->tableName(), $criteria);
$dataProvider = new CSqlDataProvider($command, array('params' => $criteria->params));
$data = $dataProvider->getData();
```
