### ISSUE TITLE
gii module may break if you extend CWebUser (and rely on it). Somehow hardcodedly instantiates CWebUser directly despite config/main.

### ISSUE THREAD

**Issue by teo1978** [yiisoft/yii#2668]
In my application I have extended a lot of Yii's default classes and use my own extended versions to replace base application components.

Among others, I have a HttpRequest class which extends CHttpRequest, a WebUser class which extends CWebUser, and a bunch of others.
My config/main.php's components array is configured so that these classes are used for the corresponding applications component.

Now when I try to run gii, for some reason it happens that Yii::spp()->user is an instance of pure CWebUser, instead of WebUser, and this eventually causes errors.

In my particular case this is triggered by a validator, because in my config/main.php I also reassign builtin validators to custom classes, such as:

```
  CValidator::$builtInValidators['required']='RequiredValidator';
```

then something in gii triggers a 'required' validator, and my RequiredValidator triggers a chain of calls which ends up calling Yii::app()->user->preferredLanguage.

My own WebUser class does have a getPreferredLanguage() method, so that shouldn't be a problem at all.
But as I said, for some weird reason (apparently a bug) Yii::app()->user here is _not_ an instance of my own WebUser, as it usually is; it is a direct instance of CWebUser, hence the error:

```
Property "CWebUser.preferredLanguage" is not defined.
```

I have no idea why and how it happens that, when running gii, Yii::app()->user is forced to be an instance of CWebUser despite the application's configuration.

**Comment by m00nk** [comment]
I have the same problem: the application gets CWebUser instead my WebUser if gii is enabled. And all works fine if I remove the 'gii' section from config. 

The issue is in **Yii 1.1.16**. 
In Yii **1.1.12** the same code works fine without removing 'gii' from the config.
