### ISSUE TITLE
run MessageCommand failed.

### ISSUE THREAD

**Issue by hehbhehb** [yiisoft/yii#2919]
Saving messages to C:\xampp\htdocs\parsecode\yii\demos\map\protected\messages..
\messages\zh_cn\yii.php...PHP Error[2]: array_key_exists(): The first argument should be either a string or an integer
    in file C:\xampp\htdocs\parsecode\yii\framework\cli\commands\MessageCommand.
php at line 167
#0 C:\xampp\htdocs\parsecode\yii\framework\cli\commands\MessageCommand.php(167): array_key_exists()
#1 C:\xampp\htdocs\parsecode\yii\framework\cli\commands\MessageCommand.php(120): MessageCommand->generateMessageFile()
#2 C:\xampp\htdocs\parsecode\yii\framework\console\CConsoleCommandRunner.php(71): MessageCommand->run()
#3 C:\xampp\htdocs\parsecode\yii\framework\console\CConsoleApplication.php(92): CConsoleCommandRunner->run()
#4 C:\xampp\htdocs\parsecode\yii\framework\base\CApplication.php(180): CConsoleApplication->processRequest()
#5 C:\xampp\htdocs\parsecode\yii\framework\yiic.php(33): CConsoleApplication->run()
#6 C:\xampp\htdocs\parsecode\yii\demos\map\protected\yiic.php(16): require_once()

My yii ver is 1.1.14
i print the $message variable, it is a boolean var. i don't know why the variable type of $message is boolean.  when i added following statement, it is passed.
if (!is_string($message) && !is_int($message))
    continue;

**Comment by yairpe** [comment]
I know it's an old question but just happened to me today and it might help somebody.

My way to find the Yii::t() lines that break the message gathering:

1. Run the command with redirection like …. > C:\tmp\zz    this will show only the errors on the console.

2. In \yii\framework\cli\commands\MessageCommand.php around line 144 just before   $messages[$category][]=eval("return $message;"); 
add: echo "message=$message\r\n";
so it will show all messages and run again with redirection.

3. Look in the redirected file for strings from the error message. Search for these messages in your files and fix the bad Yii::t() lines

Maybe the great folks that brought us the fantastic Yii will provide a simpler solution to find the erroneous needle in the haystack ?

**Comment by samdark** [comment]
We did in Yii 2.0. I've re-implemented it using tokenizer so it tells exactly what's wrong. I thought about backporting it since it could fit but currently I don't have enough time for it.
