### ISSUE TITLE
No shared locks acquired when reading files: CStatePersister, log rotation, maybe more. Concurrent file read/write ops aren't safe

### ISSUE THREAD

**Issue by teo1978** [yiisoft/yii#2921]
UPDATE: see my comments Oct 3 2014, Oct 15 2014, and Jan 6 2015.
The real issue is: CStatePersister acquires an EX lock for writing, but doesn't acquire any SH lock for reading, so nothing is done whatsoever to prevent reading state.bin while it is being written (by another instance of the app). This obviously causes random data corruption when reading state.bin. If no cache is used, this will "only" cause random, presumably rare, 500 errors for few users. But if there is a cache component, a corrupted version of state.bin coming from a failed read will be cached, causing the site to be down until the cache for state.bin expires.

NOTE: log rotation seems to be affected by the exact same issue. EVERY other part of the framework that does file reads/writes should be reviewed, to make sure that shared locks are aquired when reading files.

--- Original description: ---
This may well have been triggered by some error in my code, but ending up with corrupted data in state.bin is something that should never, ever happen under ANY circumstances, and if it does, state.bin should probably be automatically cleared (after making a backup and logging an error).

CException

PHP NOTICE at /var/www/vhosts/xxx.net/httpdocs/yii/framework/base/CStatePersister.php (84): unserialize() [<a href='function.unserialize'>function.unserialize</a>]: Error at offset 311269 of 311296 bytes

/var/www/vhosts/xxx.net/httpdocs/error_handling.php(24)

12         E_COMPILE_WARNING=>'COMPILE WARNING',
13         E_USER_ERROR=>'USER ERROR',
14         E_USER_WARNING=>'USER WARNING',
15         E_USER_NOTICE=>'USER NOTICE',
16         E_STRICT=>'STRICT VIOLATION',
17         4096=>'RECOVERABLE ERROR',
18         8192=>'DEPRECATED',
19         16384=>'USER DEPRECATED',
20     );
21     if (isset($names[$errno])) $errname=$names[$errno];
22     else $errname="ERROR of level $errno";
23     restore_error_handler();
24     throw new CException("PHP $errname at $errfile ($errline): $errstr");
25     //die("PHP error $errno at $errfile ($errline): $errstr");
26 }
27 
28 set_error_handler('handleErrorAsException', error_reporting());
Stack Trace
#0	
 unknown(0): handleErrorAsException(8, "unserialize() [<a href='function.unserialize'>function.unseriali...", "/var/www/vhosts/xxx.net/httpdocs/yii/framework/base/CStateP...", 84, ...)
#1	
–  /var/www/vhosts/xxx.net/httpdocs/yii/framework/base/CStatePersister.php(84): unserialize("a:7712:{s:30:"cachecheck.access.assignments.";i:18;s:25:"cacheck...")
79         $stateFile=$this->stateFile;
80         if($this->cacheID!==false && ($cache=Yii::app()->getComponent($this->cacheID))!==null)
81         {
82             $cacheKey='Yii.CStatePersister.'.$stateFile;
83             if(($value=$cache->get($cacheKey))!==false)
84                 return unserialize($value);
85             elseif(($content=@file_get_contents($stateFile))!==false)
86             {
87                 $cache->set($cacheKey,$content,0,new CFileCacheDependency($stateFile));
88                 return unserialize($content);
89             }
#2	
–  /var/www/vhosts/xxx.net/httpdocs/yii/framework/base/CApplication.php(660): CStatePersister->load()
655      * @throws CException if the state persister is not available
656      */
657     public function loadGlobalState()
658     {
659         $persister=$this->getStatePersister();
660         if(($this->_globalState=$persister->load())===null)
661             $this->_globalState=array();
662         $this->_stateChanged=false;
663         $this->detachEventHandler('onEndRequest',array($this,'saveGlobalState'));
664     }
665 
#3	
–  /var/www/vhosts/xxx.net/httpdocs/yii/framework/base/CApplication.php(600): CApplication->loadGlobalState()
595      * @see setGlobalState
596      */
597     public function getGlobalState($key,$defaultValue=null)
598     {
599         if($this->_globalState===null)
600             $this->loadGlobalState();
601         if(isset($this->_globalState[$key]))
602             return $this->_globalState[$key];
603         else
604             return $defaultValue;
605     }

I don't think the rest of the trace is relevant

**Comment by teo1978** [comment]
When you say this is hard to reproduce, are you sure you're not confusing this issue with the one described in https://github.com/yiisoft/yii2/issues/3460? Because I think there's very little relation, if any at all, as I commented above.

Also, are you sure postponing this is a good idea? This compromises data integrity at its most basic level. You're almost guaranteed to experience state corruption, log corruption, and who-knows-what-other-data corruption (probably anything that is based on writing and reading files) on any yii-based web application that has significant traffic, i.e. significant probabilities of simultaneous reads and writes. Note that "significant traffic" is not even my case; the application I work at has ridiculous traffic compared to "real-world" scenarios, yet I have already hit the bug.  
That makes me wonder whether Yii has ever been used for project of any significant scale, because if that was the case, this couldn't have gone unnoticed for such a long time.

**Comment by teo1978** [comment]
Should I file a separate issue for every component affected?
So far I know of:
- CStatePersister (fix proposed)
- CFileLogRoute::rotateFiles()
- CFileCache (just found out it's affected too)

**Comment by samdark** [comment]
Yes, it's preferred separated.
