### ISSUE TITLE
CDbSession

### ISSUE THREAD

**Issue by evilebottnawi** [yiisoft/yii#2927]
When put into the session instance class, the returned data is not correct.
```php
Yii::app()->user->setState('user', User::model()->findByPk(1));
```
```php
Yii::app()->user->getState('user'); //not correct
```
Addslashes in readSession and writeSession is solve this problem.

**Comment by samdark** [comment]
Fixed by https://github.com/yiisoft/yii/commit/74934b0a5856af5052b8127920622c9826862a26
