### ISSUE TITLE
CDbCommandBuilder::createCountCommand() and PostgreSQL

### ISSUE THREAD

**Issue by jfragoulis** [yiisoft/yii#3004]
When calling `CDbCommandBuilder::createCountCommand()` on a model with composite primary key the generated command select is as such:

``` sql
SELECT COUNT(DISTINCT key1,key2,...)
   FROM ...
```

which fails when running Postgres. The generated error is: 
`SQL: SQLSTATE[42883]: Undefined function: 7 ERROR: function count(character varying, integer) does not exist LINE 1: SELECT COUNT(DISTINCT "t".id, "t".library_id) FROM "ab_colle... ^ HINT: No function matches the given name and argument types. You might need to add explicit type casts.`

**Comment by samdark** [comment]
Won't be fixed in 1.1.
