### ISSUE TITLE
COciSchema::checkIntegrity causes errors during tests 

### ISSUE THREAD

**Issue by redguy666** [yiisoft/yii#3043]
Current implementation is buggy as it only tries to disable constraints one by one. If you try to disable constraint that is required by another contraint (like PK constrant that is required by another FK contraint) you will get:

ORA-02297: cannot disable constraint -dependencies exist

read more: http://arjudba.blogspot.com/2008/12/ora-02297-cannot-disable-constraint.html

I think we should disable constraints in order: first all FKs, then UKs / PKs / others... if not - we should rollback current implementation, or maybe there is another solution I am not aware of...

**Comment by diegobill** [comment]
any news on this one?
