### ISSUE TITLE
Support apcu of php 5.5

### ISSUE THREAD

**Issue by iobotis** [yiisoft/yii#3048]
About a month ago, I updated my test server to the latest version of apache(2.4) and php(5.5).
Everything works fine, except I had to change function "flushValues" of class "CApcCache" to the following code to make it work.

```
    protected function flushValues()
{
        if (extension_loaded('apcu')) {
            return apc_clear_cache();
        }
        return apc_clear_cache('user');
}
```

I have been testing the new function on my production server which currently runs apache 2.2 and php 5.3 the past month and had no issues.

**Comment by yuriEfin** [comment]
for php7 
protected function flushValues()
    {
        if (extension_loaded('apcu')) {
            return apcu_clear_cache();
        }
        return apc_clear_cache('user');
    }

**Comment by cebe** [comment]
@yuriEfin can you please open a new issue. or even better fix it and send a pull request?
