### ISSUE TITLE
CHttpRequest::getIsSecureConnection not working with CloudFlare proxy

### ISSUE THREAD

**Issue by nacesprin** [yiisoft/yii#3091]
Hello. I'm using CloudFlare cache with https connection, and always return false. The problem were the nests. When using CF proxy, $_SERVER['HTTPS'] doesn't exist, and never reached $_SERVER['HTTP_X_FORWARDED_PROTO'] validation. Then, I've nested correctly and now works fine:

I've fixed with this change:

before:

public function getIsSecureConnection()
        {
                return isset($_SERVER['HTTPS']) && ($_SERVER['HTTPS']=='on' || $_SERVER['HTTPS']==1)
                        || isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO']=='https';
        }

after:

public function getIsSecureConnection()
        {
                return (isset($_SERVER['HTTPS']) && ($_SERVER['HTTPS']=='on' || $_SERVER['HTTPS']==1) )
                        || ( isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO']=='https');
        }

**Comment by Groonya** [comment]
HTTP_X_FORWARDED_PROTO is in $secureProtocolHeaders property of class yii/web/Request.
It's cutting off if request is not from trusted hosts in filterHeaders method.
