### ISSUE TITLE
Relational INNER JOIN queries using LIMIT give wrong results

### ISSUE THREAD

**Issue by jurgenvandulst** [yiisoft/yii#3095]
Hi,

Consider having two tables, 'parent' and 'children', where children table has a foreign key to parent. The tables have the following contents:

```
PARENT     CHILDREN
id           id     parent_id
1            1      1
2            2      1
3            3      1
             4      2
             5      2
             6      2
             7      3
             8      3
             9      3
```

And also consider the following code to find all parents with their children that have child with id 6 or less.

```
$result = Parent::model()->with(array(
    'children' => array(
        'joinType' => 'INNER JOIN', 
        'condition' => 'children.id <= 6'
    ), 
))->findAll();
```

This code works fine. It returns parents 1 and 2 with relations to the first 6 children.

Now however, consider the code below. The difference being that I added a limit of 3 parents:

```
$result = Parent::model()->with(array(
    'children' => array(
        'joinType' => 'INNER JOIN', 
        'condition' => 'children.id <= 6'
    ), 
))->findAll(array('limit' => 3));
```

Now all of a sudden 3 parents are returned, with the last parent (id 3) having no related children. This is not expected behavior in my opinion. I should get the same results as with the first statement.

In my view, the cause for this behavior is that by adding the limit clause, Yii will use two queries to fetch the result. The first query fetches all parents, limited by 3. And the second query joins all children to those 3 parents, see the querylog below:

```
SELECT `t`.`id` AS `t0_c0` FROM `parent` `t` LIMIT 3;

SELECT `t`.`id` AS `t0_c0`, `children`.`id` AS `t1_c0`, 
`children`.`parent_id` AS `t1_c1` FROM `parent` `t` 
INNER JOIN `children` ON (`children`.`parent_id`=`t`.`id`) 
WHERE (`t`.`id` IN (1, 2, 3)) AND (children.id <= 6);
```

This behavior is correct for LEFT OUTER JOIN's (the Yii default). But when using INNER JOIN the join condition can actually affect the results of the parent query. The parent with id 3 should not be returned. 

In the second query, Yii does select t.id, which refers to the parent id. it could look at whether all previously selected parents are also returned by the second query. If not, it should omit them in the returned results.

Using the 'together' option is no solution in this instance, as it would return the first 3 results of the composite query, which would result in getting 1 parent with 3 children.

**Comment by rizwanmcs** [comment]
Hi guys,
below is my query and i want to limit the post media table record which is last table in my scenario can any one help me that how i can get all the boxes with only 5 media images
and here is my db design
user_posts { id (primary key) } 
post_media { user_posts_id (foreign key) }
user_posts_boxes { user_posts_id (foregin key), box_id (foreign key)}
box { id (primary key) }
-----------------------
SELECT PM.id                               AS mid, 
       PM.FILE, 
       PM.file_type, 
       B.id, 
       B.NAME, 
       B.picture, 
       (SELECT Count(user_posts_boxes.id) 
        FROM   user_posts_boxes, 
               user_posts 
        WHERE  user_posts.id = user_posts_boxes.user_posts_id 
               AND B.id = user_posts_boxes.box_id 
               AND B.archive = 0 
               AND user_posts.archive = 0) AS postCount 
FROM   box B 
       LEFT JOIN user_posts_boxes UPB 
              ON B.id = UPB.box_id 
       LEFT JOIN user_posts UP 
              ON ( UPB.user_posts_id = UP.id 
                   AND UP.archive = 0 ) 
       LEFT JOIN post_media PM 
              ON ( UP.id = PM.user_post_id 
                   AND PM.FILE <> '' ) 
WHERE  B.user_id = 43 
       AND B.archive = 0 
ORDER  BY B.id DESC
