### ISSUE TITLE
backslash "\" not treated correctly by createUrl

### ISSUE THREAD

**Issue by teo1978** [yiisoft/yii#3103]
Sometimes you are forced to escape some special characters with a backslash in the regular expression used in a urlManager rule if you need to match those characters literally, for example:

    'foo/\*<areas:[^\d].*>' => 'foo/bar'
where I use \* to match a literal "*" in the url.

These url rules will be processed correctly by parseUrl(), but not by createUrl()

So, in the example above, an url like '/foo/*hello' will be correctly parsed as equivalent to /foo/bar?areas=hello

However, Yii::app()->createUrl('foo/bar', 'areas'=>'hello') will output "/foo/\\\*hello" instead of the expected "/foo/*hello", that is, it puts an extra backslash. 

In turn, some browsers (namely Chrome) will automagically transform that to /foo//*hello, for some reason, i.e. replacing the "\" with a "/", which I don't know whether it is standard-compliant or a browser's bug, but that's pretty irrelevant here.

**Comment by lierdakil** [comment]
So do you suppose this can be closed now?

**Comment by qiangxue** [comment]
Thanks for your help!

**Comment by eirikhm** [comment]
This actually introduced a regression, see #4051
