### ISSUE TITLE
CActiveRecord::with() - incorrect phpdoc return-type annotation

### ISSUE THREAD

**Issue by mindplay-dk** [yiisoft/yii#3115]
The [return-type of CActiveRecord::with()](https://github.com/yiisoft/yii/blob/master/framework/db/ar/CActiveRecord.php#L1706) is defined as `CActiveRecord`, but should be `$this` to allow for method-chaining to work correctly.

**Comment by olleharstedt** [comment]
If the return value can be null, the PHPDoc should be `static|null`, not only `static`. Psalm is confused by this.
