### ISSUE TITLE
CClientScript component dependencies.

### ISSUE THREAD

**Issue by SamMousa** [yiisoft/yii#3120]
The package management provide by CClientScript is ideal for cases where you need to include pure js/css libraries.
In the case of extensions however, CClientScripts' dependency management cannot be used.

For example consider YiiStrap, a popular extension adding bootstrap to Yii. Ideally any other 3rd party libraries could be added to the packages in CClientScript and mention they depend on the bootstrap component.

By adding a component key to the CClientScript configuration one could specify that a certain js / css package will be added when loading the associated component.

This does not break lazy loading for the component since CClientScript will only need to load it if the package is actually registered at some point during execution.

This does not have any effect on BC and it will not have a performance impact in any scenario.

I'm willing to create PR for this (probably after the holidays).

**Comment by samdark** [comment]
Won't port that to 1.1.
