### ISSUE TITLE
Please expose CUrlManager's parseUrl() mechanism so that an arbitrary url (string) can be parsed

### ISSUE THREAD

**Issue by teo1978** [yiisoft/yii#3133]
This is a feature request (though I think the lack of this feature is an issue).

Use case: I have a string which is an url and I want to check whether this is a valid url within the current web application, and if so, see which would be the resulting controller/action route, and maybe the get parameters as well.

More specific real use case (but one can imagine infinite other cases): my web application can run in a kind of "kiosk mode" in which case output is processed and every link to anything outside the application (even in the same domain) is removed during output processing (no, not generating links in the first place is not enough, because there can be links in content created by users, e.g. posts), and also links to some specific routes that are within the web application scope (e.g. /site/contact).

So I would need to apply the same parsing that is done with the incoming request, but apply it to an arbitrary url.

Issue: there's no way to call Yii::app()->urlManager's parseUrl() on anything else than the current request. It's not even possible to extend CUrlManager and/or CHttpRequest somehow and expose the url-parsing mechanism so that it can be used on a string, because the logic is in CUrlManager::parseUrl() which expects a CHttpRequest object.

I haven't yet thought about it deeply enough to state exact requirements on how the API should be, but either CUrlManager and/or CHttpRequest should somehow allow to reuse that url-parsing logic on a string that is not the current request's url. The part of stripping out the domain name can perfectly be left to the author's code, I'm talking about the part that parses the rest of the url.

**Comment by peter-gribanov** [comment]
+1
