### ISSUE TITLE
CValidator createValidator()

### ISSUE THREAD

**Issue by ghost** [yiisoft/yii#3144]
You are using preg_split which is screwing up my logic when I have spaces in my attribute names. It is only supposed to seperate commas from the string. I solved this issue using explode:

line 149 and 150:
        if(is_string($attributes))
            $attributes=preg_split('/[\s,]+/',$attributes,-1,PREG_SPLIT_NO_EMPTY);

Solution:
    if(is_string($attributes))
            $attributes=explode(',',$attributes);

**Comment by EugeneG9** [comment]
Hi. With new regex, rules like my(spaces before first attribute) don't work anymore:

```
array('	diary_number,
		project_id,
		submitted_by_id,
		time_started_onsite,
		work_being_done', 
		'required'),
```
As solution, you can change regex to `/^\s+|\s*,\s*/`. Thanks.

**Comment by cebe** [comment]
Fixed, thanks for reporting!
