### ISSUE TITLE
Logout user if password changed

### ISSUE THREAD

**Issue by atrandafir** [yiisoft/yii#3152]
Hey I was just wondering wouldn't it be considered normal behaviour of the framework to invalidate a user if his password gets changed?

Because let's say someone finds out your password, and you login and change it, but that person can still be logged into your account until the session expires, and if it's cookie based it will stay logged in forever.

Should this be considered a issue? Or should be considered the developer's preference to build a system that checks if the login info changed? And if so, someone has any implementation example?

**Comment by noc2spam** [comment]
You know what, this was the downfall. Because other frameworks did not resist, they moved on.

May be don't reply with your favorite one next time, but solve the problem. 

Bye yii.
