### ISSUE TITLE
Yii demo appliance outdated

### ISSUE THREAD

**Issue by rawtaz** [yiisoft/yii#3186]
Hi,

I so recall having brought this up a while back, but I can't find the/an issue for it. So I'll make a new one.

I know I've said it many times before but here we go again; The VMware appliance on the Yii site is _badly_ outdated. It is lightyears old. It's from 2009! Let's just remove it. Even if someone tries it, it's a very old copy of the framework.

Perhaps it would be better to point to the Turnkey Linux one at http://www.turnkeylinux.org/yiiframework ? It seems that one is being kept up to date.

**Comment by JedMeister** [comment]
I know that this issue is quite old, and we (as in TurnKey) didn't actually do a very good job of keeping our appliance up to date there for a while. Things are pretty much back on track now.

Obviously we'll make an effort to keep it up to date, but if anyone is interested in helping out that'd be great and will ensure more regular updated ISOs. 

I'm more than happy to provide guidance on using our public open source build tools. Please ping me (jeremy AT turnkeylinux.org) if you're interested.

**Comment by cebe** [comment]
I tried to figure out from the turnkey website but did not find an answer. What is the benefit of having Yii on turnkey compared to installing a standard debian and put yii on it? How does it compare to a vagrant or docker setup which one can use to try it?

**Comment by JedMeister** [comment]
You're most welcome :smile: 

As the TurnKey Yii appliance is essentially Debian (with some tweaks) with Yii installed on top; there is no real advantage other than the fact the heavy lifting has already been done. 

As a developer that is used to getting your hands dirty and/or already using tools such as vagrant or docker there is probably no major advantage at all beyond the convenience of downloading a single ISO (or OVA or Proxmox LXC container etc) and being able to almost instantly launch multiple VMs that are exactly the same (which obviously docker can also do; and vagrant can to a degree too). FWIW we actually provide Docker builds too and we have had requests for Vagrant boxes but haven't yet explored that very deeply.

IMO where TurnKey shines is if you want to host on alternate platforms. We have a built in backup system called [TKLBAM](https://www.turnkeylinux.org/tklbam) which you can use to migrate your data between instances of TurnKey. So you can do your development on a local VM (or LXC container, etc) and then migrate your content to your production (and/or staging) server in the cloud. We have a platform that we call the Hub which allows you to easily launch a TurnKey server on AWS and include your backup data at launch time.

Even those advantages are probably insignificant if you are a developer that has an established workflow that already fulfils your needs. But for newbs and devs just starting out it can be a boon to getting a quick stable start. We have also had feedback from experienced devs (including some that don't actually use TurnKey in production) that they love the ease of being able to check out some specific software (that is new to them) without having to invest any time at all (at least in the setup).

Finally, having a TurnKey appliance provides additional exposure to Yii, supporting your SEO and giving potential users another avenue that they my find useful (even if they end up using something other than TurnKey in the end).

Like I said, there is no pressure. We'll continue to keep producing it; but we can generally produce a superior appliance with support from upstream devs and/or community. In our opinion, a better appliance is a win-win. The appliance is more up to date and more likely to conform to upstream "best practice" which in turn creates the best possible experience of your software on our platform.

**Comment by cebe** [comment]
Thanks for the detailed answer! I was just wondering about the benefits because Yii is not something that someone would setup without writing code compared to setting up applications like Issue tracking software etc. 
The workflow for Yii would be to set up the box, and start writing/changing code that is inside.
If TurnKey is suitable for this workflow there is a use case for Yii and I am happy to provide input on creating an instance.

**Comment by cebe** [comment]
@JedMeister is there a way to provide multiple variants of an image? e.g. yii2-basic application and yii2-advanced application?

**Comment by JedMeister** [comment]
@cebe - Unless a complete additional image is created, currently not really. IIRC the current image provides yii2-advanced application. 

We do have plans to provide users the choice of adding additional configuration and optional extras post-install but it will require a rewrite of our existing confconsole software. It needs a serious refresh anyway (the code is about 5 years old now) but ideally we'd like to rewrite it from scratch.

That has been on the cards for a while now, but unfortunately it keeps getting pushed back by "more important" stuff. Hopefully we'll get it done sometime soonish though...

Also thanks for the PR! :smile:
