### ISSUE TITLE
cjuiautocomplete - use (active)SearchField

### ISSUE THREAD

**Issue by Leffe108** [yiisoft/yii#3279]
A common use case for auto complete is to use on a search field. However, it is currently not possible to make CJuiAutoComplete use (active)SearchField instead of (active)TextField other than sub classing and overriding the whole run() method (which is almost the entire widget code).

Here is four arguments for using the search field for search use cases:
1. It is more semantically correct
2. Screen readers will announce it as a search field instead as a text field
3. Many AT (assistive technology) have shortcuts to jump to search fields.
4. In iOS and possible also Android, the virtual screen keyboard will show a Search button instead of the Okay button.

Thus I propose that it should be possible to configure CJuiAutoComplete so that a search field will be generated instead of a text field. I guess there are genuine use cases when text field is preferred so a commit need to either add an configuration option or move rendering of the input field to a protected method that can be overriding without having to duplicate the whole run() code in your application.

**Comment by samdark** [comment]
Won't be fixed in 1.1.
