### ISSUE TITLE
View files can access protected methods of widgets

### ISSUE THREAD

**Issue by marcovtwout** [yiisoft/yii#3347]
We found a possible design flaw in Yii 1. Consider the following example:

```php
// MyWidget.php
class MyWidget extends CWidget
{
    protected function fooProtected()
    {
        throw new Exception('protected reached!');
    }
}

// MyController.php
class MyController extends CController
{
    public function actionIndex()
    {
        $this->render('index');
    }
}

// index.php:
<?php
    $widget = $this->widget('MyWidget');
    $widget->fooProtected(); // exception: 'protected reached'
?>
```

The protected widget function is available to the view, and this is unexpected.

How is this possible? Because both the controller and the widget inherit from the same base class CBaseController, and the view file is included in the base class. Quoting the [PHP manual](http://www.php.net/manual/en/language.oop5.visibility.php#language.oop5.visibility-other-objects): 

> Objects of the same type will have access to each others private and protected members even though they are not the same instances. This is because the implementation specific details are already known when inside those objects.

Check the implementation here. Since the view file is included in the common base class function renderInternal(), it gets access to protected methods of any subclasses (widgets). https://github.com/yiisoft/yii/blob/1.1.14/framework/web/CBaseController.php#L115

I thought about possible solutions, but I cannot think of one that is backwards compatible. But at least it might be worth documenting.

**Comment by samdark** [comment]
I don't think it should be emphasized since it's kinda bad practice.
