### ISSUE TITLE
Create/document a good way to configure CHtml

### ISSUE THREAD

**Issue by igorsantos07** [yiisoft/yii#3373]
First of all, I've searched the repository and Google for info on this but found nothing. If there is, please point me and sorry in advance.

So, I guess we all know CHtml is that bad child over there that's used statically everywhere and stuff. But while the class have several static config properties, there's no easy way to configure it - since for example it's not a component that would obey to `config/main.php`.

Is there a better way to configure it than throwing code in the config main file,
like `CHtml::$errorCss = 'danger';`?

**Comment by samdark** [comment]
The way to configure CHtml is about settings static properties. In Yii 2.0 better way is there. Won't be ported to 1.1.
