### ISSUE TITLE
[RFC] Ability to customize CHtml usage

### ISSUE THREAD

**Issue by igorsantos07** [yiisoft/yii#3374]
I've found myself, like a bunch of other people probably have been as well, trying to do something and stumbled over some `CHtml` undesired behaviour. Some people are using [error-prone hacks](http://www.yiiframework.com/forum/index.php/topic/28979-how-to-override-yii-core-classes/), and others have simply given up on the case and are using plain old HTML to write their templates.

After some thinking I got an idea for a small refactor on CActiveForm (and maybe other classes that use CHtml as well) where you could define and overwrite the HTML class used by the components, something as follows:

```php
class CActiveForm extends CWidget {
    /** Here we define the HTML class name or path alias, enabling easily configuration */
    public $html = 'CHtml';

    public function label($model, $attribute, $htmlOptions = array()) {
        // Instead of calling the static method, we use an instance method that will be handled internally
        // return CHtml::activeLabel($model, $attribute, $htmlOptions);
        return $this->htmlActiveLabel($model, $attribute, $htmlOptions);
    }

    /** Here we handle any html*() calls and redirect them to the correct class */
    public function __call($method, $args) {
        if (strpos($method, 'html') === 0) {
            $method = 'xxx'; //remove the prefix and lowercase the first letter
            return call_user_func_array(self::$html."::$method", $args);
        }
        else {
            return call_user_func_array($this, $args); //throw up
    }
```

The biggest "drawback" is having to use search & replace to change "CHtml::" into "$this->htmlX", what's not a big deal at all.

This way any developer can extend CHtml and use it easily to write custom forms and whatnot.

What do you think about this approach? If you agree I will send a PR soon :)

**Comment by samdark** [comment]
Won't be backported.
