### ISSUE TITLE
PHP Error[8]: Undefined offset: 0 at CDataProviderIterator

### ISSUE THREAD

**Issue by jrobles-boom** [yiisoft/yii#3379]
In a case of updating a large recordset using CDataProviderIterator to obtain the data, the issue arise when $_totalItemCount is greater than the real data from the DataProvider.

Scenario:
A list with 30 items using a pagesize of 10. 
The criteria uses a condition of item status = 1
Update through a loop, discarding 10 of them to status = 0

Issue:
At the beginning of page 2 there's no items left to loop, and error arises.

Possible fixes:
Refresh $_totalItemCount on CDataProviderIterator::loadPage method.
Check if there's data available on CDataProviderIterator::valid method.

**Comment by zelenin** [comment]
this fix is very wrong. It's fix the exception but not its reason.

**Comment by nineinchnick** [comment]
@jrobles-boom if you modify data fetched by dataProvider manually you should also set the total item count yourself. And you really shouldn't modify that data _while_ iterating over it.

This issue is invalid.

**Comment by jrobles-boom** [comment]
Sorry @nineinchnick  I disagree:

1. The objective of an iterator is to provide data as manageable chunks among others.
A recordset could be changed by external actions (Take it as is running a cron do "A" while administrators of a site could change a record at will "B") so It could happen (real world vs. best practices ;P)

2. CDataProviderIterator does not check the changed value of CDataProvider totalItemCount, as is used at instance time, and not every page load. There's no method to notify CDataProviderIterator the item count has changed, neither.

**Comment by samdark** [comment]
@jrobles-boom what do you mean by "at instance time, and not every page load"? Instantiating happens at least once per page load.

**Comment by jrobles-boom** [comment]
Sorry, I mean CDataProviderIterator::pageLoad

**Comment by jrobles-boom** [comment]
Thanks!

**Comment by nineinchnick** [comment]
@jrobles-boom would performing the loop while in a db transaction resolve that issue?

Another issue is that forcing recalculation of total items count between each iteration could impose a heavy performance hit.

**Comment by jrobles-boom** [comment]
The transaction is done at item level. For each record there's a number of actions to be performed, between tables etc. A transaction of a hundred items multiplied by two or three actions per item surely have bigger impact than a count.
I think It will suffice if a method exists to refresh the count on the next page load on demand, sketch:

foreach( provideriterator as item){
if (x->method()) {
 item->updateRecord();
 providerIterator->refreshCountOnNextLoad()
}
}

maybe?

**Comment by nineinchnick** [comment]
That would be the safest solution, if @samdark  agrees maybe you should update your PR.

Instead of a method this could be a new iterator property with three values (new constants):

* never refresh count (default)
* refresh on next load (being reset to _never_ after next load)
* always refresh count

**Comment by jrobles-boom** [comment]
Perfect!

**Comment by zelenin** [comment]
I see that my issue in using relations in CActiveDataProvider
```php
        $dataProvider = new CActiveDataProvider(
           ...
            [
                'with' => [.......]
            ]
        );
```
it's working perfect without relations.

**Comment by zelenin** [comment]
I'm not confirm my last comment. Same error with relations or without. My test database is not change but undefined offset is different every time. Seems like iterator very not stable.

**Comment by didux1** [comment]
Still have the same issue. Hope you`ll fix it soon!

**Comment by Hassaan-Hassaan** [comment]
The issue happened with me when I used 
$criteria->together=true;
when removed this , the issue doesn't happen

**Comment by gekannt** [comment]
I feel like it fails on the last step of iteration

**Comment by gekannt** [comment]
In my situation problem happens exactly in case  when primary keys allocated as  1-1056 , empty space and again 185000 - 3798200. If ids are sequential no problem then. Just a note -my pk is not named as "id" but another name.

**Comment by gekannt** [comment]
I found this extension, seems to be working
