### ISSUE TITLE
Errors in testing classes when using phpunit.phar

### ISSUE THREAD

**Issue by kburton** [yiisoft/yii#3418]
I installed PHPUnit in the phar format as seems to be the recommended method on their site. This package comes with all of the dependencies and extra packages bundled into a single file.

When trying to run unit tests through Yii, the following require_once lines are causing errors, because the files don't exist:

CWebTestCase

```
require_once('PHPUnit/Extensions/SeleniumTestCase.php');
```

CTestCase

```
require_once('PHPUnit/Runner/Version.php');
require_once('PHPUnit/Util/Filesystem.php'); // workaround for PHPUnit <= 3.6.11
require_once('PHPUnit/Autoload.php');
```

This applies to Yii 1.1.14 and the current development version.

Could this be avoided by simply checking if those classes are already defined before using require_once?

Further, when performing assertions, the following warning is raised:

```
PHP Warning:  include(PHPUnit_Extensions_Story_TestCase.php): failed to open stream: No such file or directory in /home/keith/Dev/Web/Yii/framework/YiiBase.php on line 427
```

This can be avoided by altering the error_reporting level, but still needs to be fixed.

**Comment by dastra** [comment]
phpunit.phar has PHPUnit/Extensions/SeleniumTestCase bundled within it. 

However at the top of yii/framework/test/CWebTestCase.php there's the line:

require_once('PHPUnit/Extensions/SeleniumTestCase.php');

CWebTestCase.php requires SeleniumTestCase.php to exist as an actual file; which it doesn't in the case of the .phar bundle.

To fix this, we need to extract the source classes from the .phar file:

To do this:

sudo mkdir -p /usr/share/php/PHPUnit
sudo mkdir -p /usr/share/php/PHP

cd /usr/local/bin/
mkdir /tmp/phpunit
sudo php -r '$phar = new Phar("phpunit.phar"); $phar->extractTo("/tmp/phpunit");'

sudo cp -rp /tmp/phpunit/php-invoker/* /usr/share/php/PHP/
sudo cp -rp /tmp/phpunit/dbunit/* /usr/share/php/PHPUnit/
sudo cp -rp /tmp/phpunit/phpunit-selenium/* /usr/share/php/PHPUnit/
sudo cp -rp /tmp/phpunit/phpunit-story/* /usr/share/php/PHPUnit/

rm -rf /tmp/phpunit

And then it works fine

**Comment by Vehsamrak** [comment]
This issue fixes with PHPUnit Beta-Quality Build phar (https://phar.phpunit.de/phpunit-beta.phar)

**Comment by ziplizard** [comment]
@dastra I have done exactly as you have described. My env: Ubuntu 12.04, phpunit 4.8.24, php 5.4.45, pear version 1.10.1. And I no longer get the "failed to open file" error, but now I'm getting: Cannot redeclare class PHPUnit_Extensions_SeleniumTestCase in /usr/share/php/PHPUnit/Extensions/SeleniumTestCase.php on line 1217
Any ideas on this? Something to do with the autoload?

**Comment by dastra** [comment]
@ziplizard I would assume this is because you've got SeleniumTestCase class included twice by different package managers; maybe it's been installed via composer (if you're using it) or pear?
