### ISSUE TITLE
Can't create simpleType with CWsdlGenerator

### ISSUE THREAD

**Issue by antoniom** [yiisoft/yii#3419]
`CWsdlGenerator` defines either a primitive type (`xsd:string`, `xsd:int` etc) or a `complexType`. It cannot create a `simpleType` in order to define a string with enumerated values.

See http://stackoverflow.com/q/24405206/1149919 for a more detailed example.

**Comment by antoniom** [comment]
Why closed? Do you need additional info?

**Comment by samdark** [comment]
Because of http://www.yiiframework.com/news/90/update-on-yii-1-1-support-and-end-of-life/
