### ISSUE TITLE
db->cache() is applied to next query

### ISSUE THREAD

**Issue by dmitry-zaporozhan** [yiisoft/yii#3421]
Had to deal with following code

```
$db->cache(500)->query()->readAll();
```

followed by

```
ActiveRecord::model()->findByPk();
```

In result the second query was cached. This happens because `CDbCommand::queryInternal` is called with empty `method` thus caching is not executed but `queryCachingCount` has been set and next `queryInternal` with not empty `method` will be cached (even without calling `cache()`).

**Comment by samdark** [comment]
Won't be fixed in 1.1.
