### ISSUE TITLE
Gii generates wrong classnames and filenames for uppercase table names

### ISSUE THREAD

**Issue by warden** [yiisoft/yii#3449]
On Windows, when the table is named e.g. TBL_TABLENAME, then gii generates wrong plural names for relations and wrong model names, i.e.
- with prefix set to TBL_ should result in a model file named Tablename.php while it results in TABLENAME.php and with a relation name of tABLENAMES instead of Tablenames
- similarly TBL_TABLE_NAME should result in TableName.php while it results in TABLENAME.php

Patch coming in pull request.

**Comment by samdark** [comment]
Won't be fixed in 1.1.
