### ISSUE TITLE
CDbHttpSession readSession() don't get session data from postgresql database

### ISSUE THREAD

**Issue by mikolajzieba** [yiisoft/yii#3468]
Hi,
There is a problem with reading session using CDbHttpSession class in PostgreSQL database. I'm using default Yii session table template. 

Session data is stored in bytea field which on windows environment (still don't know why) is not properly read.
I have found this issue when tried to deploy my application to windows server (on linux everything works fine). 
When i'm trying to store any data in session (using Yii::app()->session['var'] = 'val' or 
Yii::app()->session->add('var','val')) it is properly stored in database after request (i have checked it on linux instance and data is saved in 100% properly). The problem occurs when readSession($id) is reading database, content of received "data" result is a strange and certainly not one that has been saved.

For example in one request i have saved variables in session:
Yii::app()->session['aaa'] = 'qwer';
Yii::app()->session->add('asdf','qqqqqq');
After request i can see in "data" field in database:
"aaa|s:4:"qwer";asdf|s:6:"qqqqqq";" 
Everything looks fine.
When i start another request or try to refresh page, readSession() of CDbHttpSession class returns:
"x6161617c733a343a2271776572223b617364667c733a363a22717171717171223b"
As you can guess the outcome, the session is empty.
On linux with exactly this same code, config and database everything works fine.
When i have changed column type from bytea to text everything works fine on windows and linux. 

I don't have idea why on windows bytea is read in wrong way, but simply replacing bytea field with text is a good solution i think. 

Environment with problems: 
OS: Windows Web Server 2008 R2
Apache 2.2
PHP 5.4.26
Yii 1.1.13
PostgreSQL(libpq) Version 	8.3.3
PostgreSQL(libpq) 	PostgreSQL 8.3.3, compiled by Visual C++ build 1500
Database: "PostgreSQL 9.3.4 on x86_64-unknown-linux-gnu, compiled by gcc (Debian 4.7.2-5) 4.7.2, 64-bit"
I'm connecting to this same database from linux and windows instance.

**Comment by samdark** [comment]
Fixed by https://github.com/yiisoft/yii/commit/74934b0a5856af5052b8127920622c9826862a26
