### ISSUE TITLE
Request: add an option to always show the CListView pager

### ISSUE THREAD

**Issue by gstaruk** [yiisoft/yii#3470]
Often the design of a page requires the existence of certain elements. For example where a pagination is required, when using CListView the pager will disappear when there is only one page (or no pages) of results.

This means the layout may end up with a big blank area that does not go well with the rest of the page.

I think it would be good to have an option to determine whether to always the display the pager. In this case, the pager would just simply show page number 1 highlighted (with prev/next buttons inactive).

**Comment by samdark** [comment]
Won't be fixed in 1.1.
