### ISSUE TITLE
 Bug In Yii-1.1.15. Cdbcommandbuilder

### ISSUE THREAD

**Issue by lucamarletta** [yiisoft/yii#3475]
Ive reported for version 1.14 a bug for support postgresql schema in createMultipleInsertCommand bug I noticed that still appear in 1.15.

I fix it whit this line

in CDbCommandBuilder class:

line 291 $tableName=$table->rawName; //replacing   $tableName=$this->getDbConnection()->quoteTableName($table->name);

could you include in core for next version please?

**Comment by samdark** [comment]
Won't be fixed in 1.1.
