### ISSUE TITLE
use session with postgresql

### ISSUE THREAD

**Issue by fmfeggman** [yiisoft/yii#3476]
yii version 1.1.15

my config :
        'db'=>array(
            'class'=>'CDbConnection',
            'connectionString'=>'pgsql:host=localhost;port=5432;dbname=comm',
            'username'=>'postgres',
            'password'=>'123456',
        ),
		'session' => array (
            'class' => 'system.web.CDbHttpSession',
            'connectionID' => 'db',
            'sessionTableName' => 'session_table',
        ),

table structure for session_table:
		CREATE TABLE "public"."session_table" (
		"id" char(32) COLLATE "default" NOT NULL,
		"expire" int4,
		"data" bytea
		)
		WITH (OIDS=FALSE);
		
yii can't read session data, i changed the bytea into varchar, problem solving!

**Comment by c-schmitz** [comment]
I can confirm the issue and the PR is fixing it properly. If you have comments on the PR please let me know.

**Comment by limesurvey-translations** [comment]
@fmfeggman Why did you close it?
