### ISSUE TITLE
Setting unknown property: yii\console\Request::enableCookieValidation

### ISSUE THREAD

**Issue by ruskid** [yiisoft/yii#3488]
"php yii help" gets this Exception, cause yii\console\Request doesnt have a property cookieValidationKey. This happens because I have set this property in my common config file, I suppose to use cookie validation in backend and frontend, but not console ;)

``` php
'request' => [
            'enableCookieValidation' => true,
            'enableCsrfValidation' => true,
            'cookieValidationKey' => 'xxxxxxx',
        ],
```

Quick workaround is to set those properties in backend and frontend configs, but I dont think this follows the DRY principle.

**Comment by shahzadthathal** [comment]
I have same issue when I run this commond:

 ./yii migrate --migrationPath=@yii/rbac/migrations

Exception 'yii\base\UnknownPropertyException' with message 'Getting unknown property: yii\console\Request::cookies'

in E:\wamp\www\yii2app\vendor\yiisoft\yii2\base\Component.php:143

Stack trace:
#0 E:\wamp\www\yii2app\common\components\LanguageSelector.php(12): yii\base\Component->__get('cookies')
#1 E:\wamp\www\yii2app\vendor\yiisoft\yii2\base\Application.php(315): common\components\LanguageSelector->bootstrap(Object(yii\console\Application))
#2 E:\wamp\www\yii2app\vendor\yiisoft\yii2\base\Application.php(267): yii\base\Application->bootstrap()
#3 E:\wamp\www\yii2app\vendor\yiisoft\yii2\console\Application.php(124): yii\base\Application->init()
#4 E:\wamp\www\yii2app\vendor\yiisoft\yii2\base\Object.php(107): yii\console\Application->init()
#5 E:\wamp\www\yii2app\vendor\yiisoft\yii2\base\Application.php(206): yii\base\Object->__construct(Array)
#6 E:\wamp\www\yii2app\vendor\yiisoft\yii2\console\Application.php(89): yii\base\Application->__construct(Array)
#7 E:\wamp\www\yii2app\yii(26): yii\console\Application->__construct(Array)
#8 {main}


and here is code of LanguageSelector 


```<?php 

namespace common\components;
use yii\base\BootstrapInterface;

class LanguageSelector implements BootstrapInterface
{
    public $supportedLanguages = [];

    public function bootstrap($app)
    {
        $preferredLanguage = isset($app->request->cookies['language']) ? (string)$app->request->cookies['language'] : null;
        // or in case of database:
        // $preferredLanguage = $app->user->language;

        if (empty($preferredLanguage)) {
            $preferredLanguage = $app->request->getPreferredLanguage($this->supportedLanguages);
        }

        $app->language = $preferredLanguage;
    }
}```

**Comment by newscloud** [comment]
I'm getting this too on a fresh install of a cloned Github tree. I've never seen this before. And none of my other sites need cookie request defined in console. 

```
$ ./yii migrate/up 
Error: Setting unknown property: yii\console\Request::enableCookieValidation
PHP Warning:  array_map(): An error occurred while invoking the map callback in /var/www/jcore/vendor/yiisoft/yii2/log/FileTarget.php on line 106
```

**Comment by tedyonly** [comment]
avoid to set property at common/config/main.php such as 
'bootstrap' => [
		'translatemanager',				// for I18n is ok
		//'languagepicker'			// language picker will effect to the console
		],
