### ISSUE TITLE
CListView summary and empty text rendering

### ISSUE THREAD

**Issue by yii-user** [yiisoft/yii#3498]
Suppose we wish to output the following markup:

```
<div class="summary">
    <p class="heading">YOUR ACTIVE LISTINGS</p>
    <p class="showing">SHOWING 1-10 OF 20 RESULTS</p>
</div>

<div class="items">
...
</div>

<div class="pager">
...
</div>
```

The code we need to use is:

```
<?php $this->widget('zii.widgets.CListView', array(
	'dataProvider'=>$dataProvider,
	'itemView'=>'_view',
	'template'=>'{summary}{items}{pager}',
	'summaryText'=>'<p class="heading">YOUR ACTIVE LISTINGS</p><p class="showing">SHOWING {start} TO {end} OF {count} RESULTS</p>',
	'emptyText'=>'YOU DO NOT CURRENTLY HAVE ANY ACTIVE LISTINGS.',
)); ?>
```

However, when there are no results, `emptyText` is displayed within the `items` container. `summary` is not output on the page. This can affect the layout of the page, as in the example above we rely on `summary` to provide the heading for the results.

Would a possible solution be to have an option to specify whether summary is always shown? Alternatively how about an option called `header` which would allow us to specify any content to show before items? This option could also recognise the `summary` placeholder.

**Comment by mdeweerd** [comment]
Please also think of sorting:
http://www.yiiframework.com/forum/index.php/topic/60707-no-listview-sorter-if-empty-list/

related code: https://github.com/yiisoft/yii/blob/master/framework/zii/widgets/CListView.php#L306

**Comment by mdeweerd** [comment]
Seems related with https://github.com/yiisoft/yii/pull/2900
