### ISSUE TITLE
Wrong value for $this->isNewRecord in CActiveRecord::afterSave() 

### ISSUE THREAD

**Issue by paalg** [yiisoft/yii#3508]
When we reach a models function afterSave, the property isNewRecord should already be set to false, since it is now stored in the database. This does not happen in the framework version 1.1.15.

Paste this code into a CActiveRecord class to see property isNewRecord value:

   protected function afterSave() {
       parent::afterSave();
       // This value should be true inside this function
       var_dump($this->isNewRecord;
       die();
   }

**Comment by Lexxtor** [comment]
@klimov-paul what's the reason to determine it? Any way, in most cases `$this->scenario == 'update'` is `true` when the model was inserted.

**Comment by cebe** [comment]
@Lexxtor it is needed for example if you want to send notification on new created records differently then on updated ones.
