### ISSUE TITLE
Yii Database migration incorrect with CDbConnection autoCommit set to false

### ISSUE THREAD

**Issue by visitsb** [yiisoft/yii#3526]
I noticed in **Yii v1.1.15**, if you set `autoCommit=>false` for `db` component in `config/console.php`, and perform a brand new migration using `/usr/bin/php yiic migrate up`, then `tbl_migration` is newly created, but it turns out that the table is _empty_. 

The migration is actually successful since my tables are created without any errors, but I have no way to `mark` or `migrate down` anymore. And `/usr/bin/php yiic migrate history` shows `No migration has been done before.`

Note: I am using `safeUp`, `safeDown` in my migration. I am using MySQL 5.6.19.

The issue does not occur if I do _not_ use (or comment out) `autoCommit=>false` for `db` component in `config/console.php`.

**Comment by samdark** [comment]
Won't be fixed in 1.1.
