### ISSUE TITLE
The method CActiveRecord::getOldPrimaryKey() returns a wrong value. 

### ISSUE THREAD

**Issue by iAchilles** [yiisoft/yii#3555]
The method CActiveRecord::update() allows to specify list of attributes that must be saved. So, if the primary key attribute is manually assigned with a different value and list of attributes does not contain the name of the primary key, the primary key value will not be updated, but the method CActiveRecord::getOldPrimaryKey() will return the value that was manually set.

``` php
$model = Foo::model()->findByPk(1);
var_dump($model->getOldPrimaryKey()); // string(1) 1
$model->attr = 'abc';
$model->pk = 777;
$model->update(array('attr'));
var_dump($model->getOldPrimaryKey()); // int(777) 
```

**Comment by ilyar** [comment]
:+1:
