### ISSUE TITLE
CJSON::decode does not properly flag invalid JSON input as invalid (return NULL)

### ISSUE THREAD

**Issue by GerHobbelt** [yiisoft/yii#3589]
When the bad content resides inside an array in the JSON input string, then that array content is decoded as NULL but the CJSON::decode() call itself still produces the rest and thus acts as if the input is legal (valid).

Minimal example to show the difference between PHP json_decode() (PHP 5.4+) and CJSON::decode() -- note the incorrect "y" array element: the colon is illegal --:

```
var_dump(json_decode('{ "x": [ "y" : { "A": 1 }], "z": 7 }'));
//   => NULL 

var_dump(CJSON::decode('{ "x": [ "y" : { "A": 1 }], "z": 7 }'));
//   => array(2)
//      x => array(1)
//          0 => NULL 
//      z => integer 7
```

The reason CJSON::decode() fails is because apparently decode errors are not propagated in its own PHP-based decoder, which, thanks to #403, is invoked when PHP native `json_decode()` returns NULL, as it does here.
## I have not provided a fix, because...:

Looking at the CJSON.php code, you'll find that the place where the array is parsed at line 515:

```
$arr[] = self::decode($slice,$useArray);
```

cannot easily detect where the returned NULL is a 'proper' NULL (because the input `$slice` was `null`) or an error-signaling NULL.

One option would be to pass along an variable reference which can be used to flag the error in any recursive call to `self::decode()`. Or one could throw an exception and catch it at the root call level. 
I don't know which solution flavor is prefered by the YII coders (personally I would go for the extra pass-by-reference parameter + if() check, assuming that would produce generally faster (as in: less slow) code in PHP, compared to nested try/catch exception stacks). 

**Side Note**: given the way CJSON::decode() is written, I bet the same bug type exists in the object decode path (where `{"a","b"}` is array-like illegal JSON) as it uses self::decode() recursion too.

**Comment by samdark** [comment]
Won't be fixed in 1.1.
