### ISSUE TITLE
CFileValidator made the attribute NULL even if the attribute is required

### ISSUE THREAD

**Issue by joshuatam** [yiisoft/yii#3672]
~~CUploadedFile::getInstance NOT Returning NULL when no file is submitted.~~

CFileValidator made the attribute NULL even if the attribute is required
The original code worked on 1.1.15, but failed on 1.1.16.

Example Code:
In CActiveRecord::rules():

``` php
array('file', 'required'),
array('file', 'file','types'=>'jpg, gif, png', 'allowEmpty'=>true),
```

Then in the file 

``` php
$model->file = CUploadedFile::getInstance($model, 'file');
// $model->file is NULL when no file is submitted.
// But it allows to save even it is an required attribute.
```

**Comment by nacesprin** [comment]
If i set 'save'=>false then throws error "CFileValidator.save not found".

So, which is the solution finally?

**Comment by joshuatam** [comment]
@nacesprin Typo, should be ```'safe'=>false```
