### ISSUE TITLE
CHtml::getIdByName does not include the point in the title

### ISSUE THREAD

**Issue by De-Luxis** [yiisoft/yii#3678]
If the field contains a point in the name, then the validation is perceived as css class.
example:
Name: PaymentModel[payment][form][1][0][field_cs.number][viewValue]
Id: PaymentModel_payment_form_1_0_field_cs.number_viewValue

Correct:
`return str_replace(array('[]','][','[',']',' ','.'),array('','_','_','','_','_'),$name);`
Sorry my english. Надеюсь понятно объяснил =)

**Comment by De-Luxis** [comment]
yii js vidation find $('#PaymentModel_payment_form_1_0_field_cs.number_viewValue')
More precisely:
ID: PaymentModel_payment_form_1_0_field_cs
Class: number_viewValue

And validation on the client does not pass.

**Comment by samdark** [comment]
Won't be fixed in 1.1.
