### ISSUE TITLE
CErrorHandler ignores YII_DEBUG for PHP errors when errorAction is defined

### ISSUE THREAD

**Issue by MonkeyMaster** [yiisoft/yii#3683]
In Yii 1.1.16 PHP errors always render via errorAction regardless of debug mode, exceptions still respect it though. Why PHP errors and exceptions now render differently? I found the only way to bring error stack trace back - by removing errorAction in dev config.

**Comment by samdark** [comment]
CErrorHandler.php, 367

**Comment by samdark** [comment]
I think in both cases it should now use errorAction...

**Comment by mdomba** [comment]
this is a duplicate of #2903, shouldn't be closed so all discussion is on one issue?
