### ISSUE TITLE
Remove inline style in CForm.php

### ISSUE THREAD

**Issue by alaabadran** [yiisoft/yii#3686]
Using 
` style="visibility:hidden" ` in both
renderElement() and renderBegin() is wrong.   
They should be replaced at least with ` style="display:none"`   
or removed completely (recommended)

**Comment by cebe** [comment]
so chaning to `display:none` would solve your issue, right? I think this is the best way to keep BC.

**Comment by cebe** [comment]
Fixed, thanks for reporting!

**Comment by cebe** [comment]
For reference: http://stackoverflow.com/questions/5439078/why-is-an-input-tag-not-allowed-directly-within-a-form-tag
