### ISSUE TITLE
release archives could not be downloaded in China

### ISSUE THREAD

**Issue by muhammadjava** [yiisoft/yii#3688]
First of all, thanks for the great work. I'm a big fan of Yii.

Recently, I'm having issues downloading .tar/.zip releases (1.1.15 and on). My browser hangs a long time at this URL "https://s3.amazonaws.com/github-cloud/releases..." until timeout, or when connected just receives "Access Denied" XML file.

Is there any way do make it available for download at other hosts?

By the way, the "Source Code" link (on "releases" page) works though. The download file also contains "framework", so can it be used for production the as well?

Thanks.

**Comment by cebe** [comment]
You may clone the git repository and check out the desired version:

```sh
git clone https://github.com/yiisoft/yii.git
cd yii
git checkout 1.1.16
```

This is the same as the framework release, it just includes more files like documentation and examples so you can use it too.

**Comment by muhammadjava** [comment]
Thanks a lot.
