### ISSUE TITLE
Column aggregation inheritance for relations

### ISSUE THREAD

**Issue by M0on75e1l** [yiisoft/yii#3689]
Doctrine 2 ORM's page in wikipedia:
>Other notable features of Doctrine are:
>   * column aggregation inheritance (similar objects can be stored in one database table, with one type-column specifying the subtype of the particular object - the correct subclass is always returned when a query is done);

<p>I think that's cool, but I can't find even brief discussion about some similar feature in Yii.</p>
I have a table containing information about bets `tbl_bet` and corresponding model `Bet`. User can bet on `Match`, `Map` or `Event`, so I have these three models as well, and that's why I've added two fields to my `tbl_bet`: `event_class` and `event_id`.  When user is betting on one of above three types of events, a new instance of `Bet` model is being created and it's `event_class` field gets corresponding class name.
Then to access event object from `Bet` model I have to use a value from `event_class` and then populate the record like this:
```php
/**
 * This is the model class for table "tbl_bet".
 *
 * @property string $event_class
 * @property integer $event_id
 */

class Bet extends CActiveRecord {
    /* ... */
    public function someMethod()
    {
        $eventClassName = $this->event_class;
        $event = $eventClassName::model()->findByPk($this->event_id);
    }
}
```
But wouldn't it be nice if I could just define relation and get an instance of class based on a value of `event_class` property? If I want to use this event object in different methods then I must manually develop some caching mechanism.

**Comment by nineinchnick** [comment]
I think this [article](http://www.yiiframework.com/wiki/198/single-table-inheritance/) covers it.

**Comment by M0on75e1l** [comment]
@nineinchnick 
>Relational databases do not support inheritance so if we need to represent it, we have to somehow store meta info while keeping performance by minimizing JOINs. One way to solve this problem is using single table inheritance. All fields for the whole class tree are stored in a single table. Class name is stored in the type field of the same table.

It's close but I've asked about relations. How can we apply that technic to populate correct **relation** class?

**Comment by cebe** [comment]
So you want to define one relation that goes to different tables dependent on a value of the record?
This is not possible with AR because we can not form a query in SQL that does eager loading for this kind of relation.

**Comment by claudiocarotenuto** [comment]
You're asking for polymorphic associations.

Claudio Carotenuto
Email: ing.claudio.carotenuto@gmail.com
Skype id: claudiocarotenuto
Mobile: +393408536910

2015-01-02 13:52 GMT+01:00 Carsten Brandt <notifications@github.com>:

**Comment by M0on75e1l** [comment]
@claudiocarotenuto maybe, I am not familiar with Rails, here I found a brief explanation of polymorphic associations:
http://guides.rubyonrails.org/association_basics.html 
@cebe yes, that's actually what I want. But if it's really possible in Rails AR, as @claudiocarotenuto mentioned, then it should be possible in Yii, I think. It's not possible with eager loading, but it's definitely possible with lazy loading.

**Comment by cebe** [comment]
at least for Yii 1.1 we are not going to implement it, if you want, you can open an issue for yii2 so we can consider it there later.
