### ISSUE TITLE
Minified JS for core packages

### ISSUE THREAD

**Issue by aztech** [yiisoft/yii#3692]
I suggest to create minified files for all core packages and update packages.php to use minified script files in case the YII_DEBUG is not set (like jquery package is defined).

**Comment by cebe** [comment]
This means we need a script that does the minifying when we update core js files. This should be part of the build commands: https://github.com/yiisoft/yii/tree/master/build/commands
Can you create such a script and send a PR?

**Comment by aztech** [comment]
There is a few compressors that can be used. The most popular are:
- JAVA-based [YUI Compressor](http://yui.github.io/yuicompressor/) from Yahoo;
- JAVA-based [ClosureTools](https://github.com/google/closure-compiler) from Google ([example](https://developers.google.com/closure/compiler/docs/api-tutorial2));
- [UglifyJS2](https://github.com/mishoo/UglifyJS2);
- [MinifyJS](https://code.google.com/p/minify/)

Which of them the Yii team would like to use?
Other question is if the compressed JS should be gzipped too.
Last but not least, I think it's worth to create solution which can be easily ported to Yii2.

**Comment by marcovtwout** [comment]
Most Javascript libraries such as jQuery are using Grunt with grunt-contrib-uglify. Seems like a good choice.

**Comment by samdark** [comment]
Not going to do it for 1.1.
