### ISSUE TITLE
Non-BC change on 1.1.16 (CSecurityManager encrypt/decrypt)

### ISSUE THREAD

**Issue by pmoust** [yiisoft/yii#3694]
Stated in the UPGRADE instructions;

```
- The implementation of `CSecurityManager::encrypt()` and `decrypt()`
were changed to be more secure.
  The old implementations were renamed as `legacyEncrypt()` and
`legacyDecrypt()`. If you use these methods to encrypt
  your data, you should either call legacy versions now to avoid code
break or take the following steps to use the new
  version (which we highly recommend):

  1. Decrypt existing data that were encrypted using `legacyDecrypt()`.
  2. Change key via application config (encryptionKey property of
securityManager component) to the one that conforms
     to recommendations.
  3. Encrypt the data using `legacyEncrypt()`.

  You can disable key validation by setting validateEncryptionKey
property of securityManager component to false but
  if it strongly not recommended.
```

`legacyEncrypt()` is nowhere upstream.

**Comment by kilinvs** [comment]
Also encryption algorithm definition as array is non backward compatible since 1.1.16, only strings now supported.

**Comment by pmoust** [comment]
A rant: this is a sensitive part of our application, and I assume to everyone that is using Yii and utilise the `CSecurityManager` or extend it.
Shouldn't there be a smoother way to introduce this change? A notice on 1.1.15 that the signature/implementation will change on next release would suffice.

Need an answer on whether I should buy me some time by checking in my extension of `CSecurityManager` to check if `legacyDecrypt` exists to use that one over `decrypt` whilst keep using `encrypt()`. Is `encrypt()` meant to be the same across 1.1.15 and 1.1.16 or not?

**Comment by pmoust** [comment]
@samdark @cebe @qiangxue please don't make us unit test the core framework in our test suites :see_no_evil:

**Comment by Ben5501** [comment]
In addition the CSecurityManager class property validateEncryptionKey is not used. So it is not possible to switch of the key validation as described above by setting the value to false. Am I right?

**Comment by samdark** [comment]
@pmoust no, there's no better way to introduce this change. Encryption wasn't good enough so we have to make it like that. It's very visible in the UPGRADE guide.

**Comment by pmoust** [comment]
@samdark the UPGRADE notes are flawed.

**Comment by samdark** [comment]
I'll check it next week (on vacation now).

**Comment by DanaLuther** [comment]
I am also having a huge issue with this. The legacyEncrypt() function does not exist, and using the legacyDecrypt() is not validly matching my stored encrypted passwords, so I'm VERY leery of trying to run any sort of batch conversion any time soon. I have millions of data records stored that will need to be converted.  Instead of being able to use the legacy methods for seamless upgrade until we have time to run a conversion, I will *have* to convert to move upwards.

**Comment by DanaLuther** [comment]
Also, setting the validateEncryptionKey property to false does not appear to have any impact and is not utilized anywhere in the CSecurityManager.

**Comment by DanaLuther** [comment]
In the new implementation of legacyDecrypt, it always calls md5 on the key:
`$derivedKey=$this->substr(md5($key),0,mcrypt_enc_get_key_size($module));`

In the old decrypt method, it only ran the md5 if the key was not explicitly provided:
` $key=$this->substr($key===null ? md5($this->getEncryptionKey()) : $key,0,mcrypt_enc_get_key_size($module));`

**Comment by samdark** [comment]
`legacyDecrypt` is already fixed in master.
