### ISSUE TITLE
CController::renderDynamic gives <###dynamic-0###>

### ISSUE THREAD

**Issue by fazliddin** [yiisoft/yii#3699]
It seems this issue was solved according to this: https://code.google.com/p/yii/issues/detail?id=1565. But I still experiencing this problem:
1. Caching component is enabled
2. Added COutputCache to controller filters
I have view file:

```
<div class="row clearfix">
    <?php foreach ($data as $item): ?>
        <?php $this->renderPartial('/product/_item', array('data'=>$item)); ?>
    <?php endforeach ?>
</div>
<?php if($index==1): ?>
    <div class="row clearfix">
        <?php
            $this->renderDynamic(
                'widget',
                'ext.banner.BannerWidget',
                array(
                    'bannerCode'=>'markaz',
                    'cssClass'=>'banner horizontal-banner'
                ),
                true
            );
        ?>
    </div>
<?php endif; ?>
```

this file is passed to CListView. Here is BannerWidget:

```
<?php

class BannerWidget extends CWidget
{
    public $bannerCode;
    public $cssClass='';

    function init()
    {
        $file=dirname(__FILE__).DIRECTORY_SEPARATOR.'jquery.slides.min.js';
        $file=Yii::app()->getAssetManager()->publish($file);
        Yii::app()->clientScript->registerScriptFile($file);

        $file=dirname(__FILE__).DIRECTORY_SEPARATOR.'banner.css';
        $file=Yii::app()->getAssetManager()->publish($file);
        Yii::app()->clientScript->registerCssFile($file);

        $banner = BannerModel::getItemsByCode($this->bannerCode, System::getCurLang());

        if(!empty($banner))
            $this->render($banner->template, array('items'=>$banner->bannerItems));
    }
} 
```

here is banner view file:

```
<div class="<?=$this->cssClass?>">
    <?php foreach ($items as $item):
    echo CHtml::link(CHtml::image($item->image_url, $item->description, array('class'=>'img-responsive')),$item->link);
     endforeach ?>
</div>
<br>
```

I have put this widget in many parts of web page and they all work fine. But problem is that one which I put inside view file passed to `CListView` gives this error text `<###dynamic-0###>` when pagination is clicked, that is, page=2, page=3. But main page do not give error

**Comment by fazliddin** [comment]
Here is action:
```
public function actionIndex()
    {
        $posts = (new ProductModel())->getFirst(Yii::app()->params['itemCount']);
        if (Yii::app()->getRequest()->getIsAjaxRequest())
        {
            $this->renderPartial('_item_list_view',  compact('posts'));
            Yii::app()->end();
        }
                
        $this->socialUrl = $this->createAbsoluteUrl('/');

        $this->render('index', compact('posts'));
    }
```
index.php:
```
	<?php $this->renderPartial('_item_list_view', compact('posts')) ?>
```
_item_list_view.php:
```
<a id="scrollTop"></a>
<?php
        $this->widget('zii.widgets.CListView', array(
            'dataProvider'=>$posts,
            'itemView'=>'/product/_item_row',
            'ajaxUpdate'=>true,
            'id' => 'main-page-list',
            'template'=>'{items} {pager}',
            'pager'=>array(
                'nextPageLabel'=>'кейингиси',
                'prevPageLabel'=>'олдингиси',
                'header'=>'',
                'cssFile'=>'',
                'htmlOptions'=>array('class'=>'pagination'),
            ),
            'itemsCssClass'=>'',
            'htmlOptions'=>array('class'=>''),
            'afterAjaxUpdate' => 'function(){
                $("html, body").animate({scrollTop: $("#scrollTop").position().top}, 1000);}'
        ));
?>
```

**Comment by fazliddin** [comment]
Interesting thing is when I comment
``` 
if(Yii::app()->getRequest()->getIsAjaxRequest())
{
            $this->renderPartial('_item_list_view',  compact('posts'));
            Yii::app()->end();
}
```
it works

**Comment by lupus78** [comment]
I'm also having this issue. I have a similar setup to Fazliddin, the only difference is that I have each list item cached separately (so the whole page is uncached, but the list items are cached). It is a search page with filters, sort and pager.

The first time the cache builds, everything is fine. Once you sort or filter the list, and get the results in a different order, the ###dynamic-nn### tags appear or maybe wrong content is replaced dynamicaly.

That's what I've figured out by looking into the cache files and doing some debuging:
- when the cache builds, the first item in my list will get a ###dynamic-0### tag, the second will be ###dynamic-1### and so on. Those are than saved into the cachefiles.
- once those list items are listed in a different order, the cache files will be read up, than the cache systems finds there is a dynamic piece. The first items dynamic piece will go into the 0 index of CController::_dynamicOutput, while the cache may refer to it as ###dynamic-6### (cause it was the 7th item back when the cache was created)

**Comment by fazliddin** [comment]
Do you use CListView here

**Comment by lupus78** [comment]
Yes I do
