### ISSUE TITLE
Undefined variable: acceptedLanguage in CHttpRequest

### ISSUE THREAD

**Issue by ddebin** [yiisoft/yii#3700]
Notice: Undefined variable: acceptedLanguage in [...]CHttpRequest.php on line 1054

...when using `CHttpRequest::getPreferredLanguage` !

Shouldn't it be `$preferredLanguage` instead of `$acceptedLanguage` on [L1054](https://github.com/yiisoft/yii/blob/1.1.16/framework/web/CHttpRequest.php#L1054) ?

**Comment by cebe** [comment]
right, this has been introduced by #2734.
