### ISSUE TITLE
[DOCS] unclear statement in CStatePersister documentation

### ISSUE THREAD

**Issue by teo1978** [yiisoft/yii#3701]
http://www.yiiframework.com/doc/api/1.1/CStatePersister

"CStatePersister is a core application component used to store global application state. It may be accessed via CApplication::getStatePersister(). page state persistent method based on cache."

The last part "page state persistent method based on cache." doesn't  make sense. I guess it's a piece of a sentence that was removed or something. It starts in lowercase after a fullstop, but neither removing the fullstop nor changing the P to uppercase it makes any sense. I really can't get what the author meant to say.

**Comment by samdark** [comment]
Removed it. Thanks.
