### ISSUE TITLE
Warning: mcrypt_module_get_supported_key_sizes() expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by S1lentium** [yiisoft/yii#3704]
In config main.php:

```
'securityManager'=>array(
    'cryptAlgorithm' => array('rijndael-256', '', 'ofb', ''),
    'encryptionKey' => 'ThisIsMySecretKey',
),
```

**Comment by georaldc** [comment]
Getting the same error here. I believe this wasn't a problem before the commit https://github.com/yiisoft/yii/commit/15fd6792513d733d3785c838d32a718485dabace added some changes to the CSecurityManager class because this was when the offending line was added: ```$supportedKeyLengths=mcrypt_module_get_supported_key_sizes($this->cryptAlgorithm);```
