### ISSUE TITLE
Regression in CPasswordHelper::generateSalt()

### ISSUE THREAD

**Issue by marcovtwout** [yiisoft/yii#3707]
Yii 1.1.6 unexplicitly raised the version constraint for using CPasswordHelper.

The issue is caused by this change: https://github.com/yiisoft/yii/commit/17ab79f694fa8245e84242be608c2e105e0f8be2 (issue https://github.com/yiisoft/yii/issues/3042)

The string prefix $2y is only supported since PHP 5.3.7. The code should probably check the PHP version, and use the previous implementation ($2a) otherwise?

See also: http://php.net/manual/en/function.crypt.php

**Comment by samdark** [comment]
`$2y` should work with previous versions as well. Is it actually causing trouble? If yes, how?

**Comment by marcovtwout** [comment]
On one of our hosts with PHP version: PHP 5.3.3-7+squeeze23 with Suhosin-Patch (cli):

```
exception 'CException' with message 'Interne fout tijdens het genereren van de hash.' in /(..)/application/vendor/yiisoft/yii/framework/utils/CPasswordHelper.php:97
Stack trace:
#0 /(..)(469): CPasswordHelper::hashPassword('test123')
```
https://github.com/yiisoft/yii/blob/1.1.16/framework/utils/CPasswordHelper.php#L97

A shorter hash is returned by crypt(), which causes this if-condition to fail: `strlen($hash))<32`

Yii 1.1.15 implementation, get_defined_vars():
```
array(4) { ["password"]=> string(7) "test123" ["cost"]=> int(13) ["salt"]=> string(29) "$2a$13$qsxC6U/lTrhCjIDKPq0juz" ["hash"]=> string(60) "$2a$13$qsxC6U/lTrhCjIDKPq0juus8lKQMYbOXs7NXG8DYDGb2eD5YqaGT6" }
```
Yii 1.1.16 implementation, get_defined_vars():
```
array(4) { ["password"]=> string(7) "test123" ["cost"]=> int(13) ["salt"]=> string(29) "$2y$13$eAw4PtWKbch2N/Qiji2UZi" ["hash"]=> string(13) "$2MHZsSq3y9q." }
```

**Comment by samdark** [comment]
Hmm. Weird. I suspect it's something about suoshin. I'll check it.
