### ISSUE TITLE
Definitive Guide to Yii: $criteria->select = false documentation bug

### ISSUE THREAD

**Issue by kevhiggins** [yiisoft/yii#3709]
The related model criteria example at the the below link has a bug in it.
http://www.yiiframework.com/doc/guide/1.1/en/database.arr#performing-relational-query-without-getting-related-models

Due to a bug fix at https://github.com/yiisoft/yii/pull/2295 `'select' => false`, no longer works.
I've had success with `'select' => ''` and `'select' => array()` though.

**Comment by marcovtwout** [comment]
Passing `'select' => false` doesn't work anymore, in any place where CDbCriteria is used, or only in relations() method? This could be a regression, not a documentation issue.

**Comment by kevhiggins** [comment]
It looks like `'select' => false` is not broken in all cases.

The only situation where I can get `'select' => false` to fail is on a `with` criteria nested within another `with` criteria.

For example, if you uncomment the line below, the query will fail with the following error:
`array_diff(): Argument #1 is not an array`

```php
$result = Page::model()->find([
    'with' => [
        'createdByUser' => [
            'with' => [
                'profile' => [
//                    'select' => false,
                ],
            ],
        ],
    ],
]);
```
So, this could either be a regression, or the intended behavior of multiple nested `with` criterias. 
If it's not a regression, then it should probably be documented somewhere. 

The documentation issue I mentioned for 
http://www.yiiframework.com/doc/guide/1.1/en/database.arr#performing-relational-query-without-getting-related-models works fine as long as you don't nest multiple `withs`

**Comment by kevhiggins** [comment]
I ran a few more tests, and it looks like there was an underlying issue in some of my custom code.

Next time, I will make sure to test using a base Yii installation first.

Closing.
