### ISSUE TITLE
Module alias not defined, depending on configuration

### ISSUE THREAD

**Issue by marcovtwout** [yiisoft/yii#3711]
The Yii guide states, that every module gets an alias based on module id. But, depending on how the module class is defined, the alias becomes available under different circumstances. An example:

Config file:
```php
'modules' => array(
   'foo' => array(),
   'bar' => array(
        'class' => 'vendor.test.bar.BarModule'
   ),
),
```

The alias `foo` is available directly after application is constructed: https://github.com/yiisoft/yii/blob/7b0281b4f0ee6fd1e0e64f0dedd571ccce9536fd/framework/base/CModule.php#L357

The alias `bar` only becomes available when the module is called: https://github.com/yiisoft/yii/blob/7b0281b4f0ee6fd1e0e64f0dedd571ccce9536fd/framework/base/CModule.php#L82

Is there a reason why the `bar` alias is not set earlier?

Untested code for a possible solution:

CModule::setModules()
```php
...
if(!isset($module['class']))
{
    if (Yii::getPathOfAlias($id)===false)
        Yii::setPathOfAlias($id,$this->getModulePath().DIRECTORY_SEPARATOR.$id);
    $module['class']=$id.'.'.ucfirst($id).'Module';
}
// new:
else 
{
    $moduleClass = Yii::getPathOfAlias($module['class']);
    if ($moduleClass!==false && Yii::getPathOfAlias($id)===false)
        Yii::setPathOfAlias($id,dirname($moduleClass));
}
```

**Comment by cebe** [comment]
the problem with the module in vendor is that it may implement the `getBasePath()` method and return a base path that is different from the default. This way Yii can only set the path after instantiating the module and calling getBasePath(). If you only define the ID, the base path is the default and know, so yii can set it.

**Comment by marcovtwout** [comment]
I understand the complication. Can we update the documentation noting this?

**Comment by cebe** [comment]
If you find a good place where it may fit, feel free to send a pull request.

**Comment by marcovtwout** [comment]
Posted as a comment.

**Comment by cebe** [comment]
cool, thanks
