### ISSUE TITLE
(Active)Query->count() returns string

### ISSUE THREAD

**Issue by bmvankessel** [yiisoft/yii#3712]
It can be regarded as a bug.

The documentation states that the count method will return an integer. However the method count uses the method queryScalar returning either a boolean or a string.

I encountered this 'bug' while checking the outcome of count on both type and value causing the check always to fail.

Please either adjust the documentation or cast the result of count to integer.

**Comment by cebe** [comment]
this is a documentation issue, we can not cast to integer because the integer may be greater than a 32bit integer value.

**Comment by cebe** [comment]
This looks like it is meant for yii2, so next time please report issues in https://github.com/yiisoft/yii2 repository.

**Comment by cebe** [comment]
closed by https://github.com/yiisoft/yii2/commit/4267b53d43d48900b1f53cf010e05e16deb65815
