### ISSUE TITLE
Using cache for method "getAttributes" of a model class, enables cache for the very next model call.

### ISSUE THREAD

**Issue by arfeen** [yiisoft/yii#3713]
The problem I found when I used a simple getAttributes method with cache. As follows:

$fields = AnyModel::model()->cache(200)->getAttributes();

Now, I called another model after this line:

$activerecord = FeedModel::model()->findByPk(1);

So I found that "FeedModel" is now enabled for cache and serving the records it fetched first time, even though both models are different. This cache was enabled for 200 seconds as you can see getAttributes method was called for 200 seconds of cache invalidation.

The trace can be seen in log profiler as well.

Yii Framework 1.1.8
XAMPP 1.7.7 Windows 7
MySQL 5.5.16
Firefox v. 35.0
Cache Engine: SQLite

**Comment by samdark** [comment]
That's expected since enabling cache works till the query is done. `getAttributes` isn't performing any queries.
