### ISSUE TITLE
Add authclient OAuth2

### ISSUE THREAD

**Issue by EngRajabi** [yiisoft/yii#3728]
OAuth2 using many project.
create oauth server and client .
please add OAuth2

**Comment by klimov-paul** [comment]
We do not have time to support authclient at Yii1. There are many 3ed party extensions, which you may use instead.

**Comment by EngRajabi** [comment]
note 3ed party extensions for oauth2 server

**Comment by klimov-paul** [comment]
Still I am afraid such enhancement is out of the Yii1 scope. We simply don't have enough researces for this.
