### ISSUE TITLE
Undocumented (if any) support for position in CClientScript.registerCoreScript()

### ISSUE THREAD

**Issue by matteosistisette** [yiisoft/yii#3732]
Judjing from this line of the source code:
https://github.com/yiisoft/yii/blob/1.1.16/framework/web/CClientScript.php#L594

it looks like registerCoreScript supports the second parameter (and the third, for that matter) for position (i.e. POS_HEAD, etc), like registerScriptFile does.

If I'm missing something and it doesn't, then it should.
But if it does, then it is not documented, and it should be.

**Comment by cebe** [comment]
No, it does not support it, that line is only for caching.

**Comment by matteosistisette** [comment]
Whops, right, I see.

Well, then it definitely should support it. 
Actually  the most elegant solution would be for the packages to have a parameter indicating the position in the array that defines the package.
For example, one could be define the "jquery" core script to be registered at POS_HEAD and another script to be registered on POS_END.

**Comment by cebe** [comment]
While this is theoretically possiple the implementation is not easy as it also needs to consider dependecies between packages. We have done this in Yii2 but I do not think we will add this to yii1 as it will take too much time. You can try and send a pull request though if you want this to be supported.
