### ISSUE TITLE
add Extensions to core cunique

### ISSUE THREAD

**Issue by EngRajabi** [yiisoft/yii#3736]
Extensions unique-multiple-columns-validate
linke : http://www.yiiframework.com/extension/unique-multiple-columns-validate/
please add extensions unique multiple to core cunique framework

**Comment by cebe** [comment]
We are not going to add complete new features to yii 1.1. Especially not when there is an extension. What is the reason for your request?

**Comment by cebe** [comment]
btw: http://stackoverflow.com/questions/9670992/yii-how-to-make-a-unique-rule-for-two-attributes/9692637#9692637
