### ISSUE TITLE
CHtml::activeLabelEx() overrides explicit 'required' parameter in htmlOptions

### ISSUE THREAD

**Issue by matteosistisette** [yiisoft/yii#3738]
Please see this:
https://github.com/matteosistisette/yii/commit/b748fa6c66e47065197dee448909a4fde1ea8a47

I wanted to do a pull request but I don't know how to do it without including other things with which I messed around.

It's just one line of code.

I think activeLabelEx() should not override the 'required' parameter if it is explicitly passed in the htmlOptions parameter.

**Comment by cebe** [comment]
merged it, thanks.
