### ISSUE TITLE
How to integrate payment gateway in yii2 using PayPal extension for the Yii2

### ISSUE THREAD

**Issue by sunnybhakta** [yiisoft/yii#3742]
How to use paypal extension in yii2. I am using this link
https://github.com/marciocamello/yii2-paypal.
I installed extension and also added code in config file .

But there is not more information what to do next . So please help me.

**Comment by klimov-paul** [comment]
Address this question to the author of the extension you mention.

**Comment by sunnybhakta** [comment]
Hello klimov-paul , i am creating a website using yii2.0 in which payment gateway integration is required using paypal . I read above document but not helped because i think it is incomplete. can you help me how can i integrate payment gateway in yii2.

**Comment by abhishek0306** [comment]
Hi,
I am using yii2 framework in my Website and now i have to integrate paypal in to my website. I have installed yii2 extension for paypal in my code and also entered that configuration to my config file. Can you tell me whats the next step to do now.

**Comment by cebe** [comment]
please use the forum to ask questions, github is a bug tracker.
