### ISSUE TITLE
Fix typo in Gii generating crud code section of Definitive Guide

### ISSUE THREAD

**Issue by userlond** [yiisoft/yii#3744]
Here it is http://www.yiiframework.com/doc-2.0/guide-start-gii.html#generating-crud-code (section Generating CRUD Code, first screenshot of section). I believe that view path should be smth like @app/views/country, not \app\view\country.

Sorry if I'v made a mistake.

**Comment by samdark** [comment]
You're correct and there's already an issue about it. btw., this issue tracker is about Yii 1.1.
