### ISSUE TITLE
YII forum

### ISSUE THREAD

**Issue by mvinoth94** [yiisoft/yii#3746]
Hi Ter ,

I'm active in Yii forum more then one year.Recently i login in to the Yii forum. My active post/comments all are missing.

my id : mvinoth94@yahoo.com

Thank you.
regards.
vinoth.mohan

**Comment by samdark** [comment]
http://www.yiiframework.com/forum/index.php/user/144524-vinothmohan/ 43 posts.  Dec 13 2014 05:32 AM last active.

**Comment by samdark** [comment]
Is it wrong?

**Comment by mvinoth94** [comment]
Hi,

Nop. Its not wrong. I have two id account and i wrongly login to old account.
Thanks .
Tq

 


     On Tuesday, 10 February 2015, 17:23, Alexander Makarov <notifications@github.com> wrote:
   

 Is it wrong?—
