### ISSUE TITLE
Using PJAX

### ISSUE THREAD

**Issue by berthojoris** [yiisoft/yii#3751]
I use pjax to load all page with Yii1 ?
My code in layput

```php
<?php
Yii::app()->clientScript->registerScript('PjaxLoad',"
$(document).pjax('a', '#content');
",CClientScript::POS_END);
?>
```
When I call a page with pjax, all client-side **enableClientValidation** validation using **CActiveForm** becomes not run properly. Is there a way to reload in order to validate client pjax I re-run?

**Comment by samdark** [comment]
Not that I'm aware of.
