### ISSUE TITLE
CPgsqlSchema::dropIndex() is broken

### ISSUE THREAD

**Issue by kiaplayer** [yiisoft/yii#3757]
It seems that now CPgsqlSchema::dropIndex() cannot drop index which was added by new CPgsqlSchema::createIndex() (#788). I've got this error:

    SQLSTATE[2BP01]: Dependent objects still exist: 7 ERROR:  cannot drop index <index_name> because constraint <index_name> on table <table_name> requires it
    HINT:  You can drop constraint <index_name> on table <table_name> instead.

I had to restore old version of createIndex() in my PgsqlSchema class to fix it :(

**Comment by nineinchnick** [comment]
To fix this, `dropIndex()` would have to read from `information_schema.table_constraints` to see if there is an unique constraint named like the index. The problem would be to split `$table` argument into schema name and table name.

I think the #2803 PR should be reverted, it's way easier and actually fixes the issue completely. A note in `createIndex()` comment can be left why it doesn't use recommended syntax.

**Comment by c-schmitz** [comment]
I don't think it is a solution to fall back to the old way - modern indexes are usually created the new way (if created manually or using the PGAdmin tool ) and this function won't still be able to do drop these, then.
