### ISSUE TITLE
Retrieve the last line in has_one relation with millions of lines

### ISSUE THREAD

**Issue by AndersonDan** [yiisoft/yii#3758]
Something rare to happen is one to one where the second table can have millions of results for the first one. For example, I have a 'radcliente' table that has millions of 'radacct', but need to filter only with the last acct. The following are examples for better explanation:

This is generated by Yii:

(More than 40 seconds to return the result)

![criteriayii1](https://cloud.githubusercontent.com/assets/10473169/6262534/68fa07b0-b7ec-11e4-8f72-97bd2ec0607a.jpg)

![sqlyii1](https://cloud.githubusercontent.com/assets/10473169/6262541/810f365e-b7ec-11e4-8aaf-9245515d8a5c.jpg)

My solution was to extend and generate the different query to has_one:

(This is very fast, less than 500ms)

![criteriayii2solution](https://cloud.githubusercontent.com/assets/10473169/6262549/a4874112-b7ec-11e4-8a08-f8948f5bd603.jpg)

![sqlyii2solution](https://cloud.githubusercontent.com/assets/10473169/6262551/a9328366-b7ec-11e4-80fc-04685ce59df7.jpg)

The problem is this query generated CActiveDataProvider to the total count:

![count](https://cloud.githubusercontent.com/assets/10473169/6262561/024282b2-b7ed-11e4-8ade-095af3b827ae.jpg)

I do not know if the problem is exactly related to Yii, but a solution to this would be interesting.

Thank You.

**Comment by nineinchnick** [comment]
You change the join to use a different column `radacctid` instead of `client_id`, so this is a different relation. Please describe your models too.

**Comment by YKnob** [comment]
Thank you for your response. I've been doing some tests and noticed that is slow in all cases, the table 'radacct' exacerbates the problem by its size, which should not therefore limit the 1 in the subquery. Follow the models and the link to access the system, if you need to authenticate is:

To access:

http://177.86.111.30/dev2/teste

To download models and schema of radcliente and radacct: http://177.86.111.30/files.zip
