### ISSUE TITLE
Gii's form generation gives error 'The character encoding of the HTML document was not declared'

### ISSUE THREAD

**Issue by fazliddin** [yiisoft/yii#3763]
Clicking on preview button of Gii's form generator redirects to completely blank page. Browser's console says: `The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol.`

I found that such error also occured before https://code.google.com/p/yii/issues/detail?id=2883

**Comment by samdark** [comment]
Could you check AJAX response via browser debug tools?

**Comment by fazliddin** [comment]
![screenshot from 2015-02-20 15 36 05](https://cloud.githubusercontent.com/assets/5574503/6284794/43a4a1a2-b916-11e4-98e4-de2119cfebef.png)

url: index.php?r=gii/form/index&lang=en_us
