### ISSUE TITLE
incorrect doc for CEmailValidator::validateValue()

### ISSUE THREAD

**Issue by fazliddin** [yiisoft/yii#3764]
It is written that
```
Note that this method does not respect {@link allowEmpty} property.
```
But look at the code
```
if($this->allowEmpty && $this->isEmpty($value))
			return true;
...
```

**Comment by cebe** [comment]
introduced by #3283, should be reverted.

**Comment by Lexxtor** [comment]
```
Note that this method does not respect {@link allowEmpty} property.
```
Why it was done like that?

**Comment by cebe** [comment]
because `validateValue()` is to be used to check if a string is a valid email without the context of the model validation flow. It should be possible to just pass a string and check whether it is a valid email without having to check if it is empty or not before.
