### ISSUE TITLE
Formatter->asCurrency() not support netheir config['language'] nor config['formatter']['locale']

### ISSUE THREAD

**Issue by hungtrieu** [yiisoft/yii#3766]
I want to format the price, i.e: 150.000 đ; The yii\i18n\Formatter is very helpful, but it has a minor issue: it alway put the currency code before the number, so I only get đ 150.000 when call it. Please modify this function to make currency code display depend on config['language'] or config['formatter']['locale']. I don't want to use raw php function or hack the core in my case :)

Thanks.

**Comment by cebe** [comment]
`asCurrency` sounds like you are using Yii2. Please open an issue on the yii2 repository: https://github.com/yiisoft/yii2
