### ISSUE TITLE
Debug info missing for PHP-errors in CWebService

### ISSUE THREAD

**Issue by marcovtwout** [yiisoft/yii#3770]
Certain PHP errors are not caught by the exception handler or the Yii error handler. File and line number is lost, no stacktrace, and nothing shows up in the application log.

```php
class ApiController extends CController
{
    public function actions()
    {
        return array(
            'soap' => array(
                'class' => 'CWebServiceAction',
            ),
        );
    }

    /**
     * @soap
     */
    public function test()
    {
        new Test123;
    }
```

```php
<?php

class Test123
{
    public function __construct()
    {
        :: // trigger syntax error
    }
}
```

Result:

```
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://schemas.xmlsoap.org/soap/envelope/">
   <SOAP-ENV:Body>
      <SOAP-ENV:Fault>
         <faultcode>SOAP-ENV:Server</faultcode>
         <faultstring>syntax error, unexpected ';'</faultstring>
      </SOAP-ENV:Fault>
   </SOAP-ENV:Body>
</SOAP-ENV:Envelope>
```

**Comment by cebe** [comment]
Yii 1.1 error handler can not handle php syntax errors.

**Comment by marcovtwout** [comment]
Do you know it is is SoapServer that converts this syntax error into a SoapFault then? Even if Yii's error handler cannot function here, it would be good if there is a way to get at least a file/linenumber.

**Comment by cebe** [comment]
How is this related to yii? does the yii webservice class produce this output?

**Comment by marcovtwout** [comment]
Well yes and no. The Yii webservice classes uses PHP's SoapServer class, and I think that's the one that produces this error output. Tested with SoapUI and PHP 5.4.12.

**Comment by cebe** [comment]
This should be reported to PHP then.
