### ISSUE TITLE
Undefined index: SERVER_NAME when calling getHostInfo() from PHPunit test.

### ISSUE THREAD

**Issue by marcovtwout** [yiisoft/yii#3771]
Running latest PHPunit on Windows 7 x64, I get the following error on getHostInfo():

```
Undefined index: SERVER_NAME
S:\www\test\application\vendor\yiisoft\yii\framework\web\CHttpRequest.php:344
S:\www\test\application\vendor\yiisoft\yii\framework\base\CApplication.php:568
```

This code should check if "SERVER_NAME" is set, and throw an Exception or return null if the host info cannot be determined.

Source: https://github.com/yiisoft/yii/blob/master/framework/web/CHttpRequest.php#L344

**Comment by klimov-paul** [comment]
That is not surprising since `$_SERVER['SERVER_NAME']` available only for the web request, while `phpunit` is a console command.

**Comment by marcovtwout** [comment]
Ofcourse, but Yii should not throw a low level PHP error here, don't you agree?

**Comment by cebe** [comment]
we can not check the environment in all places that are meant to be used in web context only. It should not work and it does not, thats totally fine this way.

**Comment by marcovtwout** [comment]
Maybe just a simple:

```
if (!isset($_SERVER['SERVER_NAME']))
    throw new CException(Yii::t('yii','CHttpRequest is unable to determine hostInfo.'));
```
