### ISSUE TITLE
"setPrivateState()" for sensitive data about the user

### ISSUE THREAD

**Issue by batusa** [yiisoft/yii#3772]
I guess the title talks for itself. It would be to store extra info that I want to keep only on the server-side without going to the user cookies for example...

I would set them from my useridentity and the webuser would be in charge of storing the data in session.

It's just a suggestion. 

In case you guys already have "a way" or a suggestion to achieve this goal, please let me know here.

Thank you.

**Comment by cebe** [comment]
http://www.yiiframework.com/doc/api/1.1/CWebUser#setState-detail ?

**Comment by batusa** [comment]
I'm aware of this method, however, if the programmer decides to use cookie-based login, these data from "states" will be stored on the client (web browser) with a cookie.

**Comment by batusa** [comment]
@cebe

**Comment by cebe** [comment]
No, it is stored in SESSION, check the code: https://github.com/yiisoft/yii/blob/1.1.16/framework/web/auth/CWebUser.php#L593

**Comment by batusa** [comment]
http://www.yiiframework.com/doc/api/1.1/CWebUser
"Besides, an identity may have additional persistent data which can be accessed by calling getState. Note, when cookie-based authentication is enabled, all these persistent data will be stored in cookie."

https://github.com/yiisoft/yii/blob/1.1.16/framework/web/auth/CWebUser.php#L508
This method saves user ID, username, other identity states and a validation key to cookie.

These descriptions got me to think that persistents data from webuser are stored in cookie.

**Comment by cebe** [comment]
Now I see what you are up to, yes, values saved with setState will end up in the identity cookie. What you want sounds like just storing it in the session but it will then not survive the session live time. If you need that you have to store it in the database. This is then an application specific implementation.

**Comment by batusa** [comment]
I don't want to store it in the database. I want just to keep some extra info only on my server-side.. and yes, using sessions.

If I use setState I may have my data in the client's cookie. Thing that I don't want for some particular states.

**Comment by batusa** [comment]
I would take advantage of the setState interface to keep some of them as "private".

**Comment by cebe** [comment]
setState is just a wrapper for `$_SESSION['key'] = 'value'` with a defined prefix. So you could just set the session value to keep some state in the session.
