### ISSUE TITLE
CFileHelper crashes on broken symlinks

### ISSUE THREAD

**Issue by etienneq** [yiisoft/yii#3773]
This applies to findFiles() and copyFiles() as well. The reason is in the implementation of findFilesRecursive() and copyDirectoryRecursive()

As is_file() returns false an broken symlinks the code asumes that these are directories. To fix this it should explicitly tested with is_dir() before the recursive call takes place.

I will provide a pull request shortly.

Cheers
Etienne

**Comment by samdark** [comment]
Won't work on Windows. There non-broken symlinks return is_dir true.

**Comment by samdark** [comment]
How to get such broken link?

**Comment by etienneq** [comment]
Even when the symlink points to a regular file? It tested in on Linux.
There is_file() and is_dir() work fine on symlinks.

2015-02-25 10:42 GMT+01:00 Alexander Makarov <notifications@github.com>:

**Comment by etienneq** [comment]
@samdark First create a symlink, then delete the original file or directory.

**Comment by samdark** [comment]
Won't work on Windows where `is_dir` still returns true even if original dir was deleted.
