### ISSUE TITLE
Search on different versions of article

### ISSUE THREAD

**Issue by nywuctuk** [yiisoft/yii#3775]
When you try SEARCH on blog article you can see results from 2 different versions at least
http://www.yiiframework.com/doc/blog/1.1/ru/post.model
http://www.yiiframework.com/doc/blog/1.0/ru/post.model

This bug can be anywhere else.
fix is good

**Comment by cebe** [comment]
what exactly is the problem? please elaborate.

**Comment by samdark** [comment]
How should it be fixed?

**Comment by nywuctuk** [comment]
When you find something in manual (blog its manual too) you want see fresh code.

-delete old articles
 or
-delete from search

**Comment by cebe** [comment]
you mean the search should only show the latest version or at least group different versions of the same page into one search result item?

**Comment by cebe** [comment]
moved to https://github.com/yiisoft-contrib/yiiframework.com/issues/17
