### ISSUE TITLE
Missing const TYPE_DOUBLE = 'double';

### ISSUE THREAD

**Issue by nexusevgeniy** [yiisoft/yii#3779]
Show fatal PHP error (constant is missing) in vendor\yiisoft\yii2-gii\generators\model (missing constant case Schema::TYPE_DOUBLE): 
In yiisoft/yii2/db/Schema.php missing const TYPE_DOUBLE = 'double'.
GII Model generator has error in ActiveRecord model generating with MySQL tables with Double field types.

**Comment by samdark** [comment]
It's Yii 1.1 issue tracker.
