### ISSUE TITLE
Add all available languages in messages/config.php file

### ISSUE THREAD

**Issue by NabiKAZ** [yiisoft/yii#3783]

**Comment by samdark** [comment]
What do you mean by all available?

**Comment by NabiKAZ** [comment]
means all folders exist in messages folder. for work effectively `yiic message messages/config.php` command.
I working on it and will submit new pull request now.

**Comment by NabiKAZ** [comment]
How can I submit pull request just for this commit? https://github.com/yiisoft/yii/commit/1181da2ab917353f30055cbe858a6fe0af43f1f3
