### ISSUE TITLE
dont use navbar-fixed-top class in yii template

### ISSUE THREAD

**Issue by hsadeqi54** [yiisoft/yii#3791]
Its a bog of bootstrap . And its have a problem in mobile  size  when we click on button , nav item can not scroll down. use navbar-static-top class

**Comment by samdark** [comment]
Yii 1.1 doesn't use bootstrap.

**Comment by hsadeqi54** [comment]
But yii 2 use bootstrap

**Comment by hsadeqi54** [comment]
Its in template of advansed and beasic

**Comment by cebe** [comment]
@hsadeqi54 yii 2 issues are at https://github.com/yiisoft/yii2
