### ISSUE TITLE
Not full cache DbManager

### ISSUE THREAD

**Issue by Rakovskiy** [yiisoft/yii#3792]
In DbManager cached not all methods. Such as:
* getItems ()
* getRolesByUser ()
* getPermissionsByRole ()
* getPermissionsByUser ()
* getAssignment ()
* getAssignments ()
* hasChild ()
* getChildren ()

**Comment by cebe** [comment]
are you talking about yii2? if yes, report to https://github.com/yiisoft/yii2/issues please
