### ISSUE TITLE
how to do configure the url rewrite in ningx????thanks

### ISSUE THREAD

**Issue by maige123** [yiisoft/yii#3795]
first! the web server is nginx.

in the nginx.conf, write the 
location / {  
    if (!-e $request_filename){  
        rewrite ^/(.*) /index.php last;  
    }  
} 

and in the main.php
i write the rule of  'team-buy.php'=>'/team/buy'
but is 404.

if i write the rule of 'team-buy.html'=>'/team/buy',
is ok.

why .php is wrong?

**Comment by samdark** [comment]
Check the guide, installation section.

**Comment by maige123** [comment]
but the rule is ok in apache.

**Comment by samdark** [comment]
nginx is not apache.

**Comment by maige123** [comment]
buy the rule is in the main.php, when i use nginx, the urlManager is disable?

**Comment by samdark** [comment]
No. You just have nginx config wrong. http://www.yiiframework.com/doc-2.0/guide-start-installation.html#recommended-nginx-configuration
