### ISSUE TITLE
flash message disappears after using render() in controller

### ISSUE THREAD

**Issue by batusa** [yiisoft/yii#3798]
**1.1.14**

suppose I'm at my controller class in some action and I have the following code (just as an Example):

```php
Yii::app()->user->setFlash('something', 'hey');
$this->render('myview');
echo Yii::app()->user->getFlash('something');
```

my getFlash() doesn't get anything! I realized it happens when I use the render method.

wouldn't it be a bug?

in my case I'm setting a flash message in one action, redirecting to another one, there I want to get the flash message Only when the form is submitted, but unfortunately I can't because it doesn't get anything :cry:

**Comment by cebe** [comment]
looks like your render method displays the flash message and so it will be removed. This is expected behavior.

**Comment by batusa** [comment]
how so "looks like"? have you tested it? why is it an expected behavior? my render is not displaying anything...

**Comment by batusa** [comment]
@cebe

**Comment by klimov-paul** [comment]
@batusa, I am afraid you have not provide anything to "be tested".
I have just verified flash functionaly with the latest code - it works fine.
Most probably there is something inside your view code, which clears flash message.

Unless you provide more explicit description on how to reproduce your problem, I can't see any issue here.

**Comment by batusa** [comment]
@klimov-paul I was afraid there was something in my view code that was getting rig of my flash message, but then I tested with a view file with no code, and when I use the render method it clears the flash message.

**Comment by batusa** [comment]
@klimov-paul the code sample I posted on this issue is enough to test. just go to a brand new action in your controller, create a new view file just to pass on render and then try to see if it gets the "something" flash message.

remembering that I'm using Yii 1.1.14

**Comment by klimov-paul** [comment]
What about layout file?
What about session start/close?
Look, I can not trace your program: if can provide the clear way to reproduce it, which starts from words 'create new application via webapp command', I can't do anything.

**Comment by klimov-paul** [comment]
If you are using outdated version of framework - obvious solution for you is its upgrade.

**Comment by batusa** [comment]
sorry guys, problem solved, there's no problem with the framework about that.
next time I'll think - and test - a lot before creating an issue like this one :wink: 

appreciate your time and feedbacks @klimov-paul @cebe
