### ISSUE TITLE
Feature Request: CForm configuration reusability

### ISSUE THREAD

**Issue by vercotux** [yiisoft/yii#3799]
CForm (and the whole form builder mechanism) is an amazingly useful tool Yii provides, but it lacks one simple feature to make it go into hyperdrive: the ability to "import" form configurations via the CFormInputElement [type](http://www.yiiframework.com/doc/api/1.1/CFormInputElement#type-detail) attribute.

At the moment the _type_ attribute is able to take 3 kinds of values:
- one of the predefined element aliases ("text", "hidden", "password", "textarea", "file", "radio", "checkbox", "listbox", "dropdownlist", "checkboxlist", or "radiolist") or
- "form" to create a sub-form or
- a path alias to a widget extending from a CInputWidget

I propose adding a 4th possibility: **A path alias to a CForm configuration.**
This would allow us to specify a form configuration once and then easily reuse it in multiple forms.

**Comment by samdark** [comment]
Closed since features aren't accepted into 1.1 anymore.
