### ISSUE TITLE
Get wrong collection

### ISSUE THREAD

**Issue by janeyhjy** [yiisoft/yii#3801]
When I have the same collection in two mongodb, 
eg. "a.user" and "b.user"
1. Get data from a.user
2. Save data to b.user
When save data to b.user ,the collection is a.user

**Comment by klimov-paul** [comment]
Please? provide your code.

**Comment by klimov-paul** [comment]
You should report this issue to the Yii2 repository:
https://github.com/yiisoft/yii2

Please make sure you provide more explicit description of what steps are to reproduce your problem.
