### ISSUE TITLE
fwrite\fgets expects parameter 1 to be resource, boolean given

### ISSUE THREAD

**Issue by nicdnepr** [yiisoft/yii#3805]
Why I get such errors in error.log
[Sun Mar 15 08:04:12.215403 2015] [:error] [pid 2180] [client 213.110.:50450] PHP Warning:  fwrite() expects parameter 1 to be resource, boolean given in /var/www/html/ads/protected/vendor/yiisoft/yii/framework/caching/CRedisCache.php on line 123
[Sun Mar 15 08:04:12.215435 2015] [:error] [pid 2180] [client 213.110.:50450] PHP Warning:  fgets() expects parameter 1 to be resource, boolean given in /var/www/html/ads/protected/vendor/yiisoft/yii/framework/caching/CRedisCache.php on line 135

**Comment by cebe** [comment]
you should have received an exception about not being able to connect to redis before. Are you by any chance catching a redis exception somewhere?
