### ISSUE TITLE
Calling unknown method: yii\web\UrlManager::addRules()

### ISSUE THREAD

**Issue by dyar74** [yiisoft/yii#3806]
Hello. I have some problem after update to version 2.03: "Calling unknown method: yii\web\UrlManager::addRules()". This function not present in new version of UrlManager.php. But it called in yii2-gii Module.php. 
 - operating system  - Linux  3.2.0-68-generic, Ubuntu  x86_64 GNU/Linux
- Web server - apache
- browser type - firefox
- Yii version - 2.0.3

**Comment by samdark** [comment]
Specify Gii version in Composer as 2.0.3.
