### ISSUE TITLE
Suggestion of minor change in CheckboxColumn

### ISSUE THREAD

**Issue by karpy47** [yiisoft/yii#3810]
Yii/grid/checkboxcolumn/renderHeaderCellContent()
First line of code:
$name = rtrim($this->name, '[]') . '_all';

This line causes problem when for example $this->name = 'MyForm[key]' becomes 'MyForm[key_all'.
The idea is to strip of '[]' (that is added automatically at row level) before adding '_all'.
In my example I would like to have 'MyForm[key_all]' as result.
   
Could be solved with regular expression...

**Comment by cebe** [comment]
this is the wrong repository, please report to https://github.com/yiisoft/yii2
