### ISSUE TITLE
check file exists on YiiBase::autoload, #432?

### ISSUE THREAD

**Issue by boooosh** [yiisoft/yii#3814]
If other autoloader was registered by vendors without use YiiBase::registerAutoloader, the autoloader will be append to spl autoload functions. And then PHP will throw a E_WARNING when then the vendor wanna to include its libraries.

**Comment by cebe** [comment]
have you seen? #3776
should be solved by it.

**Comment by boooosh** [comment]
well
this problem will appear in some old plug-ins without use namespace, for example, the [PHPExcel](https://github.com/PHPOffice/PHPExcel).

**Comment by cebe** [comment]
yeah we can not fix this because we can not check for file_exists in includepath. While it may be possible it will have major performance drawbacks. you can register the autoloader in another order or disable includePath.

**Comment by boooosh** [comment]
i see, thks.
