### ISSUE TITLE
Search data using ajax in yii2 (Not Pjax).

### ISSUE THREAD

**Issue by sunnybhakta** [yiisoft/yii#3817]
I am creating search form in yii2 . I am able to get using form submit but i want to know how can i do this using ajax . I have to achieve search like this link http://www.rarepink.com/loose-diamonds.

By form submit i am able to get data but i want to achieve using ajax. I also want to display the result in default gridview. I know Pjax concept in yii2 but that is not how i wanted.

Thanks

**Comment by samdark** [comment]
Please use forums for questions. GitHub is for issue reports and feature requests.
