### ISSUE TITLE
Problem with config merge strategy in advanced app (DummyCache has no server property)

### ISSUE THREAD

**Issue by dataskills** [yiisoft/yii#3822]
I assume a common scenario is having (for example) memcache on a production server but not installed for dev where one might use DummyCache. 

In this case one would have the memcache config in main.php 

    'components' => [
        'cache' => [
            'class' => 'yii\caching\MemCache',
            'servers' => [
                [
                    'host' => 'localhost',
                    'port' => 11211,
    ...

and the DummyCache config in main-local.php. 

    'components' => [
        'cache' => [
            'class' => 'yii\caching\DummyCache',
    ...

This does not work because when the configurations are combined DummyCache "inherits" the server property from the MemCache config, which it does not have, and yii\base\UnknownPropertyException is thrown.

**Comment by cebe** [comment]
depends on how you inherit/merge configs. you should not merge sub configurations when classes are different. I do not see where this is done in yii framework code, so I'm closing this.

**Comment by dataskills** [comment]
I did not merge anything on purpose, it is the default behavior as stated
in the documentation:
http://www.yiiframework.com/doc-2.0/guide-tutorial-advanced-app.html#configuration-and-environments

On Wed, Mar 25, 2015 at 9:46 AM, Carsten Brandt <notifications@github.com>
wrote:

> depends on how you inherit/merge configs. you should not merge sub
> configurations when classes are different. I do not see where this is done
> in yii framework code, so I'm closing this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yiisoft/yii/issues/3822#issuecomment-86114915>.
>



-- 
------------------------
J. Bundy
dataskills@gmail.com
+1.206.406.1534

**Comment by samdark** [comment]
That's definitely 2.0 issue. Should be in 2.0 issue tracker.

**Comment by cebe** [comment]
oops, did not see it :)
