### ISSUE TITLE
Please make Yii compatible with Heroku

### ISSUE THREAD

**Issue by starrychloe** [yiisoft/yii#3823]
Creating a new Yii basic app doesn't work on Heroku. 

```
$ mkdir tmp
$ cd tmp
$ composer create-project --prefer-dist yiisoft/yii2-app-basic .
$ git init
$ git add .
$ git commit -a -m "tmp"
$ heroku create
$ git push heroku master
$ heroku config:set YII_ENV=prod
$ heroku open
```

**Comment by samdark** [comment]
This is Yii 1.1 issue. Tracker. The one for 2.0 is there: https://github.com/yiisoft/yii2/issues

**Comment by DilwoarH** [comment]
@samdark - are there any examples of how to make Yii 1 compatible with Heroku?

**Comment by samdark** [comment]
@DilwoarH I don't know. Quick googling doesn't give results. I've never deployed to Heroku so can't help with it.
