### ISSUE TITLE
generate code with gii but keep customization

### ISSUE THREAD

**Issue by lorinczelod** [yiisoft/yii#3829]
I made my model generator, because the existing one not keep my changes in model class, if I regenerate the model for example after a table structure changing.
The first idea is, that we make two class instead of one:
First class:
<?php
namespace app\models\db\core;
/**
 * This is the model class for table "article".
 * @property integer $id
 * @property string $title
 * ......
 */
 
class CoreArticle extends \yii\db\ActiveRecord {
    /** @inheritdoc */
    public static function tableName()   {
        return 'article';
    }
 // ......
 }
 
Second class:
<?php
namespace app\models\db;
/** This is the override model class for table "article". */
class Article extends \app\models\db\core\CoreArticle
{ 
}
This second class is empty at the beginning, but here will come the customization, and never will be regenerated.

The second idea is that these model classes from tables we put e.g. to "db" subdirectory, and "core" sub-subdir respectively

**Comment by samdark** [comment]
Please use appropriate issue tracker: https://github.com/yiisoft/yii2-gii/issues

**Comment by lorinczelod** [comment]
what do you mean in appropiate using of issue tracker? This is not an issue? My code formatting is very bad? (or my english? :) ). Please give me a/some clue..

**Comment by samdark** [comment]
This issue tracker is about Yii 1.1 only. 2.0 is a separate one. Gii for Yii 2.0 is a separate one as well.

Using code tags to highlight code would be helpful as well: https://guides.github.com/features/mastering-markdown/

**Comment by lorinczelod** [comment]
Ok, I see
thank you your guideline.
Lorincz

PS. the links on http://www.yiiframework.com/ under the Development menu
and its children point to yii 1.1 things
BUT the Download menu talk about Yii2 as the stable, latest etc. version
(and about the Yii1.1: Yii 1.1 is currently under maintenance mode. )
SO...

PS2.
I like Yii2 ;)


2015-03-27 0:36 GMT+02:00 Alexander Makarov <notifications@github.com>:

**Comment by samdark** [comment]
Yeah, we're working on new website...
