### ISSUE TITLE
Extra character added with orderBy

### ISSUE THREAD

**Issue by ydakilux** [yiisoft/yii#3830]
Hello,

  I have the following query who is working : 

		$linesresults = TmtfsLinematchRes::find()
			->select(['tmtfs_linematch_res.*', 'sum(qlinematches) as sumqlinematches'])
			->joinWith(['relprojfile', 'relfilescan'])
    		->groupBy(['substring(tmtfs_proj_file.filename, 1, 8)', 'tmtfilescan.id', 'projnr'])
    		->andWhere('title like "EOJNok_NoSamplePicks"')
    		->orderBy('id')
			->all();   
But when I try to modify the orderBy clause with the following : 

                ...
    		->orderBy('substring(tmtfs_proj_file.filename, 1, 8)')
			->all();   

I get :  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1
The SQL being executed was: SELECT `tmtfs_linematch_res`.*, sum(qlinematches) as sumqlinematches FROM `tmtfs_linematch_res` LEFT JOIN `tmtfs_proj_file` ON `tmtfs_linematch_res`.`proj_file_id` = `tmtfs_proj_file`.`id` LEFT JOIN `tmtfs_linematch_def` ON `tmtfs_linematch_res`.`linematch_def_id` = `tmtfs_linematch_def`.`id` LEFT JOIN `tmtfilescan` ON `tmtfs_linematch_def`.`filescan_id` = `tmtfilescan`.`id` WHERE title like "EOJNok_NoSamplePicks" GROUP BY substring(tmtfs_proj_file.filename, 1, 8), `tmtfilescan`.`id`, `projnr` ORDER BY substring(tmtfs_proj_file.filename, `1`, `8)`

  In fact the query is almost OK, the problem is the &#096; around the 1 and not around the 8.
  The syntax highlighter "markdown" do some interpretation of the lines. So at the end of the query we see : 

substring(tmtfs_proj_file.filename, &#096;1&#096; , &#096;8)&#096;

  So the problem is around the 8) who is between the &#096; like following &#096;8)&#096;

   I can solve the problem using the alternative syntax of orderBy.

    		->orderBy('substring(tmtfs_proj_file.filename FROM 1 FOR 8)')

        Kinds Regards,

**Comment by cebe** [comment]
from the docs:

> Note that if your order-by is an expression containing commas, you should always use an array to represent the order-by information.

http://www.yiiframework.com/doc-2.0/yii-db-querytrait.html#orderBy%28%29-detail

**Comment by cebe** [comment]
also note that this is the issue tracker for yii 1.1, use https://github.com/yiisoft/yii2 next time.

**Comment by ydakilux** [comment]
Oops sorry, I just clicked on the main page on the http://www.yiiframework.com/ main page,
  then reports a bug ,and forgot about Yii 1.1

   Thanks anyway.

**Comment by cebe** [comment]
yeah, site will be adjusted for that soon.
