### ISSUE TITLE
newer PHP versions (PHP 5.6) still supported?

### ISSUE THREAD

**Issue by np28** [yiisoft/yii#3831]
On the website you require "PHP 5.1.0 or above".
Do you test and officially support PHP 5.6 for example or are any problems known?

**Comment by klimov-paul** [comment]
Unit tests are running against PHP 5.6 successfully:
https://github.com/yiisoft/yii/blob/master/.travis.yml#L7
So it is supported.

**Comment by samdark** [comment]
"Above" assumes it.
