### ISSUE TITLE
Browser back button takes me to a seperate page

### ISSUE THREAD

**Issue by graphicmist** [yiisoft/yii#3835]
Hi,

My web application is showing drunk behaviour. It happens randomly that when i navigate through pages and click back button in browser, it takes me to a different page. The pages browsed in between the page shown on pressing back button and the current page are missing from browser history. I am not able to figure out whether it is an application issue or server issue.

Anyone has faced such issue? Need help

**Comment by samdark** [comment]
It's not Yii-related.

**Comment by graphicmist** [comment]
any ideas. Is it session related issue or what? can someone give me some leads on debugging this issue.

**Comment by samdark** [comment]
Use forums for questions. Yii's github is for Yii's bugs and feature requests.

**Comment by graphicmist** [comment]
Sorry. Will keep this is mind. Thanks for the help
