### ISSUE TITLE
deleteAll() doesn't take into account with() option

### ISSUE THREAD

**Issue by PatchRanger** [yiisoft/yii#3838]
This piece of code fails:
```php
$postIds = [1]; // array of post ids to be deleted
$criteria = new CDbCriteria();
$criteria->compare('post.id',$postIds);
Comment::model()->with('post')->deleteAll($criteria);
```
with such message
```
Column not found: 1054 Unknown column 'post.id' in 'where clause'. The SQL statement executed was: DELETE FROM `comment` WHERE post.id=:ycp1. Bound with :ycp1='1'
```
I guess it is because `deleteAll()` builds delete-command directly, not using `CActiveFinder`, which helps to deal with `with()`.

**Update:** I've just understood that in my case I could use fk-value without touching relation. But it doesn't cross out the fact that `deleteAll()` doesn't work as desired.

**Comment by cebe** [comment]
methods like skopes and `with()` can only be used by find or findAll methods. This is by design and can not easily be changed.

**Comment by PatchRanger** [comment]
Ok, I see, thank you.
