### ISSUE TITLE
Showing this error when using more then one join

### ISSUE THREAD

**Issue by rahulsinh** [yiisoft/yii#3842]
SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'title' in where clause is ambiguous
can you help me:
if (!$this->validate()) {
// uncomment the following line if you do not want to any records when validation fails
// $query->where('0=1');
return $dataProvider;
}

$query ->joinWith('location');
$query ->joinWith('programCategory');
$query ->joinWith('duration');
$query ->joinWith('airport');
$query->andFilterWhere([
    'program_id' => $this->program_id,

]);

$query->andFilterWhere(['like', 'title', $this->title])
  ->andFilterWhere(['like', 'location.city', $this->location_id])
    ->andFilterWhere(['like', 'program_category.program_category_name', $this->category_id])
    ->andFilterWhere(['like', 'duration.type', $this->duration_id])
    ->andFilterWhere(['like', 'airport.city', $this->airport_id]);

return $dataProvider;
}

**Comment by mdomba** [comment]
GitHub issues are for reporting bugs, please use the yii forum for this kind of problems.
