### ISSUE TITLE
mysql unsigned int attribute

### ISSUE THREAD

**Issue by vyachin** [yiisoft/yii#3848]
Why attribute with type "int(10) unsigned null" mark as string ?
![2015 04 20-18 49 15](https://cloud.githubusercontent.com/assets/1744721/7234215/20dd8d2c-e78e-11e4-94f2-7a4c05eb1ebf.jpg)

**Comment by samdark** [comment]
That's not to lose precision. MySQL max unsigned max value is 4294967295. 32bit PHP max int is 2147483647. It can't represent half of the values that could be stored in MySQL.
