### ISSUE TITLE
ActiveRecord::tableName()

### ISSUE THREAD

**Issue by incNick** [yiisoft/yii#3851]
Can you tell me why about I must write tablename there like {{%table}}?

I think if you can change it to table_prefix, then you must also can add table_prefix directly, right?

Issue is I must use ActiveRecord::getTableSchema()->name when I want to know table name, I do think it is best way.

**Comment by samdark** [comment]
You don't have to if you don't plan to use prefixes.

**Comment by samdark** [comment]
Seems the question is about 2.0 and this is 1.1 issue tracker.
