### ISSUE TITLE
ArrayHelper::remove() error

### ISSUE THREAD

**Issue by udcms** [yiisoft/yii#3858]
error:
    public static function remove(&$array, $key, $default = null)
    {
        if (is_array($array) && (isset($array[$key]) || array_key_exists($key, $array))) {
            $value = $array[$key];
            unset($array[$key]);
            return $value;
        }
        return $default;
    }
correct:
    public static function remove(&$array, $key, $default = null)
    {
        if (is_array($array) && (isset($array[$key]) || array_key_exists($key, $array))) {
             unset($array[$key]);
            return $array;
        }
        return $default;
    }

**Comment by cebe** [comment]
The implementation matches the docs:

> Removes an item from an array and returns the value.

Also this is the wrong repo, for Yii 2.0 use https://github.com/yiisoft/yii2/issues instead.
