### ISSUE TITLE
Error PHP: Necesito ayuda urgente

### ISSUE THREAD

**Issue by angelcourt** [yiisoft/yii#3861]
file_put_contents(/data/www/html/eroi_pro/protected/runtime/state.bin): failed to open stream: Permission denied 
/data/www/html/yii/framework/base/CStatePersister.php(107)
095         else if(($content=@file_get_contents($stateFile))!==false)
096             return unserialize($content);
097         else
098             return null;
099     }
100 
101     /**
102      * Saves application state in persistent storage.
103      * @param mixed $state state data (must be serializable).
104      */
105     public function save($state)
106     {
107         file_put_contents($this->stateFile,serialize($state),LOCK_EX);
108     }
109 }
Stack Trace
#0 	+
–
 /data/www/html/yii/framework/base/CStatePersister.php(107): file_put_contents("/data/www/html/eroi_pro/protected/runtime/state.bin", "a:1:{s:34:"Yii.CSecurityManager.validationkey";s:32:"0b2d7965344...", 2) 
102      * Saves application state in persistent storage.
103      * @param mixed $state state data (must be serializable).
104      */
105     public function save($state)
106     {
107         file_put_contents($this->stateFile,serialize($state),LOCK_EX);
108     }
109 }
#1 	+
–
 /data/www/html/yii/framework/base/CApplication.php(595): CStatePersister->save(array("Yii.CSecurityManager.validationkey" => "0b2d79653443e5920fd6269f33e4a594")) 
590     {
591         if($this->_stateChanged)
592         {
593             $this->_stateChanged=false;
594             $this->detachEventHandler('onEndRequest',array($this,'saveGlobalState'));
595             $this->getStatePersister()->save($this->_globalState);
596         }
597     }
598 
599     /**
600      * Handles uncaught PHP exceptions.
#2 	+
–
 /data/www/html/yii/framework/base/CComponent.php(568): CApplication->saveGlobalState(CEvent) 
563                         // an array: 0 - object, 1 - method name
564                         list($object,$method)=$handler;
565                         if(is_string($object))    // static method call
566                             call_user_func($handler,$event);
567                         else if(method_exists($object,$method))
568                             $object->$method($event);
569                         else
570                             throw new CException(Yii::t('yii','Event "{class}.{event}" is attached with an invalid handler "{handler}".',
571                                 array('{class}'=>get_class($this), '{event}'=>$name, '{handler}'=>$handler[1])));
572                     }
573                     else // PHP 5.3: anonymous function
#3 	+
–
 /data/www/html/yii/framework/base/CApplication.php(194): CComponent->raiseEvent("onEndRequest", CEvent) 
189     public function onEndRequest($event)
190     {
191         if(!$this->_ended)
192         {
193             $this->_ended=true;
194             $this->raiseEvent('onEndRequest',$event);
195         }
196     }
197 
198     /**
199      * Returns the unique identifier for the application.
#4 	+
–
 /data/www/html/yii/framework/base/CApplication.php(157): CApplication->onEndRequest(CEvent) 
152     {
153         if($this->hasEventHandler('onBeginRequest'))
154             $this->onBeginRequest(new CEvent($this));
155         $this->processRequest();
156         if($this->hasEventHandler('onEndRequest'))
157             $this->onEndRequest(new CEvent($this));
158     }
159 
160     /**
161      * Terminates the application.
162      * This method replaces PHP's exit() function by calling
#5 	+
–
 /data/www/html/eroi_pro/index.php(15): CApplication->run() 
10 
11 // remove the following line when in production mode
12 defined('YII_DEBUG') or define('YII_DEBUG',true);
13 
14 require_once($yii);
15 Yii::createWebApplication($config)->run();

**Comment by angelcourt** [comment]
HELP!!!!

**Comment by klimov-paul** [comment]
@angelcourt, please use <a href="http://www.yiiframework.com/forum/">Official Yii forum</a> to ask a questions - GitHub is a bug tracking system.
