### ISSUE TITLE
Yii and UnCSS

### ISSUE THREAD

**Issue by IngwiePhoenix** [yiisoft/yii#3863]
UnCSS only works on static files...or URLs. I wondered if there is a way that I could get all possible views and return a JSON array of all of them? I would really like to shrink my 192 KB of CSS (includes Bootstrap, FontAwesome, few customs and is already compressed, minified and optimized...).

Would be nice if someone had an idea for this one.

[UnCSS](http://npmjs.org/uncss)

**Comment by samdark** [comment]
Please use forums for questions. GitHub is for bug reports and feature requests. Thanks!
