### ISSUE TITLE
PDO attributes are not set correctly

### ISSUE THREAD

**Issue by adombrovsky** [yiisoft/yii#3868]
I want to add to prevent of casting number to string
```
PDO::ATTR_STRINGIFY_FETCHES
PDO::ATTR_EMULATE_PREPARES
```
to my db connection. I've added it through main.php to the db component like this:
```
            'db'           => array(
                'connectionString' => 'mysql:host=localhost;dbname=',
                'emulatePrepare'   => true,
                'username'         => '',
                'password'         => '',
                'charset'          => 'utf8',
                'tablePrefix'      => '',
                'attributes' => array(
                    PDO::ATTR_STRINGIFY_FETCHES => false,
                    PDO::ATTR_EMULATE_PREPARES => false,
                )
            )
```

This attributes are set without any errors but they are not affect the result of PDO mysql query.
But i've found that if I add 
```
$this->getConnection()->setAttribute(PDO::ATTR_STRINGIFY_FETCHES, false);
$this->getConnection()->setAttribute(PDO::ATTR_EMULATE_PREPARES, false);
```
to the CDbCommand.php to the queryInternal() method it will affect the result of mysql query.

What I am doing wrong? Why these attributes doesn't work as expected? Is there another place to put them?

**Comment by tomtomsen** [comment]
in CDbConnection (https://github.com/yiisoft/yii/blob/1.1.16/framework/db/CDbConnection.php#L445) the attributes array is getting passed to the PDO constructor. 

after that (https://github.com/yiisoft/yii/blob/1.1.16/framework/db/CDbConnection.php#L462) the option 'emulatePrepare' will be set. 

in your case the attribute PDO::ATTR_EMULATE_PREPARES => false, gets overruled by 'emulatePrepare'   => true.
i guess if you set emulatePrepare to false everything should work as expected.

**Comment by samdark** [comment]
As @tomtomsen said, `emulatePrepare` has higher priority and it's not going to be changed.
