### ISSUE TITLE
Need a database-based StatePersister implementation

### ISSUE THREAD

**Issue by teo1978** [yiisoft/yii#3872]
http://www.yiiframework.com/doc/api/1.1/CStatePersister

Just like you provide CStatePersister as the default state persister component, you should as well provide a database-based implementation of the IStatePersister interface, using a database table, so that one could use it instead of the default CStatePersister.

You even suggest:
> Since server resource is often limited, be cautious if you plan to use CStatePersister to store large amount of data. You should also consider using database-based persister to improve the throughput.

There seems to be an extension:
http://www.yiiframework.com/extension/edbstatepersister

This (if it's good enough, otherwise a better implementation) should be part of the core framework.

**Comment by samdark** [comment]
Threre's no plan to extend Yii 1.1 features but in this case we can merge ready pull request.
