### ISSUE TITLE
yiiactiveform reset() function not callable

### ISSUE THREAD

**Issue by vercotux** [yiisoft/yii#3873]
Calling something like `$form.reset().trigger("reset");`

yields an error:

> TypeError: $(...).reset is not a function

**Comment by cebe** [comment]
can you please give more context about where this happens?

**Comment by georaldc** [comment]
Is that a jQuery object and are you trying to call reset() against it? There is no native reset() jQuery method and you would have to call it against a javascript object (something like $form[0].reset())
