### ISSUE TITLE
CPagination - wrong value of currentPage

### ISSUE THREAD

**Issue by peter-gribanov** [yiisoft/yii#3874]
Perhaps this question has been asked and after the transition to version 2.0, it is not so relevant, but still I want to ask. Why is `CPagination::getCurrentPage()` returns a wrong value?

Example:

``` php
$provider = new CActiveDataProvider($this);
$provider->pagination->pageVar = 'page';
$provider->pagination->pageSize = 30;
$provider->getData();
var_dump($provider->pagination->getCurrentPage()+1 == $_GET['page']);
```

Return:

```
bool(true)
```

I understand that when data is received for a page 1, select all records from 0 to 30, but that is no reason to specify -1 for the current page number. The current page should always correspond to the actual current page number, and offset has to be calculated.

``` php
public function getOffset()
{
    return ($this->getCurrentPage() - 1) * $this->getPageSize();
}
```

**Comment by shehi** [comment]
@peter-gribanov this gets even funnier :) You missed one more thing in the same file:

https://github.com/yiisoft/yii/blob/master/framework/web/CPagination.php#L204

So when you need to use that bloody ```createPageUrl()``` method, you have to decrease the page number by 2.

**Comment by peter-gribanov** [comment]
@samdark костыли плодим)))

**Comment by samdark** [comment]
http://www.yiiframework.com/news/90/update-on-yii-1-1-support-and-end-of-life/
