### ISSUE TITLE
UrlManager yii 1.1.12 and yii 1.1.17-dev

### ISSUE THREAD

**Issue by diogopms** [yiisoft/yii#3875]
Hi, i am trying to upgrade the yii to the last yii 1.1 but i don't know why the same code doesn't work in yii 1.1.17

I want that all urls with this pattern are linked to LoginController > actionIndex
http://URL/current/login or http://URL/v2.0/login or http://URL/v2.0/api/login

I know that is not the best way to have many url linked to the same controller, but i have lots of legacy.

Yii 1.1.12 (works)
```php
 'urlManager'=>array(
            'urlFormat'=>'path',
            'showScriptName'=>false,
            'rules' => [
                '(v1.0|v2.0|v2.0/api)/login' => 'login/index',
            ],
        ),
```

yii 1.1.17-dev (not working)
```php
 'urlManager'=>array(
            'urlFormat'=>'path',
            'showScriptName'=>false,
            'rules' => [
                '(v1.0|v2.0|v2.0/api)/login' => 'login/index',
            ],
        ),
```
yii 1.1.17-dev (working only with single word (v1.0))
```php
   'urlManager'=>array(
            'urlFormat'=>'path',
            'showScriptName'=>false,
            'rules' => [
                'v1.0/login' => 'login/index',
            ],
        ),
```

**Comment by samdark** [comment]
Do you have time to trace it to particular commit using `git bisect`?

**Comment by diogopms** [comment]
I compared the two classes:

Change this from false to true.
```php
	/**
	 * @var boolean whether this rule is only used for request parsing.
	 * Defaults to false, meaning the rule is used for both URL parsing and creation.
	 * @since 1.1.7
	 */
	public $parsingOnly=true;
```

or comment this part:

```php
if(!$this->parsingOnly)
			$p=preg_replace_callback('/(?<=^|>)[^<]+(?=<|$)/',array($this,'escapeRegexpSpecialChars'),$p);
```

This fix my specific problem, but i need to understand why this happen, or i can do a pull request with this fix.

Thanks

**Comment by samdark** [comment]
https://github.com/yiisoft/yii/issues/3103. I guess you have to escape dots because it's part of regex.

**Comment by lookphp** [comment]
amazing!

**Comment by lexeo** [comment]
Hi there. Unfortunately I ran into the same issue. 
We've upgraded our production server to PHP7.0 and we need to run our application with Yii 1.1.17, but we can't. Because of the routing issue.
We have many routing patterns like:

```
'(?:<lang:\w{2}>/)\?example' => 'example/index'
'(?:<lang:\w{2}>/)\?example/blahblah' => 'example/someaction'

'(?:<lang:\w{2}>/)\?example/blahblah(/<param1:\d{4}-\d{2}-\d{2}(T\d{2}-\d{2})?>)?' => 'example/someaction'
```

Now it doesn't work because of escaping special chars.
Is there any other way to make it work, except:

```
'example' => 'example/index'
'<lang:\w{2}>/example' => 'example/index'

'example/blahblah' => 'example/someaction'
'example/blahblah/<param1:\d{4}-\d{2}-\d{2}>' => 'example/someaction'
'example/blahblah/<param1:\d{4}-\d{2}-\d{2}T\d{2}-\d{2}>' => 'example/someaction'
'<lang:\w{2}>/example/blahblah' => 'example/someaction'
```
... etc.

This way doesn't look good for me due to code duplication.
Thanks in advance.

**Comment by MaXL-ru** [comment]
After upgrading Yii to 1.1.17 we have the same problem.

Next rule not work:
```'catalogs/<typeName:[\w-]+>/<controller:\w+>/[^/]+/[^/]+/cg<concreteModelGroupId:\d+>(?:_<modelColorId:\d+>)?' => 'catalogs/<controller>Catalog/concreteModelGroupParts'

**Comment by eirikhm** [comment]
Did not see this issue when I created my ticket, more info in #4051
