### ISSUE TITLE
Move Identity Cookie code into separate functions in web\User.php

### ISSUE THREAD

**Issue by maine-mike** [yiisoft/yii#3883]
I would like to create an extension to implement a more elaborate “Remember Me” mechanism, such as the one described here:  http://jaspan.com/improved_persistent_login_cookie_best_practice

In order to do this, I would like to override the functions that manage identity cookies in web\User.  This works for sendIdentityCookie because that function deals exclusively with identity cookies.  It doesn’t work so well for loginByCookie because in addition to managing the identity cookies, that function also establishes the current identity and triggers the before and after login events.  As I understand it, if I were to override that function, I would have to duplicate that code in my code and I would prefer not to do that.

I would like to propose moving all code related to identity cookies into separate functions so they can be overridden.

I took a stab at what that might look like and it’s located here:  https://github.com/maine-mike/yii2/blob/master/framework/web/User.php

While going through the code, I noticed these other things that I included in my code:

- Currently there are two choices for autoRenewCookie:  never or after every page load.  I think it would be a good idea to offer a middle-of-the-road option to renew the cookie after each loginByCookie.  So the identity cookie would be renewed when someone opens a new browser session and is logged in through the identity cookie.

- There are various places (such as the before and after login events) where $duration indicates if auto-login was requested on the login method, but auto-login won't actually be enabled unless $enableSession and $enableAutoLogin are both true.  I added in some of those checks.

- It would be helpful if switchIdentity and sendIdentityCookie included a parameter to indicate if this is a cookie-based login.  In order to keep the parameter order consistent, I made beforeLogin and afterLogin match switchIdentity.

- In order to provide as much flexibility as possible, I included an $identity parameter for clearIdentityCookie.  This is needed for enhanced "Remember Me" functionality.

Thank you for considering these changes.

Mike

**Comment by samdark** [comment]
I'm OK with refactoring of cookie-related stuff into a set of protected methods. Do you have time to prepare a pull request?

**Comment by maine-mike** [comment]
OK.  Great.  Here is a pull request:

https://github.com/yiisoft/yii2/pull/8695

**Comment by maine-mike** [comment]
Sorry... I had left out the comment blocks...

https://github.com/yiisoft/yii2/pull/8698

**Comment by samdark** [comment]
So that's Yii 2.0. Closing this one then since it's Yii 1.1 issue tracker.

**Comment by maine-mike** [comment]
Hi Alexander,

I created a pull request with just moving the cookie stuff out and it’s here:

https://github.com/yiisoft/yii2/pull/8714

Thank you!

Mike.
