### ISSUE TITLE
yii website routing error

### ISSUE THREAD

**Issue by pine3ree** [yiisoft/yii#3884]
Cannot find the yii website src, so i posted this "issue" here:

http://www.yiiframework.com/doc/guide/3.1/en/form.model
http://www.yiiframework.com/doc/guide/4.3/en/form.model
http://www.yiiframework.com/doc/guide/5.6/en/form.model

in general
http://www.yiiframework.com/doc/guide/[2-9].[0-9]/en/{valid-1.1-section}

point to 

http://www.yiiframework.com/doc/guide/1.1/en/form.model

instead of resulting in a 404 response

**Comment by cebe** [comment]
thanks for reporting this. We are working on a new version of the website where this error is not present anymore. It will be fixed once the new site is online.
