### ISSUE TITLE
CSort multi sort not working in version 1.1.16

### ISSUE THREAD

**Issue by dashkhuu85** [yiisoft/yii#3893]
Operating system: Windows 7 SP1
Web server: Xampp 5.6.8
Browser type: Google Chrome Version 43.0.2357.124 m
Yii version: 1.1.16

When I use CSqlDataProvider in CGridview I enabled multisort true 
![in controller](https://cloud.githubusercontent.com/assets/12380628/8247472/2b956a9e-1684-11e5-89da-a75156df3ed5.png)

the initial grid with default sort order looks like this image
![nosort](https://cloud.githubusercontent.com/assets/12380628/8247473/2b95ba8a-1684-11e5-99c3-407035d39092.png)

if I sort with a single column (lets say Default)
![sort by default asc](https://cloud.githubusercontent.com/assets/12380628/8247474/2b9627fe-1684-11e5-8390-026af8c80d9e.png)
and multi sort with second column (let it be Title)
![sort by default asc title asc](https://cloud.githubusercontent.com/assets/12380628/8247475/2b96187c-1684-11e5-8f1b-2259fe16f1e0.png)
as you can see this just sorts with a single column (only with Title)

But if we swap the old direction with currently selected attributes sort order for array merge function in CSort file (Framework->Web->CSort.php => line 302)
if($this->multiSort)
	$directions=array_merge(array($attribute=>$descending),$directions);
else
	$directions=array($attribute=>$descending);
as below (the corrected one)
if($this->multiSort)
	$directions=array_merge($directions,array($attribute=>$descending));
else
	$directions=array($attribute=>$descending);
fixes the problem.
![csort](https://cloud.githubusercontent.com/assets/12380628/8247471/2b94014a-1684-11e5-8908-7951db49f0a2.png)

The below image is correct on after swapping array merge arguments
![sort by default asc title asc-correct](https://cloud.githubusercontent.com/assets/12380628/8247476/2b966584-1684-11e5-8fae-36913d1fc6a1.png)

I think this should be corrected in further Yii releases.

**Comment by AloneCoder** [comment]
Can't reproduce it

**Comment by gelahcem** [comment]
you are right!, any way after swapping array merge arguments on CSort.php i couldn't sort it again by 'Title' let's say. On Yii2 the array merge arguments keeps the same as on Yii 1.1.16

**Comment by samdark** [comment]
What do you mean by swap?

**Comment by gelahcem** [comment]
![swap](https://cloud.githubusercontent.com/assets/5724410/10511783/03757904-733c-11e5-8d45-7bd28adc4401.png)

$directions=array_merge(array($attribute=>$descending),$directions);

changed to:

$directions=array_merge($directions, array($attribute=>$descending));

**Comment by cherifGsoul** [comment]
I have the same bug 
```php
new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
			'sort'=>array(
				'multiSort'=>true,
				'sortVar'=>'sort',
				'separators'=>array(',','.'),
				'attributes'=>array('*')
			)
		));
```

Im on RESTful API when the url is like this:
```
/api/authors?sort=lastname.desc,firstname.asc
```
the generated SQL:
```sql
SELECT * FROM `author` `t` 
WHERE (t.is_deleted=:isDeleted) 
AND (is_deleted=:ycp1) 
ORDER BY `t`.`lastname` DESC 
LIMIT 10. Bound with :isDeleted=0, :ycp1='0')
```

Is this will be corrected?

**Comment by cherifGsoul** [comment]
the CSort::getOrderBy should handle multiSort which is not the case sorting without links is impossible the use case for this RESTful APIs

**Comment by cherifGsoul** [comment]
For restful API it works, I dont have to do:
```
/api/authors?sort=lastname.desc,firstname.asc
```

Just remove asc and it works:
```
/api/authors?sort=lastname.desc,firstname
```
