### ISSUE TITLE
dropDownList bug

### ISSUE THREAD

**Issue by TvitiDev** [yiisoft/yii#3894]
hello. I found bug in dropDownList( $items, $options = [] ). In '$options' i can write 'options', for example 
'options' => [
    'value1' => ['disabled' => true],
    'value2' => ['label' => 'value 2'],
]
If i want choose default "selected", i write  'value1' => ['selected' => true], but this code not work. If i add space after 'selected' this code begin work 'value1' => ['selected ' => true]
My opinion - this bug. Please correct

**Comment by AloneCoder** [comment]
This is yii 1.1 issue tracker and according to [documentation](http://www.yiiframework.com/doc/api/1.1/CHtml#dropDownList-detail) a valid call has a little bit different syntax
```php
public static string dropDownList(string $name, string $select, array $data, array $htmlOptions=array ( ))
```

**Comment by TvitiDev** [comment]
Sorry, confused topic. This bug is yii2. In yii1 this code work

**Comment by samdark** [comment]
This is Yii 1.1 issue tracker.
