### ISSUE TITLE
CHtml::listBox() $select parameter can't be array, as it writen in phpDoc

### ISSUE THREAD

**Issue by Lexxtor** [yiisoft/yii#3898]
https://github.com/yiisoft/yii/blob/master/framework/web/helpers/CHtml.php#L1046

```
CHtml::listBox(); // have @param mixed $select
// but it passes $select to
self::dropDownList();
// where: @param string $select
```

Bug was found when I try to pass array in CHtml::listBox() as it's described in phpDoc, and it cause error: `htmlspecialchars() expects parameter 1 to be string, array given`

**Comment by AloneCoder** [comment]
Despite phpDoc blocks it seems that you're doing something wrong
This code works well:
```php
echo CHtml::listBox(
    'listBoxTest',
    ['foo', 'bar'],
    ['foo' => 'baz', 'bar' => 'foobar', 'qux' => 'quux'],
    $htmlOptions = array(
        'multiple' => true,
    )
);
```

**Comment by Lexxtor** [comment]
Yes,  I found the cause: without ` 'multiple' => true,` it induces error.
May be it must be in phpDoc.
