### ISSUE TITLE
Spaces in model validation rules

### ISSUE THREAD

**Issue by pragmas** [yiisoft/yii#3899]
After update from 1.1.10 to 1.1.16 I get a strange bug.

If you use spaces like here after CanceledBy and CanceledBy is NULL, then validation fails. Remove the space character and it works.
    public function rules() {
        return array(
                array('PersonID,CanceledBy ', 'numerical'),
        );
    }

If you add an empty beforeValidation-function, then again validation works fine.

**Comment by AloneCoder** [comment]
Such behaviour causes something else in your code
Let's see how Yii 1.1.16 creates attributes for validation  https://github.com/yiisoft/yii/blob/master/framework/validators/CValidator.php#L132 
And Yii 1.1.10 
```php 
$attributes=preg_split('/[\s,]+/',$attributes,-1,PREG_SPLIT_NO_EMPTY);
``` 

As you can see, now yii trims attributes
