### ISSUE TITLE
Bug charsets

### ISSUE THREAD

**Issue by Mackiavelly** [yiisoft/yii#3900]
There is a table in the view

```php
<?= DetailView::widget([
    'model' => $model,
    'options' => [
        'class' => 'table table-condensed table-hover table-bordered detail-view'
    ],
    'attributes' => [
        [
            'attribute' => 'Адрес',
            'value' => '',
            'format' => 'raw',
        ],
        'comments',
        'hard_off',
        [
            'attribute' => Yii::t('app', 'Sessions Now'),
            'value' => '',
            'format' => 'raw',
        ],
    ],
])?>
```

translation attributes in model

```php
'comments' => Yii::t('app', 'Comments'),
'hard_off' => Yii::t('app', 'Hard Off'),
```

ru-RU/app.php

```php
'Hard Off' => 'Отключение на крыше',
'Comments' => 'Комментарий',
'Sessions Now' => 'Текущие сессии',
```

problem see image
Attributes are listed on the Russian , not in the model , periodically breaking encoding
![1](https://cloud.githubusercontent.com/assets/11190487/8398738/e25480d6-1e03-11e5-97c4-bff4d41d3a64.png)
![2](https://cloud.githubusercontent.com/assets/11190487/8398737/e254021e-1e03-11e5-80aa-a5c352333e1c.png)
bug showing if random press F5 (refresh page)

**Comment by samdark** [comment]
Make sure source is in UTF-8, there's `<meta charset="utf-8" />` and server is configured to serve UTF-8. Overall, it's not framework issue so we can't fix it for you.

**Comment by Mackiavelly** [comment]
Of course all the sources in utf- 8
you do not understand the causes of the bug
page source does not change
bug showing if random press F5 (refresh page)

Объясню по русски, так как вы русскоязычный, с исходниками все норм, со всеми кодировками и т.д., проверял даже на чисто установленной версии yii2 basic, те транслейты который подхватываются из моделек с ними все ок, а вот если либо просто указать текст, или указать Yii::t('app', 'Sessions Now') во вьюхе, текст случайным образом, то в нормальной кодировке то в какой-то искаженной, почему искаженной, так как перевод страницы в другую кодировку средствами браузера НЕ делает текст читабельным, мое мнение происходит именно, какое-то странное искажение кодировки после первой буквы

**Comment by Mackiavelly** [comment]
вай вай, мой косяк наверное

в настройке сервера apache указал
```
<Directory /path/to/site/>
AddDefaultCharset UTF-8
</Directory>
```
все заработало

**Comment by Mackiavelly** [comment]
дополение 
```php
[
            'attribute' => Yii::t('app', 'Sessions Now'),
            'value' => '',
            'format' => 'raw',
]
```
так баг проявлеться после каждого обновлнеия фаликов на апаче через git
```php
[
            'attribute' => Yii::t('app', 'Sessions Now'),
            'value' => '',
            'format' => 'raw',
            'label' => Yii::t('app', 'Sessions Now'),
]
```
вот так все норм всегда
видимо что-то не так происходит когда система пытается превратить attribute в label...
