### ISSUE TITLE
function should also get parameters

### ISSUE THREAD

**Issue by manojdhiman** [yiisoft/yii#3901]
like in other famous framework (cakephp) the function should also get the parameters with url . like 

so that if i access the url http://192.168.1.31/yii2/web/post/index/test_post/slug
```
class PostController extends Controller
{
	public function actionIndex($slug=null,$slug2=null)
	{
		//echo "hieeeeeeee";
		echo $slug;
		return $this->render('index');
	}
}
```
so that we can get these in the functions.

**Comment by samdark** [comment]
Please elaborate.

**Comment by samdark** [comment]
This is Yii 1.1 issue tracker.
