### ISSUE TITLE
postgres не работает $model->id в actionCreate

### ISSUE THREAD

**Issue by des1roer** [yiisoft/yii#3902]
не могу использовать $model->id в actionCreate. настройки gii по дефолту. подскажите это баг или я просто не умею готовить?

**Comment by des1roer** [comment]
http://yiiframework.ru/forum/viewtopic.php?f=3&t=30589

**Comment by samdark** [comment]
Если не уверены, что баг и не готовы нормально описать проблему — лучше начать с форума.
