### ISSUE TITLE
CActiveRecord: isNewRecord() return true in afterSave()

### ISSUE THREAD

**Issue by Lexxtor** [yiisoft/yii#3906]
I suggest it must be `false`. Because it already saved.

I do same postprocessing of new records in `afterSave()` and then save them again:

```php
protected function afterSave() {
    if ($this->isNewRecord) {
        $this->same_attribute = 'value';
        $this->save(false);
    }
    parent::afterSave();
}
```

But it makes  MySql error "Duplicate entry for key PRIMARY".
If there were no PRIMARY key, then it can make infinite loop.

To get over this bug, I do some thing like:
```php
protected function afterSave() {
    if ($this->id) {
        $this->same_attribute = 'value';
        $this->isNewRecord = false;
        $this->update(['same_attribute']);
    }

    parent::afterSave();
}
```

I think this line https://github.com/yiisoft/yii/blob/master/framework/db/ar/CActiveRecord.php#L1100 must be after `$this->setIsNewRecord(false);`

**Comment by klimov-paul** [comment]
Duplicates #3508

**Comment by cebe** [comment]
we can not change this in Yii 1.1 for BC reasons, in Yii2 this is solved in a different more straight forward way.
