### ISSUE TITLE
CWebUser must raise before/after login/logout events

### ISSUE THREAD

**Issue by fazliddin** [yiisoft/yii#3907]
CWebUser must raise before/after login/logout events. It is very important in CMS development suppoting third party plugin developers. Plugin developers may to do some tasks by registering handlers.

If this issue is approved, I can create pull request.

**Comment by cebe** [comment]
you can add them in your application if needed by overriding user class and adding them to the corresponding methods: https://github.com/yiisoft/yii/blob/master/framework/web/auth/CWebUser.php#L410-L446

I do not think these are very useful in general application development.
