### ISSUE TITLE
Yii2.0.5 installation issue in windows 

### ISSUE THREAD

**Issue by chathurasudarsha** [yiisoft/yii#3908]
Problem 1
- yiisoft/yii2-gii 2.0.4 requires bower-asset/typeahead.js 0.10.* -> no matc
hing package found.
- yiisoft/yii2-gii 2.0.3 requires bower-asset/typeahead.js 0.10.* -> no matc
hing package found.
- yiisoft/yii2-gii 2.0.2 requires bower-asset/typeahead.js 0.10.* -> no matc
hing package found.
- yiisoft/yii2-gii 2.0.1 requires bower-asset/typeahead.js 0.10.* -> no matc
hing package found.
- yiisoft/yii2-gii 2.0.0 requires bower-asset/typeahead.js 0.10.* -> no matc
hing package found.
- Installation request for yiisoft/yii2-gii * -> satisfiable by yiisoft/yii2
-gii[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4].

**Comment by cebe** [comment]
are you upgrading an existing yii installation or is this a new install?
please show the command you are running and your composer.json

btw: this is the issue tracker for yii 1.1., next time please use https://github.com/yiisoft/yii2/issues

**Comment by chathurasudarsha** [comment]
hi carsten,
thank you for quick replay.

i just try to install new copy of basic.

this is my command

composer create-project --prefer-dist yiisoft/yii2-app-basic basic

i attached my json file. please find the attachment.


On Sat, Jul 11, 2015 at 11:07 PM, Carsten Brandt <notifications@github.com>
wrote:

> are you upgrading an existing yii installation or is this a new install?
> please show the command you are running and your composer.json
>
> btw: this is the issue tracker for yii 1.1., next time please use
> https://github.com/yiisoft/yii2/issues
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yiisoft/yii/issues/3908#issuecomment-120647057>.
>



-- 
D.S.P.C.S Ariyathilaka
B.I.T (UCSC- Sri Lanka)

**Comment by chathurasudarsha** [comment]
it doesn't download vendor folder too.

On Sat, Jul 11, 2015 at 11:40 PM, chathura ariyathilaka <
chathurasudarsha@gmail.com> wrote:

> hi carsten,
> thank you for quick replay.
>
> i just try to install new copy of basic.
>
> this is my command
>
> composer create-project --prefer-dist yiisoft/yii2-app-basic basic
>
> i attached my json file. please find the attachment.
>
>
> On Sat, Jul 11, 2015 at 11:07 PM, Carsten Brandt <notifications@github.com
> > wrote:
>
>> are you upgrading an existing yii installation or is this a new install?
>> please show the command you are running and your composer.json
>>
>> btw: this is the issue tracker for yii 1.1., next time please use
>> https://github.com/yiisoft/yii2/issues
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/yiisoft/yii/issues/3908#issuecomment-120647057>.
>>
>
>
>
> --
> D.S.P.C.S Ariyathilaka
> B.I.T (UCSC- Sri Lanka)
>



-- 
D.S.P.C.S Ariyathilaka
B.I.T (UCSC- Sri Lanka)

**Comment by cebe** [comment]
please make sure you have the composer asset plugin installed as described in the instructions:

http://www.yiiframework.com/doc-2.0/guide-start-installation.html#installing-via-composer

**Comment by chathurasudarsha** [comment]
hi Carsten,

i tried several times but still i can find the way it gave me mismatched of
punycode 1.3.*
  Problem 1
    - yiisoft/yii2 2.0.5 requires bower-asset/punycode 1.3.* -> no matching
pack
age found.
    - yiisoft/yii2 2.0.4 requires bower-asset/punycode 1.3.* -> no matching
pack
age found.
    - Installation request for yiisoft/yii2 >=2.0.4 -> satisfiable by
yiisoft/yi
i2[2.0.4, 2.0.5].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to
your min
imum-stability setting



On Sat, Jul 11, 2015 at 11:49 PM, Carsten Brandt <notifications@github.com>
wrote:

> please make sure you have the composer asset plugin installed as described
> in the instructions:
>
>
> http://www.yiiframework.com/doc-2.0/guide-start-installation.html#installing-via-composer
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yiisoft/yii/issues/3908#issuecomment-120650559>.
>



-- 
D.S.P.C.S Ariyathilaka
B.I.T (UCSC- Sri Lanka)

**Comment by cebe** [comment]
you need to run this command: `composer global require "fxp/composer-asset-plugin:~1.0.0"` before create project as linked in the docs above.
