### ISSUE TITLE
Ajax bugs in version 2.0.5

### ISSUE THREAD

**Issue by lisi4ok** [yiisoft/yii#3909]
Ok i found 2 bugs with ajax.
1) I Render Ajax content with Jquery: 
<div id="holder" style="display:none;"></div>
<?php
$this->registerJs("
	function render(step) {
		jQuery.post('" . Url::to(['step']) . "', { number: step })
		.done(function(response) {
			jQuery('#holder').empty().append(response);
			jQuery('#holder').fadeIn('slow');
		});
	}
	render(1);
"); 
?>

controller Action:
<?php
	public function actionStep() {
		if (Yii::$app->request->isPost && Yii::$app->request->isAjax) {
			if (Yii::$app->request->post('number') == 1)
				return $this->renderAjax('_form', ['company' => new Company, 'companyContacts' => [new CompanyContact]]);
		}
	} 
?>

in _form.php view:
<?php $this->registerJs("alert('this not showing');"); ?>
The alert never calls. also the JS is no writen in view page source.
Also eaven i write JS in previus file which is not rendered by ajax. The elements didn`t exist.
So if i try to  submit some form and i try to catch onclick event with jQuery - the element didn`t exist.

**Comment by samdark** [comment]
This is Yii 1.1 issue tracker.
