### ISSUE TITLE
CStatePersister issues error if state.bin does not exist, instead of creating it

### ISSUE THREAD

**Issue by teo1978** [yiisoft/yii#3911]
CStatePersister.php (111): fopen(/srv/www/xxxx.xxx/public_html/protected/runtime/state.bin): failed to open stream: No such file or directory

That's ridiculous: if the file doesn't exist, create it!

**Comment by cebe** [comment]
I don't see how this error could happen from the code. also there is no line 111 with fopen in the latest version, which version are you using?
https://github.com/yiisoft/yii/blob/master/framework/base/CStatePersister.php

**Comment by teo1978** [comment]
1.1.17, I'll try to update to the latest and see if it persists (pun not intended)

**Comment by teo1978** [comment]
By the way, it has just moved from line 111 to line 112

**Comment by teo1978** [comment]
Oh I see, the @ before fopen was missing in the older version

**Comment by cebe** [comment]
so this can be closed?

**Comment by teo1978** [comment]
Yep, sorry
