### ISSUE TITLE
Add data modification capability in migration scripts

### ISSUE THREAD

**Issue by jbcrouigneau** [yiisoft/yii#3912]
Unless I am mistaken, there is no mechanism dedicated to manipulate data in a migration script.
For instance, something like : 
UPDATE table SET column = CONCAT(column, $string);
UPDATE table SET column1 = column1 + column2;
We should be able to modify data, not only DB structure during DB upgrade.

Doing it through "execute" can lead to compatibly issues.
Adding data manipulation features to update method would be "cleaner".
I'm not sure of the best way to do it. Maybe a new parameter allowing to define a formula to apply on existing data (string or numeric).

Not an easy feature to add, but could be a great enhancement.

**Comment by samdark** [comment]
You can use any database-related methods and classes in migration so it's already there.
