### ISSUE TITLE
MySql Double Insert (null value for primary-key)

### ISSUE THREAD

**Issue by wsfuyibing** [yiisoft/yii#3915]
Debug-ENV
a): Yii Framework/2.0.6-dev
b): nginx/1.4.7
c): PHP/5.4.21
d): MySQL/5.5.28

#1: MySQL-Table Struct

CREATE TABLE IF NOT EXISTS `tbl_user_ai` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

#2: SQL
INSERT INTO `tbl_user_ai` (`id`) VALUES (null);

#3: Result
Two Records found

#4: PHP-Code(Yii Framework/2.0.6-dev)
return $this->getConnection('AI')
->createCommand()
->insert($this->getTable('tbl_user_ai'), ['id' => null])
->execute();

应用场景
AI表用于全站的id流水号；以id号决定分表时, 存储到哪张表中。

**Comment by serhioli** [comment]
I had same behavior when use Chrome with extensions. Explanation is easy - one of all my extensions(I think it's wappalyzer) initialize his own `XMLHttpRequest` to page from `location.href` and same controller, which I just visit, executes command to db again. If you has some extensions in your browser, try to open page in private tab.
