### ISSUE TITLE
Wrong translation

### ISSUE THREAD

**Issue by dtagliavini** [yiisoft/yii#3917]
In i18n territories array for fr.php, Unites states is translated in this way 'us' => 'É-U',

**Comment by samdark** [comment]
Please report to CLDR: http://cldr.unicode.org/

**Comment by dtagliavini** [comment]
Ok, I looked at CLDR.

In their xml they report 2 row. A normal translation and a short one.
So I suppose the short one override the previous.
In ther XML the rows for Unites States are these:
```
<territory type="US">États-Unis</territory>
<territory type="US" alt="short">É.-U.</territory>
```
I think it will be better to avoid alternative short translation.
Do you agree?

**Comment by samdark** [comment]
I don't know. It may be useful.
