### ISSUE TITLE
Repeating word 'the' on description

### ISSUE THREAD

**Issue by xpertdeveloper** [yiisoft/yii#3918]
On link: http://www.yiiframework.com/doc-2.0/guide-input-validation.html#handling-empty-inputs

Paragraph between two code block contains the word 'the' twice. see below:

> You may customize the default empty detection logic by configuring **the the** yii\validators\Validator::isEmpty() property with a PHP callable. For example,

**Comment by samdark** [comment]
Fixed. Thanks!

Next time please report to yii2 issue tracker. This one is for 1.1.
