### ISSUE TITLE
Use Schema Name option missing from gii model generator.

### ISSUE THREAD

**Issue by jlinse** [yiisoft/yii#3919]
I do not wish to have the schema name/database name added to my class name when generating relation classes.  I believe this was the older functionality.  I tracked down the fix needed to give the user the option and it appears when the "useSchemaName" option was added to the gii Generator somebody forgot to update the view in vendor/yiisoft/yii2-gii/generators/model/form.php to include the line.

echo $form->field($generator, 'useSchemaName')->checkbox();

Adding that one line in vendor/yiisoft/yii2-gii/generators/model/form.php will give the user the option to include or not the schema name in class generation.  The label and hints were already coded.

**Comment by samdark** [comment]
This is Yii 1.1 issue tracker. Please submit to https://github.com/yiisoft/yii2-gii/issues
