### ISSUE TITLE
AR 'second-level' join not working properly

### ISSUE THREAD

**Issue by coriolanweihrauch** [yiisoft/yii#3921]
**Applies to Yii Version** 1.1.17 (probably earlier versions too)

### Symptom
AR Query Builder does not include "second-level" join tables

### Detailed problem description
http://www.yiiframework.com/forum/index.php/topic/66900-ar-second-level-join-not-working/

### Proposed solution
Add
```
$this->_finder->joinAll=true;
```
In
```
yii/framework/db/ar/CActiveFinder.php:438
```
before
```
$this->buildQuery($query);
```

**Comment by AloneCoder** [comment]
Proposed solution is to use "together" option

**Comment by coriolanweihrauch** [comment]
'together' avoids the problem but does not address this specific issue.

AR allows for search in "first-level" joins but not in "second-lelvel" using ->with()
My understanding is that it should, by design, as documented in
http://www.yiiframework.com/doc/guide/1.1/en/database.arr#performing-relational-query

**Comment by cebe** [comment]
if you want to access tables in WHERE condition they must be part of the current query and thus you need to use "together" option.
