### ISSUE TITLE
bootstrap classes not updated

### ISSUE THREAD

**Issue by preventsenior** [yiisoft/yii#3922]
Hi, I've downloaded Yii 2.0.6 and have updated all files within vendor folder in my project, but I couldn't use the new method of bootstrap ActiveField: staticControl(). I've tried installing using composer as well...

**Comment by samdark** [comment]
Yes. Framework and extensions are released separately. There was framework release but no extension releases yet.

**Comment by preventsenior** [comment]
Thank you.
