### ISSUE TITLE
debug/default/toolbar from entryscript page not found 404

### ISSUE THREAD

**Issue by IvoRe** [yiisoft/yii#3923]
I have a site in production mode, but I have a special `dev.php` entryscript which still runs the site in development mode, with the debug module turned on. (Yes, I know I'm naughty...)

Sadly, Yii creates a callback to `debug/default/toolbar` while **omitting the `dev.php` entryscript**.

Of course, with the site in production, debug module is turned off and the `debug/default/toolbar` callback returns a 404 error.

Can yii2 also include an entryscript in the `debug/default/toolbar` callback?

**Comment by samdark** [comment]
Set showScriptName to true in URL manager config.

Overall, it's better to use forums for questions since GitHub is mainly for issues and feature requests.
