### ISSUE TITLE
Response->sendHeaders() patch to allow sending a Location header with a 202 status

### ISSUE THREAD

**Issue by nd4c** [yiisoft/yii#3924]
The current sendHeaders method in the Response class does not handle a php bug.

The fix is very simple and the explanation is in the comments below:

	/**
	 * Sends the response headers to the client
	 */
	protected function sendHeaders()
	{
		if (headers_sent()) {
			return;
		}
		$statusCode = $this->getStatusCode();
                // This is moved below and the statusCode is force in below...
		//header("HTTP/{$this->version} $statusCode {$this->statusText}");
		if ($this->_headers) {
			$headers = $this->getHeaders();
			foreach ($headers as $name => $values) {
				$name = str_replace(' ', '-', ucwords(str_replace('-', ' ', $name)));
				// set replace for first occurrence of header but false afterwards to allow multiple
				$replace = true;
				foreach ($values as $value) {
					header("$name: $value", $replace);
					$replace = false;
				}
			}
		}
		
		/*
		 * Patch to allow sending Location header with 202 status
		 * 
		 * If the Location header is set
		 * And the status code is not 201 or 3xx
		 * PHP will automatically set the status code to 302  
		 * 
		 * However, the status code 202 would also typically pass a Location header.
		 * 
		 * From: http://www.php.net/manual/en/function.header.php
		 * 		...
		 * 		The second special case is the "Location:" header. 
		 * 		Not only does it send this header back to the browser, 
		 * 		but it also returns a REDIRECT (302) status code to the browser 
		 * 		unless the 201 or a 3xx status code has already been set.
		 * 		...
		 * 
		 * To resolve this problem PHP does allow forcing the status:
		 * 
		 * From: http://www.php.net/manual/en/function.header.php
		 * 		void header ( string $string [, bool $replace = true [, int $http_response_code ]] )
		 * 		...
		 * 		http_response_code
		 * 			Forces the HTTP response code to the specified value. 
		 * 			Note that this parameter only has an effect if the string is not empty.
		 * 
		 * So we need to force the status AFTER all the headers are sent.
		 * (Of course, you can also pass the status with each header() call.)
		 */
		header("HTTP/{$this->version} $statusCode {$this->statusText}", true, $statusCode);
		
		$this->sendCookies();
	}

**Comment by cebe** [comment]
please report this to https://github.com/yiisoft/yii2/issues, this is the issue tracker for yii1.1.

**Comment by nd4c** [comment]
Thanks Cebe, for the quick reply!  

Sorry about that.  Will do.  Also I've updated the code to allow for the PHP default behavior...
