### ISSUE TITLE
Postgres returning id

### ISSUE THREAD

**Issue by des1roer** [yiisoft/yii#3925]
подключаю постгресс

    'db' => array(
        'class' => 'DBConnection',
        'connectionString' => 'pgsql:host=***;port=5432;dbname=**',
        'emulatePrepare' => true,
        'username' => '**',
        'password' => '**',
        'charset' => 'utf8',
        'defaultSchema' => 'SC_Tag',
        'enableProfiling' => true,
    ),

код что работал с MySql не работает в postgres

	public function actionCreate()
	{				
		$model=new Recalculation;

		if(isset($_POST['Recalculation']))
		{
			$transaction = Yii::app()->db->beginTransaction();
			try{
				$messageType='warning';
				$message = "There are some errors ";
				$model->attributes=$_POST['Recalculation'];
				if($model->save()){
					$messageType = 'success';
					$message = "<strong>Well done!</strong> You successfully create data ";
				
					$transaction->commit();
					Yii::app()->user->setFlash($messageType, $message);
					$this->redirect(array('view','id'=>$model->id));
				}				
			}
			catch (Exception $e){
				$transaction->rollBack();
				Yii::app()->user->setFlash('error', "{$e->getMessage()}");
			}			
		}

по логике $model->id должен делать что-то вроде 

      INSERT INTO test (name) VALUES ('My Name') RETURNING id;

как вижу можно конечно использовать 

     SELECT currval('test _id_seq'); 

но для этого нужно знать SEQUENCE (зависимость), что не очень удобно.

**Comment by samdark** [comment]
Что за DBConnection?

**Comment by des1roer** [comment]
делал по этой инструкции

http://copist.ru/blog/2013/10/09/yii-postgresql-schema/

**Comment by samdark** [comment]
Проблемы с неофициальными классами — не проблемы фреймворка, если не показано, что проблема есть без них.

**Comment by pvolyntsev** [comment]
Особенность реализации PostgreSQL в том, что там нет понятия AUTO_INCREMENT у первичного ключа таблицы.
Уникальное значение идентификатора нужно определить заранее, а затем устанавливать его как обычное свойство модели.

Вот это не работает:
```
$user = new User();
$user->save();
$lastId = Yii::app()->db->getLastInsertID(); // <-- будет ошибка
```

Нужно так:
```
$nextId = Yii::app()->db->getLastInsertID('tbl_user_seq'); // взять последний номер в последовательности, он тут же увеличится и повторов не будет
$user = new User();
$user->id = $nextId; // явно назначить идентификатор
$user->save();
```

где tbl_user_seq - это последовательность (sequence), созданная специально для нумерации сущностей таблицы tbl_user. Последовательность должны быть инициализирована так же как и таблица

```
CREATE TABLE tbl_user ( --- таблица
    id integer PRIMARY KEY
    --- ... другие поля
);
CREATE SEQUENCE tbl_user_seq START 1; --- последовательность специально для таблицы tbl_user

```
Вот документация
* http://www.postgresql.org/docs/9.1/static/sql-createsequence.html
* http://www.postgresql.org/docs/9.1/static/functions-sequence.html

**Comment by des1roer** [comment]
можно же после вставки узнать id

    public function actionCreate()
    {
        $model = new TType;
        if (isset($_POST['TType']))
        {
            $transaction = Yii::app()->db->beginTransaction();
            try
            {
                $messageType = 'warning';
                $message = "There are some errors ";
                $model->attributes = $_POST['TType'];
                if ($model->save())
                {
                    $messageType = 'success';
                    $message = "<strong>Well done!</strong> You successfully create data ";
                    $transaction->commit();
                    Yii::app()->user->setFlash($messageType, $message);
                    $id = Yii::app()->db->createCommand()
                            ->select("setval('vgok_site.a_template_type_id_seq',nextval('vgok_site.a_template_type_id_seq')-1)")
                            ->queryScalar();

                    $this->redirect(array('view', 'id' => $id));
                }
            }
            catch (Exception $e)
            {
                $transaction->rollBack();
                Yii::app()->user->setFlash('error', "{$e->getMessage()}");
            }
        }

**Comment by pvolyntsev** [comment]
Идентификатор надо получить из последовательности до сохранения $model, а не после.
Можно это делать автоматически в методе beforeValidate()

```
class User
{
    public $idSequenceName = 'tbl_user_seq';

    public function beforeValidate()
    {
        if ($this->getIsNewRecord())
            $this->id = Yii::app()->db->getLastInsertID($this->idSequenceName);
    }
}
```
Можно сделать поведение и привязать ко всем классам.

**Comment by des1roer** [comment]
а если не прошло валидацию а мы увеличили ид уже? тогда уж beforeSave

**Comment by pvolyntsev** [comment]
Тогда с поля id в правилах валидации надо снять проверку на required, а это неправильно

**Comment by des1roer** [comment]
там и нет никакой проверки

**Comment by des1roer** [comment]
http://yiiframework.ru/forum/viewtopic.php?f=3&t=30589
