### ISSUE TITLE
AfterSave() within a Transaction

### ISSUE THREAD

**Issue by WJRovers** [yiisoft/yii#3928]
For this example I'm saving 3 ActiveRecords succesfully in a transaction. The 2nd AR that get's saved has a special `onAfterSave` where it sends out a 'notify' request to a seperate application (REST). This request will try to look up the saved AR directly in the database by send PK values. When there's a matching row in the database; it will save that same row in his own database.

Problem: When the ActiveRecord is saved inside a transaction it will call the event but the data is not actually stored in the database as the transaction has yet to be commited.
Is there a way to call the onAfterSave after the transaction has been commited? Perhaps it is possible to make a onAfterCommitSave event?

**Comment by nineinchnick** [comment]
You should use some local queue for that. That's out of the scope of the framework anyway.

**Comment by WJRovers** [comment]
@nineinchnick Is there however a way to see if the activeRecord afterSave is being called within a transaction? From here I can adjust behaviour; should it queue up or not.
Adding to this; is there a way to execute this queue after the transaction has been commited. In other words; does the framework provide an afterCommit event?

**Comment by nineinchnick** [comment]
Yes, somewhere in the model, possibly in afterSave method check if `$this->db->transaction` is not null, see [the docs for db connection](http://www.yiiframework.com/doc-2.0/yii-db-connection.html#$transaction-detail).

There is an [afterCommit event](http://www.yiiframework.com/doc-2.0/yii-db-connection.html#EVENT_COMMIT_TRANSACTION-detail).

**Comment by nineinchnick** [comment]
Actually you don't even need a queue, you can just register an event handler in the `afterSave()` method.

**Comment by WJRovers** [comment]
@nineinchnick Im guessing you mean I have to make this AR listen to the afterCommit event. Basicly I want the AR to listen to the afterCommit event then and the problem is not that bad to solve.

Currently I made the afterSave() check wheter it is in transaction or not. When it is not it can immediatly send the notify message. When he is in transaction then it will not.

How exactly do I make the activeRecord listen to the event raised by the transaction?
`const EVENT_COMMIT_TRANSACTION = 'commitTransaction';`
Would be the event I'm looking for;

```
protected function onCommitTransaction($event){
     yii::log('We see this transaction from within the model being completed!');
}
```
Obviously does not work instantly from within the AR. Cause someone has to tell this AR the event took place right?

@nineinchnick Thank you so much allready! You're being of great help

**Comment by nineinchnick** [comment]
You have to register an event handler. You can do that in the `afterSave` method when you'll detect a transaction and then unregister it when it's fired so it only fires once.

To attach an event handler, use the [`on()`](http://www.yiiframework.com/doc-2.0/yii-base-component.html#on%28%29-detail) method.

**Comment by WJRovers** [comment]
The problem remains as this is posted under Yii1 and Yii2 answers were mostly given. I can't find the after Commit events in Yii1. Are they implemented or is this only available in Yii2?

**Comment by WJRovers** [comment]
I solved this issue by extending the default CTransaction and CDbConnection and overwriting the functions beginTransaction() and getCurrentTransaction() within CDbConnection. These now create/return a custom transaction instance.
The custom transaction instance (extending CTransaction) raises event's on the commit / rollbacks. It's basicly a copy off how things are done now in Yii2 rewritten in Yii syntax.
