### ISSUE TITLE
yii1 's createCompositeInCondition question?

### ISSUE THREAD

**Issue by yedong0839** [yiisoft/yii#3929]
Hello.
The function createCompositeInCondition  of class CDbCommandBuilder in yii 1 return  '('.implode(', ',$keyNames).') IN ('.implode(', ',$vs).')'. Why is the in condition 's column more than one.
Thanks.

**Comment by klimov-paul** [comment]
@yedong0839, please use <a href="http://www.yiiframework.com/forum/">Official Yii forum</a> to ask a questions - GitHub is a bug tracking system.
