### ISSUE TITLE
Lazyloading relations doesn't work with PDO::CASE_UPPER on PostgreSQL

### ISSUE THREAD

**Issue by ruslanbes** [yiisoft/yii#3932]
Case:
1. Set `CDbConnection::columnCase` to `PDO::CASE_UPPER`
2. Create two models, one with the relation `self::BELONGS_TO` to the other e.g.

    public function relations()
    {
        return array(
            'user'=>array(self::BELONGS_TO, 'USER', 'USER_ID'),
        );
    }

Then try to access the `user` attribute - and you'll see that it is always NULL

It happens because CActiveFinder sets columns in query to t1_c1, t1_c2 but with `PDO::CASE_UPPER` it looks for columns T1_C1, T1_C2 in the result set.

I suggest editing CActiveFinder:399 to (not sure what "Issue 482" means, it was there)

		if($this->model->getDbConnection()->getDriverName()==='oci' || $this->model->getDbConnection()->columnCase===PDO::CASE_UPPER)  // Issue 482
			$prefix='T'.$id.'_C';

**Comment by samdark** [comment]
Have you checked with code from master?

**Comment by ruslanbes** [comment]
My fault, I have overloaded some classes for CPgsqlSchema and can't now re-create the effect with a clean master installation. Closing the issue for now
