### ISSUE TITLE
Update advanced template installation instructions

### ISSUE THREAD

**Issue by heanluen** [yiisoft/yii#3933]
fxp/composer-asset-plugin:1.0.0 is outdated and it's causing deprecation notice. The installation guide "Install via Composer" section should be updated.

Read: https://github.com/composer/composer/issues/4260

**Comment by samdark** [comment]
If you're talking about Yii 2.0, it's already updated.

**Comment by heanluen** [comment]
@samdark I can still find it in 
http://www.yiiframework.com/doc-2.0/index.html
and 
https://github.com/yiisoft/yii2-app-advanced/blob/master/docs/guide/start-installation.md

**Comment by samdark** [comment]
~1.0.0 means 1.0.0 or higher so latest one should be installed.
