### ISSUE TITLE
Error message is displayed "twice" if a DB error occurs when using PageCache and DB dependency

### ISSUE THREAD

**Issue by drscre** [yiisoft/yii#3935]
I am using PageCache with DB dependency.
If DB server becomes unavailbale and I try to access DB in controller action, a DB exception is thrown.
And I get the following output:
```
{
  "name":"Internal Server Error",
  "message":"There was an error at the server.",
  "code":0,"status":500
}An internal server error occurred.
```
Notice and extra "An internal server error occurred" string after the valid JSON.

This happens because `PageCache::cacheResponse()` tries to access DB once again to caclulate variations.
Since DB is unavailble, a second exception occurs during handling of the first DB exception.

Probably, `PageCache::cacheResponse()` shouldn't be called at all for 5xx responses

**Comment by samdark** [comment]
Is it about Yii 2.0? If yes, please report to Yii 2.0 issue tracker: https://github.com/yiisoft/yii2
