### ISSUE TITLE
[DOCS] Information about hiding script name (index.php) in urls should be easier to find in Getting Started guide

### ISSUE THREAD

**Issue by teo1978** [yiisoft/yii#3938]
I can't find a specific documentation issue tracker for Yii 1, so I report this here.

Second time I start building a Yii application from scratch (though I've been maintaining one for a long time), second time I waste more time than I'd expect to in order to figure out how to hide "index.php" from the urls.

This involves two things:
- configuring **apache/ngynx** (mod_rewrite and the like): the relevant information is here: http://www.yiiframework.com/doc/guide/1.1/en/quickstart.apache-nginx-config
- setting the urlManager component's **`showScriptName`** property to false: I can't find this anywhere in the Getting Started section. I had to look up the CUrlManager API documentation (and this was an easy guess because this is the second time and I've been developing and maintaining an application in Yii for years, but I wonder how long it took me the first time to figure out; I guess I had to google it)

I'd expect:
- both things to be mentioned in the same page, as they are closely related
- some mention and/or link to be found at the page "Creating your first Yii application", because one is pretty likely to skip the Apache configuration section given that the default configuration works out of the box as far as getting the application to run is concerned. Also, setting up basic things is something one likely expects to find at the "Creating your First Application" page.

At the very least, the `showScriptName` setting should be mentioned in the **"Creating your First Application"** page (given you have suggested the user to set up the httpd server to accept urls without the script name, the most consistent thing is to do is to also suggest to set up the url manager to generate urls without it), with a link to the "Apache & Nginx configuration" page for the server configuration part.

**Comment by samdark** [comment]
Hiding is in the same section general URL management is: http://www.yiiframework.com/doc/guide/1.1/en/topics.url#hiding-x-23x

**Comment by teo1978** [comment]
Yeah but that's in "Special Topics", a section one is not likely to look at while going through the Getting Started guide.
So, I think, either you strip away everything related to hiding the script in the Getting Started guide, letting the beginner start with an application consistently showing the script name, or if you choose (as you did) to mention removing the script name in the Getting Started guide, you do it in a complete and consistent way.

Note that currently, one that follows the Getting Started guide step by step, will create an application which accepts urls without index.php but generates urls with index.php, which is pretty confusing, especially for the beginner user who reads "To hide index.php in your URLs you can do this", he does it, and he still sees index.php in his urls.

**Comment by samdark** [comment]
Yeah, could be improved.
