### ISSUE TITLE
PHP errors are not treated properly in debug mode (at least by default)

### ISSUE THREAD

**Issue by teo1978** [yiisoft/yii#3939]
The behavior described here:
http://www.yiiframework.com/doc/guide/1.1/en/topics.error#displaying-errors

> When an error is forwarded to the CErrorHandler application component, it chooses an appropriate view to display the error. If the error is meant to be displayed to end users, such as a CHttpException, it will use a view named errorXXX, where XXX stands for the HTTP status code (e.g. 400, 404, 500). If the error is an internal one and should only be displayed to developers, it will use a view named exception. In the latter case, complete call stack as well as the error line information will be displayed.
> 
> > Info: When the application runs in production mode, all errors including those internal ones will be displayed using view errorXXX. This is because the call stack of an error may contain sensitive information. In this case, developers should rely on the error logs to determine what is the real cause of an error.

applies **only to exceptions, but not to plain PHP errors**

In an out-of-the-box application freshly created with yiic webapp, at least, **PHP errors** (such as "trying to get property of non-object", etc), are **always displayed as they would in production mode**, regardless of the YII_DEBUG constant.

1) This is not properly documented: the documentation doesn't say a word about errors and exceptions being handled differently, and it uses the word "error" ("when an error is forwarded...")
2) It is not a sensible or consistent behavior in the first place.

I don't know whether this is an issue in the framework itself or in the way the example application is set up, but either way it should be corrected.

By the way, in another application of mine, I set up a custom error handler to catch plain PHP errors and re-throw them as exceptions, which not only works around this issue (which I don't even remember facing at that time) but also has the advantage to allow you to use try-catch blocks to catch any kind of errors, besides unifying the way errors and exceptions are handled. I'd suggest to include something similar as an option in Yii. (I'd provide the code if it wasn't too messy)

**Comment by samdark** [comment]
https://github.com/yiisoft/yii/blob/master/framework/cli/views/webapp/protected/config/main.php#L58
