### ISSUE TITLE
[WEB] broken link in extension search result

### ISSUE THREAD

**Issue by teo1978** [yiisoft/yii#3952]
1. Go to http://www.yiiframework.com/extensions/
2. Search for "i18n"
3. Among the search results, you get this:

> I18n ActiveRecord
> http://www.yiiframework.com/extension/i18n-activerecord

The link is broken.
> Error
> Unable to find the requested extension.

**Comment by samdark** [comment]
That one was deleted. I wonder why it's still in the search index...

**Comment by mdomba** [comment]
refreshed the index, now seems all fine
