### ISSUE TITLE
[FORUM] Search content by user is broken

### ISSUE THREAD

**Issue by teo1978** [yiisoft/yii#3953]
1. Go to the profile of this user:
http://www.yiiframework.com/forum/index.php/user/218299-nandor/
2. Click "Find my content"

Expected: the user has posted at least one message (http://www.yiiframework.com/forum/index.php/topic/32621-is-there-a-good-i18n-extension/page__view__findpost__p__243057), hence it should show up in the search results

Observed: no content is found.

Note that the "Posts" tab in the Profile page does work.

![screenshot from 2015-10-03 16 54 28](https://cloud.githubusercontent.com/assets/542107/10263443/85e1f0da-69ef-11e5-8481-841a005aff15.png)

![screenshot from 2015-10-03 16 54 47](https://cloud.githubusercontent.com/assets/542107/10263444/8c0175ee-69ef-11e5-9e17-707a780d4e2d.png)

**Comment by samdark** [comment]
That's powered by IPB. I think it shows only fairly recent posts.

**Comment by teo1978** [comment]
I guess the time threshold should be configurable and it should be possible to set it to no limit.

Otherwise, the phrasing (which I definitely hope is configurable) should be changed, because it reads "View **ALL** topics *User* has posted in or started"

**Comment by samdark** [comment]
Fixed by @mdomba.

**Comment by cebe** [comment]
will be fixed on the new website.
