### ISSUE TITLE
CDbMessageSource-based I18N is intrinsically inefficient

### ISSUE THREAD

**Issue by teo1978** [yiisoft/yii#3954]
Internationalization in Yii 1.1  is flawed at its very core in several ways, some of which I already pointed out in http://www.yiiframework.com/forum/index.php/topic/32621-is-there-a-good-i18n-extension (most of which are design issues in i18n frameworks for which solutions had existed even before Yii was even born, so it's really sad that Yii's i18n mechanism is so naive and flawed)

But **`CDbMessageSource`**-based i18N is totally ridiculous. Besides lacking documentation in the Definitive Guide, which only focuses on CPHPMessageSource as if it was the only one to be used, CDbMessageSource is intrinsically ill-conceived, in that:
- in order for it to be efficient, the **`message`** field in the MessageSource table should be an index
- but it is of type **`TEXT`**, which **cannot be an index** at least in MySQL, at least in InnoDB

`<rant>`
This makes it completely unusable (in an application of any significant size to be used in real life), which reveals the incredibly narrow-minded design, based on the assumption that DB-based i18n is something one doesn't really need (but then why even bother implementing it?). But the ability to store translation in a database is essential to any application whose "backend users" (i.e. webmasters, only to name one use case) need to be able to edit message translations (that is, any serious real-world CMS-like application). Or do you expect a customer to work with translations in PHP files?

And the fact that the message field is of type TEXT (or at least it needs to be a significantly long VARCHAR, which cannot be an index either), ultimately descends from the primary design flaw in Yii's i18n mechanism, which is using whole messages as keys, as discussed in the abovementioned thread. 
Language frameworks as old as vBulletin's one (2004 or older) have that solved in a better way: use codes, not whole message texts, as message identifiers in the application code.
`</rant>`

I wonder if Yii 2 has a better approach for i18n in general. Anyway, in Yii 1.1, at least the efficiency issue for CDbMessageSource should be addressed

**Comment by samdark** [comment]
By `addressed` you mean changing default table schema for it?

btw., keys could be used for strings. In order to do it, set sourceLanguage of the app to something like `key`.

**Comment by teo1978** [comment]
> By addressed you mean changing default table schema for it?

Changing the table schema alone won't do it. I guess the implementation needs some radical change. Actually the issue challenges the very design of the component interface, if I'm not missing some easy solution. 
This is, assuming you are not willing to change the core API.


> btw., keys could be used for strings...

(drifting off topic, my fault, to the more general issue of the bad i18n API design)
Yes, I know. Using a fictitious source language and/or setting forceTranslate to true.

First, the fact that the only reasonable use of the component is a hack shows how bad a design it is. That is, the recommended (or the only reasonable) thing to do is to set the "source" language to a fictitious one because the very concept of a "source" language should not exist in the first place. And/or one should always set forceTranslation to true which is false by default. 

Secondly, as I noted in the abovementioned thread, using a fictitious source language in which the message texts are keys doesn't solve the problem of plural forms and parameters, which is: **the definition of the plural forms and the parameters must be included in the key**.

That is a bad design because, if you need to change the definition of a message in such a way that it uses one more parameter or has one more plural form, you have to change the key (which is the source message text), which in turn means search and replace through all your code. And also, keys become long and ugly.

In a hypothetical good i18n framework, the call to print a messge would be something like:
```
Yii::t('category', 'message_key', array(50, 'name'=>'Grey'));
```
and the translation would be defined like this: (written down in terms of `CPhpMessageSource`) 
```
  'message_key'=>'{n} shade of {name}|{n} shades of {name}'
```

Instead, in Yii, even if you use a fictitious language where fictitious messages texts are keys, you are forced to include the parameters and plural forms in the key.
So the call will be something like:
```
Yii::t('category', 'message_key{n}{name}|message_key{n}{name}', array(50, 'name'=>'Grey'));
```
and the translation will have to be defined like this: 
```
  'message_key{n}{name}|message_key{n}{name}'=>'{n} shade of {name}|{n} shades of {name}'
```

I haven't even tried. Even assuming it works, it's horrible. It defeats the whole idea of using keys.

**Comment by samdark** [comment]
Radical changes aren't possible in 1.x because of backwards compatibility. There are no backwards incompatible versions planned.

I don't agree that using keys instead of English strings is **always** the most reasonable way to go. English works well and since Yii has categories, you can handle contexts and avoid naming conflicts. For people translating it's much easier to deal with source strings in English rather than artificial keys. What are your arguments for using keys only?

The case when you're adding another parameters means that the message was really changed and that it should be translated once again i.e. key should change to indicate the need of re-translation.

Also your argument that you have to include all parameters passed for a message into its source translation (which is key in the case) is wrong. You don't have to.

**Comment by teo1978** [comment]
I don't get why you mention categories: they are completely outside of the discussion as far as I understand; I am not questioning the use of categories.

> I don't agree that using keys instead of English strings is always the most reasonable way to go. English works well and since Yii has categories, you can handle contexts and avoid naming conflicts. For people translating it's much easier to deal with source strings in English rather than artificial keys. What are your arguments for using keys only?

The argument is that you shoul never have to **search-and-replace through the source code** (nor touch the application code at all for that matter) in order to change a text, regardless of whether it is in English or in Turkish. So, the texts to be displayed should always be defined as translations (meaning they should always be on the right side of a `=>` in a translation file or in the `translation` column of the `Message` table in the database). Always. So, having the concept of a "source language", and the possibility to not translate if the target language is the same as the source language, is useless. It's for the lazies who may want to save themself the work of creating a translation file for their own language (but they'll regret it sooner or later). It is harmless as long as the user is encouraged to not do that.

Now, whether these keys are compact like "login_error" or verbose plain English strings such as "Incorrect username or password" is, of course, a personal choice, that's up to the user. That's not the point. One argument in favour of compact key-like strings is, of course, that they are shorter to type and that you have more chances to remember them when you have to use them more than once in the code (as opposed to searching for them somewhere else in the code and copy them).


> Also your argument that you have to include all parameters passed for a message into its source translation (which is key in the case) is wrong. You don't have to.

That's great news. I was finding that out right now just before you wrote it (but you don't have to believe me). The sad part is that all this time I was **misguided by the documentation** to think that you had to, hence believing that Yii's whole i18n mechanism was useless.

Then it's **basically a matter of editing the documentation (and changing one default)**. 
One should not be encouraged to have the plural forms and the parameters in the message source string used in the calls to `Yii::t()`. If you want to allow it, good (for the sake of BC, and if you like, also for the sake of freedom).

What I call a *key* is the source message text. Given that the *key* appears in the source code, and typically more than once, in a well-designed application the following should be true:
* the key should almost never need to be changed, because that involves a search-and-replace
* the key should not contain the plural forms
* the key should not contain the parameters, like `{whatever}`
* the final texts of all languages, including English, should always be defined separately, that is, as translations

The third point is the only one which could be subject to personal tastes: having the parameters in the  key may increase code readability (because you see in the call the parameters that are going to be replaced), but that's at the expenses of maintainability (adding a parameter implies changing all occurrences of the key in the code).

To the above points I would add that a key should be short, as I said, but that's a matter of personal taste too (except for the practical implications in the database-based implementation).

**So,** it turns out all this is currently possible in Yii. So, I suggest:
* Change the default of `forceTranslation` to true (rendering the source language effectively irrelevant)
* Edit the documentation:
 * Leave the concept of "source language" out of the tutorial guide.
 * Convey the concept of the message source not as a whole message in a given language, but as a string identifier for the message (*key*, *code*, *identifier*, whatever you like best). You may want to stress that whether to use a short identifier or a verbose almost-whole-message plain-english text, is up to the user.
 * Encourage to always create translations even for the "source" language. 
 * Change the examples and the explanation of **plural forms and parameters** using them only **in the translations**, not the source messages, or **at the very least, mention** that they don't have to be present in the source message text.

> The case when you're adding another parameters means that the message was really changed and that it should be translated once again i.e. key should change to indicate the need of re-translation.

What?? Changing the key should not be something you do to "indicate the need" of something. Actually, it's something you should not do at all unless absolutely unavoidable. **Changing the key means you have to change the code** in all the places where the phrase is used. If you add a parameter, you may have to change a few calls, but it may also be an optional parameter, such that existing calls in the code don't need to be changed and new ones make use of the parameter.
Anyway, the need for re-translation and the need to review the code are two separate things, which should be as decoupled as possible.



Now, **regarding CDbMessageSource**.

If one uses short source message strings (whether they look like identifiers or they look like plain english texts, provided they are short and function as identifiers), then the current implementation of `CDbMessageSource` would be fine **as long as the default schema is changed** to make `SourceMessage.message` an index, and change its type to a `VARCHAR` shorter than whatever is the limit that allows it to be an index (unfortunately, I fear it's pretty small in MySQL).

So, there's a decision to be taken here: the current implementation of `CDbMessageSource` is horribly inefficient, but it is the only one backward-compatible with the currently suggested (ill-conceived) use of the API (full text source messages, source language relevant). So you can either:
* (A) change the documentation as suggested above, and change the default schema as I mentioned. Then the documentation should warn that source messages can't be longer than *N* characters, and it may suggest the old schema (TEXT, non-index column) as an alternative for those who need longer source messages, with the caveat that it will seriously impact performance,
* (B) or leave the schema as it is, add a gigantic warning that it is highly inefficient (scanning a whole table every time a message has to be used), which may not be a practical concern for applications with a small number of texts, and suggest the VARCHAR-and-index schema as an efficient alternative, with the caveat that it only supports short source message strings.


Otherwise, providing a `CDbMessageSource` implementation that is compatible with the current philosophy (supporting long source message strings), and at the same time is efficient, may be very tricky if not impossible.

**Comment by samdark** [comment]
> Change the default of forceTranslation to true

Can't do that due to backwards compatibility.

> Leave the concept of "source language" out of the tutorial guide.

I don't think it's that bad. It has cons but it has many pros as well and, as long as source language is English, it worked well for huge number of projects for years.

Key-based translation is already presented in an alternative in 2.x docs. Description could be backported into 1.x guide, I guess.

> Anyway, the need for re-translation and the need to review the code are two separate things, which should be as decoupled as possible.

From pure developer's standpoint that's true but when it comes to people who are translating, that could be different.

The thing is that there's automated `yii message` command line tool which makes it very easy for translators to run it and get a list of things to translate w/o trying to find out that there are extra parameters now passed to `some.key` message and the meaning is now a bit different. Translations are often made by people who aren't developers and aren't monitoring all commits that go into repository. Sometimes they're given translation php file by email and emailing it back translated.

> regarding CDbMessageSource

Yep. You've nailed the problem quite well. Since A isn't possible in 1.x, B sounds the only way to solve it.

**Comment by dataskills** [comment]
I think the implementation is brilliant. I have run a website in 14
languages for years. I use CDbMessageSource, I know about the inefficiency,
but I use caching so it is a total non issue. A source language is a must
have. You have to be able to write the app in one language and the
developers must be able to see exactly what text is in the code so
compacted keys is something I haven't seen since the 90's and will NEVER go
back to.

On Sat, Oct 3, 2015 at 3:40 PM, Alexander Makarov <notifications@github.com>
wrote:

> Change the default of forceTranslation to true
>
> Can't do that due to backwards compatibility.
>
> Leave the concept of "source language" out of the tutorial guide.
>
> I don't think it's that bad. It has cons but it has many pros as well and,
> as long as source language is English, it worked well for huge number of
> projects for years.
>
> Key-based translation is already presented in an alternative in 2.x docs.
> Description could be backported into 1.x guide, I guess.
>
> Anyway, the need for re-translation and the need to review the code are
> two separate things, which should be as decoupled as possible.
>
> From pure developer's standpoint that's true but when it comes to people
> who are translating, that could be different.
>
> The thing is that there's automated yii message command line tool which
> makes it very easy for translators to run it and get a list of things to
> translate w/o trying to find out that there are extra parameters now passed
> to some.key message and the meaning is now a bit different. Translations
> are often made by people who aren't developers and aren't monitoring all
> commits that go into repository. Sometimes they're given translation php
> file by email and emailing it back translated.
>
> regarding CDbMessageSource
>
> Yep. You've nailed the problem quite well. Since A isn't possible in 1.x,
> B sounds the only way to solve it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yiisoft/yii/issues/3954#issuecomment-145295783>.
>



-- 
------------------------
J. Bundy
dataskills@gmail.com
+1.206.406.1534

**Comment by teo1978** [comment]
> I know about the inefficiency,
> but I use caching so it is a total non issue

That sort of reasoning is proper of a non-developer. Unfortunately, it's fairly common.

**Comment by teo1978** [comment]
> A source language is a must
have. You have to be able to write the app in one language and the
developers must be able to see exactly what text is in the code so
compacted keys is something I haven't seen since the 90's and will NEVER go
back to.

You don't need source language for that: you just use plain texts instead of compacted keys, that's up to you.

Anyway, thinking about it, I think there could be a **backward-compatible fix to the inefficiency** of the current implementation:
* Add a field that is a hash of the text
* use that as an index 

The only slight difficulty is in figuring out a hash that is truly unique (as opposed to just "very unlikely" to produce clashes) but I guess that's a wheel that has been invented already.

Extra code is almost certainly needed to ensure backward-compatibility with existing databases from the current implementation, but it shouldn't be impossible or even difficult to have 100% BC.

**Comment by samdark** [comment]
Yeah, that could work.

**Comment by dataskills** [comment]
What do you mean? I don't get it. Retrieving translations from the database
as nothing more than an organizational tool. Would I really ever retrieve
translations again .. and again .. and again?!??! And the tens of thousands
of more times my app will need them this hour? Who's the non-developer? My
background is as a c++, java snd c# developer, I sacrificed efficiency
already as a trade off. Caching translations is what non-developers do? huh.

My advice to you is if you don't like it change it. Let's see if you can
improve it. Put up or shut up.

On Sun, Oct 4, 2015 at 9:16 AM, teo1978 <notifications@github.com> wrote:

> I know about the inefficiency,
> but I use caching so it is a total non issue
>
> That sort of reasoning is proper of a non-developer. Unfortunately, it's
> fairly common.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yiisoft/yii/issues/3954#issuecomment-145363507>.
>



-- 
------------------------
J. Bundy
dataskills@gmail.com
+1.206.406.1534

**Comment by teo1978** [comment]
> Caching translations is what non-developers do? huh.

No, caching translations is of course what anybody in their right mind would do. Relying solely on caching to resolve an inefficiency at a lower level, however, is what a bad engineer would do (I used the expression *non-developer* as a joke because you used the expression *non issue*).
Caching is a way of improving performance, when the lower-level design is already as efficient as it can be. Using caching to compensate for suboptimal database design is a misuse of caching.

> Would I really ever retrieve translations again .. and again .. and again?!??!

That's not the point. (And again, the fact that you think that is the question reveals a poor understanding of the problem from a software engineering perspective). If a single retrieval needs to scan a whole table, retrieving a translation only one time can become slow as the number of messages increases (it's O(N) instead of roughly O(1)).
The cache, by definition, is not guarantee to always hit. Not every single translation will be found in cache every single time. By caching, you drastically reduce the number of times that a translation has to be retrieved from the database, but when that happens, it can be slow. Yeah, chances are that nobody will ever notice the difference, but that doesn't make it a proper design.

> My advice to you is if you don't like it change it. Let's see if you can
improve it.

In my previous comment I provided a suggestion of how to do it. 

> Put up or shut up.

Oh well, then why do we need public bugtrackers? If you find a defect, fix it or shut up? 
Sure, writing the code and issuing a pull request would be much better, but how is shutting up better than pointing out the defect and indicating a possible solution or improvement?

**Comment by dataskills** [comment]
I would never think anyone would be using it to do single retrievals, I
have seen it once using a memory table (indexed, message fields were length
limited varchar). I think the idea is to use it as a datastore interface
for CPhpMessageSource. Beyond that, making a custom data delivery system on
top of if is no problem either.

On Sun, Oct 4, 2015 at 11:57 AM, teo1978 <notifications@github.com> wrote:

> Caching translations is what non-developers do? huh.
>
> No, caching translations is of course what anybody in their right mind
> would do. Relying solely on caching to resolve an inefficiency at a lower
> level, however, is what a bad engineer would do (I used the expression
> *non-developer* as a joke because you used the expression *non issue*).
> Caching is a way of improving performance, when the lower-level design is
> already as efficient as it can be. Using caching to compensate for
> suboptimal database design is a misuse of caching.
>
> Would I really ever retrieve translations again .. and again .. and
> again?!??!
>
> That's not the point. (And again, the fact that you think that is the
> question reveals a poor understanding of the problem from a software
> engineering perspective). If a single retrieval needs to scan a whole
> table, retrieving a translation only one time can become slow as the number
> of messages increases (it's O(N) instead of roughly O(1)).
> The cache, by definition, is not guarantee to always hit. Not every single
> translation will be found in cache every single time. By caching, you
> drastically reduce the number of times that a translation has to be
> retrieved from the database, but when that happens, it can be slow. Yeah,
> chances are that nobody will ever notice the difference, but that doesn't
> make it a proper design.
>
> My advice to you is if you don't like it change it. Let's see if you can
> improve it.
>
> In my previous comment I provided a suggestion of how to do it.
>
> Put up or shut up.
>
> Oh well, then why do we need public bugtrackers? If you find a defect, fix
> it or shut up?
> Sure, writing the code and issuing a pull request would be much better,
> but how is shutting up better than pointing out the defect and indicating a
> possible solution or improvement?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yiisoft/yii/issues/3954#issuecomment-145375008>.
>



-- 
------------------------
J. Bundy
dataskills@gmail.com
+1.206.406.1534

**Comment by teo1978** [comment]
> I would never think anyone would be using it to do single retrievals

I don't know what you mean by that.

>  I think the idea is to use it as a datastore interface for CPhpMessageSource.

I think you are way off. CDbMessageSource is **an alternative** to CPhpMessageSource: instead of storing translations in PHP files, you store them in the Db, so that, for example, translators can edit translations through a web interface (which of course you need to implement, unless you find an extension out there that does the job), rather than editing PHP files which (i) they may screw up, (ii) they would need to upload via ftp or send to you so that you upload them. By having translators edit the translations via a web interface you can also use Yii's authManager (or an extension of it) to grant permissions to edit translations to specific users or user groups.

I myself did something like that, except that I did it on top of my own (somewhat primitive) i18n component which I built from scratch (for several reasons that are not relevant here) rather than on top of CDbMessageSource.

So, if translations are stored in the DB, a translation needs to be retrieved when the message is  displayed (unless it's cached, of course).
