### ISSUE TITLE
Tables used by framework components (e.g. CDbAuthManager, CDbMessageSource) should have a prefix by default

### ISSUE THREAD

**Issue by teo1978** [yiisoft/yii#3955]
I know the table names for components which use tables, such as `CDbAuthManager`, `CDbMessageSource` and the like, can be customized through properties of theirs.

However, their **default** names should have some common prefix, e.g. "Yii_". Anybody in their right mind should use a common prefix to avoid (1) name clashes with "user space" tables and (2) have them well organized. So, the default names shouldn't be poorly-chosen names, which means either encouraging a bad practice or forcing one to use non-default values to avoid a bad practice.

**Comment by samdark** [comment]
Can't be done w/o breaking backwards compatibility. Since we don't plan any major 1.x releases it won't be changed.
