### ISSUE TITLE
Allow "partial plural forms" for a substring of a message

### ISSUE THREAD

**Issue by teo1978** [yiisoft/yii#3957]
I know you are reluctant to adding "new features" to Yii 1.1, but this is so basic.

Currently, to define a plural form for a message, you have to rewrite the whole text twice, or as many times as singular/plural forms there are, e.g.:

```
'Up to now, this article seems to have been found useful by {n} person|Up to now, this article seems to have been found useful to {n} people'
```

Of course, there is an obvious workaround, but it is cumbersome: have a separate message for `'{n} person|{n} people'`, and use its translated value as a parameter in the longer message (which would have only one form).

But it would be much better to be able to have pluralized tokens within a message, defined for example in a way similar to this:

```
'Up to now, this article seems to have been found useful by [{n} person|{n people}]'
```

(brackets are just an example, of course; some other symbol may be used)

Of course, inside the pare within brackets_or_whatever, the more general rules of pluralization would be applied (as it is currently done with the whole message): I mean I know it's not just `singular|plural`, there's the `#expression` form, etc.

**Comment by samdark** [comment]
Yii 2.0 has alike feature. Could be added to 1.1 but only if it will be pull-requested.
