### ISSUE TITLE
STAT relations break if 'on' parameter supplied

### ISSUE THREAD

**Issue by teo1978** [yiisoft/yii#3959]
http://www.yiiframework.com/doc/api/1.1/CActiveRecord#relations-detail

> relations() method
> public array relations()
> [...]
> Additional options may be specified as name-value pairs in the rest array elements:
> [...]
> - 'on': the ON clause. The condition specified here will be appended to the joining condition using the AND operator.

However, if you try to use the `'on'` parameter for a `STAT` relation, it causes this error:

> Property "CStatRelation.on" is not defined.

(I can see why: `CStatRelation` extends `CBaseActiveRelation`, while the `$on` property is only defined in its subclass `CActiveRelation`, which the other kinds of relations extend).

I can't see a good reason why a `STAT` relation shouldn't accept an `on` condition, and additionally its lack of support for it is not documented.

**Comment by georaldc** [comment]
Another problem I noticed with the Stat relation is its inability to work with custom key associations, which can be defined using arrays (fk => pk) with all the other relation types.
