### ISSUE TITLE
CAssetManager doesn't log error when failing to copy asset because source file not found

### ISSUE THREAD

**Issue by teo1978** [yiisoft/yii#3961]
I have created a small project and it works fine on my local machine.

I have deployed to an online server. The assets folder has 777 access. All the assets for gridiview systematically fail to be copied. Assets for other components have been copied succesfully (and no, I didn't upload them).

For example, I load a page that has a gridview and all the assets for the gridview fail to load:

> http://example.org/assets/f21cbaaa/gridview/styles.css
> http://example.org/assets/f21cbaaa/gridview/view.png
> http://example.org/assets/f21cbaaa/gridview/jquery.yiigridview.js
> ...

The directory `f21cbaaa` has been created. And it has 777 permissions as expected. However, it is empty.
As I mentioned, there are other (two) subfolders in assets and they do have files inside

I already tried removing all the contents of the assets folder, but the same systematically happens.

Even assuming there may be some configuration issue with the server (e.g. security restrictions for PHP despite the directories having 777 permissions):
- that does not explain how some assets got copied and others didn't
- most importantly, **application.log doesn't show any error related to AssetManager** (and the application is running in debug mode and the logger is set to log trace, info, warning and error. For example, I do see the errors due to being unhable to handle the requests for the file which don't exist)

**Comment by teo1978** [comment]
Whops, forget about it. I failed to upload zii/assets because I used --exclude=assets/* in rsync not knowing this would match also subdirectories. My fault.

**Comment by teo1978** [comment]
Wait a moment, there still **is** an issue: assetManager **should log an error** when failing to copy assets.

Oh, I see where the problem is: the source directory existed but it was empty, and **CGridView publishes the folder**. Anyway, there's something wrong if missing asset sources can go undetected. This seems to me a **design issue**.
Maybe Yii's widgets (and any component that uses assets) should embrace a best practice of **publishing all files individually** instead of whole directories: this way the existence of all files would be checked.
Or perhaps CAssetManager could allow a parameter when publishing a folder which would be an array of filenames, whose existence would be checked, only when the folder is created. Then it would be the app's responsibility to use these file lists when publishing folders; and of course Yii's builtin widgets would do it.

**Comment by samdark** [comment]
There's very unlikely possbility that missing file would go unnoticed. I doubt such check is really required.
