### ISSUE TITLE
Live chat login captcha showing unknown language

### ISSUE THREAD

**Issue by sjnlabs2013** [yiisoft/yii#3962]
http://www.yiiframework.com/chat/

i am loggin into live chat from sri lanka, the login screen showing the captcha in a unknown or different language. i had to guess and login :(

**Comment by cebe** [comment]
@sjnlabs2013 can you make a screenshot and add it here? thanks!

**Comment by sjnlabs2013** [comment]
damn its coming in english now , i tried in chrome, ff, opera, ie(Javascript is required to use IRC.), and safari 

![image](https://cloud.githubusercontent.com/assets/3591216/10366031/42074762-6de5-11e5-8bbe-cdc10d9a0381.png)

**Comment by samdark** [comment]
That's Google's stuff. We can't affect it anyway except changing chat software.

**Comment by cebe** [comment]
as far as I see, we are able to adjust it with CSS. Will check that for the new site.

**Comment by cebe** [comment]
moved to https://github.com/yiisoft-contrib/yiiframework.com/issues/108
