### ISSUE TITLE
Reset default scope in relations doesn't work

### ISSUE THREAD

**Issue by bohdan-vorona** [yiisoft/yii#3964]
I сan't reset **default scope in relations**.

**My query, :**

```
$matches = MatchesStat::model()
->resetScope(true)
->with(array('best_player', 'bad_player'))
->findByAttributes(array(
            'match_id' => $this->id,
            'mode' => 'pro_league'
        ));
```

**Function relations() in the model MatchesStat:**

```
public function relations()
{
    return array(
        'best_player'
        =>
        array(self::BELONGS_TO, 'Players', '', 'on' => 't.best_pl = best_player.pl_id AND t.mode = best_player.mode', 'scopes' => array( 'resetScope' )),
        'bad_player'
        =>
        array(self::BELONGS_TO, 'Players', '', 'on' => 't.bad_pl = bad_player.pl_id AND t.mode = bad_player.mode', 'scopes' => array( 'resetScope' ))
    );
}
```

**Players, defaultScope:**

```
public function defaultScope()
{
    return array(
        'condition' => $this->getTableAlias(false, false) . '.mode = "main"',
    );
}
```

As you can see, I use **'scopes' => array( 'resetScope' )** in my relations and in my query I wrote that I need PRO LEAGUE mode (the first step). **But:**

![kcv2q](https://cloud.githubusercontent.com/assets/5950639/10393753/4afae44e-6e9b-11e5-9f99-b3a29d5d9a63.jpg)

**Comment by cebe** [comment]
`resetScope` is not a scope but a normal method so this can not work. It has been dicussed a lot before. See e.g. #1197
