### ISSUE TITLE
[WEBSITE] yii 1.1 API docs "report a bug" link points to yii2 issue tracker

### ISSUE THREAD

**Issue by teo1978** [yiisoft/yii#3966]
For example at:
http://www.yiiframework.com/doc/api/1.1/CHtml

Under the "Development" menu, click on "Report a bug"

Expected: since it is the yii 1.1 API docs, it should send you to https://github.com/yiisoft/yii/issues/new
Observed: sends you to https://github.com/yiisoft/yii2/issues/new

**Comment by samdark** [comment]
Well, it was meant to be global menu and since 2.0 is the current thing, I've replaced everything to point to 2.0 things.

It could be OK to change menu depending on the context of what's viewed.

**Comment by cebe** [comment]
will be different on new site.
