### ISSUE TITLE
CButtonColumn's default delete button does GET request if CGridView.ajaxUpdate set to false

### ISSUE THREAD

**Issue by teo1978** [yiisoft/yii#3971]
An out-of-the-box all-default `CGridView` with an out-of-the-box all-default `CButtonColumn` (such as those of the `admin` views generated by Gii) has delete buttons which generate **POST** requests (after confirmation).

If you change `CGridView`'s `ajaxUpdate` property to false, so that updates of the page related to pagination and filtering are not done via ajax, then the delete buttons (still after asking for confirmation as expected), instead of doing _POST_  requests behave like regular links, doing a GET request, which of course is usually undesirable and will also be blocked by well-designed action filters (like those put in place by default by Gii) which would only allow a delete action to be done via post.

This makes no sense, as there is no reason why the ajax vs non-ajax behavior of the CGridView should in any way be related to the GET vs POST request initiated by the delete button.

**Comment by teo1978** [comment]
I see, this is caused by a **javascript error** in the code triggered by the button; hence the javascript that would do the POST request fails, and that is why the button falls back to what it would normally do when clicking on it as a link (i.e. a GET request)

```
Uncaught TypeError: Cannot use 'in' operator to search for '92' in User%5Bid%5D=&User%5Bsession_start%5D=&User%5Bis_test%5D=&User%5Bcomments%5D=&User%5Binfo%5D=isArraylike 
@ jquery.js:583jQuery.extend.each 
@ jquery.js:358(anonymous function) 
@ jquery.yiigridview.js:363jQuery.extend.each 
@ jquery.js:383jQuery.fn.jQuery.each 
@ jquery.js:136methods.update 
@ jquery.yiigridview.js:257$.fn.yiiGridView 
@ jquery.yiigridview.js:412(anonymous function) 
@ admin?quiz_id=1:128jQuery.event.dispatch 
@ jquery.js:4641jQuery.event.add.elemData.handle @ jquery.js:4309
```

**Comment by teo1978** [comment]
Looks like options.data is assumed to be an array, while other parts of the code store it as a string using $(...).serialize()

**Comment by teo1978** [comment]
Ouch, I didn't think my messing around with my fork would appear here until I would issue a pull request

**Comment by teo1978** [comment]
I have updated to the latest version and it may be fixed, but I'm not sure if completely.
I see this part is fixed:
https://github.com/yiisoft/yii/blob/master/framework/zii/widgets/assets/gridview/jquery.yiigridview.js#L331

but here you still use `serialize()` and not `serializeArray()`, so `data` is set to a string:
https://github.com/yiisoft/yii/blob/master/framework/zii/widgets/assets/gridview/jquery.yiigridview.js#L128
Not sure whether that may be an issue.

**Comment by thaddeusmt** [comment]
I am getting this error in one other spot in the jquery.yiigridview.js, on the 1.1.16 branch, when `ajaxUpdate` is set to false on the CGridView.

`options.data` is a serialized string on line 363 where `$.each()` iterates over it. Prior to jQuery 1.9 `$.each()` just iterated over each character of the string, and nothing happened (no error either). Now, with jQuery 1.11, it throws this error:

In the 1.1.16 branch changing line 327 from this:

`options.data = $(settings.filterSelector).serialize();`

to this:

`options.data = $(settings.filterSelector);`

Seems to work OK as a fix, by not serializing the options in the first place.

**Comment by thaddeusmt** [comment]
This seems to be related to this issue as well: #3745
