### ISSUE TITLE
CFileValidator does not work with ajax validation - always reports empty value error

### ISSUE THREAD

**Issue by teo1978** [yiisoft/yii#3978]
I kind of feel like I reported this already, but I searched (including closed issues) and can't find it.

Steps to reproduce:
1. have a model with a file field and a file validator not allowing empty value:

```
    //...
    public $uploadedFile;
    //....
    public function rules()
    {
        return array(
            array('uploadedFile', 'file', 'types'=>array('jpg','jpeg', 'png', 'gif')),  
        );
    }
```

and a CActiveForm widget with `ajaxValidation` and `validateOnSubmit` 
2. Submit the form without selecting a file => you get the validation error as expected "uploadedFile cannot be blank"
3. Now do select a file and attempt to submit the form again

Expected: now it should obviously validate succesfully
Observed: it keeps issuing the error "uploadedFile cannot be blank".

The same form does work if I select a file the first time. (EDIT: no it doesn't)

**Comment by samdark** [comment]
https://github.com/yiisoft/yii/blob/master/UPGRADE#L26

**Comment by teo1978** [comment]
Well, then:

1) this should be mentioned at http://www.yiiframework.com/doc/api/1.1/CFileValidator
Do you expect users to read every release note?

2) Since this renders CFileValidator effectively useless if `safe` is true, then why not set `safe` to false in `CFileValidator` by default?? (overriding CValidator's default)

**Comment by teo1978** [comment]
And actually no, setting `safe` to false doesn't change a thing.

**Comment by teo1978** [comment]
And I was wrong in the description: you don't need to 

Actually, the first ajax validation is performed at the very moment I click on the "choose file" button (while the browser's window to select file is still open), which it shouldn't, but assuming this glitch, it is expected that the first ajax validation returns the error.
After that, all subsequent ajax validations do, including the validate on submit.

If I disable ajax validation, the same works as expected (error if no file uploaded, validated succesfully if file uploaded). If I disable validateOnSubmit, ajax validation still systematically highlights the bogus error, but as the form is finally submitted it works.

Something is definitely wrong, or not documented enough.

**Comment by teo1978** [comment]
The problem seems to be that the hidden field being sent via ajax is never assigned a value.

**Comment by samdark** [comment]
Well, file upload can't be sent via AJAX in most of the cases.

**Comment by teo1978** [comment]
What are you talking about? Of course the file can't be sent via ajax, but does that mean that the form's ajax validation should break altogether because it has a file field???
Also, it used to work.

**Comment by samdark** [comment]
OK. Probably something is broken. Which version was OK?

**Comment by teo1978** [comment]
> OK. Probably something is broken. Which version was OK?

I'm not sure. Actually, now I'm doubting if it really used to work, because I used to have allowEmpty=true.

The fact is: I have the rules cited above (and now `'safe'=>false`), a `CActiveForm` widget with `enableAjaxValidation` true and `clientOptions[validateOnSubmit]` true. I expect the form to be fully functional. Of course, it can't ajax-validate the file type, but the general philosophy of client and ajax validation is (or should be): (1) validate on the client and via ajax everything you can, and (2) definitely don't prevent a form to be sent because there's something you cannot possibly validate client-side or via ajax, so, if something can't be validate (meaning it's theoretically impossible to validate it), consider it valid in a client-side or ajax validation. Otherwise, you have a form that is fully functional, and by just turning on ajaxValidation and validateOnSubmit, it breaks, preventing you to send a form with valid data. That cannot be right under any circumstances.

**Comment by teo1978** [comment]
Since `fileField()` creates a `hidden` field together with the `file` field, I assumed it was supposed to assign it a value when a file was selected, and I thought this was used to ajax-validate the non-emptiness of the field.

But I suspect I was wrong: maybe the hidden field is just there in order to send a `''` value?

**Comment by samdark** [comment]
It's there in order for isset to work as far as I remember.

**Comment by teo1978** [comment]
Yeah, I guess so.

So, is it possible that you just never considered ajax validation for forms containing file fields, which hence never worked??

**Comment by samdark** [comment]
Yes, it's possible.

**Comment by georaldc** [comment]
I rarely use ajax validation through yii so I can't comment on the actual issue at hand, but one thing I do agree with is yii missing needed documentaion on how it handles uploads. If I remember correctly, CFileValidator always looks for a CUploadedFile instance when you run validate so handling updates on existing models can be a bit tricky, unless the attribute is not set to be safe. If this is something that is mentioned in the framework documentation found in the site, then I probably just missed it.
