### ISSUE TITLE
Dublicate start session from yii 1.x ?

### ISSUE THREAD

**Issue by nikolasr200** [yiisoft/yii#3985]
I ve faced recently a very serious security issue (not yii related) and i was asked to do an escalation on the session start, session id etc proceedures followed in my yii project to eliminate any issues.

I noticed that when application "starts" there are two following attempts for session_start.
Specifically in 
yiilite.php

	public function init()
	{
		parent::init();
		Yii::app()->getSession()->open();
		if($this->getIsGuest() && $this->allowAutoLogin)
			$this->restoreFromCookie();
		elseif($this->autoRenewCookie && $this->allowAutoLogin)
			$this->renewCookie();
		if($this->autoUpdateFlash)
			$this->updateFlash();
		$this->updateAuthStatus();
	}

and then following 

CWebUser 

	public function init()
	{
		parent::init();
		Yii::app()->getSession()->open();
		if($this->getIsGuest() && $this->allowAutoLogin)
			$this->restoreFromCookie();
		elseif($this->autoRenewCookie && $this->allowAutoLogin)
			$this->renewCookie();
		if($this->autoUpdateFlash)
			$this->updateFlash();
		$this->updateAuthStatus();
	}

is there some specific reason that session gets initialized twice?

**Comment by samdark** [comment]
It won't be initialized twice. Second call will be ignored unless session was terminated in between.

**Comment by nikolasr200** [comment]
Hi, thank you for your response, the reason for asking is because during logging application initialization and serving request, there was monitored second initialization of session, which i didnt notice to be ignored somehow. Could you please elaborate a little further on this?

By "ignored" you mean that although second session is started there is no affect to the originally started session?

**Comment by samdark** [comment]
That's how PHP works. If there's a session, `session_start()` basically does nothing.

**Comment by nikolasr200** [comment]
Thank you very much once more
