### ISSUE TITLE
Meta tags are getting html encoded

### ISSUE THREAD

**Issue by dangarhow** [yiisoft/yii#3987]
When  you try to register a meta tag the content field get htmlencoded, so if you want to set a url that has get parameters they will get htmlencoded.

Example:

$this->registerMetaTag(['property'=>"og:url",'content'=>"http://www.mydomain.com/?foo=bar&foo2=bar2"]);

Outputs:

```
<meta property="og:image" content="http://www.mydomain.com/?foo=bar&amp;foo2=bar2">
```

**Comment by samdark** [comment]
That is how it should be. Ampersands in HTML are to be encoded.
