### ISSUE TITLE
表单上传的bug

### ISSUE THREAD

**Issue by kaopur** [yiisoft/yii#3989]
表单中的文件上传保存后，当再次修改的时候，通过<?= $form->field($model, 'img')->fileInput(['maxlength' => true]) ?>渲染出来的文件域，没有将之前的value赋值给隐藏域。

**Comment by samdark** [comment]
Could you please use English? Thanks!

**Comment by kaopur** [comment]
My English is very poor, please don't laugh at me. ^_^
My Yii version is 2.0.6.
I make a form from "<?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>".
Create is OK.
But Then I will update the data,the hidden input's value is empty from Yii auto created.
Like This:
<div class="form-group field-sys-img">
<label for="sys-img" class="control-label">Img</label>
<input type="hidden" value="" name="Sys[img]">
<input type="file" onchange="changeImg()" maxlength="" value="upload/2015/11/15-142532769.png" name="Sys[img]" id="sys-img">
<div class="help-block"></div>
</div>

I will try to source "basic\vendor\yiisoft\yii2\helpers\BaseHtml.php" activeFileInput() method of the modified into "return static::activeHiddenInput($model, $attribute, ['id' => null]) . static::activeInput('file', $model, $attribute, $options);"
Now the method is OK.

**Comment by samdark** [comment]
That works as expected. You won't get existing image there automatically and you must implement it manually if you want to. This is because there are cases where instead of overwriting one image you need it to accept another one and add it to the set of existing ones.

**Comment by kaopur** [comment]
Ok, Thanks.
