### ISSUE TITLE
CHttpException not working with HHVM

### ISSUE THREAD

**Issue by ceasbz** [yiisoft/yii#3994]
Hello, 

When the server returned an exception of type `CHttpException`: 

```
eg. throw new CHttpException(404,'The requested page does not exist.');
```

The server does not redirect the error and explodes on the screen for user. Can anyone tell me how I can work this way?
#### STACK:

HHVM: `HipHop VM 3.10.1`
Yii: `1.1.16`

**Comment by samdark** [comment]
Could you provide a screenshot of the explosion?

**Comment by cauealves** [comment]
Hello @samdark,

It is only this what appears on the screen:

![captura de tela 2015-12-01 as 10 29 50](https://cloud.githubusercontent.com/assets/7065285/11500801/94aa8122-9816-11e5-8f3a-e61fd86c285e.png)

And the normal behavior is to render the error.php template and this is not happening.

**Comment by samdark** [comment]
Have you configured HHVM?

```
 hhvm.server.implicit_flush = true
 hhvm.error_handling.call_user_handler_on_fatals = true
```

**Comment by cauealves** [comment]
Yes, and the same thing happens.

This is my confs:
```
hhvm.enable_zend_compat = true

hhvm.server.implicit_flush = true

hhvm.error_handling.throw_bad_type_exceptions = true
hhvm.error_handling.throw_too_many_arguments = true
hhvm.error_handling.warn_too_many_arguments = true
hhvm.error_handling.throw_missing_arguments = true
hhvm.error_handling.throw_invalid_arguments = true
hhvm.error_handling.enable_hip_hop_errors = true
hhvm.error_handling.call_user_handler_on_fatals = true
```

**Comment by samdark** [comment]
Yii 2.0 works well with it so could be one of https://github.com/yiisoft/yii2/issues?q=label%3A"feature%3Ahhvm+compatibility"+is%3Aclosed

**Comment by cauealves** [comment]
Hello @samdark,

Currently cannot perform the migration to `Yii 2.0`. So I will try to understand if there is any specific setting that helps me in the current version.

Please if you have some insight let me know.

**Comment by samdark** [comment]
I don't. I know that we've achieved good error handling for HHVM in Yii 2.0 but I don't remember how.

**Comment by cauealves** [comment]
No problem, I'll try to understand :smile:
