### ISSUE TITLE
php 7 return 500 server error with CHttpException

### ISSUE THREAD

**Issue by farmani** [yiisoft/yii#3997]
when I throw an exception in php 7 it return a 500 server error. like when we want to show a 403 or 404 or whatever
PHP message: PHP Fatal error:  Uncaught CHttpException: You are not authorized to perform this action.

**Comment by samdark** [comment]
How / where are you throwing it?

**Comment by farmani** [comment]
```php
if ($user->isGuest === true)
    $user->loginRequired();
else
    throw new CHttpException(403, $message);
```


```
2015/12/17 01:02:35 [error] 1039#1039: *271 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught CHttpException: You are not authorized to perform this action. in /path/to/BackendController.php:60

**Comment by samdark** [comment]
I can't reproduce it.

**Comment by farmani** [comment]
the error was because changes in default php.ini 
display_errors was off by default but there is another issue with CHttpException in php 5.6 it works greate but in php 7 I still receive Uncaught CHttpException that means yii couldn't catch exceptions and add its own error handler for exceptions in php 7 

<b>Fatal error</b>:  Uncaught CHttpException: "Bla Bla Bla". in /path/to/controllers/MovieController.php:705

**Comment by farmani** [comment]
for the one who has same problem make sure you set two constant correctly:

```php
defined('YII_ENABLE_ERROR_HANDLER') or define('YII_ENABLE_ERROR_HANDLER', true);
defined('YII_ENABLE_EXCEPTION_HANDLER') or define('YII_ENABLE_EXCEPTION_HANDLER', true);
```

**Comment by farmani** [comment]
sorry yii folks :(

**Comment by dux86** [comment]
> for the one who has same problem make sure you set two constant correctly:
> 
> ```
> defined('YII_ENABLE_ERROR_HANDLER') or define('YII_ENABLE_ERROR_HANDLER', true);
> defined('YII_ENABLE_EXCEPTION_HANDLER') or define('YII_ENABLE_EXCEPTION_HANDLER', true);
> ```

Thank you! It heps.

for amirvenus: "Where do you set those two constants?"
in index.php
