### ISSUE TITLE
Docs not rendering code

### ISSUE THREAD

**Issue by craigpotter** [yiisoft/yii#3999]
On this page 

http://www.yiiframework.com/doc/guide/1.1/en/database.arr#relational-query-with-named-scopes 

There is a section of code example which isn't rendering as code 

~~ [php] // note the repetition of the relationship name, which is necessary $approvedComments = $post->comments('comments:approved'); ~~

**Comment by cebe** [comment]
fixed, thanks for reporting. This will be updated on the website with the next release.
