### ISSUE TITLE
Include jquery-migrate-1.2.1.min into core JS web/js/source

### ISSUE THREAD

**Issue by stepanzarubin** [yiisoft/yii#4006]
This allows keep older project working with latest version of framework/jquery
Then in conf file:

```
'clientScript' => array(
    'packages' => array(
            'jquery'=>array(
                'js'=>array(YII_DEBUG ? 'jquery.js' : 'jquery.min.js','jquery-migrate-1.2.1.min.js'),
            ),
),
```

**Comment by samdark** [comment]
We aren't going to supply it by default but it worth mentioning somewhere in docs how to achieve that.

**Comment by samdark** [comment]
Could you work on a pull request?

**Comment by stepanzarubin** [comment]
What should I do? update docs?

Here are reasons to supply by default:
1. JQuery migrate plugin is an official one, so I think its ok to have it whenever core library is.
2. When we upgrade framework version we do not want to add/edit its files.
    e.g. I decided upgrade to 1.1.17 and forgot about extra step of adding migrate plugin manually.
   of course this will not happen much because this version is latest or almost latest but since in most      cases JS is a main roadblocker to upgrade, it would much easier for people to have it all together and instruction of how to have painless upgrade with a single config line.

Not sure what am I missing?

**Comment by samdark** [comment]
1. It's extra file and extra bytes.
2. It's not needed in many projects not targeting older versions.
