### ISSUE TITLE
jquery.yiiactiveform.js Uncaught TypeError: jQuery(...).yiiactiveform is not a function

### ISSUE THREAD

**Issue by sjnlabs2013** [yiisoft/yii#4009]
i created a new sample application

getting this error 

Uncaught TypeError: jQuery(...).yiiactiveform is not a function

the file is also there in yii-1.1.17.467ff50\framework\web\js\source

**Comment by samdark** [comment]
How did you created sample application?

**Comment by sjnlabs2013** [comment]
using windows cmd

**Comment by dunaicapa** [comment]
It also happens if you include jquery twice.

**Comment by cebe** [comment]
> It also happens if you include jquery twice.

that is clearly an error and you should not do this. jQuery must be included exactly once. Closing this issue unless detailed information is provided on how to reproduce it.
