### ISSUE TITLE
Modsec Sec rule of STREAM_OUTPUT_BODY causes yii2 pages to load blank with no errors

### ISSUE THREAD

**Issue by zmoddynamics** [yiisoft/yii#4010]
Hello, 

I have a very strange problem which I am having no success debugging. I'm using a Cpanel/WHM server setup with several different web sites and frameworks (Wordpress, Yii2, etc.)

I added a custom Modsec Rule in ModsecTools of apache :

SecRule STREAM_OUTPUT_BODY "@rsub s/<\/html>/<a href=\"http:\/\/\"><\/a><\/html>/" "id:'999001',phase:4,t:none,nolog,pass"

this rule cause an injection of <a href=""></a> just above the closing </html> tag of any page served up by Apache. 

After enabling the rule, I checked that indeed the <a href=""></a> tag is injected just above the closing </html> tag of all other pages (ie. on any Wordpress sites we are hosting on this server etc). The only application that does not load properly is the Yii2 application. Basically, any page you go to on the Yii2 application just shows a blank page with no errors. [Note. I am in Debug mode for the Yii2 application here and development environment:

define('YII_DEBUG', true);
define('YII_ENV', 'dev');

Disabling the rule in Modsec causes all pages to be rendered properly. Hence, the issue must be in the modsec rule + Yii2 framework interaction. 

I have scanned all apache and server log files, including all the error_log files and debug folders of the yii application and there are no errors generated. Nor do any show when loading the page since it just comes back blank.

Could someone please help me out? Does Yii2 framework have a bug when STREAM_OUTPUT_BODY rule of ModSecurity is used to inject some content ?

Thank you for your time.

**Comment by SilverFire** [comment]
Well. First of all you've posted the issue to a wrong repo. It's Yii1 repo. 

Please, check the status code of the response.
Try to enable full PHP logging and check PHP error logs.

```ini
display_startup_errors = On
display_errors = On
log_errors = On
error_reporting = E_ALL
```

Currently we have no info about `STREAM_OUTPUT_BODY` incompatibilities with Yii2.

Please note, that we use GitHub is for bug reports. We are happy to help you on [support forum](http://www.yiiframework.com/forum/) or in gitter room https://gitter.im/yiisoft/yii2. It's always better to text there, unless you are sure it is a Yii2 core problem.

**Comment by zmoddynamics** [comment]
My apologies. I will add some of the PHP directives you mention below and re-check but I'm fairly certain this is a core problem.

I will re-check with a fresh installation of the yii basic application to be sure.

Sent from my iPhone

On Jan 21, 2016, at 1:48 AM, Dmitry Naumenko <notifications@github.com<mailto:notifications@github.com>> wrote:


Well. First of all you've posted the issue to a wrong repo. It's Yii1 repo.

Please, check the status code of the response.
Try to enable full PHP logging and check PHP error logs.

display_startup_errors = On
display_errors = On
log_errors = On
error_reporting = E_ALL

Currently we have no info about STREAM_OUTPUT_BODY incompatibilities with Yii2.

Please note, that we use GitHub is for bug reports. We are happy to help you on support forum<http://www.yiiframework.com/forum/> or in gitter room https://gitter.im/yiisoft/yii2. It's always better to text there, unless you are sure it is a Yii2 core problem.

-

**Comment by SilverFire** [comment]
No problem :) If you will be still able to reproduce it on the clean install, please, open a new issue iy https://github.com/yiisoft/yii2 repo

**Comment by zmoddynamics** [comment]
Will do. Thank you Dmitry.

Sent from my iPhone

On Jan 21, 2016, at 9:03 AM, Dmitry Naumenko <notifications@github.com<mailto:notifications@github.com>> wrote:


No problem :) If you will be still able to reproduce it on the clean install, please, open a new issue iy https://github.com/yiisoft/yii2 repo

-
