### ISSUE TITLE
CStarrating doesen't submit empty / resetValue

### ISSUE THREAD

**Issue by Bhoft** [yiisoft/yii#4011]
I have added this to my code  but the resetValue isn't ever submitted ?

```
   $rating_Widget = $this->widget('CStarRating', array(
        'model'=>$model,
        'attribute' => 'project_review_rating',
        'minRating' => 1,
        'maxRating' => 5,
        'ratingStepSize'=> 1,
        'allowEmpty'=>true,
        'resetValue'=> " -1", // useless
        'titles'=>array(
                '1'=>'Normal',
                '2'=>'Average',
                '3'=>'OK',
                '4'=>'Good',
                '5'=>'Excellent'
        ),
    ), true);
```

only if I add a hidden field before the CStarRating radio buttons with my "default" or empty value i can set it.

```
   echo CHtml::activeHiddenField($model, 'project_review_rating', array('value'=>'-1'));
```

reproduce:
- Just add a CStarRating to a form
- submit rating some value (1-5) and create an error on some other field. 
- submitted value is selected, use the reset button and submit form again
- old rating value is still selected $_POST['Projectreviews']['project_review_rating'] not set at all.

resetValue even doesn't work if the value is one of the available settings. I tried also integer as well as string like mentioned in the api. http://www.yiiframework.com/doc/api/1.1/CStarRating#resetValue-detail

**Comment by samdark** [comment]
Won't be fixed in 1.1.
