### ISSUE TITLE
Pjax - GridView - LinkPager -  not populating browser address bar

### ISSUE THREAD

**Issue by marshmanGit** [yiisoft/yii#4012]
Just updated to latest 2.0.7-dev
GridView paging no longer populates the browser address bar thus causing pjax to reload entire page.

Expecting:  index.php?r=csuser%2Findex&page=3&per-page=15
Getting: index.php?r=csuser%2Findex

**Comment by SilverFire** [comment]
How to reproduce it? Did you clean the cache (runtime/cache, web/assets)? Does it work as expected on stable 2.0.6?

**Comment by SilverFire** [comment]
Also you've posted the issue to a wrong repo. Please, reopen it in https://github.com/yiisoft/yii2 and provide answers on my questions.
