### ISSUE TITLE
как сделать constructor injection?

### ISSUE THREAD

**Issue by badimalex** [yiisoft/yii#4016]
есть класс filterService
нужно чтобы при создании его экземпляра создавался также экзепляр Advert и инжектился через в FilterService, пока решаю проблему так, можно как то избежать вызова init?

	'components'=>array(

		'FilterService' => [
			'class' => 'FilterService',
			'advert' => [
				'class' => 'Advert',
			]
		],

    /** @var  $advert Advert */
    public $advert;

    public function init()
    {
        parent::init();
        $this->advert = Yii::createComponent($this->advert);
    }

**Comment by badimalex** [comment]
спасибо.

**Comment by samdark** [comment]
Вопросы лучше задавать сюда: http://yiiframework.ru/forum/. Тут репортятся баги и постятся хотелки.
