### ISSUE TITLE
[WEBSITE] Ad over page content

### ISSUE THREAD

**Issue by teo1978** [yiisoft/yii#4018]
http://www.yiiframework.com/doc/api/1.1/CHtml

![screenshot from 2016-02-20 22-31-08](https://cloud.githubusercontent.com/assets/542107/13199301/2da35a16-d822-11e5-851b-fcfa383d3cef.png)

(BTW, does anybody know how the f**\* to report this to Google Adwords? The options for reporting an ad don't include anything about the ad preventing from reading page content, nor do they allow to include additional comments in the report)

**Comment by teo1978** [comment]
Forgot to mention, it's not systematic (far from it, actually).

**Comment by cebe** [comment]
you may log in to remove ads to workaround this.
