### ISSUE TITLE
CController::widget() creates widget even if widget alias in invalid

### ISSUE THREAD

**Issue by fazliddin** [yiisoft/yii#4019]
If widget class is already imported, that is, available without any `require_once`, then `CController::widget()` is creating widget without any error even if alias is invalid.

In my case, I use my own `CategoryMenuWidget` in header and in footer, in `layout/main.php`:
```
<?php $this->widget('category.widgets.CategoryMenuWidget') ?>
### some code ###
<?php $this->widget('catalog.widgets.category.CategoryMenuWidget') ?>
```
Menus are rendered properly twice, although alias `catalog.widgets.category.CategoryMenuWidget` is absolutely invalid, thus Yii is hiding mistake of developer. Result is fragile code (as Uncle Bob says).

After crawling Yii core I found `CWidgetFactory::createWidget` which does not check existence of alias.

**Comment by samdark** [comment]
Any idea on how to fix that?

**Comment by samdark** [comment]
That's how PHP autoloading works. If there's a class with the same fully qualified name that is already present, autoloading isn't triggered at all so there's no way to check it without harming performance badly. Since 5.3 it's possible to use namespaces which help to avoid such clashes.
