### ISSUE TITLE
session_regenerate_id(): Session object destruction failed, Yii1.1.17

### ISSUE THREAD

**Issue by suriyabaskaran** [yiisoft/yii#4020]
Related to #2376 

i am running into same issue, if i use CRedisCache as my session component on Yii 1.1.17.
My system is configured as,

1. Ubuntu 14.04 LTS
2. Apache 2.4.7
3. PHP Version 7.0.3-5+deb.sury.org~trusty+1 (php7.0-fpm)
4. redis-server 2.8.4

Trace log,

> 2016/02/23 12:49:27 [error] [php] session_regenerate_id(): Cannot regenerate session id - session is not active (/var/www/html/library/framework/yiilite.php:4615)
Stack trace:
#0 /var/www/html/library/framework/yiilite.php(4361): WebUser->changeIdentity()
#1 /var/www/html/library/framework/yiilite.php(4220): WebUser->restoreFromCookie()
#2 /var/www/html/library/framework/yiilite.php(1073): WebUser->init()
#3 /var/www/html/library/framework/yiilite.php(925): CWebApplication->getComponent()
#4 /var/www/html/protected/components/Controller.php(156): CWebApplication->__get()
#5 /var/www/html/protected/controllers/SiteController.php(10): SiteController->init()
#6 /var/www/html/library/framework/yiilite.php(1767): SiteController->init()
#7 /var/www/html/library/framework/yiilite.php(1688): CWebApplication->runController()
#8 /var/www/html/library/framework/yiilite.php(1205): CWebApplication->processRequest()
#9 /var/www/html/index.php(16): CWebApplication->run()
REQUEST_URI=/
in /var/www/html/protected/components/Controller.php (156)
in /var/www/html/protected/controllers/SiteController.php (10)
in /var/www/html/index.php (16)

**Comment by coolcflame87** [comment]
I think this issue [#2376](https://github.com/yiisoft/yii/issues/2376#issuecomment-191232856) relates to PHP 7. works fine with PHP 5.6. 

I have also reported CHttpException issue with PHP 7 too [#4002](https://github.com/yiisoft/yii/issues/4002#issuecomment-188679305)

i am using these modules 
* yii-user-management 0.8
* yii-audit-module 1.1.9

**Comment by dirx** [comment]
We run into a similar issue with CMemCache and MemCached.

Cause: PHP7 is handling return values from custom session handlers more strict than 5.*.
See: http://php.net/manual/de/migration70.incompatible.php#migration70.incompatible.other.fixes-custom-session-handler

CMemCache returns false when trying to delete a non existing value which gives fatal error "session_regenerate_id(): Session object destruction failed".

Possible solutions:

* CCachedHttpSession::destroySession should always return true
* CMemCache behavior should return true when deleting non existing values (which might be no error case). Memcached::getResultCode() will return Memcached::RES_NOTFOUND if the key does not exist.

Same may apply to CRedisCache.

**Comment by samdark** [comment]
@dirx could you work on a pull request solving it?

**Comment by dirx** [comment]
@samdark what solution do you prefer?

**Comment by samdark** [comment]
1st one with destroySession returning true. Would like comment there explaining why.

**Comment by dirx** [comment]
Here is an incomplete overview of possible return values from some Cache drivers when calling delete (internally deleteValue):

* CFileCache: false on error or key not found, true on success
* CDbCache: always true (throws Exception on error)
* CMemCache: false on error or key not found, true on success
* CRedisCache: false on 0 values deleted (= key not found), true on >= 1 values deleted
* CApcCache: false on error or key not found, true on success (only apc, not apcu checked)

Did not take a deeper look into the others.

Seems like most of them are handlng non existing keys as error case and therefore return false.
PHP before 7 just ignored this behavior.
