### ISSUE TITLE
Canada population

### ISSUE THREAD

**Issue by kungurcave** [yiisoft/yii#4022]
Is it correct at page [http://www.yiiframework.com/doc-2.0/guide-start-databases.html](http://www.yiiframework.com/doc-2.0/guide-start-databases.html)?

**Comment by SilverFire** [comment]
:laughing: no problem, fixed https://github.com/yiisoft/yii2/commit/89dc2570c2dd095feafd7f2b587159edde669afc

P.S.: This issue is related to https://github.com/yiisoft/yii2 repository

**Comment by kungurcave** [comment]
And image, please

**Comment by SilverFire** [comment]
Would you like to submit a PR? :)

**Comment by SilverFire** [comment]
https://github.com/yiisoft/yii2/commit/10aee2cfabbac0dad6ad08362bd70a72bf9b87b3

**Comment by kungurcave** [comment]
Добрый день, Дмитрий!

Куда подписаться?
До понимания шуток мой английский еще не дорос :)

С уважением, Михаил Варин

__________________

**Comment by SilverFire** [comment]
Это было предложением создать Pull Request с обновленным скриншотом

**Comment by kungurcave** [comment]
Аа, понял. Я тут впервые залез, в связи с попыткой начать изучать Ай-яй-яй.
Думал, при чем здесь Public Relations :)

С уважением, Михаил Варин

__________________

**Comment by kungurcave** [comment]
Where here button "Pull Request"?
