### ISSUE TITLE
HTMLPurifier_Lexer may not be created while purifying by CHtmlPurifier

### ISSUE THREAD

**Issue by Izumi-kun** [yiisoft/yii#4026]
After executing ([CHtmlPurifier.php:84](https://github.com/yiisoft/yii/blob/master/framework/web/widgets/CHtmlPurifier.php#L84))
`$content=$this->getPurifier()->purify($content);`
HTMLPurifier creates a lexer
`$lexer = HTMLPurifier_Lexer::create($config);`
A function will check for DOM support ([HTMLPurifier.standalone.php:7488](https://github.com/yiisoft/yii/blob/master/framework/vendors/htmlpurifier/HTMLPurifier.standalone.php#L7488))
`class_exists('DOMDocument')`

So, if PHP hasn't DOM support (--disable-dom) then an Yii' autoload will be executed ([YiiBase.php:432](https://github.com/yiisoft/yii/blob/master/framework/YiiBase.php#L432))
`include($className.'.php');`

It throws exception.

Two ways:
1. Check file existence before including. Yii' bug?
2. Check class exists without autoload (`class_exists('DOMDocument', false)`). Vendor' bug?

Any thoughts?

**Comment by cebe** [comment]
> Check class exists without autoload (class_exists('DOMDocument', false)). Vendor' bug?

I would say this is the issue, if you want to check for php builtin class, autoloading must be skipped...

**Comment by SamMousa** [comment]
@Izumi-kun Could you make a PR for the commit above? Then it can be merged back into Yii core.

**Comment by samdark** [comment]
@SamMousa I can merge it myself...

**Comment by Izumi-kun** [comment]
@SamMousa I think better way is update whole HTMLPurifier to v4.9.3 when it will be done (my [PR](https://github.com/ezyang/htmlpurifier/pull/130) is already merged by @ezyang). Change directly vendor's autogenerated file is not good.

**Comment by SamMousa** [comment]
@Izumi-kun that will require testing the new version for any other compatibility issues.. I agree with the general sentiment but since Yii1 is no longer in development things are different in my opinion.

**Comment by SamMousa** [comment]
Hmm if it's already merged htan this can be closed right?

**Comment by samdark** [comment]
Update of HTMLPurifier is a security fix so we'll make another release for that. Closing for now.
