### ISSUE TITLE
Invalid path of alias on CModule::setModules() introduced 1.1.16

### ISSUE THREAD

**Issue by tonybolzan** [yiisoft/yii#4027]
If you have a submodule with same name as another module, getPathOfAlias() loads a wrong module.
Example:
I have 3 modules:

``` php
'modules' => array(
    'A',
    'B' => array(
        'modules' => array(
            'A', // This module is never loaded
        ),
    ),
),
```

[CModule::setModules()](https://github.com/yiisoft/yii/blob/master/framework/base/CModule.php#L356)
In module `B`,  when module `B->A` is loaded,  `$id` = `A` is passed to `getPathOfAlias` making Yii load first module called `A`

**Comment by samdark** [comment]
Won't be fixed.
