### ISSUE TITLE
return false in controller have no efect

### ISSUE THREAD

**Issue by tonybolzan** [yiisoft/yii#4028]
[CAction.php::runWithParams()](https://github.com/yiisoft/yii/blob/master/framework/web/actions/CAction.php#L76) never return false and [CController::invalidActionParams()](https://github.com/yiisoft/yii/blob/master/framework/web/CController.php#L308) 

CAction.php#L76

``` php
$this->run();
return true;
// Change to
return $this->run();
```

CAction.php#L109

``` php
$method->invokeArgs($object,$ps);
return true;
// Change to
return $method->invokeArgs($object,$ps);
```

**Comment by tonybolzan** [comment]
Same problem in
[CInlineAction.php::runWithParams()](https://github.com/yiisoft/yii/blob/master/framework/web/actions/CInlineAction.php#L49)
Back to `return $controller->$methodName();`

**Comment by cebe** [comment]
an action is not supposed to return anything. what makes you believe this should work?

**Comment by tonybolzan** [comment]
All functions in php return something, and "if" statement described above in runAction() line 308 presume that if you return false, the invalidActionParam() is called, this is default behavior until 1.1.16

**Comment by samdark** [comment]
Closing since changing that would be backwards incompatible.
