### ISSUE TITLE
applyLimit in CMssqlCommandBuilder.php doesn't have the same concept with CDbCommandBuilder.php

### ISSUE THREAD

**Issue by sitawit** [yiisoft/yii#4031]
From the comment of `applyLimit()` in CMssqlCommandBuilder.php
`$limit maximum number of rows, -1 to ignore limit.`

It doesn't really mean that, in the case of **0**, the function still ignore. While the same functions of other database type or its parent will ignore only **-1** while **0** still count. 

To make it consist with the rest of database type.
So I suggest applying an update to be like this.

```
public function applyLimit($sql, $limit, $offset)
    {
        $limit = $limit!==null ? (int)$limit : -1;
        $offset = $offset!==null ? (int)$offset : -1;
        if ($limit >= 0 && $offset <= 0) //just limit
            $sql = preg_replace('/^([\s(])*SELECT( DISTINCT)?(?!\s*TOP\s*\()/i',"\\1SELECT\\2 TOP $limit", $sql);
        elseif($limit >= 0 && $offset > 0)
            $sql = $this->rewriteLimitOffsetSql($sql, $limit,$offset);
        return $sql;
    }

```

What do you guys think?

**Comment by samdark** [comment]
Sure, consistency is a good thing. Would be great to have a test for it as well.
