### ISSUE TITLE
CErrorHandler handles PHP Errors unproperly on PHP 7.0.5

### ISSUE THREAD

**Issue by fernandosavio** [yiisoft/yii#4036]
When PHP raises an Error the framework (version 1.1.17) ignores YII_DEBUG value and handle the error as it would do in production (No stacktrace, etc).

I fixed this issue changing `base/CErrorHandler.php:367` file from:
`if($this->errorAction!==null)`
to:
`if($this->errorAction!==null && !YII_DEBUG)`

I hope it helps you to fix this annoying bug.

**Comment by fernandosavio** [comment]
Probabily related to issue #3939 (tagged as `docs`)

**Comment by samdark** [comment]
As @fernandosavio mentioned, it's expected behavior.

**Comment by fernandosavio** [comment]
The expected behaviour is to **not** debug a PHP Error, only PHP Exceptions in Debug Mode?

**Comment by samdark** [comment]
Yes. Well, it's handled via default app config: https://github.com/yiisoft/yii/blob/master/framework/cli/views/webapp/protected/config/main.php#L58

**Comment by fernandosavio** [comment]
This really helped me to solve my problem without changing the framework!

Thanks @samdark !

**Comment by teo1978** [comment]
And why is this nonsense behavior the default?

**Comment by samdark** [comment]
@teo1978 it's not by default. In default app config it's the same as old behavior.

**Comment by teo1978** [comment]
I'll have to test again because I'm confused.
What I'm reading here is:

>> The expected behaviour is to not debug a PHP Error, only PHP Exceptions in Debug Mode?

> Yes. 

And you point to https://github.com/yiisoft/yii/blob/master/framework/cli/views/webapp/protected/config/main.php#L58 which seems to me is doing exactly that.

I don't know whether that's new or old, but if it's _current_, I don't see how it could be considered reasonable.
