### ISSUE TITLE
CActiveRelation replaces "with"

### ISSUE THREAD

**Issue by thuey** [yiisoft/yii#4038]
I submitted this issue on the [forum](http://www.yiiframework.com/forum/index.php/topic/67450-cactiverelation-replaces-with/page__p__288015#entry288015), but I haven't heard anything and this problem keeps popping up. Here's the contents, for your convenience:

First of all, I apologize if this issue has already been addressed. I haven't been able to find it.

I have a query similar to the following:
```
Post::model()->findAll(array(
    'with' => array(
        'comment' => array(
            'scopes' => array(
                'readerScope' => array()
            ),
           'with' => array(
               'author'
            )
        )
    )
));
```

Where readerScope adds a relation. For example:
```
public function readerScope()
{
    $this->dbCriteria->mergeWith(array('with' => 'readers'));
    return $this;
}
```

The scope is more complicated than this, but it gets the basic situation across.

The problem is that 'readers' isn't being included in the query. In fact, during the findAll() process, it gets removed from the "with." After digging through the Yii source code, this happens because in buildJoinTree of CActiveFinder, it first applies the scopes:
```
$criteria=$model->getDbCriteria();
$criteria->scopes=$scopes;
$model->beforeFindInternal();
$model->applyScopes($criteria);
...
$relation->mergeWith($criteria,true);
```

So at this point, "with" contains both 'readers' and 'author'. Then, it calls $relation->mergeWith($options). $options at this point is:
```
array(
           'scopes' => array(
                'readerScope' => array()
            ),
           'with' => array(
               'author'
            )
)
```

The problem is that in CActiveRelation, mergeWith doesn't merge "with", instead it replaces the "with":
```
        public function mergeWith($criteria,$fromScope=false)
        {
                ...

                if(isset($criteria['with']))
                        $this->with=$criteria['with'];

                ...
        }
```

Since it replaces the "with", 'readers' disappears, and the "with" is back to just containing 'author'.

Why doesn't CActiveRelation actually merge the "with" instead of replacing it, and is there a work-around?

**Comment by cebe** [comment]
I see the problem, thanks for the detailed request. However changing it will mean to break backwards compatibility for existing applications and Yii 1.1 is in maintenance mode, which means that only bugfixes can be made that do not break BC, sorry.

**Comment by thuey** [comment]
Do you know of a work around? We're considering overriding this function just for ourselves. Can you think of any potential negative consequences from doing that?

**Comment by cebe** [comment]
Just just have to make sure that merging "with" is always what you want. Should be fine then.
