### ISSUE TITLE
Session break when using MoltinCart and setFlash Yii

### ISSUE THREAD

**Issue by berthojoris** [yiisoft/yii#4039]
When use [Moltin Cart](https://github.com/moltin/cart) I always fails when using `Yii::app()->user->setFlash()`. Functions for adding and removing item in basket have always failed. How can I use both (set flash function on yii and add, remove function on moltin cart) ?

**Comment by tomtomsen** [comment]
It seems like a general session problem. Moltin Cart stores the Cart into the Session, as does setFlash.

Have you tried writing a simple test, like counting a number in session?

I dont think its an yii issue. Moltin Cart writes the Cart into $_SESSION['cart'], while setFlash writes it somewhere else. they couldn't affect each other.

**Comment by berthojoris** [comment]
@tomtomsen 
If you try to add cart like
`public function actionAddcart()
 {
        $cart = new Cart(new Session, new Cookie);
        $cart->insert(array(
      		'id'       => $data['id'],
      		'name'     => $data['name'],
      		'price'    => $data['price'],
      		'quantity' => 1,
    	));
        $this->redirect(array('/cart/list'));
 }`
The shopping cart will be filled and the page will be moved to list. **But** when I use `Yii::app()->user->setFlash()` and create notification like 
`public function actionAddcart()
 {
        $cart = new Cart(new Session, new Cookie);
        $cart->insert(array(
      		'id'       => $data['id'],
      		'name'     => $data['name'],
      		'price'    => $data['price'],
      		'quantity' => 1,
    	));
       Yii::app()->user->setFlash('success', 'Cart updated...');
        $this->redirect(array('/cart/list'));
 }`
The page will be moved (normal) but the **basket** will not be charged anything

**Comment by tomtomsen** [comment]
Hi, i've played around with your code and Moltin Cart. 
I'm using php 5.4, yii 1.1.15, Mulin/Cart master.

my test code:
```php
	public function actionTestA() {

		$_SESSION = array();

		if (!isset($_GET['reset'])) {
	        $cart = new Cart(new Session, new Cookie);
	        $cart->insert(array(
	            'id'       => 'xxxxx',
	            'name'     => 'Product 1',
	            'price'    => 77.99,
	            'quantity' => 1,
	        ));
	    }

        // Yii::app()->user->setFlash('success', 'Cart updated...');
        $this->redirect(array('/site/testB'));
	}

	public function actionTestB() {
		$cart = new Cart(new Session, new Cookie);
		\PVD::dump($cart);
		\PVD::dump($cart->contents());
		\PVD::dump($cart->contentsArray());
	}
```

In my case the cart is always empty. it seems like the __destruct method in Moltin/Cart/Storage/Session.php sees always an empty $cart.

I had to add
```php
    public function insertUpdate(Item $item) {
        $x = parent::insertUpdate($item);
        $_SESSION['cart'] = serialize(static::$cart);

        return $x;
    }
```
in Moltin/Cart/Storage/Session.php to make it work.

despite that, i still dont think its an yii issue.

**Comment by berthojoris** [comment]
@tomtomsen 
Thanks....Maybe If these solutions solve this problem I sure could use this way. But if there is no other way than to edit a file into the core of this library?

**Comment by tomtomsen** [comment]
you could write a class which extends Session. Like:
```php
class MySession extends \Moltin\Cart\Session
{
   public function insertUpdate(..) {..}
}
```

and then use it like ```new Cart(new MySesssion(), ..)```

that way you wouldn't modify the core files

**Comment by samdark** [comment]
Closing since it doesn't look like framework issue.

**Comment by berthojoris** [comment]
@tomtomsen 
Hai...New case when I add 
```
public function insertUpdate(Item $item) {
        $x = parent::insertUpdate($item);
        $_SESSION['cart'] = serialize(static::$cart);
        return $x;
}
```

Cart can't add multiple item in basket. Earlier if we not changed this Session class, and we add item to the basket with the same item code,  application will sum total of the items with the same item code. But if we change the class, then it can not calculate total which same item code in cart.

Can you help me @tomtomsen ?

**Comment by tomtomsen** [comment]
Ill answer you directly via email.
