### ISSUE TITLE
Assigning CDbCriteria::condition only as string. Why? 

### ISSUE THREAD

**Issue by andreymeretsky** [yiisoft/yii#4040]
There is a cool implementation of assigning condition as array in **CDbCommand**. 
Why **CDbCriteria** doesn't have the same? You may only  to copy the **processConditions** to **CDbCriteria**  to achieve the power of nesting conditions :muscle: 
Or is there another way to build nesting conditions and then assign them to CDbCriteria::condition ?

**Comment by samdark** [comment]
Which cool implementation are you referring to?

**Comment by rob006** [comment]
@samdark https://github.com/yiisoft/yii/blob/master/framework/db/CDbCommand.php#L1511

@andreymeretsky try:

```php
$criteria->condition = $command->where($nested_conditions_array)->getWhere();
```

**Comment by andreymeretsky** [comment]
@rob006 Thanks a lot! 
So now i can use  CDbCriteria nested conditions either in CDbCommandBuilder or in ActiveRecord.
