### ISSUE TITLE
while display session flash message crashing my design in yii2

### ISSUE THREAD

**Issue by nagarajanp1naga** [yiisoft/yii#4045]
Yii::$app->getSession()->setFlash('error', 'Please login');
Its showing flash message on my view by default, meanwhile crashing my design which i have bootstrap dropdown class on click of that its not showing the contents.
 
![err1](https://cloud.githubusercontent.com/assets/18677339/15494669/5f136124-21a9-11e6-917c-7a389162564f.jpg)

After getting error message, if i click cart nothing happening, even error.
![err2](https://cloud.githubusercontent.com/assets/18677339/15494670/5f137376-21a9-11e6-9fe0-01b8c46c1fa8.jpg)

**Comment by cebe** [comment]
this is not a problem with yii but an issue in your layout, you need to integrate the flash messages better.
