### ISSUE TITLE
Regression in 1.1.17 CUrlManager

### ISSUE THREAD

**Issue by eirikhm** [yiisoft/yii#4051]
Issue #3103 introduced a regression that breaks certain routes (optional groups). Not sure if this was supported by design, but it breaks our apps.

There are no tests for these scenarios in CUrlManagerTest. See referenced commit for updated tests.

The issue was introduced with 132ad24fc53cfbb24c25c00ebd97e15c09155915, where the $this->parsingOnly condition leads to a regex that mangles the route.

**Comment by lierdakil** [comment]
I don't suppose you were using this for url creation? From what I can remember, `createUrl` shouldn't work correctly with rules you show. If so, make those rules `parsingOnly`, which allows full-blown regex (not only in parameters) by design.

**Comment by samdark** [comment]
It was intentional fix. We've never officially supported regex outside parameters.
