### ISSUE TITLE
Comand builder not return correct results when use HAVING COUNT in sql

### ISSUE THREAD

**Issue by andreipasat** [yiisoft/yii#4054]
I generate a sql query using command builder which looks like that :

``` sql
SELECT `p`.*, `p`.`id` AS `p_id`, `c`.`c_name`, `c`.`id` AS `c_id`, `sc`.`sc_name`, `cl`.`cl_url`, `cl`.`cl_company_name`, `cl`.`cl_name`, `cl`.`cl_surname` 
FROM `property` `p` 
JOIN `categories` `c` ON p.p_category_id = c.id 
JOIN `sub_categories` `sc` ON p.p_sub_category_id = sc.id 
JOIN `clients` `cl` ON p.p_client_id = cl.id 
JOIN `property_kitchen_options` `pko` ON p.id = pko.pko_property_id 
WHERE p_status = "active" AND p.p_is_sell = 0 AND cl.cl_not_show_objects = 0 AND p.p_type = 'buy' AND p.p_category_id = 3 
AND pko.pko_kitchen_option_id IN(10,5) 
GROUP BY `p_id` 
HAVING COUNT(pko.pko_property_id) = 2 
ORDER BY `p_show_price` DESC, `p_price` ASC, `p`.`p_add_date` DESC LIMIT 5
```

Key tables here are property and property_kitchen_options. In property_kitchen_options table it's saved ONE to MANY relation. One pko_property_id can have many pko_kitchen_option_id.

When I run this sql in phpmyadmin i get right results but when i try to get results in code i get empty array or wrong results.

``` php
$results  = $command->queryAll();
```

I tryed to use queryRow(),queryColumn() query() and the same problem.

If I remove HAVING COUNT(pko.pko_property_id) = 2 from sql all works fine.

Anyone have ideas how to fix this problem ?

Yii version - 1.1.17
PHP version - 5.5.12
Operating system    - windows 8

**Comment by cebe** [comment]
can you show the yii code you used to run the query?

**Comment by andreipasat** [comment]
I found that problem is not in Yii but in PDO that YII use for db conection. I tryed to use clean PDO and the same result but if I use msqli works fine. If there is a method for switch from PDO to msqli will be helpful for me.

**Comment by cebe** [comment]
can you show the PDO code that causes the problem? it would be much easier to understand the problem

**Comment by andreipasat** [comment]
$command->select('p.*, p.id as p_id, c.c_name, c.id as c_id, sc.sc_name,cl.cl_url,cl.cl_company_name,cl.cl_name,cl.cl_surname '.$distance);
$command->from(Property::model()->tableName()." p");
$command->join(Categories::model()->tableName().' c', 'p.p_category_id = c.id');
        $commandCount->join(Categories::model()->tableName().' c', 'p.p_category_id = c.id');
        $command->join(SubCategories::model()->tableName().' sc', 'p.p_sub_category_id = sc.id');
        $commandCount->join(SubCategories::model()->tableName().' sc', 'p.p_sub_category_id = sc.id');
        $command->join(Clients::model()->tableName().' cl', 'p.p_client_id = cl.id');
        $commandCount->join(Clients::model()->tableName().' cl', 'p.p_client_id = cl.id');

        $having = '';
			if (!empty($model->kitchen)) {
				$explode = explode(',',$model->kitchen);
				$command->join(PropertyKitchenOptions::model()->tableName() . ' pko', 'p.id = pko.pko_property_id');
				$commandCount->join(PropertyKitchenOptions::model()->tableName() . ' pko', 'p.id = pko.pko_property_id');

				$conditions .= " AND pko.pko_kitchen_option_id IN(:kitchen)";
				$params[':kitchen'] = $model->kitchen;
				$having .= " COUNT(pko.pko_property_id) = ". count($explode). " AND";
			}

                $command->where($conditions,$params);
		if (!empty($having)) {
			$having = substr($having,0,-3);
			$command->having($having);			
			$command->group('p_id');
		}
               $results = $command->queryAll(); // return empty array
//

**Comment by georaldcamposano** [comment]
Your code is a bit confusing. Where do $commandCount, $having and $conditions come from? Why is there a leading " AND" in your $having variable that is trimmed out? Also, does the final query executed match what you are expecting?

**Comment by georaldc** [comment]
That block of code is a bit confusing. Where do $commandCount, $having and $conditions come from? Why is there a leading " AND" in your $having variable that is trimmed out? Also, does the final query executed match what you are expecting?
