### ISSUE TITLE
LinkSorter bug 

### ISSUE THREAD

**Issue by ITfighter** [yiisoft/yii#4060]
When i set label for attribute, i see exception 
![bug](https://cloud.githubusercontent.com/assets/14202900/16370568/7e51acca-3c49-11e6-8348-3692b9208af4.png)

 Code:
 <?= ListView::widget([
                        'dataProvider' => $dataProvider,
                        'itemView' => 'market_place_item',
                        'layout' => "{sorter}\n{summary}\n{items}\n{pager}", // Add sorter to layout because it's turned off by default
                        'sorter' => [
                            'linkOptions' => [
                            ],
                            'attributes' => [
                                'service_type'=>
                                    'label' => 'Test'
                                ],
                               // 'seller_download_speed',
                            ]
                        ],]
                ); ?>

but when i remove label option, all is good. Please help me, thank )

**Comment by tomtomsen** [comment]
from your screenshot. it seems to be a yii2 issue. you have posted it as yii1 issue. please post it https://github.com/yiisoft/yii2/issues there

**Comment by ITfighter** [comment]
ok, thank for your feedback

2016-06-27 10:20 GMT+03:00 tom tomsen <notifications@github.com>:

> from your screenshot. it seems to be a yii2 issue. you have posted it as
> yii1 issue. please post it https://github.com/yiisoft/yii2/issues there
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/yiisoft/yii/issues/4060#issuecomment-228671000>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/ANi4FLJLErMjW2bSFjaxgSxwGSJ4PnWkks5qP3nUgaJpZM4I-ytO>
> .
>



-- 
Alexander Khivrych
Email: *alexandr.khivrich@gmail.com <alexandr.khivrich@gmail.com>*
Linkedin: https://www.linkedin.com/in/alexanderkhivrych
Skype: alexander.khivrych
Phone:(093) 283-32-06
