### ISSUE TITLE
CGridView AJAX update also reloads filters (removing JS binding)

### ISSUE THREAD

**Issue by BelegUS** [yiisoft/yii#4068]
Scenario:
- There is a `CGridView` with a column
 - That column has a filter which uses a widget (eg. `select2` from YiiBooster, any fancy datepicker etc.)
- When grid is updated via AJAX, it seems filters are also reloaded (rebuilt in DOM) 
- Because of that those custom filters are broken (as their bindings are lost)

Why during grid update grid filters are also rebuilt in DOM? Is it necessary? If yes, is there a viable workaround for that kind of problem?

**Comment by cebe** [comment]
you can add bindings to a parent element that does not get replaced using the selector option on jquerys on() method: https://api.jquery.com/on/

**Comment by BelegUS** [comment]
How am I supposed to do that when my filter is a widget, and all the JS/rendering logic is on either Yii's or YiiBooster side? I don't want to put a hack there.

I disagree with Your "it's not a bug, it's a feature" attitude. How adding separate JS codes to fix framework flaws is a "good practice" in any way?

**Comment by cebe** [comment]
I have no idea what YiiBooster is but if the YiiBooster Widget registers the Javascript here, that would be the place to change it.

The whole table has to be reloaded because header links will change.
