### ISSUE TITLE
[DOCS] wrong link in CDbCommand docs

### ISSUE THREAD

**Issue by teo1978** [yiisoft/yii#4070]
http://www.yiiframework.com/doc/api/1.1/CDbCommand#setSelect-detail

> Please refer to **select()** for details on how to specify this parameter.

The link doesn't link to `select()` but to the `select` property, which is most probably where you come from in the first place if you are looking at `setSelect()`.

**Comment by cebe** [comment]
known problem in the documentation generator of the old website. will be fixed on the new website soon.
