### ISSUE TITLE
Compare with partial match and integers does not work in postgres

### ISSUE THREAD

**Issue by olleharstedt** [yiisoft/yii#4071]
Seems like postgres does not type cast integer to string. So

    $criteria->compare('id', $someid, true);

will not work.

Known problem?

Error:

> No operator matches the given name and argument type(s). You might need to add explicit type casts.. The SQL statement executed was: SELECT COUNT(*) FROM "sometable" "t" WHERE tid LIKE :ycp0

**Comment by cebe** [comment]
how do you expect a partial match on an integer to work? The result of  `id LIKE 123` seems quite undefined to me. if you want to use the number as a string, you should cast it first.

**Comment by olleharstedt** [comment]
No idea. It happened to work on MySQL. Would be nice if behvaiour was consistent among database engines. So maybe throw exception instead if Yii knows it's an integer or number?

**Comment by cebe** [comment]
there is a reason why different DBMS exist. Postgres is more strict about types than MySQL.

**Comment by olleharstedt** [comment]
Yes, and some projects have to adapt to several at once. It's not always easy to test on all database systems. It wouldn't hurt if the framework gave you a helping hand in this matter.

**Comment by cebe** [comment]
in this specific case there is nothing that can be done from framework side as we do not know the column type when generating the WHERE condition.

**Comment by olleharstedt** [comment]
Ah, OK. In that case, thank you for your feedback. Have a nice day!
