### ISSUE TITLE
Disable Yii Validation Error Message on focus / blur - Yii1

### ISSUE THREAD

**Issue by VAMEHTA** [yiisoft/yii#4073]
Hello i have a issue with Login jquery modal box..  i have used login form of CActive and below the form i have a link of signup. after opening the modal of login box , without any interaction with input field i am clicking on the signup link, and its showing the validation of email address.
my validation are also working with ajax so i have used the enableClientValidation=>true  so by making it false its submits the form without validation on client side.. 

![login_validation_issues](https://cloud.githubusercontent.com/assets/1196222/17075932/e8c6318e-50c1-11e6-9071-a579436e3bf8.jpg)

**Comment by karmrajzala** [comment]
@VAMEHTA : Following two thinks also set to false -  `'validateOnBlur' => false, 'validateOnChange'=> false,`.

And set true validationOnSubmit - `'validateOnSubmit' => true`

**Comment by VAMEHTA** [comment]
Thanks for the Help.. its working now..  :)
