### ISSUE TITLE
Package aviability checking do not working in 1.1.17

### ISSUE THREAD

**Issue by sokolnikov911** [yiisoft/yii#4075]
This problem was found after upgrading to 1.1.17 vesion.

[Documentation sais:](http://www.yiiframework.com/doc/api/1.1/CClientScript#packages-detail): _When calling registerPackage to register a script package, this property will be checked first followed by corePackages. If a package is found, it will be registered for rendering later on._

But when we try to register unavailable package "package_name"
`Yii::app()->getClientScript()->registerPackage('package_name');`

we got error:

> CException
> There is no CClientScript package: package_name

My temporary solution: 

```
        if (isset(Yii::app()->getClientScript()->packages['package_name'])) {
            Yii::app()->getClientScript()->registerPackage('package_name');
        }
```

**Comment by cebe** [comment]
why do you expect registering an unexisting package to work?

**Comment by sokolnikov911** [comment]
I do not expect registering, I expecting package checking without errors if packacge do not registered, as it is subscribed in documentation.

**Comment by cebe** [comment]
this behavior was introduced by #3391 and #3393. Exception is thrown in debug mode, a warning is logged in production mode.

**Comment by cebe** [comment]
we could introduce a method that allows checking whether a package exists.

**Comment by sokolnikov911** [comment]
Yes, maybe some protected method for checking. Something like `hasPackage('package_name')`. And add explanation in [documentation](http://www.yiiframework.com/doc/api/1.1/CClientScript#packages-detail) about Exceptions if package not available.

**Comment by SamMousa** [comment]
Since no development on yii 1 is going on, I suggest to update the documentation instead.

@sokolnikov911 A workaround for you is to just catch the exception.
