### ISSUE TITLE
CMarkdownParser and cyrillic content

### ISSUE THREAD

**Issue by olegpro** [yiisoft/yii#4083]
$content:

~~~
[php]

$info = array();

function oGetMessage($key, $fields) {
    $messages = array(
        'EVENT_TYPE_UPDATE' => 'Тип почтового события #EVENT_NAME# [#ID#] успешно обновлён',
        'EVENT_TYPE_UPDATE_ERROR' => 'Ошибка обновления типа почтового события #EVENT_NAME# [#ID#]',
        'EVENT_TYPE_ADD' => 'Тип почтового события #EVENT_NAME# [#ID#] успешно добавлен',
        'EVENT_TYPE_ADD_ERROR' => 'Ошибка добавления типа почтового события #EVENT_NAME#',
        'EVENT_MESSAGE_UPDATE' => 'Почтовый шаблон с типом #EVENT_NAME# [#ID#] и темой «#SUBJECT#» успешно обновлён',
        'EVENT_MESSAGE_UPDATE_ERROR' => 'Ошибка обновления почтового шаблона с типом #EVENT_NAME# [#ID#] и темой «#SUBJECT#». #ERROR#',
        'EVENT_MESSAGE_ADD' => 'Почтовый шаблон с типом #EVENT_NAME# [#ID#] и темой «#SUBJECT#» успешно добавлен',
        'EVENT_MESSAGE_ADD_ERROR' => 'Ошибка добавления почтового шаблона с типом #EVENT_NAME# и темой «#SUBJECT#». #ERROR#',
    );
    return isset($messages[$key])
        ? str_replace(array_keys($fields), array_values($fields), $messages[$key])
        : '';
}

~~~

$parser = new CMarkdownParser();

echo $parser->safeTransform($content);

Output:

![2016-08-21_00-36-49](https://cloud.githubusercontent.com/assets/1092443/17834244/71754462-6737-11e6-8f3f-53d5e1a08a28.png)

What could it be?

Everywhere encoding utf8

**Comment by samdark** [comment]
Are you absolutely sure it's utf-8?

**Comment by olegpro** [comment]
I create a page for the test even without the data from the database.

![2016-08-21_17-55-47](https://cloud.githubusercontent.com/assets/1092443/17838243/86b40246-67c8-11e6-9460-a609d118acd9.png)

Output:

![2016-08-21_17-56-23](https://cloud.githubusercontent.com/assets/1092443/17838245/9b62d1f4-67c8-11e6-9484-b81d4cf6bd53.png)

![2016-08-21_17-57-35](https://cloud.githubusercontent.com/assets/1092443/17838251/d85dce2e-67c8-11e6-99e2-38bc3c29af98.png)

![2016-08-21_18-00-49](https://cloud.githubusercontent.com/assets/1092443/17838261/405425c8-67c9-11e6-9742-da7e6aecef6f.png)

PHP 7. change of version 5.6  does not solve.

**Comment by cebe** [comment]
unable to reproduce, added a test case: 04f9793

**Comment by olegpro** [comment]
Yes, on the other Yii project there is no such problem.

I understand that the problem in the server. Can you tell what it might be?

**Comment by samdark** [comment]
No idea. I can't reproduce it locally so can't fix it from Yii side...

**Comment by olegpro** [comment]
The problem was mbstring.func_overload = 2

Solution: set mbstring.func_overload = 0
