### ISSUE TITLE
How to point multiple domains (or subdomains) to a single module

### ISSUE THREAD

**Issue by georaldc** [yiisoft/yii#4084]
How does one achieve this where you could have multiple domains pointing to the same module? For example

http://domain1.com -> points to myCustomModule
http://domain2.com -> points to myCustomModule

I am able to easily map a single domain by prepending the following rules to the UrlManager component config

```
'http://domain1.com/<controller:\w+>/<id:\d+>' => 'myCustomModule/<controller>/view'
'http://domain1.com/<controller:\w+>/<action:\w+>/<id:\d+>' => 'myCustomModule/<controller>/<action>'
'http://domain1.com/<controller:\w+>/<action:\w+>' => 'myCustomModule/<controller>/<action>'
```

but adding any more domain rules afterwards won't work because the initial 3 ```domain1.com``` rules would satisfy those requests and create links pointing to domain1.com instead.

Sorry if this is more of an implementation question but replies in the official forum seem to come rarely.

**Comment by samdark** [comment]
Please use forum for questions: http://www.yiiframework.com/forum/

GitHub is an issue tracker.
