### ISSUE TITLE
Memory leak when database is offline

### ISSUE THREAD

**Issue by kkrzysztof** [yiisoft/yii#4089]
Yii 2.0.9
debug mode = on
PHP 5.6.25-2+deb.sury.org~xenial+1 (cli) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Advanced PHP Debugger (APD) v1.0.2-dev, , by George Schlossnagle
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

Reproduce:
1. Turn off mysql service (service mysql stop)
2. Try this code
`
    public function actionDb()
    {
        try {
            Yii::$app->db->createCommand('SELECT 1')->execute();
        } catch (\Exception $ex) {
            throw new \yii\web\HttpException(500);
        }
    }
`
3. Run action db
4. Getting:
 PHP Fatal Error – yii\base\ErrorException
Allowed memory size of 524288000 bytes exhausted (tried to allocate 32 bytes)
    1. in /var/www/p2ploan/vendor/yiisoft/yii2/log/Logger.php at line 144

144. $ts = debug_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS);

Additional info:
After turning off mysql service, phpmyadmin is receiving
SQLSTATE[HY000] [2002] No such file or directory

It's quite strange - when I'm logged on web, then turning off mysql - I'm getting correct error from Yii: 
SQLSTATE[HY000] [2002] No such file or directory

**Comment by samdark** [comment]
Please report to https://github.com/yiisoft/yii2/issues. Thanks.
