### ISSUE TITLE
Re-Build new attribute in model, but not automatically inside attribute 

### ISSUE THREAD

**Issue by berthojoris** [yiisoft/yii#4092]
When I add `new attribute` in model without relating to the table

```
public $rel_merchant_name;
public $rel_merchant_type;
```

And I add extra functionality to `afterFind()` method like

```
$this->rel_merchant_name = 'aaa';
$this->rel_merchant_type = 'bbb';
```

to determine the initial value of both these attributes.

But why when I make API to read data from a table I use AR in Yii, I do not get the value of these two additional attributes automatically when using the `findAll()`?
# 

OS : Windows
Yii Version : 1.1.17

**Comment by samdark** [comment]
It's not clear what the issue is... could you provide a way to reproduce it? Thanks!

**Comment by berthojoris** [comment]
I mean,
How do I get if I add additional attributes in the model, and when I use `findAll` function on the controller, I get also the value of these attributes has been entered as an attribute in the results from `findAll` automatically
