### ISSUE TITLE
Documentation about HAS_ONE relations is tremendously ambiguous

### ISSUE THREAD

**Issue by teo1978** [yiisoft/yii#4100]
When thinking of a `HAS_ONE` relation from `ModelA` to `ModelB`, the first thing I ask myself is:
Is it (1) like a `BELONGS_TO` relation where the instance of `ModelB` it points to may be null (i.e. a `ModelA` may or may not belong to a `ModelB`), or is it (2) a special case of a `MANY_MANY` relation where the number of `ModelB` that a `ModelA` may have is constrained to at most one?

If it was (1), it means that (i) at the schema level, it is implemented via a column in `ModelA`'s table pointing to the primary key in `ModelB`'s table, and (ii) that would be the foreign key you would have to specify when defining the relation in `relations()`. If it was (2), then it would be vice-versa.

The reference documentation at http://www.yiiframework.com/doc/api/1.1/CActiveRecord#relations-detail doesn't answer this fundamental question. And the Definitive Guide seems to give a pretty clear answer which seems to be exactly the opposite of the reality:

http://www.yiiframework.com/doc/guide/1.1/en/database.arr#declaring-relationship

> HAS_ONE: this is special case of HAS_MANY where A has at most one B

So that would definitely be (2).

However, looking at the source code:

```
class CBelongsToRelation extends CActiveRelation
{
}
class CHasOneRelation extends CActiveRelation
{
}
```

The implementation of `CHasOneRelation` seems to be identical to `CBelongsToRelation` (just dummy subclasses of `CActiveRelation`), so it seems it's case (1), unless there's some convolute magic going on at some higher level in the code.

The reference at http://www.yiiframework.com/doc/api/1.1/CActiveRecord#relations-detail needs to be much clearer, and the Definitive Guide needs to not be misleading.

**Comment by samdark** [comment]
> HAS_ONE: this is special case of HAS_MANY where A has at most one B

It's correct.

> The implementation of CHasOneRelation seems to be identical to CBelongsToRelation

It's correct as well except belongs to is the opposite direction from has one.

**Comment by teo1978** [comment]
> It's correct.

I see, after doing a quick test.

Still, the reference of `CActiveRecord::relations()` must be explicit about this.

> It's correct as well except belongs to is the opposite direction from has one.

I'm curious about how that's done, but that's outside the scope of this issue I guess.

**Comment by samdark** [comment]
Any idea what exactly should be explicit?

**Comment by teo1978** [comment]
> Any idea what exactly should be explicit?

To what table the foreign key belongs for each kind of relation. The `HAS_ONE` case is the least obvious one (unless you state that it's a special case of `HAS_MANY`, which right now one has to go to the Definitive Guide to find out), but I usually expect the docs to not consider anything obvious, so I would like to see a list of the four cases.

For a `BELONGS_TO` relation, you specify the column in this table that points to the pk of the other table; for `HAS_MANY` and `HAS_ONE` it's the other way round. This is not the suggested phrasing (I'm very bad at writing docs), it's the information that I find missing in the docs. For the MANY_MANY case it does say how it works (though comes at the end of a paragraph with partially unrelated information, and the format for specifying the keys is in an "e.g." between parenthesis as if it was not crucial)
