### ISSUE TITLE
Update HTMLPurifier for PHP 7 compatibility

### ISSUE THREAD

**Issue by marcovtwout** [yiisoft/yii#4103]
Yii 1 uses HTMLPurifier 4.6.0

HTMLPurifier 4.8.0 declares full PHP 7 compatibility: http://repo.or.cz/w/htmlpurifier.git/blob/v4.8.0:/NEWS

Could you update HTMLPurifier?

**Comment by samdark** [comment]
Done.

**Comment by marcovtwout** [comment]
Seems to work fine, thank you. Some minor changes are introduced between 4.6 and 4.8, perhaps it is nice to link to the changelog: http://repo.or.cz/w/htmlpurifier.git/blob/v4.8.0:/NEWS
