### ISSUE TITLE
Update Console.php for PHP 7 compatibility

### ISSUE THREAD

**Issue by marcovtwout** [yiisoft/yii#4104]
In PHP 7 the "/e" flag has been removed: http://php.net/manual/en/function.preg-replace.php#refsect1-function.preg-replace-changelog

I found it in this line: https://github.com/yiisoft/yii/blob/master/framework/vendors/TextHighlighter/Text/Highlighter/Renderer/Console.php#L182

```php
$this->_output = preg_replace('~^~em', '" " . str_pad($i++, $len, " ", STR_PAD_LEFT) . ": "', $this->_output);
```

This call should probably be rewritten to preg_replace_callback()?

**Comment by samdark** [comment]
Fixed. Please test it.

**Comment by marcovtwout** [comment]
That was fast. Did you change it looking at the source only?

**Comment by samdark** [comment]
Yes. Does it work as expected?

**Comment by marcovtwout** [comment]
A quick test case shows it's still working as expected (even though this renderer is not directly used in Yii)
