### ISSUE TITLE
CActiveRecord.isNewRecord property insufficiently documented.

### ISSUE THREAD

**Issue by teo1978** [yiisoft/yii#4109]
The documentation of `CActiveRecord.isNewRecord` only says:
> Returns if the current record is new.

That is the same as saying nothing. Missing information includes:
- what the semantics of a record "being new" are (e.g. created via the `new` operator and not saved to the DB, I guess)
- when the property is automatically changed

For example, one thing that I wanted to check, and expected to find here, was whether this property is automatically set to false after saving a new record via `save()`. The answer is yes, and it's documented in the `save()` and `insert()` methods, but one would expect to find it here as well.

**Comment by dynasource** [comment]
hi Teo, thanks for your feedback. 
Your statements are correct. Regarding this, can you do some suggestions to improve the guide? Perhabs even with a PR?
