### ISSUE TITLE
CTextHighlighter produces warnings on php7

### ISSUE THREAD

**Issue by Bhoft** [yiisoft/yii#4116]
Hi I have an issue with one older yii1 application, which produces problems depending on the type declarations behaviour of php7.

I have error_reporting = E_ALL

First of all with php5.x there is no problem. 
But with PHP7 there is a Problem on the Pear Text_Highlighter Class.

Sadly the Classes and the Renderer do have problems with the correct usage of strings and array's.

e.g. they try to use $this->_output in Array::acceptToken as an array when they have initially set the string value to ''.

In PHP5 this is no problem, but in PHP7 this produces warnings and depending on the error_reporting completely stops rendering.

Some extensions use this highlighter for rendering e.g. https://github.com/malyshev/yii-debug-toolbar/ 

Which then renders the error output of php inside a panel and destroys the application design (because of inline css from the error page).

A simple test for this problem which works on php5 but produce an warning with php7:

```
$sql = "SELECT * FROM YiiCache";
$textHighlighter = Yii::createComponent(array(
    'class' => 'CTextHighlighter',
    'language' => 'sql',
    'showLineNumbers' => false,
));

$highlight_sql = $textHighlighter->highlight($sql);
echo '<br> highlight: <br>';
echo $highlight_sql;
```

I knew that yii1 is OOL and that I can disable the warning with the error_reporting but maybe this can be fixed by switching to another hightlighter class which also works with php7.

**Comment by samdark** [comment]
Already fixed in master: https://github.com/yiisoft/yii2/issues/13247

**Comment by Bhoft** [comment]
I have created this issue for yii1 and not yii2 ;)

**Comment by samdark** [comment]
Wrong link. Sorry https://github.com/yiisoft/yii/commit/f8f60cdd8f2db340393fbca9a252e42f1319ebea

**Comment by Bhoft** [comment]
thanks for this fast fix ;)
