### ISSUE TITLE
CGridView :: CButtonColumn :: click try to use jQuery.live function in yii 1.1.17

### ISSUE THREAD

**Issue by asiabaa** [yiisoft/yii#4117]
CGridView :: CButtonColumn :: click try to use jQuery.live function in yii 1.1.17
While jQuery 1.9 or higher has remove jQuery.live() function.
So we need to write this code before we try to use click delegate.
`	$.fn.extend({
		live:function(){
			return this.on;
		}
	});`

**Comment by SamMousa** [comment]
I think this is not current.
https://github.com/yiisoft/yii/blob/9b14ff3e3f26512f5ade6cd9757eda0b43b81b8b/CHANGELOG#L789
