### ISSUE TITLE
Gii can break if you extend CWebUser

### ISSUE THREAD

**Issue by teo1978** [yiisoft/yii#4118]
This issue may not be specific to Gii, it's triggered by trying to use Gii but my guess is that it's a more general issue.

I have my app set to use a custom `WebUser` class that extends `CWebUser`.
Also, at the beginning of `config/main.php` I override sme default validators with some custom ones.

Here's the relevant part of `config/main.php`:
```
CValidator::$builtInValidators['required']='RequiredValidator';
CValidator::$builtInValidators['compare']='CompareValidator';
CValidator::$builtInValidators['email']='EmailValidator';
CValidator::$builtInValidators['date']='DateValidator';
CValidator::$builtInValidators['length']='StringValidator';

return array(
  'components'=>array(
    //...
    'user'=>array(
    			'allowAutoLogin'=>true,
    			'class'=>'WebUser',  // extends CWebUser
    			// 'loginUrl'=>array('/user/login'),
    ),
    //...
  ),
  //...
);
```

Now, I try to access http://example.com/gii and I get an error because one of my custom validators (triggered by a form in Gii's login view) calls a custom application component of mine which in turn accesses a property in my custom `WebUser` class, namely `Yii::app()->user->isExpo` but for some reason, the base class `CWebUser` has been instanciated rather than my custom `WebUser` one.

Here's the stack trace:
```
exception 'CException' with message 'Property "CWebUser.isExpo" is not defined.' in /path/to/public_html/yii/framework/base/CComponent.php:130
Stack trace:
#0 //path/to/public_html/yii/framework/web/auth/CWebUser.php(146): CComponent->__get('isExpo')
#1 //path/to/public_html/protected/components/I18N.php(165): CWebUser->__get('isExpo')
#2 //path/to/public_html/yii/framework/base/CComponent.php(111): I18N->getCurrentLanguage()
#3 //path/to/public_html/protected/components/I18N.php(17): CComponent->__get('currentLanguage')
#4 //path/to/public_html/protected/components/I18N.php(40): I18N->pseudoInit()
#5 //path/to/public_html/protected/components/I.php(6): I18N->t('validators.requ...', NULL, Array)
#6 //path/to/public_html/protected/components/RequiredValidator.php(5): I::t('validators.requ...')
#7 //path/to/public_html/yii/framework/validators/CValidator.php(175): RequiredValidator->__construct()
#8 //path/to/public_html/yii/framework/base/CModel.php(287): CValidator::createValidator('required', Object(LoginForm), 'password', Array)
#9 //path/to/public_html/yii/framework/base/CModel.php(260): CModel->createValidators()
#10 //path/to/public_html/yii/framework/web/helpers/CHtml.php(2435): CModel->getValidators('password')
#11 //path/to/public_html/yii/framework/web/helpers/CHtml.php(1807): CHtml::activeInputField('password', Object(LoginForm), 'password', Array)
#12 //path/to/public_html/yii/framework/web/widgets/CActiveForm.php(838): CHtml::activePasswordField(Object(LoginForm), 'password', Array)
#13 //path/to/public_html/yii/framework/gii/views/default/login.php(5): CActiveForm->passwordField(Object(LoginForm), 'password')
#14 //path/to/public_html/yii/framework/web/CBaseController.php(126): require('/path/to...')
#15 //path/to/public_html/yii/framework/web/CBaseController.php(95): CBaseController->renderInternal('/path/to...', Array, true)
#16 //path/to/public_html/yii/framework/web/CController.php(869): CBaseController->renderFile('/path/to...', Array, true)
#17 //path/to/public_html/yii/framework/web/CController.php(782): CController->renderPartial('login', Array, true)
#18 //path/to/public_html/yii/framework/gii/controllers/DefaultController.php(47): CController->render('login', Array)
#19 //path/to/public_html/yii/framework/web/actions/CInlineAction.php(49): DefaultController->actionLogin()
#20 //path/to/public_html/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#21 //path/to/public_html/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#22 //path/to/public_html/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#23 //path/to/public_html/yii/framework/web/CWebApplication.php(282): CController->run('login')
#24 //path/to/public_html/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii/default/log...')
#25 //path/to/public_html/yii/framework/base/CApplication.php(184): CWebApplication->processRequest()
#26 //path/to/public_html/index.php(27): CApplication->run()
#27 {main}
```

**Comment by teo1978** [comment]
The problem seems to be here:
https://github.com/yiisoft/yii/blob/1.1.17/framework/gii/GiiModule.php#L124

Apparently `GiiModule` does force the base class `CWebUser` to be loaded as the `user` component. I don't think any module should ever, ever do that with any component.

**Comment by samdark** [comment]
It does that to ensure that Gii has login separated from the regular users login. Else password protection would not make any sense. If you replace core validator you should make sure it works the same way in the same situation.

**Comment by teo1978** [comment]
Well you are explaining the root cause of the issue, and you might be proving it's tricky to fix, but that doesn't mean that there's not an issue.

> If you replace core validator you should make sure it works the same way in the same situation.

What do you mean "in the same situation"??
I have made sure that my validators work under the assumption that the application is running with the configuration in `config/main.php`. If that is not a safe assumption, there's something seriously wrong with the framework. If it is, then whoever breaks that assumption (in this case Gii) must take responsibility for it.

Am I supposed to design each and every component in the application with no dependency whatsoever on any feature that I introduce in my version of any other component of the application?? While I do understand that that level of isolation would be great and it's good to get as colse as possible to that, that cannot possibly be a requirement. What would be the point in being able to extend a component (such as `CWebUser`) if any public feature added to it cannot be used ANYWHERE outside the component itself because I have to assume that a module could replace it with the base version (or its own)? Yes, I know, there would still be a value in it, but it's too much of a limitation (you could only change the way a component works, but it could never introduce new features to be used by other parts of the application). And I haven't seen any such rule documented anywhere.

> It does that to ensure that Gii has login separated from the regular users login

Are you sure that is the only way to provide a separate isolated login? Couldn't it be that you took a clever shortcut (as opposed to building an ad-hoc login into the Gii module completely unrelated to the `CWebUser` component) that turns out to be not that clever, as it is incompatible with the ability to extend application components?

**Comment by nkostadinov** [comment]
@teo1978 has a point here. I faced similar issue and wasted like a couple of hours debugging the problem. The Gii module should be changed and should not force the CWebUser to the base class.

**Comment by samdark** [comment]
The rule is called Liskov substitution principle and is one of OOP fundamentals.

In the particular case you can check `if (Yii::app()->user instanceof MyWebUser) {`.

**Comment by teo1978** [comment]
No man, Liskov substitution principle has nothing to do with this.

**Comment by samdark** [comment]
Then answer is yes. You're relying on behavior and properties which are not part of CWebUser interface while Yii::app()->user is guarantees you only CWebUser interface and nothing more. Want more then check for it.

**Comment by teo1978** [comment]
Then again:

> What would be the point in being able to extend a component (such as CWebUser) if any public feature added to it cannot be used ANYWHERE outside the component itself

**Comment by teo1978** [comment]
> check for it.

That doesn't necessarily solve the problem. I can check whether `Yii::app()->user` is a `MyWebUser`, but if it isn't and I need it to be then what??
By setting `'class'=>'MyWebUser'` for the `user` component in my app configuration, I should be able to rely upon the fact that my `user` component is a `MyWebUser`.

**Comment by teo1978** [comment]
>  Couldn't it be that you took a clever shortcut (as opposed to building an ad-hoc login into the Gii module completely unrelated to the CWebUser component) that turns out to be not that clever...

Now that I think about it, the very idea of Gii being a module inside the application (meaning, in "my" application) is in itself wrong. Being a development tool, it should be completely isolated from the application. I get it, it needs to know part of the application configuration (such as access to the database and the application files path, and little more), but then again, making it part of the application so that it gets the whole config for free is a clever shortcut that turns out to be not that clever.
