### ISSUE TITLE
mcrypt deprecated in php7.1

### ISSUE THREAD

**Issue by mashhadi** [yiisoft/yii#4119]
CSecurityManager depends on mcrypt where as it is deprecated in PHP7.1 and recommendation are to use OpenSSL, which may cause existing application to stop working on newer php version.

**Comment by cebe** [comment]
In this case as also related to other issues it looks like PHP7.1 is the maximum supported version for yii 1.1. Note that Yii 1.1 is in maintenance mode for some time and no new features or bugfixes will be added in general. http://www.yiiframework.com/news/90/update-on-yii-1-1-support-and-end-of-life/

**Comment by devcommiter** [comment]
> CSecurityManager depends on mcrypt where as it is deprecated in PHP7.1 and recommendation are to use OpenSSL, which may cause existing application to stop working on newer php version.

At least in the PHP7.1 we can use mcrypt, because it's only **deprecated**, but not **removed**.
