### ISSUE TITLE
Upgrade from 1.1.6 to 1.1.17

### ISSUE THREAD

**Issue by naveenabt** [yiisoft/yii#4124]
After upgrading from 1.1.6 to 1.1.17 ,captcha is not working.
Below error we are getting.

actioncaptcha() does not exist.
framework/web/actions/CInlineAction.php(45)
framework/web/CController.php(308): CInlineAction->runWithParams(Array)
framework/web/filters/CFilterChain.php(133): CController->runAction(Object(CCaptchaAction))

Please help on this error.

**Comment by samdark** [comment]
1. Make sure action exists.
2. Make sure case is correct. Should be `actionCaptcha` with capital `C`.
3. Make sure user can access it.

**Comment by naveenabt** [comment]
same function was working in 1.1.6 but not working in 1.1.17

**Comment by naveenabt** [comment]
Below action am using in controller.
 
public function actions(){
        return array('captcha'=>array('class'=>'CCaptchaAction','backColor' => 0xFFFFFF,),);
    }

**Comment by samdark** [comment]
Can you revert framework and check if it works again? If it works, it's a good idea to use [git bisect](https://git-scm.com/book/en/v2/Git-Tools-Debugging-with-Git) to find out commit which caused the break. Since I can't reproduce it myself, I cannot find the reason why it's broken in your case.

**Comment by naveenabt** [comment]
yes i have checked with framework 1.1.6, it is working fine.

**Comment by samdark** [comment]
1.1.16 or 1.1.16?

**Comment by naveenabt** [comment]
1.1.6

**Comment by samdark** [comment]
Well, the best suggestion I have is to recommend doing git bisect.

**Comment by SamMousa** [comment]
This seems to be working just fine on 1.1.17; I get the action to run, so it's probably a misconfiguration.
