### ISSUE TITLE
Rename messages folder from `fa_ir` to `fa`

### ISSUE THREAD

**Issue by NabiKAZ** [yiisoft/yii#4127]
As you see here: https://github.com/yiisoft/yii2/pull/1939 was conducted after the debate, the Persian language of the `fa-IR` folder rename was changed to the `fa`.

What is your opinion about such a change in Yii Framework version 1 ?

**Comment by samdark** [comment]
Sounds OK to me but need to check if fallback works well (I've re-did it for Yii 2.0). Feel free to provide a pull request.

**Comment by NabiKAZ** [comment]
@hesna
@ahb360 
@samdark
@cebe

**Comment by NabiKAZ** [comment]
I'm not sure for this change, because the Yii1 is very old, and so maybe exist some code with base `fa_ir` folder in her projects.

**Comment by hesna** [comment]
@NabiKAZ I'm pretty sure there are legacy systems depending on `fa_ir`, at least I myself know multiple cases, both personal and work related. not sure what effect such change would make.
I personally think it's better to let it be, to make sure old systems continue working and also to add one more reason to encourage people use Yii2 ;)
Thanks for asking.

**Comment by cebe** [comment]
We could simply copy `fa_ir` to `fa` so both would work.

**Comment by NabiKAZ** [comment]
@hesna غیر مستقیم رسوندی که بابا بیخیال این نسخه ۱ بدردنخور بشیم :-D 👍

**Comment by NabiKAZ** [comment]
@cebe implementation is easy, but is not guarantee for compatible with many old projects !

**Comment by hesna** [comment]
@NabiKAZ بله هدفم همین بود دقیقا :)) ارزش آپدیت کردن نداره بگذریم ازش :ی

**Comment by cebe** [comment]
@NabiKAZ if we copy instead of moving it, how could it break?

**Comment by NabiKAZ** [comment]
@cebe I'm not sure this is a good idea.

**Comment by samdark** [comment]
Thought more about it, it's not a good idea to rename it.
