### ISSUE TITLE
CButtonColumn 'click' live event attached multiple times... 

### ISSUE THREAD

**Issue by kosenka** [yiisoft/yii#4134]
CButtonColumn 'click' live event attached multiple times when entire grid widget is replaced through ajax.

`	

	protected function registerClientScript()
	{
		$js=array();
		foreach($this->buttons as $id=>$button)
		{
			if(isset($button['click']))
			{
				$function=CJavaScript::encode($button['click']);
				$class=preg_replace('/\s+/','.',$button['options']['class']);
				//$js[]="jQuery(document).on('click','#{$this->grid->id} a.{$class}',$function);";

				// http://www.yiiframework.com/forum/index.php/topic/27521-cbuttoncolumn-click-live-event-attached-multiple-times-when-entire-grid-widget-is-replaced-through-ajax/page__view__findpost__p__154738
				if(true) {
					$js[]="if(typeof(_gridf)==='undefined'){_gridf={};}"
						."if(typeof(_gridf['on-{$this->grid->id}-{$class}'])!=='undefined') {jQuery(document).off('click','#{$this->grid->id} a.{$class}',_gridf['on-{$this->grid->id}-{$class}']);}"
						."_gridf['on-{$this->grid->id}-{$class}']=$function;"
						."jQuery(document).on('click','#{$this->grid->id} a.{$class}',_gridf['on-{$this->grid->id}-{$class}']);";
				} else {
					$js[]="jQuery('#{$this->grid->id} a.{$class}').live('click',$function);";
				}
			}
		}
		if($js!==array())
			Yii::app()->getClientScript()->registerScript(__CLASS__.'#'.$this->id, implode("\n",$js));
	}
`

**Comment by samdark** [comment]
Sure it does since `registerScript` is used multiple times. That's expected.
