### ISSUE TITLE
Gii Model Generator warning preventing Diff view with PHP7

### ISSUE THREAD

**Issue by apphancer** [yiisoft/yii#4135]
When using Gii's Model Generator and creating an previously generated Model, clicking on the "diff" is showing a warning which is preventing from viewing the contents of the diff in the modal window.

The warning is the following:  Methods with the same name as their class will not be constructors in a future version of PHP; Text_Diff has a deprecated constructor.

**Comment by samdark** [comment]
That's already fixed in master.
