### ISSUE TITLE
Partial match compare not working with timestamp without timezone Postgres

### ISSUE THREAD

**Issue by mindro** [yiisoft/yii#4139]
Is there any chance to make partial match work for date(timestamp without timezone)?
`$criteria->compare('"Date"',$this->Date, false);`

If partial match is true, im getting this error:
Error 500: <h1>CDbException</h1>
<p>CDbCommand failed to execute the SQL statement: SQLSTATE[42883]:
Undefined   function: 7 ERROR:  operator does not exist: timestamp without 
time zone ~~ unknown

**Comment by samdark** [comment]
No. Yii 1.1 is in security and PHP 7 compatibility fixing mode so won't be fixed.
