### ISSUE TITLE
Composer packages with "include-path" conflict with YiiBase::import  

### ISSUE THREAD

**Issue by unameisfine** [yiisoft/yii#4140]
YiiBase::import on every function call rewrite php include_path and Composer packages with "include-path" don't working.

**Comment by SamMousa** [comment]
````
	/**
	 * @var boolean whether to rely on PHP include path to autoload class files. Defaults to true.
	 * You may set this to be false if your hosting environment doesn't allow changing the PHP
	 * include path, or if you want to append additional autoloaders to the default Yii autoloader.
	 * @since 1.1.8
	 */
	public static $enableIncludePath=true;
````

Disable the PHP include path if you want to use other atuoloaders. This is not a bug.

Also, includePath in composer.json is deprecated: https://getcomposer.org/doc/04-schema.md#include-path
