### ISSUE TITLE
1.1.18 release date

### ISSUE THREAD

**Issue by marcovtwout** [yiisoft/yii#4141]
Yii 1.1.17 was released in january 2016. According to the latest official statement (http://www.yiiframework.com/news/90/update-on-yii-1-1-support-and-end-of-life/) critical bugfixes and PHP7 compatiblity support has ended in december 2016.

There are quite a few PHP7 issues that are already fixed in the latest master: (https://github.com/yiisoft/yii/blob/master/CHANGELOG, https://github.com/yiisoft/yii/issues?utf8=%E2%9C%93&q=label%3Acompatibility%3APHP7%20)
Is there a planned release date for 1.1.18?

**Comment by cebe** [comment]
we plan to make that release but we have not set a date yet. should be within the next few months.

**Comment by SamMousa** [comment]
@cebe Any reason not to release every merge? Waiting doesn't benefit anyone and there's no active development on Yii1 anyway.

**Comment by samdark** [comment]
I'll handle release soon.

**Comment by samdark** [comment]
Ah, nope. There are some regressions to deal with first.

**Comment by marcovtwout** [comment]
@samdark What kind of regressions?
(For our team we are already doing incremental releases (1.1.17.x) every few months.)

**Comment by SamMousa** [comment]
It would be nice to have a collection issue with a checklist for the regressions you want to have fixed before release. That way we can make PRs and help you close them ASAP.

**Comment by samdark** [comment]
https://github.com/yiisoft/yii/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.1.18

**Comment by tomfotherby** [comment]
> Ah, nope. There are some regressions to deal with first.

Hi @samdark - At www.peopleperhour.com we are upgrading from php 5.6 to php 7 and will use current `HEAD` (7b44abc8). We haven't found any regressions from testing on staging for a few weeks. I'm not saying there's aren't regressions, just that we don't know what they are. If you know any cases, please let us know.

**Comment by SamMousa** [comment]
@tomfotherby The link he posted above lists all the issues that need to be fixed before a release.

**Comment by tomfotherby** [comment]
Yeah, but that's never going to happen. Many are from 2014.

**Comment by SamMousa** [comment]
I agree, but from that perspective it's fine to use HEAD as well, or even fix to a specific commit.
Since there is no development other than the odd bugfix that should be just fine right?
(It's what I do after realizing fixing all those bugs would be a waste of time)

**Comment by tomfotherby** [comment]
Cool, good to hear, thanks. That's the plan. It's just the above comment that spooked me a bit:

> Ah, nope. There are some regressions to deal with first.

Do you know something I don't?

**Comment by samdark** [comment]
Nope. I've updated my projects which use 1.1 to HEAD and PHP 7.1 as well. No issues so far. I just need to deal with that list of issues and fix ones that make sense. If you have time to help, it would be much appreciated.

**Comment by SamMousa** [comment]
I can help a bit, but some of them are not really regressions just improvements that only few people need.
The real regressions I can look at, would be great to have a label for them.

**Comment by samdark** [comment]
I haven't reviewed majority of these yet so if you think something could be done later, comment there.

**Comment by samdark** [comment]
Reviewed milestone issues. Lowered the number significantly.

**Comment by samdark** [comment]
We're finally done with issues. Doing extra review...

**Comment by cebe** [comment]
http://www.yiiframework.com/news/133/yii-1-1-18-is-released/

**Comment by marcovtwout** [comment]
Just a quick check: You are keeping the project open for issues and PR's (security and php 7 compatibility only?)

If so, you could mension here (https://github.com/yiisoft/yii/issues/new) or here (https://github.com/yiisoft/yii/issues/new) that you are no longer accepting bug or feature requests.

**Comment by samdark** [comment]
Good catch. Done.

**Comment by marcovtwout** [comment]
I meant to paste this one as the second link, maybe good to change that one too: https://github.com/yiisoft/yii/blob/master/CONTRIBUTING.md

**Comment by samdark** [comment]
Added note there as well.
