### ISSUE TITLE
ambiguous error while using unique validator

### ISSUE THREAD

**Issue by sepidemahmoodi** [yiisoft/yii#4142]
Hi,
this rule is in page model rules : 
`[['code'], 'unique']`
and  `code` attribute exist in post model.

 I join two table in page::find() : 
`$query = new ActiveQuery(get_called_class());
$query->joinWith('post');
`
then ambiguous error accured on same `code` attribute.

`SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'code' in where clause is ambiguous
The SQL being executed was: SELECT EXISTS(SELECT `page`.* FROM `page` LEFT JOIN `post` ON `page`.`postId` = `post`.`id` AND ((`code`='12')))`

it seems in
`yii\validators\UniqueValidator::prepareConditions($targetAttribute, $model, $attribute)`
adding table name as prefix while preparing conditions solve this problem.

**Comment by cebe** [comment]
please report this to https://github.com/yiisoft/yii2, this tracker is for Yii 1.1.
