### ISSUE TITLE
Handling DB connection troubles

### ISSUE THREAD

**Issue by b1rdex** [yiisoft/yii#4144]
Recent days our project db is loaded too much and time to time we gave connections count overflow.
Some of this situations are handled properly and CDbExceptions are thrown, but some are not handled at all. Here is some errors from log:
```
[15-Mar-2017 09:46:42 Asia/Vladivostok] PHP Notice:  Trying to get property of non-object in /www/versions/750.3/vendor/yiisoft/yii/framework/db/ar/CActiveRecord.php on line 661
[15-Mar-2017 09:46:42 Asia/Vladivostok] PHP Fatal error:  Uncaught Error: Call to a member function getColumnNames() on null in /www/versions/750.3/vendor/yiisoft/yii/framework/db/ar/CActiveFinder.php:403
Stack trace:
#0 /www/versions/750.3/vendor/yiisoft/yii/framework/db/ar/CActiveFinder.php(47): CJoinElement->__construct(Object(CActiveFinder), Object(Purchases))
#1 /www/versions/750.3/vendor/yiisoft/yii/framework/db/ar/CActiveRecord.php(912): CActiveFinder->__construct(Object(Purchases), Array)
#2 /www/versions/750.3/vendor/yiisoft/yii/framework/db/ar/CActiveRecord.php(1609): CActiveRecord->getActiveFinder(Array)
#3 /www/versions/750.3/protected/models/Purchases.php(2180): CActiveRecord->count(Object(CDbCriteria))
#4 /www/versions/750.3/protected/components/Controller.php(286): Purchases->findVipTodayCount(Object(CDbCriteria))
#5 /www/versions/750.3/protected/components/Controller.php(123): Controller->setupVipCount()
#6 /www/versions/750.3/vendor/yiisoft/yii/framework/web/CWebApplication.php(281): Controller->init()
#7 /www/versions/750.3/vendor/yiisoft/yii/frame in /www/versions/750.3/vendor/yiisoft/yii/framework/db/ar/CActiveFinder.php on line 403
```

I think there should be some checks to not produce fatal errors.
Notice + fatal errors are always in pair in log as I see.

**Comment by samdark** [comment]
It doesn't look like connection trouble. You're calling a method on `null` so it's lacking checks for the case there's no records. Check `findVipTodayCount()`.

btw., Yii 1.1 reached its EOL: http://www.yiiframework.com/news/90/update-on-yii-1-1-support-and-end-of-life/ So there would be no further bugfixes except security ones for 1.1.

**Comment by b1rdex** [comment]
You read stacktrace wrong. Problems are at framework/db/ar/CActiveFinder.php:403 and framework/db/ar/CActiveFinder.php:403 and not in client code.

**Comment by samdark** [comment]
Probably. First of all, try code from master branch. Problem might be fixed there.

If it doesn't work, unfortunately, I can't help since that's not security issue and, as I've already pointed out, 1.1 reached EOL.
