### ISSUE TITLE
Error with migration using postgresql

### ISSUE THREAD

**Issue by rockdolfolk** [yiisoft/yii#4145]
Hi,
I have created a table with a field null by default with a migration.
Then I prepared another migration changing to not null and generates a syntax error:

    public function safeUp()
    {
        ...
        $this->alterColumn('yiibasico.usuario', 'email', SCHEMA::TYPE_STRING . ' NOT NULL');
    }

When I execute the migration:

Apply the above migration? (yes|no) [no]:yes
*** applying m170318_223054_cambio_nombre
    ...
    > alter column email in table yiibasico.usuario to string NOT NULL ...Exception: SQLSTATE[42601]: Syntax error: 7 ERROR:  error de sintaxis en o cerca de «NOT»
LINE 1: ...o"."usuario" ALTER COLUMN "email" TYPE varchar(255) NOT NULL

The syntax for postgres is

ALTER TABLE yiibasico.usuario
    ALTER COLUMN email **SET** NOT NULL

Please correct this little bug.

Thanks.

Rodolfo.

**Comment by samdark** [comment]
Well, you need to use correct syntax.

**Comment by rockdolfolk** [comment]
I doesn't work.
I've made a lot of tests and then didn't work.


   $this->alterColumn('yiibasico.usuario', 'email', 'string  NOT NULL');

    $this->alterColumn('yiibasico.usuario', 'email', SCHEMA::TYPE_STRING . ' NOT NULL');

    $this->alterColumn('yiibasico.usuario', 'email', SCHEMA::TYPE_STRING . ' SET NOT NULL');


    $this->alterColumn('yiibasico.usuario', 'email', ' SET NOT NULL');

should be standar for any dabase...

Thanks

**Comment by samdark** [comment]
You are passing strings around and these are not correct. Try using builder:

```php
$this->alterColumn('yiibasico.usuario', 'email', $this->string()->notNull());
```
