### ISSUE TITLE
Regarding a issue in yii2-social widget

### ISSUE THREAD

**Issue by GowthamGowty** [yiisoft/yii#4147]
Hi Team,

Recently i have used the Yii2-social widget for the google signin, i have found that the google platform.js is included in the file GooglePlugin.php file. I have noticed that the js file is registered without the random string appended at the end. I suggest to append the random string in that js file  as i did below
$view->registerJsFile('https://apis.google.com/js/platform.js?'.mt_rand(), [
            'position' => View::POS_HEAD, 
            'async' => true, 
            'defer' => true
        ]);

If we didnt include the random string then the js file will not get loaded for the second time on the ajax request.

Scenario to use this random string purpose:
If we are going to have ajax popup login form with the google signin option then it will work only for the first time, for the next time without page load it wont work, it will not generate the google signin button. To Avoid that problem we need to include the random number after the js file name.

Thanks,

**Comment by SamMousa** [comment]
@GowthamGowty your bug report is not for this project..

**Comment by GowthamGowty** [comment]
May i know where i need to inform yii team

**Comment by SamMousa** [comment]
http://bfy.tw/Ao0r

**Comment by GowthamGowty** [comment]
@SamMousa  Thanks

**Comment by SamMousa** [comment]
@GowthamGowty You can close this issue.
