### ISSUE TITLE
How to manage/store a string generated with securityManager->encrypt

### ISSUE THREAD

**Issue by atrandafir** [yiisoft/yii#4150]
We have a web based email client that works similar to all other web/desktop email clients.

You can manage your email accounts, by adding new email account or editing it from a form.

What we wanted to do is to save the email password someway encrypted. 

So basically the user enters in the form the first time the plain password and before saving to the database we're encrypting it using securityManager->encrypt.

Then when we need to send email with that account, before sending it, we decrypt the password so we can login to the mail server.

Everything works, adding and editing, but from time to time something weird happens like the encrypted string gets corrupted.

I don't know when it happens, when saving to db, or retrieveing it, or submitting the form with the encrypted password.

![form with encrypted password](https://cloud.githubusercontent.com/assets/3097251/24506493/fbe9ae4c-155d-11e7-97b2-75a1cbc3ae24.png)

I'm using 1.1.16. 

The password is stored to a MySQL table:

Field: password
Type: varchar(255)
Charset: utf8_general_ci

The project files are utf8.

I haven't tried to reproduce this in a new separate project to see if it happens.. so maybe there could be something "wrong" with our app but since the encrypted string generates such rare chars and the corrupted error happens randomly.. I was curious to know if there's a known way to handle strings generated with securityManager->encrypt.

**Comment by samdark** [comment]
There's nothing special about these strings.

**Comment by samdark** [comment]
Closing since no info on how to reproduce the issue was provided.

**Comment by atrandafir** [comment]
Great, thanks I just wanted to know that, if you say there's nothing special about them I'll leave it as it is and if in the future I find out something more specific I'll let you know.
