### ISSUE TITLE
Deprection warning on PHP 7

### ISSUE THREAD

**Issue by realtebo** [yiisoft/yii#4151]
this happens when creating a new model using Gii:

> Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; Text_Diff has a deprecated constructor in /yii/framework/gii/components/Pear/Text/Diff.php on line 20

For precision, it will be shown in the modal of diff beetween actual version of a model class and the already existing one.

I'm using 

    PHP 7.0.15-0ubuntu0.16.04.4 (cli) ( NTS )

**Comment by samdark** [comment]
Have you tried code from master branch?
