### ISSUE TITLE
PHP 7.1.3 unserialize issue

### ISSUE THREAD

**Issue by twisted1919** [yiisoft/yii#4152]
Hi, 

Sorry if this has been discussed before, but any way we can fix this? I am getting:   
`Notice: unserialize(): Unexpected end of serialized data in /var/www/vhosts/domain/httpdocs/apps/common/framework/caching/CCache.php on line 108`  

Seems to be related to https://bugs.php.net/bug.php?id=70187 but on php 7.0 i don't get this issue.

Thank you.

**Comment by twisted1919** [comment]
Sorry, i see this has been discussed already. Closing.

**Comment by kamal3294** [comment]
100 % its working fine :+1: 
[Notice: unserialize(): Unexpected end of serialized data in /var/www/html/site.com/pub/ub-tool/yii/caching/CCache.php on line 108](https://www.youtube.com/watch?v=iaU_ik_Qo7Y)
And Open CCache.php on line no 108.
see below code : 
**[$value=unserialize($value);](https://www.youtube.com/watch?v=iaU_ik_Qo7Y)**
Change to :
[**$value=unserialize(base64_decode($value));**](https://www.youtube.com/watch?v=iaU_ik_Qo7Y)
Its working fine 
And see more please visit video Link : https://www.youtube.com/watch?v=iaU_ik_Qo7Y

**Comment by bravist** [comment]
Thanks @kamal7606 , it works now
