### ISSUE TITLE
You broke the minimum version compatibility promise!

### ISSUE THREAD

**Issue by twisted1919** [yiisoft/yii#4162]
From the description: 
> The minimum requirement by Yii is that your Web server supports PHP 5.1.0 or above. Yii has been tested with Apache HTTP server on Windows and Linux operating systems.

But the code... 
https://github.com/yiisoft/yii/blob/master/framework/vendors/zend-escaper/Escaper.php#L101

**Comment by samdark** [comment]
Yeah, seems to be 5.3... Is it a problem for you?

**Comment by twisted1919** [comment]
@samdark - yeah, some of my customer for God knows what reason, are still on php 5.2 and this is also how i found out about the issue, they started to complain after an upgrade.
For now i have changed the file on my end to just use `Exception` class and that works just fine as far as i can see. 

Thing is that the framework should stay to it's promise and be compatible with the php version it advertises.

Thank you.

**Comment by samdark** [comment]
Agree. Could you pull request a fix w/ changelog? I'm travelling and can't really reach the keyboard.

**Comment by twisted1919** [comment]
@samdark - Sure, i'll do this on Monday ;)

**Comment by cebe** [comment]
Fixed, thanks for reporting!
