### ISSUE TITLE
HTML encoding issues on 1.1.19

### ISSUE THREAD

**Issue by nikolasr200** [yiisoft/yii#4163]
On version 1.1.19 when inserting HTML code on adderror (model addError) the HTML doesn't get decoded, but it is displayed as raw HTML when the error occurs.

For example in a model 
`$this->addError('attribute_name', 'The field is required<br>Please fill in the text');`

The result is raw HTML 
`The field is required<br>Please fill in the text`

Instead of
The field is required
Please fill in the text

**Comment by samdark** [comment]
https://github.com/yiisoft/yii/blob/master/UPGRADE#L29

**Comment by nikolasr200** [comment]
so i guess the recommended workaround on this is to go with sth like this, on each view?

```
// some code
$form = $this->beginWidget('CActiveForm', array(
                 'id' => 'old-ebill-user-form',)
);
// some code
echo CHtml::decode($form->error($model, 'username'));
// some code
$this->endWidget();
```
