### ISSUE TITLE
PHP 7.2: count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by cebe** [yiisoft/yii#4167]
### What steps will reproduce the problem?

A lot of tests on PHP 7.2 are failing with

```
count(): Parameter must be an array or an object that implements Countable
```

`count()` throws a warning since PHP 7.2 in case a scalar or non-countable object is passed. We rely on this behavior in many places so code needs to be adjusted.

Need to check how many places are affected and whether its easy to fix. If its hard to fix in a BC way, PHP 7.1 may be the last version that Yii 1.1 runs on.

### More info

- https://wiki.php.net/rfc/counting_non_countables
- http://php.net/manual/en/function.count.php

**Comment by snowleopard24** [comment]
@cebe Have you opened an issue against this on https://bugs.php.net/ ?
I'm getting the same error as well

**Comment by cebe** [comment]
this is not a bug, but a feature ;) PHP changed count() behavior in the following RFC: https://wiki.php.net/rfc/counting_non_countables

**Comment by pajon** [comment]
How it looks like with upgrade to PHP 7.2 ?

**Comment by samdark** [comment]
Not a good idea for now.

**Comment by b1rdex** [comment]
Here are 7.2 comatability fixes:
https://github.com/b1rdex/yii/commit/713a80e32654e720fbd22b77594c3328a8994dd9
https://github.com/b1rdex/yii/commit/8a8ac14ab925df683ecd481c986662acf885c96c
https://github.com/b1rdex/yii/commit/972c3b62d17f7ba1a122c05a867aa0f73d1f89ca

**Comment by pajon** [comment]
Hello, there are some issues.

- Function  **session_status** is supported from 5.4, so there is backwards incompatibility.(must be compatible from 5.2) 

- Function count return 0 if null parameter is used before 7.2 and your patches don't fix this case. 

There is maybe better solution to create new **count** (**_count** for example) function which have behaviour like before 7.2.

**Comment by b1rdex** [comment]
@pajon I have no need to support 5.4, so you are free to add `function_exists` check.
As per `count(null)` — well, that sucks. Glad that 7.2 removed this. I don't see possibility for `null` to be presented in code I've provided fixes for (based on `string|array` docblock on `primaryKey` field).

**Comment by manumonviru** [comment]
Hi Is there any option slove this pblm 
 message: sizeof(): parameter must be an array or an object that implements countable
Php version :- 7.2
Laravel version  5.4.30

Please help me with the details

**Comment by pajon** [comment]
@manumonviru **sizeof** is just alias to **count** function.

**Comment by rajuginne** [comment]
i have same issue with wordpress

**Comment by samdark** [comment]
Partly fixed.

**Comment by sokolnikov911** [comment]
Can you put this fix in release?

**Comment by samdark** [comment]
Hope having it soon. We have 7.2 tests now and these are passing.

**Comment by AbuMuhammad** [comment]
There is another one on framework/gii/generators/model/ModelCode.php:371
Fixed it with
```
...
$pk=$table->primaryKey;
$count=is_array($pk) ? count($pk) : 1;
return ($count === 2 // we want 2 columns
...
```

**Comment by samdark** [comment]
https://github.com/yiisoft/yii/commit/9e5e427c13af7c67bb5d4ca77516a32b7c7a98b0

**Comment by seregagl** [comment]
There is another one on framework/web/CController.php:928

```
public function renderDynamic($callback)
{
        $n=count($this->_dynamicOutput);
        echo "<###dynamic-$n###>";
...
```

**Comment by samdark** [comment]
@seregagl would you like to fix it and do a pull request? If not, please create a separate issue. Will be lost here in the closed one...

**Comment by aztechowski** [comment]
There is another issue in CActiveFinder in queryOneMany
in line if(count($fks)!==count($pkTable->primaryKey))
If primaryKey is string the count() doesn't work.
It can be easy fixed with:
`if(count($fks)!==count(array($pkTable->primaryKey)))`

**Comment by samdark** [comment]
Would you like to send a pull request fixing it?

**Comment by aztechowski** [comment]
I've checked trunk version and it looks it is already fixed with https://github.com/yiisoft/yii/commit/05d2c67555e8b67ef54906148775997acf018840. The latest version 1.1.19 is not.
What are plans regarding 7.2 compatibility? When the next release that is 7.2 compatible will be released?

**Comment by bytebrain** [comment]
I've fixed it by setting memory_limit to 256M in my php.ini. ...it does the job for now...

**Comment by jjdunn** [comment]
Please forgive me if this is not the correct issue on which to report problems, but there's at least one place that got missed.  Just upgraded to Yii 1.1.20 today and PHP 7.2.11.

in /framework/db/schema/CDbCriteria.php
`public function addInCondition($column,$values,$operator='AND')
	{
		if(($n=count($values))<1)
			$condition='0=1'; // 0=1 is used because in MSSQL value alone can't be used in WHERE`

suggest changing this to :
`if ((empty($values))`

**Comment by rob006** [comment]
`$values` should be array according to PHPDoc - if you get this error it means that you're calling these methods in a wrong way.

**Comment by jjdunn** [comment]
> `$values` should be array according to PHPDoc - if you get this error it means that you're calling these methods in a wrong way.

our application has been using Yii since 2009 and it's worked fine - the methods mentioned in the previous comment have been quite robust at handling various arguments.  Sometimes it gets called with empty value, or single (non-array) value; or array with 1 element, or array with multiple elements.  The first three cases break now in PHP 7.2

The patches in my previous comment are to make the framework more robust and consistent with previous behavior, so the application code does not have to change.

Note that we're running our Dev/Test environment with error_reporting = E_ALL, so the warnings emitted by 7.2 are actually reported as errors.  I like this so we can find/fix them now...

**Comment by cebe** [comment]
If you pass a scalar value as `$values` the `count()` will return 1, which gets you into the `elseif($n===1)` branch. There you have `$value = reset($values)`, which would fail because `reset()` expects an array.

So I do not see how your code runs fine in other PHP versions < 7.2: https://3v4l.org/nHrpA

**Comment by jjdunn** [comment]
> 
> 
> If you pass a scalar value as `$values` the `count()` will return 1, which gets you into the `elseif($n===1)` branch. There you have `$value = reset($values)`, which would fail because `reset()` expects an array.
> 
> So I do not see how your code runs fine in other PHP versions < 7.2: https://3v4l.org/nHrpA

Thank you @cebe and @rob006 for this feedback.  

I have taken this opportunity to audit all our application code that uses CDbCriteria::addInCondition() and ::addNotInCondition().  All instances *except one* pass an array as the $value parameter.  The one case where a non-array is (sometimes) passed, it's always empty.  I will fix the application code in this one case.
