### ISSUE TITLE
when configure multiple masters with multiple slaves, the connections object db was null

### ISSUE THREAD

**Issue by enze** [yiisoft/yii#4169]
version Yii 2.0.12

Scene: multiple masters with multiple slaves,  split db and split table

When a database is switched in the list, a connection is lost. That is, $this->_masters is null and configured as one master with multiple slaves. There is no problem.

main.php

```
'section' => [
			'class' => 'yii\db\Connection',
			'tablePrefix' => 'tbl_',
			'masterConfig' => [
				'username' => 'username',
				'password' => 'password',
				'attributes' => [
					PDO::ATTR_TIMEOUT => 10,
				],
			],
			'masters' => [
				['dsn' => 'mysql:host=host;dbname=db_section_%;charset=utf8;'],
				['dsn' => 'mysql:host=host;dbname=db_section_%;charset=utf8;'],
			],
			'slaveConfig' => [
				'username' => 'username',
				'password' => 'password',
				'attributes' => [
					PDO::ATTR_TIMEOUT => 10,
				],
			],
			'slaves' => [
				['dsn' => 'mysql:host=host;dbname=db_section_%;charset=utf8;'],
				['dsn' => 'mysql:host=host;dbname=db_section_%;charset=utf8;'],
			],
			
		],
```
model ar

	public static function getDb() {
		$db = md5(self::$sn . self::$dataId);
		$dbNo = $db[0];

		$db = Yii::$app->get('section');
		
		if (false === empty($db->dsn)) {
			Yii::configure($db, [
				'dsn' => preg_replace('/[%|\w+?];charset=utf8/i', $dbNo, $db->dsn),
			]);
		} else {
			$dsn = [
				'master' => [],
				'slave' => [],
			];
			array_map(function ($master) use (& $dsn, $dbNo) {
				$masterDsn = preg_replace('/[%|\w+?];charset=utf8/i', $dbNo . ';charset=utf8', $master['dsn']);
				array_push($dsn['master'], ['dsn' => $masterDsn]);
			}, $db->masters);

			array_map(function ($slave) use (& $dsn, $dbNo) {
				$slaveDsn = preg_replace('/[%|\w+?];charset=utf8/i', $dbNo . ';charset=utf8', $slave['dsn']);
				array_push($dsn['slave'], ['dsn' => $slaveDsn]);
			}, $db->slaves);
			
			Yii::configure($db, ['masters' => $dsn['master'], 'slaves' => $dsn['slave']]);
		}
		
		$db->close();
        
		return $db;
	}

exception：

```
exception 'yii\base\InvalidConfigException' with message 'None of the master DB servers is available.' in yiisoft/yii2/db/Connection.php line 568

**Comment by samdark** [comment]
Please report to https://github.com/yiisoft/yii2
