### ISSUE TITLE
Bug in CAssetManager::publish

### ISSUE THREAD

**Issue by pajon** [yiisoft/yii#4171]
### What steps will reproduce the problem?
CAssetManager->publish("directory", true);
CAssetManager->publish("directory", false);

both calls return same response, but they don't have to because parameter **$hashByName** is different.

It is due to cache value is depend only on **path** parameter and don't **$hashByName**.

Lines with issue
$this->_published[$path]=$this->getBaseUrl()."/$dir/$fileName";
$this->_published[$path]=$this->getBaseUrl().'/'.$dir;

Solution is generate cache based path and hashByName
$hash = sha1($path . $hashByName ? 1 : 0);
$this->_published[$hash]=$this->getBaseUrl()."/$dir/$fileName";
$this->_published[$hash]=$this->getBaseUrl().'/'.$dir;

### What is the expected result?
Different response for call with same directory but different $hashByName
### What do you get instead?
Same response

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 1.1.19
| PHP version      | 7.1.8
| Operating system | Debian

**Comment by samdark** [comment]
Won't fix it since it's not related to either PHP compatibility or security and 1.1 reached EOL.
