### ISSUE TITLE
ActiveDataProvider not returning expected records. 

### ISSUE THREAD

**Issue by nadeemse** [yiisoft/yii#4174]
ActiveDataProvider returning fewer records than actual query. When I remove Group by then it's working fine. 

## Query

```
SELECT 
    `pc`.`id` AS `id`,
    `pc`.`name` AS `Title`,
    `pc`.`code` AS `code`,
    `pc`.`amount` AS `Value`,
    `pc`.`type` AS `type`,
    SUM(price) revenue,
    SUM(total_sum) totalRevenue,
    COUNT(order.id) AS total_orders,
    SUM(discount) discount,
    `order`.`source` AS `source`
FROM
    `order`
        INNER JOIN
    `promo_to_customer` `ptc` ON order.id = ptc.order_id
        INNER JOIN
    `promo_codes` `pc` ON ptc.promo_code_id = pc.id
WHERE
    (`order`.`branch_id` = '1')
        AND (DATE(time) >= '2017-09-01')
        AND (DATE(time) <= '2017-09-27')
GROUP BY `order`.`source` , `ptc`.`promo_code_id`
ORDER BY `pc`.`id` DESC
```

### What is the expected result?
Active Data provider returning fewer records than actual query. When I'm running the same query in MySQL client it's returning more records. 

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.4
| PHP version      | 5.6
| Operating system | Mac

**Comment by samdark** [comment]
Please report to https://github.com/yiisoft/yii2. This is Yii 1.1 repository.
