### ISSUE TITLE
Fix MariaDB 10.2 current_timestamp()

### ISSUE THREAD

**Issue by yaBliznyk** [yiisoft/yii#4179]
Last comment in https://github.com/yiisoft/yii/issues/2993
CURRENT_TIMESTAMP changed to current_timestamp() in MariaDB latest version

**Comment by yaBliznyk** [comment]
Please add this fix to Yii 1.1.20 )

**Comment by cebe** [comment]
would you like to send a pull request?

**Comment by yaBliznyk** [comment]
I'm lazy, seriously ((

**Comment by cebe** [comment]
Yii 1.1 has reached end of live, so you'd need to wait for someone who also needs this. Its not going to be added if not by the people like you.

**Comment by yaBliznyk** [comment]
I overcame myself and made a pull request))
