### ISSUE TITLE
Old 1.1.15 branch

### ISSUE THREAD

**Issue by marcovtwout** [yiisoft/yii#4181]
@samdark Would it make sense to remove this branch? https://github.com/yiisoft/yii/tree/1.1.15-branch

**Comment by cebe** [comment]
it was created to make a security release from it. Why do we need to delete it?

**Comment by rob006** [comment]
> Why do we need to delete it?

The right question is "Why do we need to keep it?" :D

**Comment by samdark** [comment]
Yes. Could be removed. Tag will be preserved and will point to correct commit.

**Comment by samdark** [comment]
Removed.
