### ISSUE TITLE
PHP 7.2 - CHtml::value() behaves differently for objects.

### ISSUE THREAD

**Issue by softark** [yiisoft/yii#4186]
### What steps will reproduce the problem?

Unit test CHtmlTest::testValue() for CHtml::value() fails for 4 data sets

| # | model | attribute | default | expected | return 
|---|-------|-------|-------|-------|-------
|12|(object)array('k1'=>'v1','k2'=>'v2','v3','v4')|0|null|null|'v3'
|13|(object)array('k1'=>'v1','k2'=>'v2','v3','v4')|1|null|null|'v4'
|29|(object)array('k1'=>array('k2'=>array('k3'=>'v3')),array('v1','k4'=>'v4'))|'0.0'|null|null|'v1'
|30|(object)array('k1'=>array('k2'=>array('k3'=>'v3')),array('v1','k4'=>'v4'))|'0.k4'|null|null|'v4'

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 1.1.19
| PHP version      | 7.2
| Operating system | linux

**Comment by softark** [comment]
Might be a problem of (object) casting of an array.
I noticed that CHtml::value() behaves as if an "(object)array" is just an "array".

The following are the corresponding array versions of data set which all pass the test.

| # | model | attribute | default | expected | return 
|---|-------|-------|-------|-------|-------
|4|array('k1'=>'v1','k2'=>'v2','v3','v4')|0|null|'v3'|'v3'
|5|array('k1'=>'v1','k2'=>'v2','v3','v4')|1|null|'v4'|'v4'
|25|array('k1'=>array('k2'=>array('k3'=>'v3')),array('v1','k4'=>'v4'))|'0.0'|null|'v1'|'v1'
|26|array('k1'=>array('k2'=>array('k3'=>'v3')),array('v1','k4'=>'v4'))|'0.k4'|null|'v4'|'v4'

**Comment by softark** [comment]
PHP RFC: Convert numeric keys in object/array casts
https://wiki.php.net/rfc/convert_numeric_keys_in_object_array_casts

I'm afraid it also affects Yii 2, doesn't it?

**Comment by softark** [comment]
So the relation between object and array changed drastically in PHP 7.2. They look almost the same. It looks  a good design change to me, but it breaks BC very severely for sure.

IMO, "Won't Fix" might be the best solution for it.
And it might be one of the good reasons for Yii 1.1.x to give up PHP 7.2.

**Comment by samdark** [comment]
Yes. Probably not supporting 7.2 is a good move. Will discuss it.
