### ISSUE TITLE
Document required PHP <=7.1 and extensions in composer.json

### ISSUE THREAD

**Issue by bkonetzny** [yiisoft/yii#4187]
### What steps will reproduce the problem?
Composer will allow installation of Yii on PHP7.2, which is not compatible at the moment.

### What is the expected result?
Don't install Yii on PHP7.2

### What do you get instead?
Yii can be installed via composer on PHP7.2

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 1.1.19
| PHP version      | 7.2
| Operating system | Linux

**Comment by samdark** [comment]
Not needed anymore.
