### ISSUE TITLE
CHtml::linkButton not use href/submit htmloptions !

### ISSUE THREAD

**Issue by mcarbonneaux** [yiisoft/yii#4192]
CHtml::linkButton not correctly use href/submit htmloptions and set link only to '#'.

in the source code they force the url to '#':
```php
if(!isset($htmlOptions['submit']))
        $htmlOptions['submit']=isset($htmlOptions['href']) ? $htmlOptions['href'] : '';
    return self::link($label,'#',$htmlOptions);
```
the fixed must be :
```php
if(!isset($htmlOptions['submit']))
        $htmlOptions['submit']=isset($htmlOptions['href']) ? $htmlOptions['href'] : '';
    return self::link($label,$htmlOptions['submit'],$htmlOptions);
```

The fix reference are her:
http://www.yiiframework.com/forum/index.php/topic/37872-chtmllinkbutton-parameter/

**Comment by samdark** [comment]
Won't be fixed in 1.1. See http://www.yiiframework.com/news/90/update-on-yii-1-1-support-and-end-of-life/

**Comment by mcarbonneaux** [comment]
even though I created a 'pull requests'?

by that many people still use much the v1 (on old applications), this will be practice for them to have the patch included in the latest version.

Is not feature requests but bug fix.

**Comment by samdark** [comment]
As explained in the post from 2015:

> Yii 1.1 will receive critical bugfixes and PHP 7 compatibility fixes till the end of 2016. After that we will only respond to and fix security issues if any will be found until at least the end of 2018. Even after security support has ended, all the code and documentation will be still available.

We're accepting security fixes and, making an exception for PHP 7.2 fixes as well for the next release. That's it. We're nowadays fully focused on 2.0 and 2.1 and don't have enough hands to take care of 1.1.

**Comment by mcarbonneaux** [comment]
I know... But it's very simple fix...

**Comment by samdark** [comment]
That needs review anyway.

**Comment by mcarbonneaux** [comment]
the change is not very complex...

in my case i worked for me. and also for who as made the topic on yii forum...

the CHtml::linkButton without change make link with href = '#' systematicly (in place of using $htmlOptions['submit'])... in fact then dont do what is supposed to do... with this change they use correctly the href/submit option like is supposed to do...

actualy the linkbutton is done as is : 
- http://www.yiiframework.com/doc/api/1.1/CHtml#linkButton-detail 
- https://github.com/yiisoft/yii/blob/1.1.19/framework/web/helpers/CHtml.php#L555

and they use CHtml::link http://www.yiiframework.com/doc/api/1.1/CHtml#link-detail
and the seconde argument are the link url... 
```
public static string link(string $text, mixed $url='#', array $htmlOptions=array ( ))
```

but in the code they passe '#' as url... in any case...

```php
public static function linkButton($label='submit',$htmlOptions=array())
{
    if(!isset($htmlOptions['submit']))
        $htmlOptions['submit']=isset($htmlOptions['href']) ? $htmlOptions['href'] : '';
    return self::link($label,'#',$htmlOptions);
}
```

the possible change is tu pass the $htmlOptions['submit'] variable in place of '#', and '#' if $htmlOptions['submit'] and $htmlOptions['href'] are not set...
```php
if(!isset($htmlOptions['submit']))
        $htmlOptions['submit']=isset($htmlOptions['href']) ? $htmlOptions['href'] : '#';
    return self::link($label,$htmlOptions['submit'],$htmlOptions);
```

**Comment by samdark** [comment]
For how long do you plan to run Yii 1.1 project? Thinking about giving it out to team of people interested and heading em all permissions etc.

**Comment by mcarbonneaux** [comment]
Migration to yii 2.0 is too complex, the application while continue to use yii 1.1 for long time...
All new application using yii start with 2.0, but the old one while rest in 1.1.
