### ISSUE TITLE
CWebApplication::$controllerNamespace not working 

### ISSUE THREAD

**Issue by Rafalsky** [yiisoft/yii#4196]
### What steps will reproduce the problem?
I am not able to work with https://www.yiiframework.com/doc/guide/1.1/en/basics.namespace#namespaced-classes

The default namespace not working, I am trying to define 'controllerNamespace' in application configuration but without results.

Also I am noticed that CWebApplication::$controllerNamespace; is not used anywhere.

### What is the expected result?
1. Global namespaced controllers should works as default for backward compatibility
2. Namespace 'application\components' should works as default if there exists (as per documentation)
3. I should be able to configure  CWebApplication::$controllerNamespace

### What do you get instead?
Only global namespaced controllers works as default

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 1.1.19
| PHP version      | 7.1.14
| Operating system | macOS 10.13.3

**Comment by samdark** [comment]
> Also I am noticed that CWebApplication::$controllerNamespace; is not used anywhere.

https://github.com/yiisoft/yii/blob/master/framework/web/CWebApplication.php#L349


From: https://www.yiiframework.com/doc/guide/1.1/en/basics.namespace#namespaced-controllers

> By default Yii uses controllers from the global namespace. These classes are located under protected/controllers. You can change this behavior in two different ways: using controllerMap and using controllerNamespace. The former allows you to use controllers from various namespaces. The latter requires less configuration while setting a common namespace for all controllers.
