### ISSUE TITLE
Wrong PHPDoc return value in CActiveRecord

### ISSUE THREAD

**Issue by olleharstedt** [yiisoft/yii#4200]
Note that only PHP 7 compatibility issues are accepted. For security issues contact maintainers privately.

### What steps will reproduce the problem?

Check return type of e.g. `findByAttributes`.

### What is the expected result?

`static|null`

### What do you get instead?

`static`

### Additional info

Line: https://github.com/yiisoft/yii/blob/master/framework/db/ar/CActiveRecord.php#L1520

| Q                | A
| ---------------- | ---
| Yii version      | 1.1.?
| PHP version      | 7.?
| Operating system |

**Comment by olleharstedt** [comment]
I can do that, but this fix might need to be applied in more places.

**Comment by cebe** [comment]
feel free to adjust all places you see.
