### ISSUE TITLE
Problemn with registerMetaTag

### ISSUE THREAD

**Issue by acebizant** [yiisoft/yii#4201]
Hi,
there is a problem with  `registerMetaTag`
I can't use
Yii::$app->view->registerMetaTag(["name"=>"description","content"=>$description]);
When $description contains HTML entities like &hearts; `&hearts;`
becouse
`renderTagAttributes` does not have parameter to turn off double encode.

Instead of `registerMetaTag` i have to do:
in my base shop controller
Yii::$app->view->params['metadescription'] = $description;
and in layout
`<?php if (isset($this->params['metadescription'])) {?>
    <meta name="description" content="<?=html_entity_decode($this->params['metadescription'])?>" />
    <?php } ?>`

So, can you change it?
Thank You

| Q                | A
| ---------------- | ---
| Yii version      | 2
| PHP version      | 7
| Operating system | Windows/Debian

**Comment by samdark** [comment]
No. It's a bugfix and bugfixes are no longer accepted to 1.1 except security issues and PHP 7 compatibility.
