### ISSUE TITLE
CDbCommandBuilder createCountCommand

### ISSUE THREAD

**Issue by gkmk** [yiisoft/yii#4215]
https://github.com/yiisoft/yii/blob/master/framework/db/schema/CDbCommandBuilder.php
Line 128
Can we have approximate count instead of actual count?

### What steps will reproduce the problem?
$widget = $this->widget('zii.widgets.grid.CGridView', array(
    'dataProvider' => $model->search(),
    'enableHistory' => true,
    'filter' => $model,
    'columns' => $columns,
        ));

### What is the expected result?
Instant result of limited 10 results per page with pagination enabled.

### What do you get instead?
Wait time of about 10 seconds on 6milion records.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 1.1.15
| PHP version      | 7.0.26
| Operating system | Amazon Linux

**Comment by samdark** [comment]
Changes are not accepted to Yii 1.1 so the answer is no.
