### ISSUE TITLE
Yii 1.1.19 is not compatible in some cases with Php 5.1.6

### ISSUE THREAD

**Issue by benrivero** [yiisoft/yii#4217]
I download latest Yii 1 version: 1.1.19 and working with Php 5.1.6 using Gii Tool I cant create Models, I get this error on log. 

[03-Jul-2018 09:43:54] PHP Warning:  Unexpected character in input:  '\' (ASCII=92) state=1 in /Applications/MAMP/htdocs/myapp/yii/framework/vendors/zend-escaper/Escaper.php on line 101
[03-Jul-2018 09:43:54] PHP Parse error:  syntax error, unexpected T_STRING in /Applications/MAMP/htdocs/myapp/yii/framework/vendors/zend-escaper/Escaper.php on line 101

I end using Yii 1.1.16

**Comment by samdark** [comment]
Any idea why?

**Comment by benrivero** [comment]
This line: 

throw new Exception\InvalidArgumentException(

Use \ symbol for use of namespaces, I Guess that is not compatible with PHP 5.1

**Comment by rob006** [comment]
This was already fixed in master: https://github.com/yiisoft/yii/commit/7944ca5c6f246b22a6c24bdc8ab3e0f6c9c7fcbc

A year ago...

**Comment by benrivero** [comment]
I download the 1.1.19 version of the site, that is not updated?

**Comment by benrivero** [comment]
I can see that the master version points to 1.1.20 under development. Thanks for your help. (Damn client host, can't upgrade PHP from 5.1.6, is very hard to work with that limitation)

**Comment by samdark** [comment]
Oh, we need to tag it :(

**Comment by cebe** [comment]
going to tag 1.1.20 today.
