### ISSUE TITLE
Updating Jquery from 1.11.1 to a newer version

### ISSUE THREAD

**Issue by Niickles** [yiisoft/yii#4219]
Hello all, we are working to renew a fairly large website and we want to implement a new jquery version... 

we looked at upgrading yii from version 1.14 to 1.20 but sadly jquery 1.11.1 is still being used here. upgrading to yii 2.x will take a lot of time and we dont really have that time. 
for us to be able to update to a more recent version of jquery which version would be the best and easiest to use?

thanks in advance

**Comment by samdark** [comment]
Replace it as an asset served from your source code.
