### ISSUE TITLE
PHP 7.2 create_function in CHttpRequest is deprecated

### ISSUE THREAD

**Issue by martinpetrasch** [yiisoft/yii#4220]
**create_function** in class *CHttpRequest* and function *getPreferredLanguages()* is deprecated in PHP 7.2.0 as stated in http://php.net/manual/de/function.create-function.php

### What steps will reproduce the problem?
Call *getPreferredLanguages()* from `CHttpRequest`

### What is the expected result?
Should run without throwing an error.

### What do you get instead?
`Function create_function() is deprecated (yii/1.1.20/framework/web/CHttpRequest.php:1053)`

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 1.1.20
| PHP version      | 7.2
| Operating system | macOS 10.12.6

**Comment by ThePepster** [comment]
Just a note. Yii 1.1.20 is compatible with PHP 5.1.0 and above. The pull request above is not compatible with PHP 5.1 or 5.2.

**Comment by jjdunn** [comment]
Um...this ticket should please be reopened, because:
 1. the fix from ThePepster is valid, but must be replicated in yiilite.php copy of CHttpRequest::getPreferredLanguages()
 2. there's another usage of create_function() in framework/logging/CProfileLogRoute.pdf ::displaySummary()

**Comment by samdark** [comment]
yiilite.php is regenerated on release.

**Comment by TomasVotruba** [comment]
For future cases of `create_function`, [I wrote a tool that converts it instantly](https://www.tomasvotruba.cz/blog/2018/12/17/function-create-function-is-deprecated-in-php-72-how-to-migrate/).
