### ISSUE TITLE
reset() expects parameter 1 to be array, integer given in GII diff

### ISSUE THREAD

**Issue by ahmadasjad** [yiisoft/yii#4226]
Note that only PHP 7 compatibility issues are accepted. For security issues contact maintainers privately.

### What steps will reproduce the problem?

[model_and_controller_to_check_yii1.1.20_gii_error.zip](https://github.com/yiisoft/yii/files/2388211/model_controller_to_check_yii1.1.20_gii_error.zip)
There are two files one is a controller and another is a model. Once you'll try to regenerate the crud from the Model, click **preview** button then click on **diff** text of the controller going to be generated. Now you'll see the error `reset() expects parameter 1 to be array, integer given`

### What is the expected result?
Difference between old and new code when going to generate crud from Active Record model using GII

### What do you get instead?
reset() expects parameter 1 to be array, integer given

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 1.1.20.6ed384
| PHP version      | 7.1.20-1
| Operating system | ubuntu16.04.1

**Comment by ahmadasjad** [comment]
### Here is the stacktrace:
```
2018/09/17 15:40:10 [error] [php] reset() expects parameter 1 to be array, integer given (/var/www/html/yii-1.1.20.6ed384/framework/gii/components/Pear/Text/Diff/Engine/native.php:196)
Stack trace:
#0 /var/www/html/yii-1.1.20.6ed384/framework/gii/components/Pear/Text/Diff/Engine/native.php(88): Text_Diff_Engine_native->_compareseq()
#1 /var/www/html/yii-1.1.20.6ed384/framework/gii/components/Pear/Text/Diff.php(56): Text_Diff_Engine_native->diff()
#2 /var/www/html/yii-1.1.20.6ed384/framework/gii/components/Pear/Text/Diff/Renderer/inline.php(136): Text_Diff->__construct()
#3 /var/www/html/yii-1.1.20.6ed384/framework/gii/components/Pear/Text/Diff/Renderer.php(165): Text_Diff_Renderer_inline->_changed()
#4 /var/www/html/yii-1.1.20.6ed384/framework/gii/components/Pear/Text/Diff/Renderer.php(140): Text_Diff_Renderer_inline->_block()
#5 /var/www/html/yii-1.1.20.6ed384/framework/gii/components/TextDiff.php(20): Text_Diff_Renderer_inline->render()
#6 /var/www/html/yii-1.1.20.6ed384/framework/gii/CCodeGenerator.php(109): compare()
#7 /var/www/html/yii-1.1.20.6ed384/framework/web/actions/CInlineAction.php(49): CrudGenerator->actionDiff()
#8 /var/www/html/yii-1.1.20.6ed384/framework/web/CController.php(308): CInlineAction->runWithParams()
#9 /var/www/html/yii-1.1.20.6ed384/framework/web/CController.php(286): CrudGenerator->runAction()
#10 /var/www/html/yii-1.1.20.6ed384/framework/web/CController.php(265): CrudGenerator->runActionWithFilters()
#11 /var/www/html/yii-1.1.20.6ed384/framework/web/CWebApplication.php(282): CrudGenerator->run()
#12 /var/www/html/yii-1.1.20.6ed384/framework/web/CWebApplication.php(141): CWebApplication->runController()
#13 /var/www/html/yii-1.1.20.6ed384/framework/base/CApplication.php(185): CWebApplication->processRequest()
#14 /var/www/html/belair/site/index.php(24): CWebApplication->run()
REQUEST_URI=/gii/crud/diff/0
```

**Comment by samdark** [comment]
Thanks for reporting but only PHP 7 incompatibilities and security fixes are accepted.

**Comment by LeoZandvliet** [comment]
Excuse me for 'reopening' this issue, but I dug into this error because I too experience problems with the `diff` but felt it was not a php 7.x issue.
I've created a phpunit testclass and tested explicitly with php7.0 and phpunit 6.5 to make it reproducable.
Unfortunately, I don't understand what is really done in the called function to help solve it.

A simple 'switching of lines' between 2 files will recreate it already:

	public function test_differences2()
    {
        $diff = new Text_Diff('auto', array(array('1 line', '2 line', '3 line'), array('1 line', '3 line', '2 line')));
        $this->assertEquals(false, $diff->isEmpty());
    }
	
Will throw

	reset() expects parameter 1 to be array, integer given
	
This test (others will not, see attached file) calls Text_Diff->_diag() that has on lines \#193 - 196:

	$matches = $ymatches[$line];
    reset($matches);
    foreach($matches as $match) {
		reset($match);


With the variables:

	$ymatches = Array(
		[2 line] => Array(
			[0] => 1
		)
		[3 line] => Array(
			[0] => 0
		)
	)

	$line = '2 line';
	
So `$matches` will be an array of integers, and `$match` always an integer.

A file with more (succesful) tests is attached, much more 'differences' could be added to test for once this error is solved.
[Text_DiffTest.txt](https://github.com/yiisoft/yii/files/7171199/Text_DiffTest.txt)

**Comment by LeoZandvliet** [comment]
Okay, I've found a solution for this by sniffing in the newest version of the file `framework/gii/components/Pear/Text/Diff/Engine/native.php` within the [horde source code](https://github.com/horde/Text_Diff/blob/master/lib/Horde/Text/Diff/Engine/Native.php) on github,  still not understanding what that code really does :)

Please use the file in the attachment and swap it with `framework/gii/components/Pear/Text/Diff/Engine/native.php` or change the `for loop` on line 188-221 with the much shorter one:

	for (; $x < $x1; $x++) {
		$line = $flip ? $this->yv[$x] : $this->xv[$x];
		if (empty($ymatches[$line])) {
			continue;
		}
		$matches = $ymatches[$line];
		foreach ($matches as $y) {
			if (empty($this->in_seq[$y])) {
				$k = $this->_lcsPos($y);
				assert($k > 0);
				$ymids[$k] = $ymids[$k - 1];
				break;
			} elseif ($y > $this->seq[$k - 1]) {
				assert($y <= $this->seq[$k]);
				$this->in_seq[$this->seq[$k]] = false;
				$this->seq[$k] = $y;
				$this->in_seq[$y] = 1;
			}
		}
	}
[Text_Diff_Engine_Native.txt](https://github.com/yiisoft/yii/files/7171456/Text_Diff_Engine_Native.txt)

Generated diffs now at least work in more cases and look good with php 7.4 (and I assume =>7.0 )

**Comment by marcovtwout** [comment]
Issue confirmed, break seems to be introduced in https://github.com/yiisoft/yii/commit/3881dddc6eb6ca8ea43a76797bf65f24088a8abe

**Comment by marcovtwout** [comment]
After examining the differences between both libraries I think it's best to simply patch our existing Text_Diff version. Will continue discussion for the fix in the PR.
