### ISSUE TITLE
PHPUnit-6 introduced change that breaks compatibility with php-7.2

### ISSUE THREAD

**Issue by gianniszach** [yiisoft/yii#4227]
### Background information
My Yii project is running on php-5.6 and the tests on phpunit5. During our migration to php-7.2 we noticed that PHPUnit needs an upgrade to at least version PHPUnit-6 upgrade to support php-7.2. 

The issue is caused by PHPUnit-6 where the `PHPUnit_Framework_TestCase` is removed and replaced with `PHPUnit\Framework\TestCase` ([migrating to phpunit-6](https://thephp.cc/news/2017/02/migrating-to-phpunit-6))

Yii's `/framework/test/CTestCase.php` extends from `PHPUnit_Framework_TestCase` and the phpunit tests fail with error trying to include the non-existing `PHPUnit_Framework_TestCase`.

### What steps will reproduce the problem?
Install phpunit-6 and run the Yii tests

### What is the expected result?
Expected Yii to autoload phpunit files without errors.

### What do you get instead?
```
Warning: include(PHPUnit_Runner_Version.php): failed to open stream: No such file or directory in /frameworks/yii-1.1.20.6ed384/framework/YiiBase.php on line 463
```
I believe this is related to the way `CTestCase.php` does the PHPUnit autoload, if you pass this error by requiring the PHPUnit autoload.php before Yii you'll get the error:
```
Warning: include(PHPUnit_Framework_TestCase.php): failed to open stream: No such file or directory in /frameworks/yii-1.1.20.6ed384/framework/YiiBase.php on line 463
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 1.1.20
| PHP version      | 7.2
| Operating system | Debian Linux

EDIT: I forgot to mention that I bypassed this issue by requiring the `phpunit/autoload.php` before loading Yii and then requiring a custom `PHPUnit_Framework_TestCase.php` where I defined the empty classes of `class PHPUnit_Framework_TestCase extends PHPUnit\Framework\TestCase` and `class PHPUnit_Runner_Version`

**Comment by samdark** [comment]
I think it could be solved in a way similar to https://github.com/yiisoft/yii2/blob/master/tests/compatibility.php

**Comment by ddziaduch** [comment]
@samdark @gianniszach there is already solution for that. There is a file in the repo: https://github.com/yiisoft/yii/blob/master/tests/compatibility.php

Include it in your `bootstrap.php` file and it will work. Probably 😀

**Comment by gianniszach** [comment]
Yes, the [compatibility.php file](https://github.com/yiisoft/yii/blob/master/tests/compatibility.php) solves the issue with `PHPUnit_Framework_TestCase` class but not with `PHPUnit_Runner_Version`.

Which, as @samdark, said it can be solved in the same way. Adding this to compatibility.php fixed the issue with `PHPUnit_Runner_Version` too. 
```
if(!class_exists('PHPUnit_Runner_Version') && class_exists('PHPUnit\Runner\Version'))
{
    abstract class PHPUnit_Runner_Version extends \PHPUnit\Runner\Version {}
}
```

**Comment by samdark** [comment]
@gianniszach would you like to send a pull request?

**Comment by bizmate** [comment]
I am still seeing this issue on yii 1, phpunit 6 when i

` extends CDbTestCase
`
I tried requiring the compatibility file in the phpunit bootstrap but it is not working.

`require_once(dirname(__FILE__).'/../../../yii/tests/compatibility.php');
`
Any other devils' tricks I can use?
