### ISSUE TITLE
Issue when use SSE with Yii

### ISSUE THREAD

**Issue by rekhakum** [yiisoft/yii#4230]
I try to use SSE(Server Sent Event) with Yii. I am trying to trigger 2 ajax from view file. One for SSE and one to run my long running stored procedure. I see from Console that it triggers both AJAX at the same time but the second request is kept on waiting until the first one finish.  We can't run both at the same time together?

**Comment by samdark** [comment]
Please use forum for questions: https://forum.yiiframework.com/
