### ISSUE TITLE
Column is int & unsigned, why gii generate model type is string?

### ISSUE THREAD

**Issue by Sun-FreePort** [yiisoft/yii#4242]
### What's main ?

I usually use Unix timestamp.

Gii generate model is string type of Unix timestamp columns.

So, i find get it:

https://github.com/yiisoft/yii/blob/4874064325c12c338229549702df60c2d3101744/framework/db/schema/mysql/CMysqlColumnSchema.php#L11-L36

The "int" & "unsigned" column is string (and use partial match), why so designed ?

### Tip

I find this issue https://github.com/yiisoft/yii/issues/2535, can i take a pr to php73 branch?

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 1.1.x（latest version）
| PHP version      | 7.2.4
| Operating system | Win7 64bit

**Comment by samdark** [comment]
That is known issue that won't be fixed since Yii 1.1 is in security and PHP 7 compatibility mode only.
