### ISSUE TITLE
Logical defect in CModel->validate(attribute)

### ISSUE THREAD

**Issue by edebise** [yiisoft/yii#4249]
### What steps will reproduce the problem?
When calling CModel->validate('attribute')

### What is the expected result?
We expect to get true if this CModel->attribute has no error
It has to check only if 'attribute' is valid.

### What do you get instead?
But we get true if CModel has no error.
It checks if all CModel is valid as calling CModel->validate(null).

In framework/base/CModel.php line 161
  	We should have:  	return !$this->hasErrors($attribute);
  	Instead of: 	return !$this->hasErrors();

**Comment by rob006** [comment]
First argument should be an array. Does it work if you call `validate(['attribute'])`.

**Comment by edebise** [comment]
Hi, yes it works better! I didn't see 'array' in the doc, Sorry.
