### ISSUE TITLE
Assets: file not exists

### ISSUE THREAD

**Issue by trulave** [yiisoft/yii#4252]
### What steps will reproduce the problem?
Register file somewhere in application
```php
$this->registerCSS('application.widgets.assets.css.style');
```
Then publish directory somewhere else
```php
Yii::app()->assetManager
    ->publish(Yii::getPathOfAlias('application.widgets.assets.css'));
```

### What is the expected result?
/assets/8d24d942/another_style.css
Request Method: GET
Status Code: 200 OK

### What do you get instead?
/assets/8d24d942/another_style.css
Request Method: GET
Status Code: 404 Not Found

### Description
The root of the problem in `CAssetManager::generatePath` method.
https://github.com/yiisoft/yii/blob/master/framework/web/CAssetManager.php#L325
Cause path for directory `application/widgets/assets/css` will be (if we use symbolic link):
```php
CAssetManager::hash($file.filemtime($file)); // "application/widgets/assets/css" + "timestamp"
```
But it this is true for file in this directory too:
```php
CAssetManager::hash(dirname($file).filemtime($file)); // "application/widgets/assets/css" + "timestamp"
```
If timestamps of file and parent directory equals asset hash will be equal too. Firts call register file and second publish directory leads that symbolic link won't be created, as evidenced by next code part:
![image](https://user-images.githubusercontent.com/5782269/54427372-5cf16300-472b-11e9-8073-5d08df08d0df.png)
https://github.com/yiisoft/yii/blob/master/framework/web/CAssetManager.php#L240

Why both timestamps can be equals? E.g. when you edited file in PHPStorm, IDE update same modify date for file and parent direcory too.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 1.1.20
| PHP version      | 7.1
| Operating system | Debian 8

**Comment by samdark** [comment]
Thanks for report but bugs aren't being fixed in 1.1 branch except security issues and PHP compatibility.
