### ISSUE TITLE
CActiveRecord.getTableAlias() bug

### ISSUE THREAD

**Issue by yapro** [yiisoft/yii#4254]
Note that only PHP 7 compatibility issues are accepted. For security issues contact maintainers privately.

### What steps will reproduce the problem?

docker run lebnik/php:yii1-bug-1 php /tmp/yii/WebRoot/testdrive/protected/yiic mybug

or manualy: look at https://github.com/yapro/php/blob/yii1-bug-1/Dockerfile

### What is the expected result?

2:2

### What do you get instead?

0:2

`mybug` is a command with content:

```
<?php
class MybugCommand extends CConsoleCommand
{
    public function run($args) {
        $activeRecord = User::model();
        $condition = $activeRecord->getDbCriteria()->addInCondition('id', [1]);
        $activeRecord->updateAll(// here will be used $this->getDbCriteria(true)
            [
                'password' => '123',
            ],
            $condition
        );

        $usersOne = User::model()->findAllByPk([2,3]);// here will be used $this->getDbCriteria(false)
        $usersTwo = User::model()->findAllByPk([2,3]);// here will be used $this->getDbCriteria(true)
        echo count($usersOne) . ':' . count($usersTwo) . PHP_EOL;
    }
}
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 1.1.19
| PHP version      | PHP 7.1.23 (cli) (built: Oct 16 2018 01:08:49) ( NTS )
| Operating system |Linux vb 4.15.0-43-generic #46~16.04.1-Ubuntu SMP Fri Dec 7 13:31:08 UTC 2018 x86_64 GNU/Linux

Bug in file: https://github.com/yiisoft/yii/blob/master/framework/db/ar/CActiveRecord.php#L1432

Now:
> $this->getDbCriteria(false)

Must be:
> $this->getDbCriteria(true)

**Comment by samdark** [comment]
That doesn't look like PHP compatibility issue. Fixed are no longer accepted to Yii 1.1.
