### ISSUE TITLE
PHP 7 compatibility issues: PHP4 style constructor and create_function()

### ISSUE THREAD

**Issue by kenguest** [yiisoft/yii#4256]
gii/components/Pear/Text/Diff3.php:
Use of deprecated PHP 4 style class constructor is not supported in PHP7+

vendors/markdown/markdown.php:
create_function() is deprecated since PHP7.2 - should be using an anonymous function instead.

**Comment by samdark** [comment]
Constructor part solved.

**Comment by kenguest** [comment]
I've reinstated use of create_function in markdown.php so to keep compatibility with 5.1.x as requested.

Looking at the changelog it seems others replaced create_function calls with anonymous functions elsewhere, facilitating migration to a maintained version of PHP. 

This is why I'm making these changes in the first place....

**Comment by samdark** [comment]
@kenguest no. https://github.com/yiisoft/yii/commit/68e5e86a11162a54673d83f8d0a5939b621d8040
