### ISSUE TITLE
Default value error for a not null DB column with PHP 7.2

### ISSUE THREAD

**Issue by monikakatiyar16** [yiisoft/yii#4258]
I have a table with a NOT NULL column, say employee_summary. This column contains value only if the user is an employee, otherwise not.

For a non-employee use case, the insert/update using Yii 1.1.21, MySQL 5.5, PHP 5.6, it works correctly and inserts an empty string there.

When I try to execute the same use case on Yii 1.1.21, MySQL 5.7, PHP 7.2, it gives me the following error:
"CDbCommand failed to execute the SQL statement: SQLSTATE[HY000]: General error: 1364 Field 'employee_summary' doesn't have a default value."

Expected result: Similar to Yii 1.1.21 + PHP 5.5 - to store blank value in the employee_summary field

| Q                | A
| ---------------- | ---
| Yii version      | 1.1.21
| PHP version      | 7.2
| Operating system | Llinux Ubuntu 18.04 (Bionic)

**Comment by samdark** [comment]
Can you try to downgrade PHP version without downgrading MySQL? Would it be the same error?

**Comment by monikakatiyar16** [comment]
@samdark I tried downgrading the PHP to v5.6. It still gives the same error.

**Comment by samdark** [comment]
Then it's not PHP 7 compatibility issue but MySQL my.ini settings.

**Comment by monikakatiyar16** [comment]
Okay.. Could you please guide me what to check for in MySQL ini settings. I did compare the ini settings on both the servers (Yii 1.1.21, MySQL 5.5, PHP 5.6, Ubuntu 14) vs (Yii 1.1.21, MySQL 5.7, PHP 7.2, Ubuntu 18).

**Comment by rob006** [comment]
This is related to strict mode enabled by default in MySQL 5.7. You should add `default` rule to your model validation, which will set this attribute to empty string. Or add default value to this column in DB.

**Comment by monikakatiyar16** [comment]
@robregonm Thank you so much. That helped! :)
