### ISSUE TITLE
500 internal error 

### ISSUE THREAD

**Issue by buibr** [yiisoft/yii#4259]
Today 10/05/2019 updated Yii by composer update.

Every request that i make to my application through ajax reques, it returns 500 Internal error with data in body.

So, the data is ok but the code is not good.

https://imgur.com/5WQrXnr

https://imgur.com/UcCInir

### What steps will reproduce the problem?
I dont know?!!

### What is the expected result?
Should return 200 code.

### What do you get instead?
500 internal error.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.19-dev
| PHP version      | 7.1.26
| Operating system | Ubuntu

**Comment by samdark** [comment]
This repository is for Yii 1.1. Please report to https://github.com/yiisoft/yii2

**Comment by buibr** [comment]
Thanks @samdark i just fixed the problem was 
yii2-debug some file were missing when updated by composer.
