### ISSUE TITLE
PHP 7.3 mcrypt removed

### ISSUE THREAD

**Issue by php5developer** [yiisoft/yii#4260]
Note that only PHP 7 compatibility issues are accepted. For security issues contact maintainers privately.

### What steps will reproduce the problem?

Since mcrypt extension was removed in PHP 7.3 so when I call **CSecurityManager** class **encrypt** or **decrypt** method I get error:

Error: Call to undefined function mcrypt_module_get_supported_key_sizes() in \framework\base\CSecurityManager.php:534

Does anybody have temporary solution to solve this issue? Thank you.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 1.1.21
| PHP version      | 7.3.5
| Operating system |

**Comment by PrplHaz4** [comment]
@php5developer https://github.com/yiisoft/yii/issues/4182

**Comment by samdark** [comment]
@php5developer are you sure you're using latest version?

**Comment by php5developer** [comment]
Just downloaded latest version from github and website. In both archives CSecurityManager has a lot of "mcrypt_*" functions calls. As I understand mcrypt was removed in PHP 7.3

**Comment by machour** [comment]
@php5developer mcrypt was removed from PHP 7.2, but you can still install it from PECL (https://github.com/yiisoft/yii/issues/4182#issuecomment-355245105), or use a compat library (https://github.com/yiisoft/yii/issues/4182#issuecomment-367518611).

**Comment by php5developer** [comment]
@machour Understood. Thank you.
