### ISSUE TITLE
PHP 7.3 CUrlValidator with validateIDN option: INTL_IDNA_VARIANT_2003 is deprecated

### ISSUE THREAD

**Issue by npushkov** [yiisoft/yii#4261]
Note that only PHP 7 compatibility issues are accepted. For security issues contact maintainers privately.

### What steps will reproduce the problem?

Validate any url via CUrlValidator with `validateIDN` option set to `true`

### What is the expected result?

Url is validated without PHP errors

### What do you get instead?

PHP Error [500]
idn_to_ascii(): INTL_IDNA_VARIANT_2003 is deprecated 

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 1.1.21
| PHP version      | 7.3
| Operating system |

**Comment by machour** [comment]
@npushkov should be fixed by #4262, could you give it a try?

**Comment by npushkov** [comment]
@machour I have tried it, #4262 fixes this issue. Thank you!

**Comment by machour** [comment]
Thank you, let's keep this issue open until the PR gets merged.

**Comment by samdark** [comment]
Its merged. @machour thank you for looking into it.
