### ISSUE TITLE
Cache get() returns false at no value, should return null

### ISSUE THREAD

**Issue by olleharstedt** [yiisoft/yii#4263]
The interface to the cache system is sub-optimal. There's no way to cache a boolean value, since get() will return false at failure. If it's changed to return null instead, it will be possible to cache anything.

This seems to be the case in both Yii 1 and 2. Didn't check 3.

**Comment by machour** [comment]
Yii 3 is PSR-16 compatible and will return null: https://github.com/yiisoft/cache

Closing this since Yii 1 & Yii 2 are in feature-freeze mode, so this won't be changed.

**Comment by olleharstedt** [comment]
Thanks for the feedback.
