### ISSUE TITLE
PHP 7.3 Call to undefined function mcrypt_module_get_supported_key_sizes()

### ISSUE THREAD

**Issue by vyachin** [yiisoft/yii#4265]
Note that only PHP 7 compatibility issues are accepted. For security issues contact maintainers privately.

### What steps will reproduce the problem?
делаем простой проект и настраиваем SecurityManager через конфиг приложения. Нас интересует это свойство https://www.yiiframework.com/doc/api/1.1/CSecurityManager#encryptionKey-detail
Приложение можно заменить простым скриптом
```

require_once __DIR__ . '/vendor/yiisoft/yii/framework/yii.php';
$config = [
    'basePath'=>__DIR__,
    'components'=> [
        'securityManager' => [
            'encryptionKey' => '1234567890123456789012',
        ]
    ],
];
$app = Yii::createConsoleApplication($config);
$sm = Yii::app()->securityManager;

```
### What is the expected result?
чтобы приложение работало без ошибок 

### What do you get instead?
```
Error: Call to undefined function mcrypt_module_get_supported_key_sizes() in /Users/vyachin/12345/vendor/yiisoft/yii/framework/base/CSecurityManager.php:534
Stack trace:
#0 /Users/vyachin/12345/vendor/yiisoft/yii/framework/base/CSecurityManager.php(185): CSecurityManager->validateEncryptionKey('123456789012345...')
#1 /Users/vyachin/12345/vendor/yiisoft/yii/framework/base/CComponent.php(152): CSecurityManager->setEncryptionKey('123456789012345...')
#2 /Users/vyachin/12345/vendor/yiisoft/yii/framework/YiiBase.php(227): CComponent->__set('encryptionKey', '123456789012345...')
#3 /Users/vyachin/12345/vendor/yiisoft/yii/framework/base/CModule.php(393): YiiBase::createComponent(Array)
#4 /Users/vyachin/12345/vendor/yiisoft/yii/framework/base/CModule.php(103): CModule->getComponent('securityManager')
#5 /Users/vyachin/12345/commands/TestCommand.php(7): CModule->__get('securityManager')
```

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 1.1.21
| PHP version      | 7.3
| Operating system | Mac OS & ubuntu 18.04

**Comment by samdark** [comment]
Установлен ли mcrypt?

- https://github.com/yiisoft/yii/issues/4182#issuecomment-355245105
- https://github.com/phpseclib/mcrypt_compat

**Comment by vyachin** [comment]
Нет

https://www.php.net/manual/en/migration71.deprecated.php
