### ISSUE TITLE
Primary key from Model object Method is Prior to DB Schema

### ISSUE THREAD

**Issue by lengshuiyulangcn** [yiisoft/yii#4267]
Note that only PHP 7 compatibility issues are accepted. For security issues contact maintainers privately.

### What steps will reproduce the problem?

1. Extend CActiveRecord to be your own base class `BaseModel`.
2. Override `public function primaryKey()` to set the default primary key to be `id`
3. You extend the base class to be `SubModel`, mapping to a table with different primary key `(xxx_id,yyy_id)`however you forgot to override the function.
4. You got an error when you trying to access SubModel object like `SubModel.id is not a method`

### What is the expected result?

I can still get the right primary Key without the exception saying that I don't have the method.

### What do you get instead?

Exception like `SubModel.id is not a method`

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 1.1.21
| PHP version      | 7.3.5
| Operating system |

I think
https://github.com/yiisoft/yii/commit/bca0420b6799b0b2a7966aa90bcd15cb4aa73563#diff-c8167ae9b10e04df148cae0dedcd1224R8448

need to be reverted. Basically what we get from db schema should be prior than that defined
in the model class.

**Comment by b1rdex** [comment]
As `primaryKey()` description states, it's return value is used only if present. So it's the only way to override/define the primary key for the table. What would be the point of this method if its return value would be overridden by DB schema?

Just remove that `primaryKey()` in the parent class (if it's really base for all of your models) or override it with `return null` to force DB schema data usage.

**Comment by lengshuiyulangcn** [comment]
@b1rdex Thank you for reply.
I'm ok with the solution. Without modifying the framework itself I'm currently finding out all the model and check their schema to prevent the exception.  
But do you have any example where we need to override/redefine the primary key in model which already been defined in the db schema.

**Comment by b1rdex** [comment]
@lengshuiyulangcn yes, actually we have such usage in our production codebase. One of the tables has an auto-incremented primary key, but we redefine it with `primaryKey()` to another computed key, that has checksum digit added to `id`. This way we didn't have to rewrite all the queries we had when we started to use checksum-added ids.

**Comment by lengshuiyulangcn** [comment]
@b1rdex  Thank you for explaining.  I will close the issue.
