### ISSUE TITLE
yiilite.php broke 1.1.20

### ISSUE THREAD

**Issue by twisted1919** [yiisoft/yii#4268]
### What steps will reproduce the problem? 
Enable APC and use the framework (yiilite.php bootstrap file) with any code that eventually will try to access `CHttpSession::setCacheLimiter`

### What is the expected result? 
For things to work

### What do you get instead?
Undefined method `CHttpSession::setCacheLimiter`

### Additional info
This traces down to how yiilite.php file is created, most likely you need to rebuild this file with the classes having all the new methods in place.   

This also causes issues with the database drivers in some cases, i.e:  
```
2019/09/18 11:14:01 [error] [exception.CDbException] could not find driver
2019/09/18 11:14:01 [error] [exception.CDbException] CDbException: CDbConnection failed to open the DB connection. in /var/www/html/xyz/apps/common/framework/yiilite.php:8621
``` 
which is weird because it just happens in command line not in the web server even though both have pdo/pdo-mysql installed and enabled. 
So something really fishy is happening because of how the yiilite.php file has been shipped in latest version.  

| Q                | A
| ---------------- | ---
| Yii version      | 1.1.20
| PHP version      | 7.1.19
| Operating system | CentOS 7.x

**Comment by samdark** [comment]
That's weird. `yiilite.php` is built with the latest changes. You can check yourself with `./build/build lite`.

**Comment by samdark** [comment]
Here's setCacheLimiter: https://github.com/yiisoft/yii/blob/master/framework/yiilite.php#L4880

**Comment by samdark** [comment]
Can you try 1.1.21 and master?

**Comment by twisted1919** [comment]
Apparently with 1.2.1 things work just fine, so i am not sure what happened, sorry for the troubles.

**Comment by GerrGIT** [comment]
Had this a while ago, turned out the php of command line was using different php.ini which has no PDO enabled. Not sure if the same issue, but sounds exactly like it.
