### ISSUE TITLE
bindValues() causing PHP 7.2 compatibility error from count()

### ISSUE THREAD

**Issue by krunder** [yiisoft/yii#4269]
Note that only PHP 7 compatibility issues are accepted. For security issues contact maintainers privately.

### What steps will reproduce the problem?

Passing null through the $values parameter on the bindValues() method in CdbCommandBuilder.php.

### What is the expected result?

The count function return 0 as would usually be the case with versions of PHP below 7.2.

### What do you get instead?

PHP fatal error complaining that the value passed to count() should be an array or implement Countable.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 1.1.21
| PHP version      | 7.2 & 7.3
| Operating system | Windows & Linux

**Comment by rob006** [comment]
> Passing null through the $values parameter on the bindValues() method in CdbCommandBuilder.php.

This method expects array. In which case `null` will be passed?

**Comment by krunder** [comment]
Apologies for the late reply on this. It looks to be that null is generally passed into the bind values if non are specified. I experienced this with one of the projects I am working on at work.

**Comment by samdark** [comment]
@krunder why would bindValues() be called if nothing is being bound?
