### ISSUE TITLE
PHP Error[2]: include(ParagonIE_Sodium_Compat.php): failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by ursuleacv** [yiisoft/yii#4272]
When installing `paragonie/sodium_compat` I'm getting the following error:

**PHP Error[2]: include(ParagonIE_Sodium_Compat.php): failed to open stream: No such file or directory**

The class ParagonIE_Sodium_Compat cannot be found in **cli** mode, works fine in php-fpm.

### What steps will reproduce the problem?
- Install Yii framework 1.x
- cd protected
- run composer require paragonie/sodium_compat
- create a command for example TestCommand
- run php cron.php test

### What is the expected result?
work without any errors

### What do you get instead?

```
PHP Error[2]: include(ParagonIE_Sodium_Compat.php): failed to open stream: No such file or directory
    in file C:\localhost\framework\YiiBase.php at line 463
#0 C:\localhost\framework\YiiBase.php(463): include()
#1 unknown(0): autoload()
#2 C:\localhost\protected\vendor\paragonie\sodium_compat\lib\constants.php(8): spl_autoload_call()
#3 C:\localhost\protected\vendor\paragonie\sodium_compat\lib\sodium_compat.php(825): require_once()
#4 C:\localhost\protected\vendor\paragonie\sodium_compat\autoload.php(45): require_once()
#5 C:\localhost\protected\vendor\composer\autoload_real.php(70): require()
#6 C:\localhost\protected\vendor\composer\autoload_real.php(60): composerRequire50966560348a0ac36e4b9ee4405e5f09()
#7 C:\localhost\protected\vendor\autoload.php(7): getLoader()
#8 C:\localhost\protected\commands\TestCommand.php(7): require_once()
#9 C:\localhost\framework\console\CConsoleCommandRunner.php(166): require_once()
#10 C:\localhost\framework\console\CConsoleCommandRunner.php(67): CConsoleCommandRunner->createCommand()
#11 C:\localhost\framework\console\CConsoleApplication.php(92): CConsoleCommandRunner->run()
#12 C:\localhost\framework\base\CApplication.php(185): CConsoleApplication->processRequest()
#13 C:\localhost\cron.php(19): CConsoleApplication->run()
```
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 1.1.21
| PHP version      | 7.0.33
| Operating system | Windows 10 or Centos 6.6

**Comment by rob006** [comment]
You may need to set [`YiiBase::$enableIncludePath`](https://www.yiiframework.com/doc/api/1.1/YiiBase#enableIncludePath-detail) to `false` if you want to use Yii autoloader together with composer autoloader.

**Comment by ursuleacv** [comment]
Where do I add it? 
I've tried before and after 

`Yii::createConsoleApplication($config)->run();`

it didn't work

**Comment by rob006** [comment]
> Where do I add it?

Anytime before `ParagonIE_Sodium_Compat` is used. Probably right after including `framework/yii.php` file.

**Comment by samdark** [comment]
@ursuleacv so how did you solve it?

**Comment by ursuleacv** [comment]
I haven't yet, I removed the package in the console environment

**Comment by marcovtwout** [comment]
Looks like the autoloaders are not combining nicely. Since `paragonie/sodium_compat` is not required by the Yii framework, I'll guess this issue can be closed.
