### ISSUE TITLE
setcookie $options to allow setting of SameSite flag

### ISSUE THREAD

**Issue by thekonz** [yiisoft/yii#4273]
Google Chrome will soon (January 2020) basically block third-party cookies, if they do not have the SameSite flag set. See [this](https://www.chromestatus.com/feature/5088147346030592) and [that](https://www.chromestatus.com/feature/5633521622188032) for more information on the Chrome side of things.

PHP 7.3 changed `setcookie` to receive an `$options` parameter, which allows to set the SameSite flag.

**Will Yii 1.1 get an update to support the $options parameter?** Does this fall in the category of compatibility updates? 

### What steps will reproduce the problem?

Set a cookie while being a third party (ex. run your website in an iframe) in Chrome.

### What is the expected result?

The cookie should be set.

### What do you get instead?

From January 2020 on, Chrome will block this cookie.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 1.1.21
| PHP version      | 7.3

**Comment by samdark** [comment]
Yes. Look like exactly that category. Do you want to prepare a pull request?

**Comment by thekonz** [comment]
Sure, will do later.

**Comment by thekonz** [comment]
Well, the PR is there, but travis complains about some mysql server not being available.
