### ISSUE TITLE
CDataColumn::value property doc must contain that if Active record, then $data->{column_name}, if sqldataprovider then $data['column_name']

### ISSUE THREAD

**Issue by fazliddin** [yiisoft/yii#4276]
https://www.yiiframework.com/doc/api/1.1/CDataColumn#value-detail

**Comment by samdark** [comment]
Do you want to send a pull request?

**Comment by fazliddin** [comment]
ok, I will

**Comment by samdark** [comment]
@fazliddin still want to do it?

**Comment by fazliddin** [comment]
Yes I will make pull request on 26.01.2020

**Comment by fazliddin** [comment]
I just edited php files. Will it effect docs in website? Or should I change website too?

**Comment by samdark** [comment]
You need to make a pull request. After it is merged, docs will be re-generated at the website.

**Comment by fazliddin** [comment]
so I did pull request
