### ISSUE TITLE
PHP 7.4 compatibility (get_magic_quotes_gpc)

### ISSUE THREAD

**Issue by Jay04653** [yiisoft/yii#4281]
`Function get_magic_quotes_gpc() is deprecated (/web/project/vendors/yiisoft/yii/framework/web/CHttpRequest.php:130)`

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 1.1.21
| PHP version      | 7.4
| Operating system | Ubuntu 18.04.3 LTS

**Comment by rob006** [comment]
This is already fixed by https://github.com/yiisoft/yii/pull/4278. Try master branch.

**Comment by Jay04653** [comment]
Ok, thank you!

**Comment by XPOHOC269** [comment]
@samdark it is not fixed in yiilite.php
`Deprecated: Function get_magic_quotes_gpc() is deprecated in /srv/yii/current/framework/yiilite.php`

**Comment by samdark** [comment]
https://github.com/yiisoft/yii/commit/1a8654ca2ca242025f9aadd316b529a451979c38
