### ISSUE TITLE
PHP 7.0.30

### ISSUE THREAD

**Issue by gerwel** [yiisoft/yii#4282]
### What steps will reproduce the problem?
PHP 7.0.30

Hi we are currently using PHP 7.0.30 and still using Yii 1.1.17, We are planning to upgrade to yii 1.1.21 and based on your documentation only to supported PHP version , We are still planning to use 7.0.30 as of the moment to use yii framework. can this be work ???.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 1.1.?
| PHP version      | 7.?
| Operating system |

**Comment by phena109** [comment]
As far as I know, it should work.

**Comment by samdark** [comment]
Yes. Should work.
