### ISSUE TITLE
Deprecated: Function get_magic_quotes_gpc() is deprecated in /srv/yii/current/framework/yiilite.php on line 2328

### ISSUE THREAD

**Issue by XPOHOC269** [yiisoft/yii#4283]
Deprecated: Function get_magic_quotes_gpc() is deprecated in /srv/yii/current/framework/yiilite.php on line 2328

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 1.1.21
| PHP version      | 7.4
| Operating system | Ubuntu

**Comment by samdark** [comment]
https://github.com/yiisoft/yii/commit/1a8654ca2ca242025f9aadd316b529a451979c38

**Comment by XPOHOC269** [comment]
@samdark thanks a lot
