### ISSUE TITLE
Function get_magic_quotes_gpc() is deprecated

### ISSUE THREAD

**Issue by twisted1919** [yiisoft/yii#4284]
### What steps will reproduce the problem? 
Use PHP 7.4 

### What is the expected result?
Not getting any error

### What do you get instead?
Deprecated: Function get_magic_quotes_gpc() is deprecated in /vendor/yiisoft/yii/framework/web/CHttpRequest.php on line 130

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 1.1.21
| PHP version      | 7.4
| Operating system | Ubuntu via Docker (`phpdockerio/php74-fpm:latest`)

@samdark - can we please get Yii 1.1.x fully compatible with PHP 7.4?  I am sure there aren't that many issues, just small things like above.

**Comment by samdark** [comment]
Would you like to help with a pull request?

**Comment by twisted1919** [comment]
@samdark - sure i can, but what about all the other issues concerning php 7.4? The reason i wrote this mostly is because the framework needs a bit of a revamp for php 7.4 and needs core contributors attention. If you'd like us to donate a bit to make this happen, just let me know, otherwise i can submit that pull request, again, just let me know.

**Comment by b1rdex** [comment]
AFAIK, all other php 7.4 issues are fixed already in master. What other issues you mentioned are?

**Comment by twisted1919** [comment]
I meant the other two open issues for php 7.x from this repo, #4256 and #4269 which aren't closed so i assumed aren't fixed. 
And also, additional overall checks for php 7.4 compatibility, which as far as i can tell where never done.

**Comment by samdark** [comment]
@twisted1919 we're running unit tests on 7.4 so majority of framework functionality should work well.

**Comment by samdark** [comment]
This one is already fixed in master btw. so no need for a pull request.

**Comment by twisted1919** [comment]
@samdark - thanks! please do a release so we can make use of php 7.4. best.
