### ISSUE TITLE
Error processing large cron requests.

### ISSUE THREAD

**Issue by chtoesli** [yiisoft/yii#4288]
### It is fixed by adding code in the framework \ db \ CDbConnection.php code after line 468 of the entry:
$ pdo-> exec ('SET session wait_timeout = 28800');

### Additional info
| Q                | A
| ---------------- | ---
| Yii version      | 1.1.22
| PHP version      | 7.3
| Linux Ubuntu |

Corrected file: 
[CDbConnection.zip](https://github.com/yiisoft/yii/files/4121971/CDbConnection.zip)

**Comment by samdark** [comment]
Would you please provide extra details on how to reproduce the issue?

**Comment by chtoesli** [comment]
On the website in the database there are about 14,000 entries in the database table. Each record in this table records 156 field values. Based on this table, you will need to create sitemap.xml every day. This is done through a job using a cron request. Requests are very heavy. Database processing takes longer than usual because the database is very large.
After analyzing the situation, I had to change the code in the core of the framework. Entered a line to increase the time of working with the database. Now the database works without refusing a request.

Here is the error with a large request:

exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away. The SQL statement executed was: SELECT `tag`
FROM `article`' in /home/mysite/public_html/framework/db/CDbCommand.php:543
Stack trace:
#0 /home/mysite/public_html/framework/db/CDbCommand.php(377): CDbCommand->queryInternal('', 0, Array)
#1 /home/mysite/public_html/protected/commands/RobotCommand.php(468): CDbCommand->query()
#2 [internal function]: RobotCommand->actionIncrementGeneratorSiteMaps()
#3 /home/mysite/public_html/framework/console/CConsoleCommand.php(172): ReflectionMethod->invokeArgs(Object(RobotCommand), Array)
#4 /home/mysite/public_html/framework/console/CConsoleCommandRunner.php(71): CConsoleCommand->run(Array)
#5 /home/mysite/public_html/framework/console/CConsoleApplication.php(92): CConsoleCommandRunner->run(Array)
#6 /home/mysite/public_html/framework/base/CApplication.php(185): CConsoleApplication->processRequest()
#7 /home/mysite/public_html/framework/yiic.php(33): CApplication->run()
#8 /home/mysite/public_html/protected/yiic.php(7): require_once('/mysite/...')
#9 {main}

------------------
It is fixed by adding code in the framework \ db \ CDbConnection.php code after line 468 of the entry:
$ pdo-> exec ('SET session wait_timeout = 28800');
-------------
I can show the cron task code only in a personal message.

**Comment by chtoesli** [comment]
To make it clear to you, this is a advertising site zinki.ru. The database is very large, you have to process very large amounts of information!

**Comment by samdark** [comment]
There's already a solution in the framework for your case: https://www.yiiframework.com/doc/api/1.1/CDbConnection#$initSQLs-detail

**Comment by chtoesli** [comment]
sorry for the text, I speak English badly
Могу писать на русском)
