### ISSUE TITLE
Quick Survey on GitHub Repos similar to yii

### ISSUE THREAD

**Issue by raux** [yiisoft/yii#4290]
Dear yii developers,

My name is Raula Gaikovina Kula, an Assistant Professor and software engineering researcher at NAIST, Japan. I am writing on behalf of our research team that is conducting a study that traces the origins of source code within GitHub. Formally,
The aim of this project is to evaluate our proposed new approach of contributions to FLOSS projects. Because of the reusability of FLOSS, pieces of source code from the same origins spread to multiple software repositories are maintained independently, which can cause the obsolescence of source code and the increasing risk of defects and vulnerabilities. For these issues, we intend to aggregate various changes for source code of the same origins, compose integrated changes and distribute to FLOSS projects that have the related source code. We call this approach meta maintenance. We hope to be able to have a better grasp of understanding the important points of such contributions so that we can build practical tools for meta maintenance.

You work with yii has lead us to interview you on these specific changes. We gratefully request your time to tell us what your thoughts are on the topic. It should only take 5 mins.
https://forms.gle/w7UeunjDUoyq47A56 

Again, I thank you for your time and look forward to your feedback,

Hideaki Hata, Christoph Treude, Raula Gaikovina Kula, Takashi Ishio

**Comment by samdark** [comment]
Closing since that's not what issues are for.

**Comment by raux** [comment]
Hi @samdark, we apologize for this misunderstanding. I am now going to the forums. Would you have some idea as to where to post this kind of information? Many thanks, Raula

**Comment by samdark** [comment]
Forums should be OK.

**Comment by raux** [comment]
@samdark . Unfortunately, the forum message was also shut down. Could I kindly ask for 5 mins of your time? https://forms.gle/w7UeunjDUoyq47A56. We would be very grateful for this.

**Comment by samdark** [comment]
OK. Will fill it.

**Comment by raux** [comment]
@samdark Thank you for filling out our form. Raula
