### ISSUE TITLE
Postgresql 12 issue in CPgsqlSchema.php

### ISSUE THREAD

**Issue by d4rkstar** [yiisoft/yii#4294]
### What steps will reproduce the problem?
Use postgresql 12

### What is the expected result?
Application should work without problems

### What do you get instead?
SQLSTATE[42703]: Undefined column: 7 ERROR: column c.consrc does not exist

### Additional info
Steps to reproduce or a small repository showing the problem: PostgreSQL 12 removes the pg_constraint.consrc column and this breaks CPgsqlSchema.php

| Q                | A
| ---------------- | ---
| Yii version      | 1.1.22
| PHP version      | 7.2.27
| Operating system | Debian 10

**Comment by samdark** [comment]
Is there a simple way to fix it? If there isn't I'm afraid we can't have it since Yii 1.1 should only receive security fixes and PHP 7 compatibility fixes.

**Comment by d4rkstar** [comment]
Hello @samdark . Yes, i've developed a fix and i'll be glad to send a patch, but don't know how to do extensive tests.
Will send it later today.

**Comment by d4rkstar** [comment]
Take look at #4296

**Comment by romansh** [comment]
Faced the same issue. Used bio's commits to change yii code and waiting for 1.2.3.

**Comment by DrDeath72** [comment]
PHP notice
Undefined index: column_def_value
PostgreSQL 10.14 (Ubuntu 10.14-0ubuntu0.18.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, 64-bit

**Comment by marcovtwout** [comment]
@d4rkstar @DrDeath72 Could you please test the new solution in https://github.com/yiisoft/yii/pull/4323 and confirm on which PostgreSQL versions it works as expected?

**Comment by d4rkstar** [comment]
@marcovtwout Yes, i can test. Will let you know.

Regards

**Comment by d4rkstar** [comment]
@marcovtwout #4323 seems to work for me. No issue so far

**Comment by marcovtwout** [comment]
@d4rkstar Thanks - and I assume that is on v12?

**Comment by d4rkstar** [comment]
Yes

**Comment by marcovtwout** [comment]
Fixed with https://github.com/yiisoft/yii/pull/4323
