### ISSUE TITLE
A section on NGINX Unit in docs/guide/quickstart.apache-nginx-config.txt

### ISSUE THREAD

**Issue by artemkonev** [yiisoft/yii#4298]
Hi,

Will the community welcome a pull request adding a subsection about NGINX Unit (https://unit.nginx.org) in [quickstart.apache-nginx-config.txt](https://github.com/yiisoft/yii/blob/master/docs/guide/quickstart.apache-nginx-config.txt)? I imagine something similar to this: https://unit.nginx.org/howto/yii/

**Comment by samdark** [comment]
Yes. Absolutely.

**Comment by samdark** [comment]
Yii 2 and Yii 3 as well.

**Comment by artemkonev** [comment]
Great, thank you! I'll proceed with the PR.

**Comment by samdark** [comment]
Btw., would be great if you'll check our Nginx configs as well.

**Comment by artemkonev** [comment]
I'll see what I can do about that. Most probably, all updates will arrive in mid-May or so.

**Comment by samdark** [comment]
Solved by https://github.com/yiisoft/yii/commit/6f43af6f9e0f3d8a4e867d9ca5a31fe7c8343776
