### ISSUE TITLE
Updated postgres 12 query for findColumns function returns wrong sequence name in the result

### ISSUE THREAD

**Issue by varunkamra** [yiisoft/yii#4302]
Postgres 12 updated the findColumns function and the following query when run for a database table whose name and sequence name were updated after it was created returns old sequence name when this query gets executed.

`SELECT a.attname, LOWER(format_type(a.atttypid, a.atttypmod)) AS type,
	d.adsrc AS column_def_value, a.attnotnull, a.atthasdef,
	pg_catalog.col_description(a.attrelid, a.attnum) AS comment
FROM pg_attribute a LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum
WHERE a.attnum > 0 AND NOT a.attisdropped
	AND a.attrelid = (SELECT oid FROM pg_catalog.pg_class WHERE relname=:table
		AND relnamespace = (SELECT oid FROM pg_catalog.pg_namespace WHERE nspname = :schema))
ORDER BY a.attnum`

Old query that gets generated by findColumns function before postgres12 upgrade code was added gives the right sequence name for the same table

`SELECT a.attname, LOWER(format_type(a.atttypid, a.atttypmod)) AS type, CAST(pg_get_expr(d.adbin, d.adrelid) AS varchar) AS adsrc, a.attnotnull, a.atthasdef,
	pg_catalog.col_description(a.attrelid, a.attnum) AS comment
FROM pg_attribute a LEFT JOIN pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum
WHERE a.attnum > 0 AND NOT a.attisdropped
	AND a.attrelid = (SELECT oid FROM pg_catalog.pg_class WHERE relname=:table
		AND relnamespace = (SELECT oid FROM pg_catalog.pg_namespace WHERE nspname = :schema))
ORDER BY a.attnum`

**PHP version being used** 7.2.31
**Postgres** 11.8
**OS**: CentOS Linux release 7.7.1908 (Core), Ubuntu 20.04 LTS

https://github.com/yiisoft/yii/blob/09672fe0754eb939bafaf28a13b9dcad4bfaca0e/framework/db/schema/pgsql/CPgsqlSchema.php#L172

**Comment by samdark** [comment]
Have you tried with dev-master version? https://github.com/yiisoft/yii/blob/master/CHANGELOG#L7

**Comment by varunkamra** [comment]
Yes, I used the updated code from master branch that’s when it failed. If I use 1.1.22 it works.

**Comment by samdark** [comment]
Do you have time to prepare a fix?

**Comment by varunkamra** [comment]
I will try to understand both queries and come up with a solution.

**Comment by varunkamra** [comment]
https://github.com/yiisoft/yii/pull/4303

**Comment by marcovtwout** [comment]
@varunkamra Your original issue description does not seem completely accurate. If you have tested on PostgreSQL 11 you should always get outdated names, since it was implemented that way. Could you please clarify?

From https://www.postgresql.org/docs/12/release-12.html
> Remove obsolete pg_attrdef.adsrc column (Peter Eisentraut)
> This column has been deprecated for a long time, because it did not update in response to other catalog changes (such as column renamings). The recommended way to get a text version of a default-value expression from pg_attrdef is pg_get_expr(adbin, adrelid).

The implementation in Yii 1.1.22 only supported PostgreSQL up to 11 and uses an obsolete implementation (`adsrc`) to determine a column's default value.

The implementation that is _currently_ in Yii master also supports PostgreSQL 12, and only that one uses the new implementation (`pg_get_expr(adbin, adrelid)`) for PostgreSQL 12.

**Comment by varunkamra** [comment]
Actually the PostgreSQL 12 fix works great with postgreSQL version < 12 as
well and returns right sequence name. But the condition that uses d.adsrc
for < 12 doesn’t seem to return latest sequence name.

**Comment by marcovtwout** [comment]
@varunkamra That's right, `d.adsrc` will not return the latest name after changes, according to the PostgreSQL documentation. But that was already the case on Yii 1.1.22

Thank you for confirming the new implementation works on v11 as well.

**Comment by marcovtwout** [comment]
@varunkamra Could you please test the new solution in https://github.com/yiisoft/yii/pull/4323 and confirm on which PostgreSQL versions it works as expected?

**Comment by lourdas** [comment]
I tested it with PostgreSQL 12.4 on Linux and it works fine now.

**Comment by marcovtwout** [comment]
Fixed with https://github.com/yiisoft/yii/pull/4323

**Comment by varunkamra** [comment]
Will there be postgres 13 support for Yii 1.1?

**Comment by samdark** [comment]
@varunkamra if someone will contribute it, @marcovtwout will decide. Likely yes in this case.

**Comment by marcovtwout** [comment]
@varunkamra Is there anything you know that needs changing in newer versions? You could check the migration guide here https://www.postgresql.org/docs/13/release-13.html#id-1.11.6.9.4

**Comment by varunkamra** [comment]
Actually I am not sure if anything needs to change. I will install PostgreSQL 13 and test it with the Yii 1.1.

**Comment by lourdas** [comment]
I was thinking of testing version 13 with all Yii 1.1 apps in our organization. If anything surfaces from the tests, I will report it here (or maybe in a new issue).

**Comment by varunkamra** [comment]
great thank you! I will test it too.

**Comment by lourdas** [comment]
I know this issue is closed, but I've tested 5 Yii 1.1 applications in our organization with PostgreSQL 13 as a database backend and they all work fine. Thanks!
