### ISSUE TITLE
captcha not working on yii1.1.16

### ISSUE THREAD

**Issue by Nusratbek1997** [yiisoft/yii#4309]
captcha not working on yii1.1.16
### in model
    public $verifyCode;

public function rules()
    {
        return array(
            array('name, typeOfOwnership, INT,  category, OKNX, business_type,FLM, address, email, phone, subject, body', 'required'),
            array('email', 'email'),
            array('membership, status, member_date, member_num,', 'safe'),
            array('verifyCode', 'captcha', 'allowEmpty'=>!CCaptcha::checkRequirements()),
            array('verifyCode', 'safe'),
        );
    }
### view
<?php if(CCaptcha::checkRequirements()): ?>
    <div class="form-group" style="width: 100%;">
        <div>
            <?php $this->widget('CCaptcha',array(
                    'buttonLabel'=>Yii::t('common','Не вижу картинку'),
                )
            ); ?>
            <?php echo $form->textField($model,'verifyCode',['placeHolder'=>Yii::t('common','Введите код с картинки'), 'autocomplete' => 'off','required'=>true]); ?>
            <?php echo CHtml::submitButton(Yii::t('common','Отправить'),array(
                'class'=>'button',
                'style'=>'margin-left:5px;'
            )); ?>
            <?php echo $form->error($model,'verifyCode'); ?>
        </div>
    </div>
<?php endif; ?>

**Comment by samdark** [comment]
What do you mean by "not working"?

**Comment by marcovtwout** [comment]
@Nusratbek1997 Unclear what the issue is exactly. Also it seems you are explicitly disabling Captcha when requirements are not met in validation rules.
