### ISSUE TITLE
Added special option 'encode' to `$htmlOptions` argument in `CHtml::errorSummary` and `CHtml::error`

### ISSUE THREAD

**Issue by shidenko97** [yiisoft/yii#4317]
Problem with HTML tags in validator's error text

I want to rollback changes in file **framework/web/helpers/CHtml.php** from [this commit](https://github.com/yiisoft/yii/commit/acb7a3b4881b693a1a19178694e4704038df9452) . It will make HTML tags in validator's error text available again.

| Q                | A
| ---------------- | ---
| Yii version      | 1.1.22
| PHP version      | Any
| Operating system | Any

**Comment by shidenko97** [comment]
It has at least 4 reasons to make it.

- https://github.com/yiisoft/yii/commit/acb7a3b4881b693a1a19178694e4704038df9452#r33834132
- https://github.com/yiisoft/yii/commit/acb7a3b4881b693a1a19178694e4704038df9452#r33767237

**Comment by samdark** [comment]
I don't think it's a good idea:

1. It may introduce security issue.
2. It was done a long time ago so there are projects relying on the behavior.

We may introduce an option for htmlOptions to turn off HTML escaping though.

**Comment by shidenko97** [comment]
> I don't think it's a good idea:
> 
> 1. It may introduce security issue.
> 2. It was done a long time ago so there are projects relying on the behavior.
> 
> We may introduce an option for htmlOptions to turn off HTML escaping though.

Yes, it looks like better idea than my. I've did it by your way.
