### ISSUE TITLE
Phpunit 9 compatibility issue with Yii 1.1 - unable to extend class Version as it's final

### ISSUE THREAD

**Issue by aprudencio** [yiisoft/yii#4319]
### What steps will reproduce the problem?
I updated my project to have yii 1.1.22 and added PHPUnit 9.3.11 using composer. I'm using PHP 7.4.

I had to add the compatibility.php file in protected/tests/ described here: https://github.com/yiisoft/yii/issues/4227

However, the phpunit class in vendor/phpunit/phpunit/src/Runner/Version.php is declared as final. So when executing the test (../../vendor/phpunit/phpunit/./phpunit), it shows: 

    PHP Fatal error:  Class PHPUnit_Runner_Version may not inherit from final class 
    (PHPUnit\Runner\Version) in /var/www/2020/protected/tests/compatibility.php on line 18

As we cannot extend it. 

Removing the final keyword from Version.php it's the workaround for now.

### What is the expected result?
User can execute phpunit tests successfully without errors
### What do you get instead?
  PHP Fatal error:  Class PHPUnit_Runner_Version may not inherit from final class 
    (PHPUnit\Runner\Version) in /var/www/2020/protected/tests/compatibility.php on line 18

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 1.1.22
| PHP version      | 7.4
| Operating system | Ubuntu Server 20

**Comment by b1rdex** [comment]
Hi. The compatibility file should be changed: use class_alias instead of extending the original classes. 

Отправлено с iPhone

**Comment by marcovtwout** [comment]
@applee Did you not run into https://github.com/yiisoft/yii/issues/4366 when upgrading PHPUnit?
