### ISSUE TITLE
Error :: session_name(): Cannot change session name when headers already sent :: Yii1

### ISSUE THREAD

**Issue by girishcp** [yiisoft/yii#4327]
I have moved my Yii project from Windows to Linux in PHP 7.4 version and it showing the below error. Please suggest me what should I do to resolve this. I have also updated the latest framework version 1.1.22.

**_500
session_name(): Cannot change session name when headers already sent_**

![image](https://user-images.githubusercontent.com/23473721/95653398-1d147c80-0b16-11eb-9032-ac18cbeb86a3.png)

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 1.1.?
| PHP version      | 7.?
| Operating system |

**Comment by samdark** [comment]
Check that there are no symbols before all your opening `<?php` and no BOM.

**Comment by b1rdex** [comment]
![image](https://user-images.githubusercontent.com/312855/95678795-41558380-0c12-11eb-9e9a-58e5df174a67.png)
Did you upgrade from php < 7.2? I'm not sure but it looks like the session is already started at the point yii tries to configure it.

**Comment by b1rdex** [comment]
Update: do you have `session.auto_start` set to `true` in the php configuration? If so then you'd have to disable it.

**Comment by girishcp** [comment]
> ![image](https://user-images.githubusercontent.com/312855/95678795-41558380-0c12-11eb-9e9a-58e5df174a67.png)
> Did you upgrade from php < 7.2? I'm not sure but it looks like the session is already started at the point yii tries to configure it.

Thanks for your response, yes I have updated from 7.2 to 7.4 php version. Is this reason of this error, what should I do to resolve this.

**Comment by girishcp** [comment]
> session.auto_star

thanks for your response, its already disabled

session.auto_start = 0
