### ISSUE TITLE
Remove attribute tag from <script> tag

### ISSUE THREAD

**Issue by mohamedmalki** [yiisoft/yii#4349]
### What steps will reproduce the problem?

Hi, There is any way to remove or not use Attribute 'type="text/javascript"' when we use create a new js file usinf one of this function ? :
Yii::app()->clientScript->registerScript('myjavascript','(function() { // code here })();',CClientScript::POS_END);
or
Yii::app()->clientScript->registerScriptFile( $file,CClientScript::POS_END );

### What is the expected result?

It gives  '<script type="text/javascript"> // code here</script>', and W3C validator says that is a warning, you have to remove the type attribute.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 1.1.19
| PHP version      | 7.1
| Operating system |

**Comment by samdark** [comment]
Yes, should be adjusted.

**Comment by marcovtwout** [comment]
Technically it's not wrong to keep this obsolete attribute, but it's a small change to keep the w3c validator happy. I don't see any objections against removing it, unless there would be a known component in any way dependent on it. PR coming up.

**Comment by marcovtwout** [comment]
It seems we can't simply remove it always for backwards compatibility with XHTML. Lets continue discussion in the PR.

**Comment by marcovtwout** [comment]
@mohamedmalki Take a look at the solution in https://github.com/yiisoft/yii/pull/4351

**Comment by marcovtwout** [comment]
Fixed with https://github.com/yiisoft/yii/pull/4351/

You have to enable the new option to use this functionality.
