### ISSUE TITLE
CHtml documentation page is broken

### ISSUE THREAD

**Issue by wardjk** [yiisoft/yii#4353]
https://www.yiiframework.com/doc/api/1.1/CHtml
is broken. 
CHtml:7119 Uncaught ReferenceError: jQuery is not defined
    at CHtml:7119

**Comment by samdark** [comment]
Would you please provide some code to reproduce the issue? Thanks.

**Comment by wardjk** [comment]
It's not my code. Did you look at https://www.yiiframework.com/doc/api/1.1/CHtml?
![image](https://user-images.githubusercontent.com/5148283/112766032-8d845c80-8fd5-11eb-831d-f44cac004bdb.png)

**Comment by samdark** [comment]
Aha! Got it.

**Comment by wardjk** [comment]
Until it's fixed, similar documentation can be found at
https://docs.w3cub.com/yii~1.1/chtml
http://apimirror.com/yii~1.1/chtml
http://www.mbrunot.com/files/divers/yii-docs-1.1.10.r3566/api/CHtml.html

Version 1.0 documentation still works:
https://www.yiiframework.com/doc/api/1.0/CHtml

**Comment by wardjk** [comment]
It's fixed.
