### ISSUE TITLE
Downloadable release asset for 1.1.24 (tar.gz) have executable bits set on all files

### ISSUE THREAD

**Issue by sparkcodeuk** [yiisoft/yii#4367]
### What steps will reproduce the problem?

* Download the tar.gz release asset for v1.1.4: https://github.com/yiisoft/yii/releases/download/1.1.24/yii-1.1.24.a5ab20.tar.gz
* Extract the archive on a unix-based system
* Observe that the files extracted will all be set as executable

### What is the expected result?

As per previous releases the overwhelming majority of files that don't need to be set executable should not have their executable bits set. I assume this has happened because maybe the person packaging the release is doing it on Windows or something?

### What do you get instead?

Extracted archive has all files with their executable bit set which has to be resolved manually (until this can be repackaged).

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 1.1.24
| PHP version      | N/A
| Operating system | OSX Catalina (but any unix will do)

**Comment by marcovtwout** [comment]
You are correct - the build is done in a Vagrant/Virtualbox Ubuntu environment run on Windows in a mounted folder.

I'll build some new files and will check if I can replace them.

**Comment by sparkcodeuk** [comment]
If it helps at all this shows what files were set executable in the 1.1.23 tar.gz release so you can compare against your updated build when you run it:

`for i in \`find . -type f\`; do [ -x $i ] && echo $i; done`

```
./framework/yiic
./framework/cli/views/webapp/protected/yiic
./framework/db/schema/cubrid/CCubridColumnSchema.php
./framework/db/schema/cubrid/CCubridSchema.php
./framework/db/schema/cubrid/CCubridTableSchema.php
./framework/views/ca/profile-callstack-firebug.php
./framework/views/ca/log-firebug.php
./framework/views/ca/profile-summary-firebug.php
./framework/views/ca/profile-callstack.php
./framework/views/ca/error404.php
./framework/views/ca/error.php
./framework/views/ca/profile-summary.php
./framework/views/ca/error400.php
./framework/views/ca/error403.php
./framework/views/ca/log.php
./framework/views/ca/error503.php
./framework/views/ca/error500.php
./demos/blog/protected/yiic
```

My issue is because I've got some legacy non-composer codebase I'm supporting and don't want everything set executable & the extra git file mode changes logged as well.

**Comment by marcovtwout** [comment]
@sparkcodeuk That helps, as I think those views/ca and schema/cubrid files shouldn't be executable as well. Only the 3 instances of 'yiic'

**Comment by sparkcodeuk** [comment]
@marcovtwout separate (but related) can you also confirm what I'm seeing about line endings have been changed on all these files?

They look now to be Windows style CRLF, LF line endings rather than standard unix-style line endings.

**Comment by marcovtwout** [comment]
@sparkcodeuk That is correct. I'll create some new build files and update the release.

**Comment by marcovtwout** [comment]
@sparkcodeuk Please check if the new build is alright: https://github.com/yiisoft/yii/releases/download/1.1.24/yii-1.1.24.a5ab20.tar.gz

Executable files should match the list you posted earlier.
