### ISSUE TITLE
gii with error in php8:  Only the first byte will be assigned to the string

### ISSUE THREAD

**Issue by fufudao** [yiisoft/yii#4387]
### What steps will reproduce the problem?

use gii generate model class in php8

### What do you get instead?

yiisoft\yii\framework\gii\generators\model\ModelCode.php   line 408
origin:
$relationName[0]=strtolower($relationName);
fixed to 
$relationName = substr_replace($relationName, strtolower($relationName), 0, 1);

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 1.1.?
| PHP version      | 8.0
| Operating system |

**Comment by rob006** [comment]
It was already fixed in https://github.com/yiisoft/yii/pull/4370. 

@marcovtwout It may be worth to tag new release.

**Comment by samdark** [comment]
Will be done soon.
