### ISSUE TITLE
Redis cache client doesn't support SSL

### ISSUE THREAD

**Issue by andres101** [yiisoft/yii#4392]
### What steps will reproduce the problem?
Enable SSL on Redis.
### What is the expected result?
Redis cache should work.
### What do you get instead?
An error.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 1.1.25
| PHP version      | 7.3
| Operating system | Debian 10

**Comment by marcovtwout** [comment]
Fixed with https://github.com/yiisoft/yii/pull/4393
