### ISSUE TITLE
update pt lang links 

### ISSUE THREAD

**Issue by Arhell** [yiisoft/yii#4421]
http=>https

**Comment by marcovtwout** [comment]
@Arhell Is there a specific reason for creating and reviewing all these separate issues? https://github.com/yiisoft/yii/issues?q=is%3Aissue+is%3Aclosed+update+links+author%3AArhell

It really looks like a simple search+replace can fix all languages at once?

**Comment by Arhell** [comment]
> @Arhell Is there a specific reason for creating all these separate issues? https://github.com/yiisoft/yii/issues?q=is%3Aissue+is%3Aclosed+update+links+author%3AArhell
> 
> It really looks like a simple search+replace can fix all languages at once?

Hello, I try to make small changes every day.
And to search for everything as a whole will not work, not all links support https, you need to check it manually.
