### ISSUE TITLE
The select field does not work

### ISSUE THREAD

**Issue by KajetanDudczak** [yiisoft/yii#4440]
HI,

I have a problem with the select field, the code below, when I remove part of the code "data-toggle="select"" then the field starts working but is not styled.

    /select name="patt_product_unit" id="patt_product_unit" class="custom-select patt-product-unit" data-toggle="select"/

Yii version - 1.1.25
PHP version - 7.4.28

**Comment by marcovtwout** [comment]
This does not look like a Yii bug or regression or maybe not even Yii related at all. Perhaps you can find help through one of the community options: https://www.yiiframework.com/community
