### ISSUE TITLE
PHP 8.1 CPgsqlSchema error stripos(): Passing null to parameter #1 ($haystack) of type string is deprecated

### ISSUE THREAD

**Issue by JonathanArgentao** [yiisoft/yii#4456]
### What steps will reproduce the problem?
with Postgres Database configured
$model->find();

### What do you get instead?
an error: stripos(): Passing null to parameter #1 ($haystack) of type string is deprecated
CPgsqlSchema.php:194

### Additional info
adsrc is null when there's not a column default value, and stripos can't receive null

| Q                | A
| ---------------- | ---
| Yii version      | 1.1.25
| PHP version      | 8.1
| Operating system | macOS

**Comment by marcovtwout** [comment]
@JonathanArgentao Please retest with `dev-master` since it has PHP 8.1 compatibility.

**Comment by marcovtwout** [comment]
@JonathanArgentao Could you confirm this issue still exists on `dev-master`? (see https://github.com/yiisoft/yii/pull/4386)

**Comment by JonathanArgentao** [comment]
@marcovtwout Yes, still exists
