### ISSUE TITLE
Release 1.1.26

### ISSUE THREAD

**Issue by twisted1919** [yiisoft/yii#4458]
Now that dev-master contains all php 8.1 fixes, can you please release a new version?

**Comment by marcovtwout** [comment]
It's pretty likely some more 8.1 issues will be found, but I will plan a new release around the end of september.

**Comment by samdark** [comment]
A decision for release could be made by answering two questions:

1. It it making things better?
2. Does it break existing things?

If the answers are "yes" and "no" then it is a no-brainer.

**Comment by sss6672** [comment]
да

**Comment by c-schmitz** [comment]
1. Yes
2. No

**Comment by kenguest** [comment]
https://packagist.org/packages/yiisoft/yii doesn't show 1.1.26 as available, yet :-)

**Comment by marcovtwout** [comment]
Planned for the end of september, unfortunately I'm really busy right now. Please use master until then.

**Comment by marcovtwout** [comment]
Release is done like I promised :)
