### ISSUE TITLE
broken links

### ISSUE THREAD

**Issue by Arhell** [yiisoft/yii#4470]
While checking the links I found a few not working

https://github.com/yiisoft/yii/blob/master/demos/phonebook/flex/html-template/index.template.html#L11
https://github.com/yiisoft/yii/blob/master/docs/blog/ru/start.overview.txt#L25
https://github.com/yiisoft/yii/blob/master/framework/i18n/data/README.txt#L5
https://github.com/yiisoft/yii/blob/master/framework/utils/CPasswordHelper.php#L141
https://github.com/yiisoft/yii/blob/master/framework/utils/CTimestamp.php#L15
https://github.com/yiisoft/yii/blob/master/framework/web/helpers/CJSON.php#L620
https://github.com/yiisoft/yii/blob/master/framework/web/helpers/CJSON.php#L658

**Comment by sss6672** [comment]
> Проверяя ссылки, я обнаружил, что некоторые из них не работают
> 
> https://github.com/yiisoft/yii/blob/master/demos/phonebook/flex/html-template/index.template.html#L11 https://github.com/yiisoft/yii/blob/master/docs/blog/ru/start.overview.txt#L25 https://github.com/yiisoft/yii/blob/master/framework/i18n/data/README.txt#L5 https://github.com/yiisoft/yii/blob/master/framework/utils/CPasswordHelper.php#L141 https://github.com/yiisoft/yii/blob/master/framework/utils/CTimestamp.php#L15 https://github.com/yiisoft/yii/blob/master/framework/web/helpers/CJSON.php#L620 https://github.com/yiisoft/yii/blob/master/framework/web/helpers/CJSON.php#L658
