### ISSUE TITLE
Redis Cache - Deprecated: unserialize(): Passing null to parameter #1.

### ISSUE THREAD

**Issue by alexius** [yiisoft/yii#4497]
Hello everybody,
after updating Yii 1 to the version 1.1.27 we got this error:

`Deprecated: unserialize(): Passing null to parameter #1 ($data) of type string is deprecated in /srv/www/htdocs/ilya/mike.matthies.p2/protected/framework/caching/CCache.php on line 108`

### What steps will reproduce the problem?
We use cache during SQL request:

`$query = Yii::app()->db->cache(3600)
->createCommand()
->select('*, id')
->from('table')
->where('cond=1');
$rows = $query->queryAll();
`

The function 
`CDbCommand->queryAll( $fetchAssociative = ???, $params = ??? )` 
uses another function 
`CDbCommand->queryInternal( $method = 'fetchAll', $mode = [0 => 2], $params = [] )`, which uses the function 
`CCache->get( ...)`. There is a code in function `CCache->get( ...)`:

`if($this->serializer===null) $value=unserialize($value);`

which should be adjust. Passing null as a value to the function 'unserialize()' is deprecated now.

### What is the expected result?
If null, the function should just return value as for the case when we have false.

### What do you get instead?
We get error 'Deprecated'.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 1.1.27
| PHP version      | 8.1.2
| Operating system | Ubuntu 22.04.1 LTS

**Comment by rob006** [comment]
Which cache backend you're using?

**Comment by alexius** [comment]
> Which cache backend you're using?

We use Redis.

I see that this issue is going to be resolve. Thanks

**Comment by alexius** [comment]
There is another problem too - when we use the cache (php8+Yii+Redis), we get this problem 
`
Fatal error: Uncaught CDbException: The table "tablename" for active record class "TablenameRecord" cannot be found in the database. in /srv/www/htdocs/.../framework/db/ar/CActiveRecord.php on line 2391
CDbException: The table "tablename" for active record class "TablenameRecord" cannot be found in the database. in /srv/www/htdocs/.../framework/db/ar/CActiveRecord.php on line 2391
`
When we cancel the use of the cache, the error disappears. Just comment out these lines in main.conf:
`'cache'=>array(
             'class'=>'CRedisCache',
             'hostname'=> 'localhost',
             'port'=>6379,
             'database'=>1,
        ),` 
The table is existed in DB.

Why it happens and what can we do? 


Thank you!

**Comment by marcovtwout** [comment]
@alexius We recently had a similar case in https://github.com/yiisoft/yii/pull/4480 with unserialize(null) which turned out to be a problem in application code, not in framework code. Could you provide a bit more thorough reproducible sample code that demonstrates this issue so we can investigate?

**Comment by alexius** [comment]
@marcovtwout I did.

**Comment by marcovtwout** [comment]
@wtommyw confirmed this issue is reproducable with CRedis and the correct fix by https://github.com/yiisoft/yii/pull/4496

**Comment by marcovtwout** [comment]
Fixed by https://github.com/yiisoft/yii/pull/4496/
