### ISSUE TITLE
oci8 schema adapter returns null for 'KEY' field in column info which causes strpos deprecation error

### ISSUE THREAD

**Issue by johnrembo** [yiisoft/yii#4499]
### What steps will reproduce the problem?

Create app with oci8 AR
```
$app = Yii::createWebApplication('protected/config/main.php');
...
Pack::Model()->findByPk(...)
...
```

Config is:

```
return array(
...
	'components'=>array(
		'db'=>array(
			'class'=>'ext.oci8Pdo.OciDbConnection',
            'connectionString' => 'oci:dbname=(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST='.ORACLE_HOST.')
                (PORT='.ORACLE_PORT.'))(CONNECT_DATA=(SERVICE_NAME='.ORACLE_SID.')));charset='.ORACLE_CP.';',
            'username'=> ORACLE_USER,
			'password'=> ORACLE_PASS
	),
...

```

### What is the expected result?
Create an AR model

### What do you get instead?
PHP error
strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated

../yii/framework/db/schema/oci/COciSchema.php(234)

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 1.1.27
| PHP version      | 8.1.2
| Operating system | Linux 5.15.0-53-generic #59-Ubuntu SMP

**Comment by marcovtwout** [comment]
@johnrembo Could you post the full stack trace and also a simple example table that can be used to reproduce this issue?

**Comment by marcovtwout** [comment]
@johnrembo Could you test if https://github.com/yiisoft/yii/pull/4510 solves your issue?

**Comment by marcovtwout** [comment]
Marking as fixed with https://github.com/yiisoft/yii/pull/4510/
