### ISSUE TITLE
Argument 2 in number_format does not accept null

### ISSUE THREAD

**Issue by paalg** [yiisoft/yii#4506]
### What steps will reproduce the problem?
Call CFormatted::formatNumber($value) will call number_format($value) where the three next default arguments are gotten from CFormat::$numberFormat. The decimals argument will be set to null, which is deprecated, thus giving the error message given below.

The fix is to change  CFormatter::$numberFormat['deciamls'] from null to 0.

### What is the expected result?
No error message

### What do you get instead?
Error message: number_format(): Passing null to parameter #2 ($decimals) of type int is deprecated

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 1.1.27
| PHP version      | 8.1.13
| Operating system | Linux Mint 21.1

**Comment by wtommyw** [comment]
@paalg I picked this up in #4503 and added some unit tests to test for regressions. Can you let me know if this fixes your issue?
