### ISSUE TITLE
CMssqlColumnSchema - error when default column value is SQL SERVER system functions

### ISSUE THREAD

**Issue by advicente** [yiisoft/yii#4513]
### What steps will reproduce the problem?
Define or create a NOT NULL column and set default value to function getdate() or sysdatetime().

### What is the expected result?
$defaultValue = null;

The $defaultValue for this situations on method init of CMssqlColumnSchema must be NULL, and NULL must be passed to database.

### What do you get instead?
$defaultValue = 'getdate';

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 1.1.27
| PHP version      | 8.0.26
| Operating system | Windows

**Comment by marcovtwout** [comment]
@advicente Could you provide a little more code to reproduce this? It's unclear to be based on the description how exactly you are passing another default value and where you are expecting it to be returned.

Is it a regression with newer MSSQL versions or did the problem exist for longer? And can you reproduce this issue on Yii 2 as well?
