### ISSUE TITLE
Jquery in current yii1.1.30 is out of date with security issues. Looking to upgrade Jquery and JqueryUI

### ISSUE THREAD

**Issue by CrazyMoka** [yiisoft/yii#4574]
### What steps will reproduce the problem?
Using yii1.1.30
Jquery with this version is way out of date and has vulnerabilities.
jquery UI.

How can I update jquery from 1.12.4 to 3.50 and compatible JqueryUI.

What should I do.
trying to support a legacy system just a little longer..

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 1.1.30
| PHP version      | 8.1
| Operating system | Ubuntu 20.04

**Comment by marcovtwout** [comment]
This is not a support channel, please try https://www.yiiframework.com/community
