### ISSUE TITLE
Add option to sendFile() to output inline

### ISSUE THREAD

**Issue by marcovtwout** [yiisoft/yii#527]
Same request as done for xSendFile(): http://code.google.com/p/yii/issues/detail?id=2929&can=1&q=xsendfile&colspec=ID%20Type%20Status%20Priority%20Milestone%20Owner%20Stars%20Summary

**Comment by alexd3d** [comment]
I vote for this option too. Thanx!

**Comment by samdark** [comment]
No new features are going to be implemented in 1.1.
