### ISSUE TITLE
createIndex is not using the recommended way to create unique indexes on Postgres

### ISSUE THREAD

**Issue by c-schmitz** [yiisoft/yii#788]
I am using Yii with Postgres DB and when I run

```
Yii::app()->db->createCommand()->createIndex('idxName ','{{mytable}}','somecolumn',true)
```

it runs the following command on the database:

```
 CREATE UNIQUE INDEX idxName ON mytable USING btree (somecolumn);
```

while instead it should run this:

```
ALTER TABLE ONLY mytable 
    ADD CONSTRAINT idxName  UNIQUE (somecolumn);
```

Source:

http://www.postgresql.org/docs/8.0/static/indexes-unique.html

**Comment by kiaplayer** [comment]
It seems that now CPgsqlSchema::dropIndex() cannot drop index which was added by new CPgsqlSchema::createIndex(). I've got this error:

    SQLSTATE[2BP01]: Dependent objects still exist: 7 ERROR:  cannot drop index <index_name> because constraint <index_name> on table <table_name> requires it
    HINT:  You can drop constraint <index_name> on table <table_name> instead.
