### ISSUE TITLE
Uncaught Warning in CUploadedFile: it will never return false

### ISSUE THREAD

**Issue by teo1978** [yiisoft/yii#833]
Documentation of CUploadedFile says:
public boolean saveAs(string $file, boolean $deleteTempFile=true)
{return}	boolean	true whether the file is saved successfully

However, it will never return false.
Either it succeeds, in which case it returns true, or it fails, in which case the call to copy() inside CUploadedFile will cause a warning, which will trigger Yii's error handler and will cause the error page to be displayed (at least in debug mode), and the function won't return at all.

This at least happens with $deleteTempFile=false.

**Comment by teo1978** [comment]
This one is definitely not an enhancement. Is it fixed?

**Comment by samdark** [comment]
It will return false if either [there was and error](https://github.com/yiisoft/yii/blob/master/framework/web/CUploadedFile.php#L205) such as file size too big or [if there's no uploaded file to save](https://github.com/yiisoft/yii/blob/master/framework/web/CUploadedFile.php#L202).

Copy may fail if you'll specify wrong path or there are no permissions to write at that path. Since it's exceptional situation, it should not return false silently in that case.

**Comment by teo1978** [comment]
Ok, so it does return false in some cases.

However:

1) It should at least be better documented. It says "return: boolean: true [sic] whether the file is saved succsesfully". It doesn't mention different kinds of failure (upload failed vs saving failed). From that description, I expect it to always return false if saving failed for whatever cause. 

2) That failing to write the file is more of an "exceptional situation" than a failure to write is questionable. Again, it may be fine as long as at least it is well documented. But actually, I don't think it's a reasonable behavior at all. You say "silently return false", but if it's returning a value that tells whether or not the operation was succesfull, it's not silent. 

3) If you really do want it to be more "noisy" when the reason of the failure is more "exceptional" (all of which are fuzzy concepts with arbitrary thresholds), then you should throw an exception, and it should be documented: so one can catch it. Not checking and letting the code error out at a lower level (inside framework code) is always wrong, and in this case easily avoidable.

**Comment by samdark** [comment]
2) It is silent. False doesn't tell you anything about the nature of the error.
3) Ideally yes. In Yii 2.0 we're following that approach. In 1.1 overall we aren't and I don't think it's a good idea to adopt it in a single place like that.

**Comment by samdark** [comment]
https://github.com/yiisoft/yii/commit/fa8827f6358cbeb601ab6fb21443bb26cfbd912c

**Comment by teo1978** [comment]
Glad to see it documented, at least.

> 2) It is silent. False doesn't tell you anything about the nature of the error.

Oh, ok, but then also returning false on failed upload is equally silent. The fact is, there is a return value to tell you whether the operation is succesful or not: so, having cases that return false on failure and cases that trigger an uncaught warning (based on the questionable concept of what is an "exceptional" failure) is a bit of a nonsense.

By the way, in order to be able to always treat errors nicely (i.e. just check the return boolean value to know whether the operation succeeded, and trust that the application will never "crash") AND at the same time be able to distinguish the kind of error **there is maybe an easy and elegant solution**: extend the values of the **`$error`** property to include special values beyond PHP's predefined ones, to include failure to write the file.

> Ideally yes. In Yii 2.0 we're following that approach. In 1.1 overall we aren't and I don't think it's a good idea to adopt it in a single place like that.

Indeed. You should adopt it everywhere (another option to be considered, when the return value is success like in this case, and when there is not an `error` property to be used, may be to log an error and "silently" return false).

Letting the internal code of the framework generate uncaught PHP errors/warning is a bug. Of course, avoiding that strictly 100% of the times is often impractical (yielding horrible inefficiency and/or an unreasonable amount of checking code) and sometimes pedantic/useless, but this is not one of such cases, and generally, I've seen Yii 1.1 err too much on the "sloppy"  side (not checking trivial stuff and letting errors go down too deep to the lowest levels of framework code).

**Comment by samdark** [comment]
We're not going to release 1.2.0. That means 1.1 will stay as is in this regard.

**Comment by teo1978** [comment]
Ok, I thought you were still fixing bugs. (yeah, I have realized, you don't view this as a bug)

**Comment by samdark** [comment]
Fixing it all over the place will definitely break stuff in existing apps which are most likely in support phase by now. Not a good thing to do.
