### ISSUE TITLE
criteria modifications in beforeFind() do not apply when called from relation

### ISSUE THREAD

**Issue by qiangxue** [yiisoft/yii#93]
I have a ModelBehavior that modifies the owners criteria in the beforeFind() event.

$this-&gt;owner-&gt;getDbCriteria()-&gt;mergeWith($criteria);

If I want to access a Model that implements this behavior via relation my modifications to the criteria are ignored. 

I tried both ways:

// 1
$data = ExampleModel::model()-&gt;with(array('examplerelation'))-&gt;findByPk(2);
print_r($data-&gt;examplerelation);

// 2
$data = ExampleModel::model()-&gt;findByPk(2);
$relation = $data-&gt;examplerelation();

<p>Migrated from http://code.google.com/p/yii/issues/detail?id=1752</p><hr/><h2>earlier comments</h2>
<p><strong>cbrandt@metadesign.de said, at 2010-11-12T12:34:52.000Z:</strong></p>

<p>Sorry, but this does not seem to be the same problem as issue 1740 and it still does not work.
These querys are handled by CActiveFinder who does not send the criteria when calling beforeFind() and so does not care about changes to the criteria.
I am currently trying some changes in
CJoinElement::lazyFind()
will post them, if I get it to work properly.</p><p><strong>qiang.xue said, at 2010-11-12T13:22:30.000Z:</strong></p>

<p>Do you mean the query parameter passed to find method, or the criteria in the scope of the primary AR class?</p><p><strong>cbrandt@metadesign.de said, at 2010-11-12T13:51:20.000Z:</strong></p>

<p>The problem exists with both of them. There seems to be no way to modify the criteria. 
More detailed example of what I am doing (still simplified to relevant parts):

class Model1 extends CActiveRecord
    has behavior ModelTranslationBehavior
    has relation 'translations' => array(self::HAS_MANY, 'Model1Translation', 'id'),

class Model1Translations extends CActiveRecord

class Model2 extends CActiveRecord
    has relation 'model1' => array(self::HAS_MANY, 'Model1', 'model2id'),

If I call
$model2 = Model2::model()->findByPk(2);
$model1data = $model2->model1(array('order' => 'column1'));

ModelTranslationBehavior::beforeFind() gets called for Model1 but $event->criteria is null and $this->owner->getDbCriteria()->order is empty. This would be not that bad, but even if I add some other criteria(for example a with=array('translations')) to the owners criteria it does not apply to the query.</p><p><strong>qiang.xue said, at 2010-11-12T13:54:45.000Z:</strong></p>

<p>Out of time. Set for 1.1.6 milestone.</p><p><strong>cbrandt@metadesign.de said, at 2010-11-12T17:29:02.000Z:</strong></p>

<p>I played around this afternoon and made some changes to CActiveFinder and CActiveRecord.

Attached you will find a *draft* about how a fix could look like. These changes still do not address the whole problem, only example 2 of my first post seems to work and changes to $criteria->with cause some further problems.
</p><p><strong>cbrandt@metadesign.de said, at 2010-11-15T12:38:59.000Z:</strong></p>

<p>got a working patch now.

only problem I see is that I can not add $criteria->with because the join-tree has to be rebuilt somehow. Workaround for that is to add the needed with-criteria when calling the relation like this:

// 1
$data = ExampleModel::model()->with(array('examplerelation'=>array('with'=>'translations')))->findByPk(2);
print_r($data->examplerelation);

// 2
$data = ExampleModel::model()->findByPk(2);
$relation = $data->examplerelation(array('with'=>'translations'));

</p><p><strong>qiang.xue said, at 2011-01-15T19:25:08.000Z:</strong></p>

<p>Set for next milestone.</p><p><strong>qiang.xue said, at 2011-03-26T17:58:16.000Z:</strong></p>

<p>Out of time. Move to next milestone.</p><p><strong>alexander.makarow said, at 2011-04-20T01:47:17.000Z:</strong></p>

<p>Issue 2352 has been merged into this issue.</p><p><strong>intel352 said, at 2011-05-16T23:52:45.000Z:</strong></p>

<p>Workaround: Apply latest patch from issue 2029 (http://code.google.com/p/yii/issues/detail?id=2029), then use behavior scopes on the relations. Working alternative to relational beforeFind.

My typical setup now, for a situation where the criteria needs to be modified for all queries of a model (including in a relational scenario), I specify a 'scopes' option in my defaultScope(), with the name of the behavior's scope. This is working well on multiple installs.

An additional patch that I needed, was the patch found at issue 2392 (http://code.google.com/p/yii/issues/detail?id=2392), as otherwise I sometimes encountered table alias issues depending on how I was querying CActiveRecord.

Cheers</p><p><strong>cbrandt@metadesign.de said, at 2011-05-17T11:07:34.000Z:</strong></p>

<p>thx, will try it out this week!</p><p><strong>qiang.xue said, at 2012-01-01T03:36:53.000Z:</strong></p>

<p>set for 1.1.10 milestone</p><p><strong>qiang.xue said, at 2012-01-01T03:37:09.000Z:</strong></p>

<p>set for 1.1.10 milestone</p><p><strong>qiang.xue said, at 2012-01-01T03:37:35.000Z:</strong></p>

<p>set for 1.1.10 milestone</p>

**Comment by pransi** [comment]
####code 1
public function actionSam()
{
$criteria = new CDbCriteria();
        $criteria->with = array(        
            'account',
        );
         $d= Payment::model()->findAll($criteria);
}

#### code 2

public function beforeFind()
{
print_r($this->getDbCriteria());
parent::beforeFind();
}
output:
CDbCriteria Object ( [select] => * [distinct] => [condition] => [params] => Array ( ) [limit] => -1 [offset] => -1 [order] => [group] => [join] => [having] => [with] => [alias] => [together] => [index] => [scopes] => [_e:CComponent:private] => [_m:CComponent:private] => )

but i sent criteria with "account".The output is display only empty with.i try to another way to call beforeFind() function's working fine...
Payment::model()->with('account')->findAll();
o/p:
CDbCriteria Object ( [select] => * [distinct] => [condition] => [params] => Array ( ) [limit] => -1 [offset] => -1 [order] => [group] => [join] => [having] => [with] => array([0]=>account)[alias] => [together] => [index] => [scopes] => [_e:CComponent:private] => [_m:CComponent:private] => )..

how to get Criteria with in yii ?
any other solution for that...
