### ISSUE TITLE
Compare Validation fails for date fields

### ISSUE THREAD

**Issue by albanomiguel** [yiisoft/yii#948]
Sorry if this has already been reported.

When using 'compare' rule for date fields the validation can fail if the date format is not in the default format, example:

   public function rules()
   {
      array('start_date, end_date','date','format'=>'dd-MM-yyyy')
      array('end_date', 'compare', 'compareAttribute'=>'start_date', 'operator'=>'>'),
   }

If, start_date=25-05-2012 AND end_date=20-06-2012 the comparison raises a failure. This is because the date comparison validator uses datetimestamps and it does not convert textual dates into timestamps.

However, since all the information is set at the rules function, i.e. the date formats, the validation should be work fine and the user should not be forced to either create a custom validation rule or extende beforeValidate() method..

**Comment by matweew** [comment]
Did you decide not to include it to 1.1.16?

**Comment by samdark** [comment]
Yes.

**Comment by jithu121212** [comment]
But still it is missing

**Comment by cebe** [comment]
> Note that Yii 1.1 [has reached end of life](http://www.yiiframework.com/news/90/update-on-yii-1-1-support-and-end-of-life/) and won't receive updates except security fixes. Please start new projects using [Yii 2](https://github.com/yiisoft/yii2).
